- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/PublishValidation.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/linking/PublishValidationTest.kt
- ui/src/preview/translations.fi.json
- ui/src/tool-panel/location-track/dialog/location-track-edit-dialog.tsx
- ui/src/tool-panel/location-track/dialog/translations.fi.json
- ui/src/tool-panel/location-track/location-track-infobox.tsx
- ui/src/tool-panel/translations.fi.json
Hyvin pieneltä logiikkamuutokselta näyttävän taskin takaa löytyi lopulta paljon näprättävää.
Nyt pitäisi kälin toimia yhdenmukaisesti niin, että duplikaatit ovat 1:n-suhde, jossa jos duplikaatteja on lainkaan, niin keskellä on yksi kanoninen raide, johon on sitten linkitetty (ainoastaan suoraan) mahdollisia muita raiteita; mutta muuten duplikaattien linkittelyä voi tehdä vapaasti ja käsitellä ihan kuin mitä vaan dataa.
> GVT-1476 Fixes to duplicate track handling

- ui/src/api/api-fetch.ts
if a JWT is expired and the message arrives from Geoviite backend we will retry the request.
If the request fails a second time due to the same error a pop up error message is shown (JWT expired)
The fix:  a pop up appears for a re-login.
> GVT-1484 fix retry of expired JWT handling

- ui/src/map/layers/alignment-layer.ts
- ui/src/map/layers/track-number.ts
- ui/src/map/map.module.scss
Pientä hienosääntöä kuinka ratanumeroa näytetään kartalla:
Kartta zoomattuna todella kauas:
Pituusmittauslinjat pelkästään
Kartta zoomattuna kauas:
Pituusmittauslinjat ratanumerolaatikoineen
Kartta zoomattuna lähelle:
Pituusmittauslinjat ratanumerolaatikoineen ja 
sijaintiraiteet ratanumerolaatioineen, joissa on myös sijaintiraiteen nimi
> GVT-1439: Slight changes to how track numbers are displayed on top of alignments

- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/Publication.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/PublishDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/PublishService.kt
- ui/src/publication/publication-details.tsx
- ui/src/publication/publication-model.ts
Etusivun julkaisujen tarkempi näkymä ei päivittynyt automaattisesti. 
Lisätty:
- ajastettu pollaus komponentin sisälle
- status ja ratko push timestamp details-hakuun (API-kutsu ja tietokantahaku)
> GVT-1487 fix publish details automatic update

- ui/src/i18n/fi/fi.json
Huomattu v1 kättöönottopalaverissa. Erillinen tiketti merkistöongelmien tarkemmasta käsittelystä:
https://extranet.vayla.fi/jira/browse/GVT-1493
> General: Add missing XML parsing error localization string

- ui/src/tool-panel/switch/switch-infobox.tsx
Virallista ei välttämättä ole olemassa, ja siinäkin tapauksessa, että vaihde on siirtynyt, oikea näytettävä osoite on nykyversion osoite.
> GVT-1501 Show track meters for current version of switch

- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/SwitchLinkingService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/TrackLayout.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/TrackLayoutController.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/linking/SwitchLinkingServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchServiceIT.kt
- ui/src/tool-panel/switch/switch-infobox.tsx
- ui/src/track-layout/track-layout-api.ts
Kommittiviestin mukaisesti: Sekä segmentille linkitetyt että topologisesti linkitetyt vaihdepisteet tulevat nyt saman vanhan getSwitchJointConnections-API:n kautta, ja frontti käyttää nyt molempien kanssa rataosoitteiden näyttämiseen samaa logiikkaa.
Varsinainen alkuperäinen taski oli tuoda topologiset linkit mukaan "Vaihteen sijaintitiedot"-boksiin niin, että siinä näkyvät myös vaihteelle päätyvät raiteet. Tätä varten ei tarvinnut minkäänlaista muutosta SwitchJointInfoboksin omaan logiikaan, vaan se osaa päätellä yhteyslistasta jo topologiset yhteydet valmiiksi, nyt kun ne tulevat listassa mukana.
> GVT-1500 Consistentify segment-based and topological switch link display

- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/Publication.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/PublishController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/PublishService.kt
- ui/src/preview/preview-view.tsx
- ui/src/publication/publication-api.ts
- ui/src/publication/publication-model.ts
Frontti hakee nyt ensiksi kaikki julkaisuehdokkaat yhden API:n kautta, ja sitten validointi-API:n kautta vielä erikseen niille validointivirheet. Tässä siis back-end tekee periaatteessa vähän ylimääräistä työtä, koska varsinaisen validoinnin yhteydessä se hakee julkaisuehdokkaat uusiksi saadakseen listattua sekä julkaisuyksikköön liittyvät että "loput" muutetut oliot, mutta aikaa siihen ei juuri vaikuta menevän.
> GVT-1510 Separate out a publication candidate validation API

- ui/src/geoviite-design-lib/track-number/track-number-link.tsx
- ui/src/map/layers/alignment-layer.ts
- ui/src/map/layers/layer-utils.ts
- ui/src/map/location-holder/location-holder-view.tsx
- ui/src/selection-panel/alignment-panel/reference-lines-panel.tsx
- ui/src/selection-panel/selection-panel.tsx
- ui/src/selection/selection-model.ts
- ui/src/selection/selection-store.ts
- ui/src/tool-panel/geometry-alignment/geometry-alignment-linking-container.tsx
- ui/src/tool-panel/geometry-alignment/geometry-alignment-linking-infobox.tsx
- ui/src/tool-panel/geometry-alignment/reference-line-names.tsx
- ui/src/tool-panel/location-track/dialog/location-track-edit-dialog.tsx
- ui/src/tool-panel/tool-panel-container.tsx
- ui/src/tool-panel/tool-panel.tsx
- ui/src/track-layout/track-layout-store.ts
Tämä aiheutui ratanumeron valinnan ja pituusmittauslinjan valinnan epäsynkasta koska osa komponenteista valitsi ne aina yhtäaikaisesti käyttäen togglea ja osa valitsi vain pituusmittauslinjan. Oikeassa järjestyksessä klikaten ne menivät ristiin. Koko leikki on sinällään turhaa että pituusmittauslinja on 1=1 ratanumeron kanssa joten poistin pituusmittauslinjan valittavista käsitteistä - ratanumeron valinta on sama asia.
> GVT-1285 Fix reference line selection going out of sync

- ui/src/preview/change-table-entry-mapping.ts
- ui/src/preview/change-table-sorting.ts
- ui/src/preview/preview-table-item.tsx
- ui/src/preview/preview-table.tsx
- ui/src/preview/preview-view.tsx
- ui/src/publication/publication-details.tsx
- ui/src/publication/publication-table-item.tsx
- ui/src/publication/publication-table.tsx
Täällä eriytetty PublicationTable kahdeksi eriliseksi taulukoksi, sillä ne alkoivat eriytymään toisistaan aika merkittävästi. Jotain yhteisiä osia (sorttaus, yhteisten tietojen mäppäys rivi-informaatio-olioksi) lötyy `change-table`-nimen alta
> GVT-1551: PublicationTablen refaktorointia

- ui/src/preview/change-table-sorting.ts
Täällä tehty:
* Laitettu nimivertailu vertaamaan lowercase-arvoja. Aiemmin case vaikutti järjestykseen
* Lisätty listan pituuden mukaan vertailu osaksi virhevertailua tilanteissa, joissa muuten tulisi sama arvo
> GVT-1551: Järjestelyparannuksia

- ui/src/selection-panel/selection-panel.tsx
Periaatteessa selkeämpää voisi kai olla pyöräyttää filterByTrackNumberId useCallback()in sisään, ja sitten passata tämä callback itsessään filteredReferenceLinesin riippuvuudeksi, mutta tässä tapauksessa se ei näyttänyt oikein tähdelliseltä.
> GVT-1552 Update reference line list when track number filter changes

- ui/src/preview/preview-footer.tsx
- ui/src/preview/preview-table-item.tsx
- ui/src/preview/preview-table.tsx
- ui/src/preview/preview-view.tsx
Suurin pihvi täälä on validointi osissa. Huomioita tästä:
Julkaistavien muutosten taulukko validoi vain sen muutosjoukon, jotka on valittu ka. taulukkoon, mutta ylempi taulukko validoi nyt speksistä poiketen aivan koko julkaisemattoman tilan. Tämä johtuu siitä, että muutosten validointi erillisinä voi piilottaa virheitä siten, että ne tulevat näkyviin vasta kun ka. muutokset stagetaan. Esimerkki tällaisesta virheestä on jos tasakilometripiste sijaitsee ennen radan alkua tai sen lopun jälkeen.
Muutoksen stageaminen siirtää ka. muutoksen välittömästä julkaistavien muutosten listaan käyttökokemuksen parantamiseksi. Koska validoinnissa voi kestää, tilacolumnissa näytetään siirretyillä riveillä spinneri siihen saakka kunnes validointi on valmistunut.
> GVT-1525: Muutokset-taulun toimintamuutokset

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchService.kt
[https://extranet.vayla.fi/jira/browse/GVT-1512](https://extranet.vayla.fi/jira/browse/GVT-1512)
> GVT-1512 User shouldn't need to know that some switch names have double empty space in db

- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/PublicationDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchDao.kt
- infra/src/main/resources/db/migration/repeatable/R__05.01_layout_functions.sql
- infra/src/test/kotlin/fi/fta/geoviite/infra/linking/PublicationDaoIT.kt
Rikki oli ratanumeroiden hakeminen topologialinkin kautta (tämä oli jäänyt alkuperäisestä toteutuksesta minulta vaan kokonaan pois) ja näkyminen julkaisulistassa (tämä taisi olla regressio, tai toivottavasti oli kun kyllä se minun mielestä minun jäljiltä toimi); lähinnä jälkimmäisen takia lisätty testit.
> GVT-1554 Improve fetching switch track number links for publication change list

- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryElement.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/inframodel/InfraModelController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/inframodel/InfraModelConversion.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/geometry/GeometryAssertions.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/geometry/GeometryDaoIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/geometry/GeometryDomainTestData.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/inframodel/InfraModelServiceIT.kt
3DWin tuottaa suuntakulmat IM:ään myötäkelloon laskettuna, kun ne pitäisi olla vastakelloon. Toisaalta, ilmoitettuja suuntakulmia ei kannattaisi käyttää muutenkaan.
Taustaa: IM:ssä on paljon ylimääriteltyjä arvoja, mm elementtien suuntakulmat (myös pituus, kaaren chord, jne), jotka ovat myös laskettavissa muusta datasta. Ne ovat kuitenkin speksin mukaan pakollisia. Geoviite ei enimmäkseen käytä näitä lisätietoja, mutta siirtymäkaarten (spiral) tapauksessa se käytti alku/loppu suuntia geometrian laskennassa. Tässä pullarissa muutetaan tuo laskenta käyttämään PI-pistettä (Point of Intersection = alku- ja lopputangenttien kohtauspiste), jolloin ilmoitetuista dir-arvoista ei välitetä tuossakaan tapauksessa ja myös 3DWin:in tuottamat tiedostot näkyvät oikein.
> GVT-1558 Calculate spiral directions from PI-point rather than use the declared values

- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/PublicationController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/PublicationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/DraftableObjectService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutKmPostController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutKmPostService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/geocoding/GeocodingDaoIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/linking/PublicationServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutKmPostServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackServiceIT.kt
- ui/package-lock.json
- ui/package.json
- ui/src/preview/preview-footer.tsx
- ui/src/preview/preview-table-item.tsx
- ui/src/preview/preview-table.tsx
- ui/src/preview/preview-view.scss
- ui/src/preview/preview-view.tsx
- ui/src/preview/translations.fi.json
- ui/src/publication/publication-api.ts
- ui/src/publication/publication-table-item.scss
- ui/src/publication/publication-table.scss
- ui/src/vayla-design-lib/menu/menu.scss
- ui/webpack.config.js
Täällä tehty sekä bäkkäri- että fronttipuoli muutosten yksittäisestä hylkäämisestä. Summa summarum:
- Bäkkäripuolella muutettu `revertPublishCandidates()` ottamaan `PublishRequest`-tyyppisen olion, joka sisältää id:t siitä mitä revertataan (`PublishRequest`in nimen muuttamista voisi ehkä harkita jossain kohtaa)
- Fronttipuolella lisätty joka riville menu, jonka kautta pystyy reverttaamaan vain ka. riviin liittyvän muutoksen. Menut tehdään `react-contexify`-paketilla
- Esikatselunäkymän footerista poistettu Hylkää muutokset -nappi
Tätä tehdessä tuli vastaan juttuja, joita EI tehty vielä tällä tiketillä. Teen näistä omat lippulappunsa Jiraan:
- Revert ei indikoidu operaattorille välitömästi, vaan rivi poistuu taulukosta vasta kun bäkkäri on saanut poistettua draftin ja validoitua kaiken …
> GVT-1527: Muutoksen hylkääminen

- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/PublicationController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/PublicationService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/linking/PublicationServiceIT.kt
- ui/src/preview/preview-confirm-revert-changes-dialog.tsx
- ui/src/preview/preview-view.tsx
- ui/src/preview/translations.fi.json
- ui/src/publication/publication-api.ts
- ui/src/track-layout/track-layout-store.ts
- ui/src/utils/array-utils.ts
Lisätty API, joka hakee julkaistavan asian hylkäämisen riippuvuudet (sekä GVT-1570:n varsinainen juttu eli ratanumeroiden ja pituusmittauslinjojen riippuminen toisistaan, että GVT-1527:ltä jäänyt rekursiivinen sijaintiraiteiden ja vaihteiden haku), ja siirretty hylkäämisen vahvistusdialogi omaksi komponentikseen, joka sitten näyttää riippuvuuslistan.
> GVT-1570 Revert dependencies along with requested object to revert

- infra/src/main/kotlin/fi/fta/geoviite/infra/ratko/RatkoClient.kt
Getting no HTTP response at all gets reported as WebClientRequestException, not WebClientResponseException, and the original implementation would just throw that all the way up to the controller if Ratko in fact was offline.
> GVT-1463 Handle Ratko being offline in getRatkoOnlineStatus

- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/PublicationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/PublicationValidation.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/linking/PublicationValidationTest.kt
Lisäsin puhtaasti yhdenmukaisuusmielessä samassa syssyssä validaation, että vaihdepisteen sijaintia verrataan topologialinkillisen raiteen päätepisteen sijaintiin, ja tämä ei sinällään mitään riko, koska validaatio on varoitustasoinen; mutta en ole varma, onko oikeasti oikein validoida näin.
> GVT-1600 Fix validation for switches with topology links

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/TrackLayout.kt
- ui/src/linking/linking-utils.ts
- ui/src/track-layout/track-layout-model.tsx
Lisäsin nämä hakuun aikoinaan sen alkuperäisen käsityksen perusteella, miten GVT-1349 oli tarkoitus toteuttaa, mutta eipä ollutkaan. Tässä vaiheessa olikin poistettu jo näiden ainoa käyttöpaikka.
> General: Remove fallback switch joint matches

- infra/src/main/kotlin/fi/fta/geoviite/infra/dataImport/CsvParsing.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geography/GeoToolsGeometries.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/BoundingPolygon.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/LinkingService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/SwitchLinkingService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/ratko/model/RatkoCommonModel.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/Transformation.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/dataImport/CsvImportIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/dataImport/CsvParsingTest.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/geometry/TransformationTest.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/linking/LinkingTest.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/linking/SwitchLinkingServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/math/GeographyTest.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/testdata/CommonTestData.kt
Täällä toteutettu parempi erottelu Transformation-luokkaan kolmiointiverkon vaativien KKJx->ETRS-TM35FIN -muunnosten ja muiden välille. Nyt Transformation-olioiden luonnille on selkeästi eriytetyt funktiot, ja väärän käyttäminen heittää poikkeuksen. Samalla lisätty kolmioverkon välittämistä kohtiin, jossa on aiemmin ollut mahdollista tehdä transformeja KKJ-koordinaatistoista TM35:een ilman kolmioverkkoa.
> GVT-1596: Suunnitelmien importissa KKJ-muunnoksiin tulee heittoa

- ui/start_front.sh
npm ci tries to clear it anyway, but is too timid to do it properly.
> General: Manually clear node_modules in start_front.sh

- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/PublicationService.kt
This can occur when creating an entirely new track number, and placing the reference line in the publishable set first.
> GVT-1603 Fix validating reference line with inexistent track number

- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/PublicationService.kt
These objects might actually be related to the track number, but they might also just be included in the publication.
> GVT-1611 Filter track number related objects in PublicationService fetchers

- ui/src/tool-panel/km-post/dialog/km-post-edit-dialog.tsx
- ui/src/tool-panel/km-post/dialog/km-post-edit-store.ts
Tässä ongelmana ei ollutkaan varsinainen fronttipään validointi, vaan bäkkärikysely jolla kyseltiin onko ka. numerolla olemassa jo kilometripistettä. Tämä vaikutti fiksuimmalta korjata frontin päässä. Lisäsin ka. kyselyyn tarkastuksen, että kysellään kilometripisteen olemassaolevuutta vain jos kyseessä ylipäätään on järkevä kmnumber-arvo.
> GVT-1635: Uuden kilometripylvään nimeäminen väärin aiheuttaa bäkkärivirheitä

- ui/package-lock.json
- ui/package.json
Täällä oli tarkoituksena tutkia vieläkö uusin react-select käyttää inline-tyylejä. Uusia CSP:n kannalta kivempia tyylittelymahdollisuuksia on tullut uusimman version myötä, mutta react-select käyttää silti myös inline-stylejä, joten päädyin lopulta pelkästämään päivittämään komponentin sen kummemmin tyyleihin koskematta.
> GVT-1519: Update react-select to 5.7.0

- ui/src/preview/preview-view.tsx
Edelliseen unohtui taulukoiden uudelleenpiirtoon kaksi trigger-depsua. Yhtenäistetty ne käyttämään tokenia
> GVT-1646: Redraw-logiikan yhtenäistäminen

- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryPlan.kt
- ui/src/common/navigate.ts
- ui/src/geometry/geometry-model.ts
- ui/src/infra-model/infra-model-main-container.tsx
- ui/src/infra-model/infra-model-main-view.tsx
- ui/src/infra-model/infra-model-store.ts
- ui/src/infra-model/list/infra-model-list-container.tsx
- ui/src/infra-model/list/infra-model-load-button.tsx
- ui/src/infra-model/view/infra-model-edit-loader.tsx
- ui/src/infra-model/view/infra-model-toolbar.tsx
- ui/src/infra-model/view/infra-model-view-container.tsx
- ui/src/infra-model/view/infra-model-view.tsx
- ui/src/main/main.tsx
- ui/src/tool-panel/geometry-plan-infobox.tsx
- ui/src/tool-panel/translations.fi.json
Selvästi isoin osa muutosta: Jotta sai linkityksen inframodel-osioon toimimaan järkevästi, siirsin tiedon siitä, missä tilassa (list/upload/edit) ollaan, ja että mitä inframodelia ollaan edit-tilassa katsomassa, nyt storesta URLiin; edit-tilan sivut lataa nyt sisältönsä useEffect()illä, ja liikkeet inframodel-osion sisällä menee luonnostaankin myös nyt sitten vaan navigoimalla. Back-nappikin toimii siellä nyt!
En ole ihan satavarma, onko navigate.ts järkevä suuntavaihtoehto, vai kannattaisiko ennemminkin käyttää jotain valmista tyyppiturvallista URL-kirjastoa, tai jättää keskittämättä URLeja lainkaan, tms..
> GVT-1641 Add new fields & inframodel link to geometry infobox

- infra/src/main/resources/db/migration/repeatable/R__03.17.layout_reference_line_version_track_number_id_change_time_index.sql
- infra/src/main/resources/db/migration/repeatable/R__03.18.layout_track_number_version_change_time_index.sql
Yhtäältä nämä taulut on todella pieniä eivätkä tule kasvamaan nopeasti, mutta toisaalta getGeocodingContextCacheKey()tä kutsutaan kyllä melko paljon, eli kokonaisuutena lienee parempi, että nämä indeksit on systemaattisesti olemassa.
> GVT-1581 Add indexes for remaining tables used in geocoding context key query

- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryController.kt
Aiemmat oli PostMappingeja vaikka halutaan GetMappingit. Samalla camelCasetettu yhden parametrin nimi.
> GVT-1634 & GVT-1637: Korjaus endpointteihin

- infra/src/test/kotlin/fi/fta/geoviite/infra/inframodel/InfraModelServiceIT.kt
Pääjuttuna tuo clearPlanFiles jotta testit saa ajettua peräkkäin putsaamatta välissä koko tietokantaa, lisäsin samalla uuden testin kun sattui nuo duplikaattivirheet olemaan mielessä.
> Improve InframodelIT tests

- infra/src/main/kotlin/fi/fta/geoviite/infra/configuration/SecurityConfiguration.kt
Pääjuoni tuo securityContext().disable(). Vanhalla tavalla konffatessa `springSecurityFilterChain`iin ei ilmesty `SecurityContextPersistenceFilter`iä oletuksena lainkaan, mutta uudella ilmestyy: Ja sekös asiat rikkoo, koska oletuksena se yrittää ladata persistoidun SecurityContextin, paitsi että oletuspersistointitapa on vain luoda uusi konteksti, ja sinne sitten katoaa meidän `RequestFilter`in luoma autentikointi.
Toinen vaihtoehto olisi ollut siirtää `RequestFilter` itse `springSecurityFilterChain`iin, kätevästi käsillä olevalla `HttpSecurity`n `addFilterAfter`-metodilla juuri tuon `SecurityContextPersistenceFilter`in jälkeen, jolloin se ei enää saisi kadotettua meidän autentikointia. Siinä vaan on oma rumuutensa, kun luokkaan olisi pitänyt viitata suoremmin, ja se pentele on vieläpä …
> GVT-1469 Update SecurityConfiguration to not use deprecated features

- ui/src/tool-panel/geometry-alignment/geometry-alignment-infobox.tsx
- ui/src/tool-panel/geometry-plan-infobox.tsx
- ui/src/tool-panel/translations.fi.json
Näissä tilanteissa infoboksia ei näkynyt ollenkaan, joten operaattorin piti Tietää^TM, että segmentin valittua siitä näkyy tarkemmat myös pysty- ja vaakageometriaelementtitiedot. Tässä toteutettu infoboksin tynkä, jossa operaattorille ilmoitetaan asiasta.
> GVT-712: Pysty- ja vaakageometrioiden infoboksi silloin kun segmenttiä ei ole valittu

- infra/src/main/kotlin/fi/fta/geoviite/infra/integration/CalculatedChangesService.kt
The called code was already prepared for nulls, and if the switch is in fact new and not selected to be published, it indeed doesn't exist.
> GVT-1671 Remove switch existence assumption

- ui/src/preview/preview-confirm-revert-changes-dialog.tsx
Kyseessä olikin bugi kilometripylväiden revertissä. Riippuvia kilometripylväitä ei näytetä koskaan hylkäysvahvistusdialogissa (oletettavasti koska niitä ei pitäisi koskaan olla.) Samalla kilometripylväille ei tehty samanlaista filtteröintiä kuin muille tyypeille, jolloin kilometripylväs itsensä näkyi itsensä dependencynä.
> GVT-1670: Selvennä vahvistusviestiä joka näytetään muutosta hylättäessa

- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/CsvTranslations.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/ElementListing.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/inframodel/InfraModelController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/util/ResponseEntity.kt
- ui/src/data-products/element-list/continuous-geometry-search.tsx
- ui/src/data-products/element-list/element-list-store.ts
- ui/src/data-products/element-list/element-list-view.scss
- ui/src/data-products/element-list/element-list-view.tsx
- ui/src/data-products/element-list/element-table-item.tsx
- ui/src/data-products/element-list/element-table.tsx
- ui/src/data-products/element-list/plan-geometry-search.tsx
- ui/src/data-products/translations.fi.json
- ui/src/geometry/geometry-api.ts
- ui/src/geometry/geometry-model.ts
- ui/src/vayla-design-lib/table/table.scss
- ui/src/vayla-design-lib/table/table.tsx
Tämä lähti vähän käsistä. Päädyin refakkaamaan koko elementtilistauksen komponenttirakenteen yhden frontin tyylijutun takia. Toisaalta sikäli uusi malli on parempi, että vaihtaessa listaustyyppiä vanhat hakuparametrit ja -tulokset säilyvät nyt.
Samalla tehty alkuperäiselle reviewille mainittuja review-korjauksia.
> GVT-1669: Raidetiedon selkeytys elementtiluettelossa + muita refaktorointeja

- infra/src/main/kotlin/fi/fta/geoviite/infra/integration/RatkoPushDao.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/integration/RatkoPushDaoIT.kt
En saanut tätä toistumaan muuten kuin että tein samaan ratkopuskuun useamman virheen (tilanne, jonka luulin alunperin olevan mahdoton.) Tällöin näytettiin jokin satunnainen virhe, sillä erroreita ei varsinaisesti oltu järjestetty ollenkaan. Korjattu nyt niin, että varmasti tulee aina uusin virhe.
> GVT-1409: Ratko-viennissä kuuluisi näyttää aina uusin virhe

- ui/src/geoviite-design-lib/accordion/accordion.scss
- ui/src/geoviite-design-lib/accordion/accordion.tsx
- ui/src/geoviite-design-lib/eye/eye.scss
- ui/src/geoviite-design-lib/eye/eye.tsx
- ui/src/selection-panel/geometry-plan-panel/geometry-plan-panel.tsx
- ui/src/selection-panel/selection-panel-geometry-section.tsx
- ui/src/selection-panel/selection-panel.scss
- ui/src/selection-panel/selection-panel.tsx
- ui/src/utils/react-utils.tsx
Isohko pullari, koska aiemmin GeometryPlanPanel piti itse huolta yksittäisten suunnitelmien lataamisesta, mutta nyt kun halutaan pystyä lataamaan iso joukko suunnitelmia kerralla, Reactimaisesti korrekti tapa oli vetää tila ylempään komponenttiin; päädyin erottamaan sen omaksi SelectionPanelGeometrySection-komponentikseen, jotta ihan kaikki suunnitelmien lataamiseen liittyvä koodi ei olisi sekaisin muiden SelectionPanel-juttujen kanssa.
Muutin tämän siirron yhteydessä vielä muutaman muuttujan nimen hieman selkeämmäksi, niin että SelectionPanelGeometrySectionissa näkyy vähän selkeämmin, mitkä asiat riippuvat vaan siitä, mitkä suunnitelmat ovat kartalla juuri sillä hetkellä näkyvillä.
> GVT-1677 Add common eye button to geometry plan panel

- ui/src/preview/preview-footer.tsx
Edellinen osui väärään dialogiin, mutta sielläkin toki tarvittiin sulkeminen. Nyt myös itse julkaisun confirm-dialogissa.
> GVT-1682 Allow closing publish confirmation dialog

- ui/src/linking/linking-status.tsx
- ui/src/linking/linking-utils.ts
- ui/src/tool-panel/switch/geometry-switch-linking-candidates.tsx
- ui/src/tool-panel/switch/geometry-switch-linking-errors.tsx
- ui/src/tool-panel/switch/geometry-switch-linking-infobox.tsx
- ui/src/tool-panel/switch/geometry-switch-linking-start-button.tsx
- ui/src/tool-panel/switch/switch-infobox.scss
- ui/src/tool-panel/switch/switch-joint-infobox-container.tsx
- ui/src/track-layout/layout-switch-api.ts
Olipas työmaa, ja pahoittelut jo etukäteen siitä minkälainen samanlainen tämän reviewin lukeminen tulee olemaan. Lopulta en oikeastaan tainnut edes tehdä varsinaisesti mitään sille, että nappi tulisi näkyviin yhtään aiempaa paremmin. Nappi ja virheilmoitus ovat molemmat sellaisia, että ennen kuin ne voidaan näyttää, useamman eri bäkkärihaun pitää mennä kunnialla läpi. Jos operaattori kliksuttelee ympäriinsä paljon, on ihan täysin luonnollista, että selain tai bäkkäri voi mennä tarpeeksi tukkoon että joku requesti kestää pitkään tai hukkuu jonnekin. Nyt näytetään spinneri napin/virheilmon sijasta silloin kun sitä ladataan, joka ainakin omasta mielestäni on sentään fiksumpi tapa ilmaista tuo odottelu.
Päädyin tässä tekemään aika ekstensiivistä refakkia tuolle infoboksille, sillä wanha …
> GVT-1617: "Aloita linkitys" -nappi ei tule aina näkyviin vaihteelle

- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/CsvTranslations.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/ElementListing.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/util/CSVPrintingUtils.kt
Wanha malli CSV-generointiin oli vähän... kehno ja ei-skaalautuva. Tein nyt CSVEntry-dataclassin, joka yhdistää datan ja sen otsikon. Nyt columnien reorder menee käytännössä sillä, että vaan järjestellään uudelleen printattavat CSVEntryt
> GVT-1688: Elementtiluettelon CSV vastaamaan taulukkoa UI:ssa + refaktorointia

- ui/src/data-products/element-list/continuous-geometry-search.tsx
- ui/src/data-products/element-list/element-list-store.ts
Täällä toteutettu (vähän speksin ulkopuolelta) myös alku- ja loppuarvojen nollaaminen silloin kun sijaintiraidetta vaihdetaan. Jos tätä ei halutakaan, voidaan tehdä jotain muuta tilalle.
> GVT-1696: Elementit haetaan vaikka rataosoite on virheellinen

- ui/src/data-products/element-list/continuous-geometry-search.tsx
- ui/src/data-products/element-list/element-list-view.scss
- ui/src/data-products/element-list/element-list-view.tsx
- ui/src/data-products/element-list/plan-geometry-search.tsx
- ui/src/data-products/translations.fi.json
Samalla muutin termin "Jatkuva geometria" figmassa olleen "Raiteen geometria" mukaiseksi
> GVT-1701: Elementtiluettelo: Jatkuvalle geometrialle ja suunnitelmatilaiselle geometrialle saatesanat / selitys / kuvaavammat termit

- ui/src/cache/cache.ts
- ui/src/track-layout/layout-location-track-api.ts
- ui/src/track-layout/layout-switch-api.ts
- ui/src/utils/array-utils.ts
AsyncCachella pysyy yhä se ominaisuus, että sen sisältö ja changeTime vastaavat toisiaan (sikäli kuin tehdään muutosajallisia hakuja); tämä vaikuttaa toteutukseen niin, että getMany()ssä ei pysty ensiksi odottamaan haun tulosta ja vasta sitten lyömään tuloksia cacheen, koska jos näin tehtäisiin, niin tulokset olisivat voineet haun aikana vanhentua.
(Tosin en vielä tässä ottanut muutosaikoja mukaan näihin getMany()-kutsuihin, kun olisi pitänyt tehdä vastaavia säätöjä niitä käyttäviin komponentteihin; kaikki aikanaan)
> GVT-1428 Cache mass-fetches on frontend

- infra/build.gradle.kts
- infra/src/main/kotlin/fi/fta/geoviite/infra/dataImport/CsvParsing.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geography/CoordinateTransformationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geography/KKJtoETRSTriangulationDao.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/dataImport/CsvImportIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/geography/KkjToEtrsTriangulationDaoIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/geometry/TransformationTest.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/testdata/CommonTestData.kt
Täällä otettu käyttöön R*-puu KKJx->TM35FIN-muunnoksen kolmioverkon kolmiohaun nopeuttamiseksi. Mitään sen kummempia perffitestejä en ajanut, mutta tämän luul_isi_ ainakin nopeuttavan kolmioiden etsimistä merkittävästi
> GVT-1723: KKJ-kolmioverkkomuunnoksen optimointi

- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/DraftableObjectDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/DraftableObjectService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutKmPostController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/util/DaoBase.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/geometry/GeometryDaoIT.kt
- ui/src/data-products/element-list/plan-geometry-search.tsx
- ui/src/geometry/geometry-api.ts
- ui/src/infra-model/list/infra-model-list-container.tsx
- ui/src/linking/linking-utils.ts
- ui/src/selection-panel/geometry-plan-panel/geometry-plan-panel.tsx
- ui/src/selection-panel/selection-panel-geometry-section.tsx
- ui/src/selection/selection-model.ts
- ui/src/selection/selection-store.ts
- ui/src/tool-panel/alignment-plan-section-infobox-content.tsx
- ui/src/tool-panel/geometry-plan-link.tsx
- ui/src/tool-panel/km-post/geometry-km-post-linking-infobox.tsx
- ui/src/tool-panel/tool-panel-container.tsx
- ui/src/tool-panel/tool-panel.tsx
- ui/src/track-layout/layout-km-post-api.ts
Tämä eskaloitui taas vähän kun oli muitakin tätä kokonaisuutta läheltä liippaavia juttuja:
* Fronttipuolelle suunnitelmien geometriat -infoboksin suunnitelmalinkit valkkaavat nyt ka. suunnitelman toolpanelista
* Tämän takia selectionissa planheaderit piti muuttaa niin, että niistä tallennettiin pelkkä id
* Tätä myötä planheadereille oli fiksua tehdä massahaku ja ottaa se käyttöön kaikkialla
* Kun nyt tuli koskettua massahakuihin, niin tein samalla myös kilometripylväille massahaun ja otin sen käyttöön
* Samalla kävin läpi muutakin massahakukoodia ja korvasin muita vanhoja `Promise.all()`-muotoisia massahakuja uusilla, oikeilla massahauilla
* Tein täällä tiketin GVT-1437 review-korjaukset, koska ne liittyivät kanssa massahakuihin
Eli tän reviewin koodimuutoksista ehkä noin 20% liittyy …
> GVT-1739: Raiteen geometriat näkymässä suunnitelman klikkaus pitäisi valita suunnitelma + massahakujuttuja

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutAlignmentService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutAlignmentTest.kt
Merge oli liian aggressiivinen eikä ottanut huomioon sitä, että myös pelkkä tiedostonimi voi vaihtua. Tämä otetaan nyt huomioon. Lisäksi tehty regressiotesti.
> GVT-1741: Geoviite-toteutus Raiteen geometriat -näkymä näyttää ehkä väärää tietoa

- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/PublicationValidation.kt
- ui/src/preview/translations.fi.json
Täällä korjattu alkuperäinen räjähtävä validaatio ja sen lisäksi lisätty ka. tilanteelle uusi validaatio, jossa pyydetään operaattoria linkittämään koko vaihde uudelleen raiteeseen.
> GVT-1743: Virhe kun validoidaan raidetta

- ui/src/i18n/fi/fi.json
- ui/src/main/main.tsx
- ui/src/track-layout/track-layout-store.ts
- ui/src/version-holder/version-holder-view.tsx
Käytännössä tämä toimii nyt niin, että tallennetaan versioinformaatio `trackLayoutStore`en ja verrataan sitä backendiltä tulevaan. Tallennuspaikka ei ole ideaalinen, mutta en halunnut lähteä tekemään pelkästään tälle kokonaan omaa storea, ja `Main`-komponentissa käytettiin `trackLayoutStore`a jo valmiiksi.
Ensimmäisellä versiopäivityksellä storea ei vielä clearata, sillä tämän erikoistapauksen tunnistaminen olisi johtanut ylimääräiseen monimutkaisuuteen ja mahdollisiin false positiveihin resettikoodissa.
> GVT-1746: Välimuistin automaattinen tyhjennys päivityksen yhteydessä

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutAlignmentDao.kt
- infra/src/main/resources/db/migration/prod/V32__separate_segment_geometry.sql
Palautetaan segmenttitauluun start-pituus helpompia m-arvoon pohjautuvia hakuja varten. Poistin tuon tiedon segmenttirempan yhteydessä kosksa saman saa yhtä kaikki summaamalla aiempien segmenttien pituuden eikä sitä käytetty missään. Huomattiin kuitenkin Karin kanssa että tietyissä hauissa se olisi erittäin näppärä, joten palautetaan se vielä.
> GVT-1691 Restore segment start value in DB for easier m-value fetching

- ui/src/frontpage/frontpage.tsx
- ui/src/publication/card/publication-card.tsx
- ui/src/publication/translations.fi.json
Päädyin tässä poistamaan tuon viikkofiltteröinnin kokonaan ja vaan näyttämään X viimeisintä julkaisua. Ajattelin, että tämä on se, miten itse haluaisin tuon näkymän toimivan jos olisin itse operaattorin housuissa. API sivuttaa edelleen julkaisuja bäkkärin päässä, mutta kaiken järjen mukaan epäonnistuneiden julkaisujen pitäisi olla aina uusimpia julkaisuja, joten tiketillä kuvattu alkuperäinen ongelma pitäisi ratketa tällä
> GVT-1768: Julkaisun manuaalinen vienti ei ole mahdollista mikäli edellisestä julkaisusta on yli viikko

- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/PublicationController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/PublicationDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/PublicationService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/integration/RatkoPushDaoIT.kt
- ui/src/frontpage/frontpage.tsx
- ui/src/publication/card/publication-card.tsx
- ui/src/publication/publication-api.ts
Tästä tuli vähän välimallin ratkaisu. Tämäkin on (mielestäni) fiksu steppi tähän, mutta myös itse julkaisujen haku kaipaisi vähän rakastavaa kosketusta. Siellä tehdään nyt varmaan toistakymmentä round-trippiä kantaan _per julkaisu_, ja niitä olisi todennäköisesti mahdollista yhdistää yksittäisiksi hauiksi
> GVT-1768: Bäkkärirajapinta X uusimman julkaisun hakemiseen

- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/ElementListing.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryAlignment.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/ListingCommon.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/VerticalGeometryListing.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/geometry/VerticalGeometryListingTest.kt
- ui/src/data-products/translations.fi.json
- ui/src/data-products/vertical-geometry/vertical-geometry-table-item.tsx
- ui/src/data-products/vertical-geometry/vertical-geometry-table.tsx
- ui/src/data-products/vertical-geometry/vertical-geometry-view.tsx
- ui/src/geometry/geometry-model.ts
- ui/src/vayla-design-lib/table/table.scss
- ui/src/vayla-design-lib/table/table.tsx
Täällä toteutettuna siis suunnitelman pystygeometria-API:a vastaava API myös sijaintiraiteille. Samalla tehty vähän refaktorointia, sillä osa aiemmin elementtiluettelospesifisestä koodista on validia täälläkin. Ne on nyt eriytetty elementtiluettelosta vielä kokonaan omaksi kokonaisuudekseen, jota nämä molemmat käyttävät.
> GVT-1733: API: Raiteen pystygeometria

- ui/src/i18n/fi/fi.json
- ui/src/main/main.tsx
LocalStoragen clearaaminen tuntuu tarvitsevan jonkinlaista käyttäjäinputtia toimiakseen, ja siksi vanha tapa ei toiminut. Vaihdettu siten ilmoitusmekanismi alertista dialogiksi. Samalla tehty muitakin pienempiä versiopäivitykseen liittyviä quality-of-life-juttuja (merkattu kommenteilla)
> GVT-1777: Versiopäivityksen localstorage-clear ei toimi oikein

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutKmPostController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutKmPostService.kt
- ui/src/app-bar/app-bar.tsx
- ui/src/data-products/data-product-view.scss
- ui/src/data-products/data-products-store.ts
- ui/src/data-products/element-list/location-track-element-listing-search.tsx
- ui/src/data-products/element-list/plan-geometry-element-listing-search.tsx
- ui/src/data-products/kilometer-lengths/kilometer-lengths-container-with-provider.tsx
- ui/src/data-products/kilometer-lengths/kilometer-lengths-search.tsx
- ui/src/data-products/kilometer-lengths/kilometer-lengths-table-item.tsx
- ui/src/data-products/kilometer-lengths/kilometer-lengths-table.tsx
- ui/src/data-products/kilometer-lengths/kilometer-lengths-view.tsx
- ui/src/data-products/translations.fi.json
- ui/src/data-products/vertical-geometry/location-track-vertical-geometry-search.tsx
- ui/src/geometry/geometry-api.ts
- ui/src/main/main.tsx
- ui/src/track-layout/layout-km-post-api.ts
- ui/src/track-layout/track-layout-model.tsx
Nämä oli kätevintä tehdä yhtenä isona möllinä. Menee hyvin samalla kaavalla kuin elementtiluettelo ja pystygeometriat. Muita täällä tehtyjä pikkujuttuja:
- `EnvRestricted` pois pystygeometrialistan ympäriltä, kun se on menossa tuotantoon
- Siivoiltu never-tyypityksiä järkevämmiksi frontissa (pääasiassa pystygeometrian osalta)
> GVT-1753 & GVT-1754 & GVT-1755: Kilometrien pituus -sivun UI-jutut

- infra/src/main/kotlin/fi/fta/geoviite/infra/geocoding/Geocoding.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/AlignmentHeights.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutGeometry.kt
Pystygeometriakaavion korkeusviivan haun rakenteessa frontin tarpeet osoittautuivat lopulta sellaiksi, että:
- Frontti tietää näyttämänsä välin alku-ja loppukohdan etäisyyksinä raiteella (m-arvo), ja pyytää bäkkäriltä tämän välin korkeusviivaa
- Frontti esitettää haluamansa korkeusviivan tarkkuuden metreinä rataosoiteavaruudessa, niin että paras mahdollinen tarkkuus on ilmoittaa korkeus jokaiselle metrille eli tickLength=1, mutta jos näytetään pitkää raidetta kokonaisuutena, se voi mennä vaikka tasolle että tickLength=500 tai tickLength=1000
- Bäkkäri palauttaa tulokset ratakilometreittäin niin, että niille saa helposti tulevaisuudessa tehtyä ratakilometri+tickLength-yhdistelmällä frontissa pyörivän cachen
Lisäksi lasken nyt samassa syssyssä ja lähetän jokaisen pyynnön mukana koko …
> GVT-1722 Backend for fetching alignment heights

- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/CsvTranslations.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/VerticalGeometryListing.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/geometry/VerticalGeometryListingTest.kt
- ui/src/data-products/data-product-table.scss
- ui/src/data-products/element-list/element-list-view.tsx
- ui/src/data-products/element-list/element-table.tsx
- ui/src/data-products/element-list/location-track-element-listing-search.tsx
- ui/src/data-products/element-list/plan-geometry-element-listing-search.tsx
- ui/src/data-products/kilometer-lengths/kilometer-lengths-search.tsx
- ui/src/data-products/kilometer-lengths/kilometer-lengths-table.tsx
- ui/src/data-products/kilometer-lengths/kilometer-lengths-view.tsx
- ui/src/data-products/translations.fi.json
- ui/src/data-products/vertical-geometry/location-track-vertical-geometry-search.tsx
- ui/src/data-products/vertical-geometry/plan-vertical-geometry-search.tsx
- ui/src/data-products/vertical-geometry/vertical-geometry-table-item.tsx
- ui/src/data-products/vertical-geometry/vertical-geometry-table.tsx
- ui/src/data-products/vertical-geometry/vertical-geometry-view.tsx
- ui/src/geometry/geometry-model.ts
- ui/src/publication/table/publication-table.scss
- ui/src/publication/table/publication-table.tsx
- ui/src/vayla-design-lib/table/table.scss
- ui/src/vayla-design-lib/table/table.tsx
Tiketillä oli mainittu pitkä lista muutoksia, ja niistä on toteutettu melkein kaikki. Ainoastaan pyöristyksettömien raiteiden indikointi jäi pois, sillä en keksinyt UI-teknisesti fiksua tapaa näyttää niitä, kun koko nykyinen taulukko nojaa pyöristysten olemassaoloon. Näiden lisäksi taulukoiden latausbackdropista tehty `Table`-komponentin ominaisuus ja lisätty sen käyttö muillekin tietotuotteille
> GVT-1787: Pystygeometria-tietotuotteen muutokset

- ui/src/vayla-design-lib/table/table.scss
- ui/src/vayla-design-lib/table/table.tsx
Tämä johtui viime viikolla tekemästäni muutoksesta, joka teki latausindikaatiosta taulukon ominaisuuden. Näköjään menut eivät tykänneet sen tuomasta position-relativesta. Muutettu se nyt niin, että relatiivisuus asetetaan päälle ainoastaan kun taulukko on latausindikaatiotilassa, jolloin taulukkoa ei voi kliksutella muutenkaan
> GVT-1811: Esikatselun taulukoissa "Hylkää muutos" -valinta karkaa oikeaan alakulmaan

- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/CsvTranslations.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/ElementListing.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/ListingCommon.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/VerticalGeometryListing.kt
Täällä tehty:
* Korjattu isPartial-laskenta (käytetään elementtien ja segmenttien pituuksia rataosoitteiden sijaan)
* Huomiot mukaan CSV:hen
> GVT-1788: Korjauksia elementtlilistauksen korjauksiin

- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/geometry/GeometryServiceIT.kt
Juuse oli spotannut aikaisemmasta bäkkäristä, että siinä haettiin vähän oudolla tavalla noita välejä, joissa suunnitelma muuttuu: Ja niinhän se olikin, että niiden käyttö oli päin honkia.
Nyt lasketaan suunnitelmien muutoskohdat korrektimmin ja vähemmällä indeksimuljailulla niin, että frontti saa aina korkeusviivan pisteet järjestyksessä; puuttuvien korkeuksien vierestä korkeusviivan pisteet mahdollisimman läheltä (jotta sen ei tarvitse ekstraploida korkeusviivaa); ja vielä myös erikseen yhteenvedon siitä, miten raidetta yleensäkin on linkitetty.
Pienenä bonusmuutoksena mukana myös sijaintiraiteen draft/official-tilan valinta.
> GVT-1722 Tests and fixes for alignment heights backend

- infra/src/main/kotlin/fi/fta/geoviite/infra/geography/KkjEtrsTransformation.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/geometry/CoordinateTransformServiceIT.kt
Pohjimmaisena bugina tässä oli se, että KKJ1-koordinaatiston SRID:hen oli lipsahtanut näppäilyvirhe. Tämä on nyt korjattu, ja tämän lisäksi tehty testit jotka varmistavat, että kaikki KKJ-TM35-muunnokset varmasti toimivat oikein molempiin suuntiin
> General: Korjaa KKJ1-koordinaattimuunnokset

- ui/src/app-bar/app-bar.tsx
- ui/src/app-bar/translations.fi.json
- ui/src/geometry/geometry-api.ts
- ui/src/geometry/geometry-model.ts
- ui/src/main/main.tsx
- ui/src/utils/array-utils.ts
- ui/src/utils/math-utils.ts
- ui/src/vertical-geometry/coordinates.ts
- ui/src/vertical-geometry/demo-page.tsx
- ui/src/vertical-geometry/height-graph.tsx
- ui/src/vertical-geometry/height-lines.tsx
- ui/src/vertical-geometry/height-tooltip.tsx
- ui/src/vertical-geometry/labeled-ticks.tsx
- ui/src/vertical-geometry/plan-linking.tsx
- ui/src/vertical-geometry/point-indicator.tsx
- ui/src/vertical-geometry/pvi-geometry.tsx
- ui/src/vertical-geometry/snapped-point.ts
- ui/src/vertical-geometry/track-address-ruler.tsx
- ui/src/vertical-geometry/track-meter-index.ts
- ui/src/vertical-geometry/translate.tsx
- ui/src/vertical-geometry/util.ts
- ui/src/vertical-geometry/vertical-geometry-diagram.scss
- ui/src/vertical-geometry/vertical-geometry-diagram.tsx
Koodikasa. Tämä tuo siis nyt ensimmäisen version korkeuskaavion fronttipuolesta, ja väliaikaisen vain devissä näkyvän sivun, jolla kokeilla eri alignmenttien (paikannuspohja- ja geometriapuolelta) lataamista ja näyttämistä.
Tärkeimmät konseptit koodin lukuun:
- Kaikki on ihan vaan puhdasta SVG:tä (ja vähän perinteistä HTML:ääkin) käsittelevää React-koodia
- Koordinaatisto on pikseleitä tai ainakin jotain pikselinoloisia otuksia SVG:n viewboxin määrittelemässä avaruudessa
- Kaikki oliot asetellaan leveysakselille m-arvon mukaan; konversioita m-arvojen ja pikseliarvojen välillä tapahtuu ehkä vielä vähän liian monessa paikassa
- SVG:n piirtäminen menee maalarin algoritmilla, eli jokainen uusi elementti piirtyy aina entisten päälle; elementtien järjestyksellä on tällä tavalla väliä …
> GVT-1722 Initial vertical geometry diagram front-end

- ui/src/tool-panel/geometry-alignment/geometry-alignment-linking-candidates.tsx
Ei sinällään komea ratkaisu: Komeamman saisi periaatteessa esim. vaihtamalla `map`it `flatMap`eiksi ja palauttamalla tyhjän listan jos reffiä ei löytynyt, tai suodattamalla ihan erillisenä askeleena; mutta tämä on minusta sekä yksinkertaisempi muutos että oikeastaan selkeämpi esitystapa.
> General: Avoid console warnings when linking track geometry

- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/geometry/GeometryServiceIT.kt
- ui/src/vertical-geometry/snapped-point.ts
Lähetettäviä pisteitä nysvätään nyt hieman tarkemmin niin, että niitä ei tule enää niin lähekkäin aivan ratakilometrien lopuissa eikä suunnitelmanvaihdosten ympärillä. Ero näkyy käytännössä niin, että ilman tätä kommittia korkeuskaaviossa hyvin usein juuri ja juuri kilometria pitemmillä ratakilometreillä lähetettiin piste metrille 1000, ja erikseen seuraavan kilometrin alkuun, mikä näkyi suttuna kaavion piirtämisessä.
> GVT-1833 Pituuskaavion renderöintisotkuja kilometripisteiden ja suunnitelmanvaihdosten ympärillä vähemmäksi

- ui/package-lock.json
- ui/package.json
- ui/src/vertical-geometry/demo-page.tsx
- ui/src/vertical-geometry/vertical-geometry-diagram.scss
- ui/src/vertical-geometry/vertical-geometry-diagram.tsx
Rakensin korkeuskaavion alkuaan rajapintojen yksinkertaisuutta ajatellen niin, että se tietää sijaintinsa startM- ja endM-tietoina, mutta dynaamisen leveyden kanssa tämä valinta hankasi vähän vastaan, koska selainkäyttöliittymissähän on yleensä tapana, että ikkunan koon muuttaminen ei muuta zoomia vaan rajaa vaan näytettävää sisällön osaa: Siis luonnostaan pitäisi oikeastaan olla niin, että leveyden muuttuessa mMeterLengthPxOverM pysyy samana, ja endM muuttuu, ja siten siis mMeterLengthPxOverM on oikeastaan se, jonka pitäisi olla komponentin tilassa.
Mutta en tämän yhden epäsuoruuden takia nyt lähtenyt muuttamaan tilanhallintaa, vaan löin sen sijaan ResizeObserverilla reagoinnin että endM korjataan elementin leveyden muuttuessa.
> GVT-1830 Make height diagram width dynamic

- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationService.kt
- ui/src/preview/preview-view.tsx
Itse validointi on nyt melko nopea (1-2s). Se vielä kestää kun haetaan vaihteiden ratanumeroita. Sitä pitäisi ehkä miettiä muutenkin vähän uudelleen ja on vähän juteltukin siitä että koko raide-vaihde-linkin voisi siirtää poist segmenteiltä jne.
Debounce hoitaa että frontti ei tapa backaria kun pitkää muutoslistaa kliksuttelee mukaan julkaisuun. Voisi vielä tehdä sen "lisää kaikki" toiminnon mutta se tuntui jo vähän omalta tiksultaan. Nämä auttaa jo aika paljon.
> GVT-1845 Fix performance issues in publication validation

- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/AlignmentHeights.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/map/AlignmentGeometry.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/PlanLayoutTransformation.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/geometry/GeometryServiceIT.kt
- ui/src/geometry/geometry-api.ts
- ui/src/map/map-model.ts
- ui/src/map/map-store.ts
- ui/src/tool-panel/location-track/location-track-infobox-linking-container.tsx
- ui/src/tool-panel/location-track/location-track-infobox.tsx
- ui/src/tool-panel/location-track/location-track-vertical-geometry-infobox.tsx
- ui/src/tool-panel/tool-panel-container.tsx
- ui/src/tool-panel/tool-panel.tsx
- ui/src/tool-panel/translations.fi.json
- ui/src/track-layout/track-layout-container.tsx
- ui/src/track-layout/track-layout-model.tsx
- ui/src/track-layout/track-layout-slice.ts
- ui/src/track-layout/track-layout-view.tsx
- ui/src/track-layout/track-layout.module.scss
- ui/src/utils/react-utils.tsx
- ui/src/vertical-geometry/demo-page.tsx
- ui/src/vertical-geometry/labeled-ticks.tsx
- ui/src/vertical-geometry/plan-linking.tsx
- ui/src/vertical-geometry/pvi-geometry.tsx
- ui/src/vertical-geometry/ticks-at-intervals.ts
- ui/src/vertical-geometry/track-address-ruler.tsx
- ui/src/vertical-geometry/util.ts
- ui/src/vertical-geometry/vertical-geometry-diagram.scss
- ui/src/vertical-geometry/vertical-geometry-diagram.tsx
Yritin varmaan puoli päivää erotella näitä käytännön testauksen perusteella järjestelmällisen epäjärjestelmällisesti tehtyjä tviikkejä erillisiksi pullareiksi, mutta siihenpä päädyin, ettei onnistu.
Pääasialliset muutokset korkealla tasolla:
- Korkeuskaavion APIt menee nyt enemmän yksi asia kerrallaan: Erikseen alignmentin alku- ja loppupisteen haku (start-and-end), joka sinällään aiheuttaa uutta alignmenttia ladattaessa yhden round-tripin, mutta yksinkertaistaa muuten toteutusta; sitten rinnakkaisina hakuina geometrian, korkeusviivan, ja suunnitelmien linkitysalueiden haut
- Pystygeometrialle uusi infoboksi sijaintiraiteille, ja sille alkuun tilaksi vaan yksittäinen frontin yhteinen tieto siitä, näytetäänkö sijaintiraiteiden korkeuskaaviota yleensä
- Kilometritolppien ja viivoittimen …
> GVT-1839/1836/1835 korkeuskaavion frontin integrointi

- ui/src/map/map-view.tsx
Using clientWidth/clientHeight is racy at least on Firefox and can miss updates (presumably getting an out-of-date value of the element bounds). ResizeObserver seems more reliable.
> GVT-1862 Use ResizeObserver to detect map element's size changes

- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryService.kt
- ui/src/vertical-geometry/height-lines.tsx
- ui/src/vertical-geometry/vertical-geometry-diagram.tsx
Lähinnä yksinkertaistettu hähmäisen monimutkaista minAndMaxHeightsiä ja siirretty asioita niin, että isoissa funktioissa on vähemmän muuttujia skoopissa. Tästä ei tule juuri käyttäjälle näkyvää muutosta, tosin selainkonsoliin ei tule enää varoituksia siitä, kun HeightLinesin renderöinnissä yritetään piirtää NaN-koordinaatteja.
Oleellinen käyttäjälle näkyvä muutos siinä, että jos suunnitelman alignmentilla ei ole korkeusprofiilia lainkaan, niin kaavio näkyy, mutta näkyy tyhjänä, sen sijaan että ei lataudu lainkaan.
> GVT-1841 Tyhjien kaavioiden käsittely pystygeometriakaaviossa

- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryService.kt
Frontti piirtää ensimmäiselle metrille (tai tarkkaan ottaen sille, jonka osoitteen metriosa on nolla) kilometritolpan, joten jos se jätetään lähettämättä, piirto rumentuu. Periaatteessa voi aiheuttaa vähän enemmän suttua kaavion piirtämisessä, mutta kokonaisuutena näyttää paremmalta.
> GVT-1868 Always send first tick for each track km of track heights

- ui/src/vertical-geometry/labeled-ticks.tsx
Tämä tarkistus oli itse asiassa olemassa jo aiemmin. Luulin saaneeni sen yksinkertaistettua pois, mutta enpä saanutkaan.
> GVT-1833 Add check for not rendering address label too close to next km start

- infra/build.gradle.kts
- infra/src/main/kotlin/fi/fta/geoviite/infra/velho/VelhoDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/velho/VelhoService.kt
- infra/src/main/resources/application.yml
- infra/src/main/resources/db/migration/prod/V39__add_projektivelho_dictionaries.sql
- infra/src/main/resources/db/migration/prod/V40__add_projektivelho_integration.sql
- infra/src/test/kotlin/fi/fta/geoviite/infra/velho/VelhoServiceIT.kt
Tauluja alkoi tulla aika paljon ja nimenä integrations.projektivelho_taulunimi alkoi olla turhan pitkä käyttää -> siirretty omaan schemaan. Ei muita muutoksia.
> GVT-1876 separate projektivelho schema

- infra/src/main/kotlin/fi/fta/geoviite/infra/common/ChangeTimeController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/integration/RatkoPushDao.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/integration/RatkoPushDaoIT.kt
- ui/src/common/common-slice.ts
- ui/src/frontpage/frontpage-container.tsx
- ui/src/frontpage/frontpage.tsx
Ongelman pääsyynä tässä oli, että etusivulla käytettiin julkaisujen ChangeTimea. Ne eivät päivity ratkopuskujen tilojen mukana, sillä itse julkaisu ei tällöin muutu. Tein rinnalle ratkopuskuille oman ChangeTimen, jota käytetään näissä
> GVT-1875: Etusivun automaattinen tilan päivitys ei toimi

- infra/src/main/kotlin/fi/fta/geoviite/infra/util/ResponseEntity.kt
Alkuperäinen Chromen kaatumisbugi ei toistunut mulla, joten epäiltiin Jyrkin kanssa Linux-Chrome-spesifistä ongelmaa. Tässä kuitenkin korjattuna se, että Chrome latasi ääkkösiä sisältävät tiedostot väärällä tiedostonimillä (tiedostonimeksi tuli pelkkä "file"/"tiedosto")
> GVT-1843: Ääkköset InfraModelin tidostonimessä rikkoo chromen downloadin ja uploadin

- ui/src/map/map-view.tsx
Toimi tämä ilmankin tuota reffiä jollain tavalla, tosin en tiedä että miksi toimi lainkaan; mutta näemmä se pitää passata, jotta tässä tapauksessa tämä resizeObserver osaa observoida yhtikäs mitään.
> GVT-1888 Pass ref to detect map view resizes properly

- infra/src/main/kotlin/fi/fta/geoviite/infra/inframodel/InfraModelConversion.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/projektivelho/PVDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/projektivelho/PVDocument.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/projektivelho/PVIntegrationService.kt
- infra/src/main/resources/db/migration/prod/V40__add_projektivelho_integration.sql
- infra/src/test/kotlin/fi/fta/geoviite/infra/projektivelho/PVIntegrationServiceIT.kt
- ui/src/i18n/fi/fi.json
Täällä toteutettu inframallin hylkäämissyyn muiluttaminen ulos tiedoston lukemisesta. Lisäksi toteutettu PV-scheman kantaan paikka, jonne ka. tiedon voi tallentaa.
> GVT-1894: Hylkäämissyyn tallentaminen hylätyistä inframalleista

- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/VerticalGeometryListing.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/util/CSVPrintingUtils.kt
Tämä ongelma olikin pelkästään pystygeometriaexportissa. Muualla joko ei ollut ollenkaan päivämääriä/timestampeja, tai sitten oli handlattu paikallisesti ja eri formaatissa
> GVT-1899: Pystygeometrioiden CSV-eksportin luomisaika selkeämmäksi

- ui/src/infra-model/tabs/infra-model-tab-nav-item.tsx
Setterikutsun siirto renderistä klikkihändleriin välttää konsolimölyn Reactilta.
> GVT-1907 Set active inframodel tab on click

- ui/src/vertical-geometry/height-tooltip.tsx
Menin nyt siitä missä aita on matalin, eli kun olin jo aiemmin toteuttanut tämän elementin asemoimaan itsensä suhteessa koko selainikkunaan, niin jatkan samalla linjalla. Ero oli siis tuo edellisessä kommitissa tullut muutos että korkeuskaaviolla itsellään on `position: relative`, joka teki siitä positioidun elementin, mikä sitten muuttaa `position: absolute`n tulkinnan olemaankin suhteessa häneen.
> GVT-1932 Position height tooltip against viewport as intended

- ui/src/map/layers/alignment-linking-layer.ts
Tänne oli päätynyt vääriä värejä käyttöön, oletettavasti varmaan layereiden eriyttämisen yhteydessä. Korjattu.
> GVT-1930: Raiteen lyhennyksessä värit väärin päin

- ui/src/vertical-geometry/vertical-geometry-diagram.tsx
Pakotetaan kaavion oikean reunan M-arvo pysymään näytettävän alignmentin rajojen sisällä. Tämä samalla korjasi sen, että kaavion mennessä nollan levyiseksi sitä ei saanut enää resizattua.
> GVT-1847: Korkeukaavio pomppii kun selaimen leveys on suurempi kuin kaavion

- ui/src/map/layers/switch/switch-layer.ts
Set() is wrong as distinct objects representing the same switch are still distinct objects to it.
> GVT-1948 Distinctify received switches by ID

- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryController.kt
- ui/src/geometry/geometry-api.ts
- ui/src/tool-panel/alignment-plan-section-infobox-content.tsx
- ui/src/tool-panel/tool-panel-container.tsx
- ui/src/tool-panel/tool-panel.tsx
- ui/src/track-layout/track-layout-container.tsx
- ui/src/track-layout/track-layout-slice.ts
- ui/src/track-layout/track-layout-view.tsx
Tässä tuli samalla refaktoroitua toolpaneelin tabinvalintalogiikkaa jonkin verran. Vanhalla, id-pohjaisella mallilla oli helppoa tutkia onko esim. jonkun sijaintiraiteen tabi auki, mutta tutkinta siitä että minkä sijaintiraiteen tabi oli kyseessä meni paljon vaikeammaksi. Koska tämä tabitieto oli ainoa asia joka hoiti kommunikaatiota toolpanelista kuvaajaan, kuvaajan pitämisessä auki silloin kuin tabi vaihtuu johonkin ei-raidetabiin käytännössä vaati sitä, että tämä tieto saatiin ulos tuosta rakenteesta. Muutin sen nyt oliorakenteeksi, jossa on tallessa näytettävän sekä tyyppi että sen id.
> GVT-1902: Pystygeometrian kuvaajan tulisi näyttää saman raiteen tietoja kuin ominaisuustietonäkymä

- ui/src/map/layers/alignment-linking-layer.ts
- ui/src/map/layers/alignment/badge-layer-utils.ts
- ui/src/map/layers/alignment/track-number-end-point-addresses-layer.ts
- ui/src/map/tools/select-tool.ts
- ui/src/selection-panel/selection-panel-geometry-section.tsx
- ui/src/tool-bar/tool-bar.tsx
- ui/src/tool-panel/geometry-alignment/geometry-alignment-linking-candidates.tsx
- ui/src/tool-panel/geometry-alignment/geometry-alignment-linking-infobox.tsx
- ui/src/tool-panel/km-post/geometry-km-post-linking-infobox.scss
- ui/src/track-layout/track-layout-view.tsx
Useita pienempi korjauksia samassa pullarissa:
- GVT-1937: Taustaväri piirty väärin osalle ratanumeron päätepisteille
- GVT-1332: Suunnitelmat haettiin kahdesti kohdistamisen jälkeen
- GVT-1929: Sijaintiraiteiden badgeista puuttui borderit
- GVT-1933: Jätetään linkityspallurat piirtämättä kun ollaan zoomattuna
- GVT-1931&GVT-1668: Kaikkia kartan valintoja ei tyhjennetty mikäli kyseinen karttataso ei ollut päällä
- GVT-1335: Disabloidaan uuden sijaintiraiteen ja pituusmittauslinjan luonti sen jälkeen kun käyttäjä on käynnistänyt linkityksen
> GVT-General

- ui/src/vertical-geometry/plan-linking.tsx
Juurisyynä oli siis todella pitkillä raiteilla olevat hyvin lyhyet linkitykset (tai pikemminkin linkitysten välissä olevat aukot.) Esim. 11.3km mittaisella raiteella oleva 2.3mm aukko linkityksessä on tarpeeksi lyhyt, että se piirtyisi 0px levyisenä kaavioon. Suunnitelman nimeä offsetataan kuitenkin aina 2px verran, ja kun tämä otettiin huomioon myös leveyslaskennoissa, <2px leveillä osuuksilla leveys meni aina negatiiviseksi.
> GVT-1927: Korkeuskaavio huutaa konsoliin virheitä negatiivisista width-attribuuteista

- ui/src/vertical-geometry/track-meter-index.ts
- ui/src/vertical-geometry/vertical-geometry-diagram.tsx
Periaatteessa tuo track-meter-indexin muutos on se, jolla vältetään yleensä kaatuminen, jos yleensä mistä tahansa syystä kaavio yrittää laskea sijainteja raiteella silloin, kun korkeusviivaa ei ole lainkaan (eli yleensä siksi, koska yritetään näyttää kohtaa, joka on raiteen ulkopuolella).
startAndEndin haun seuraaminen tarkentaa erikseen juuri tämän taskin tapausta, eli että mitä jos alignmenttia vaihdettaessa uusi korkeusviiva ja geometria saadaankin haettua ennen kuin startAndEnd saadaan.
> GVT-1950 Turvallisempi pystygeometrian kuvaajan raiteen vaihtamisen hallinta

- ui/src/vertical-geometry/vertical-geometry-diagram-holder.tsx
Other checks vs. undefined for consistency. The one that matters is considering visibleStartM === 0 valid.
> GVT-1994 Fix calculating tickLength when track meter 0 is visible

- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/testgroup2/LinkingTestUI.kt
We already removed all the drafts in clearDrafts, going through the UI to remove them again does nothing.
> GVT-1954 Remove noop draft removals

- infra/src/main/kotlin/fi/fta/geoviite/infra/map/AlignmentGeometry.kt
Tavoitteena saada linkityksessä näkymään kaikki pisteet, silloinkin kun m-arvojen ero on osalla pisteväleistä pikkuisen alle 1:n. 
En ole ihan varma tuosta kokonaisluvuksi asti pyöristämisestä: Se oli lähinnä esteettinen valinta, sillä perusteella että onhan `resolution` myös kokonaisluku. Periaatteessa riittäisi varmaan yhtä hyvin lisätä tuohon jokin maaginen aivan pikkusäätö tyyliin `p.m - previousM + 0.001`.
> GVT-1985 Allow a bit of slack when simplifying alignments

- ui/src/vertical-geometry/vertical-geometry-diagram.tsx
Voi olla että tämä bugi ei käynyt kenenkään muun hermojen päälle (jos tämä nyt edes muilla käyttiksillä edes näkyi mitenkään), mutta Mäkkäri + touchpad -ihmisenä tämä osui minulla silmään aina kun zoomasin pystygeometriakaaviota
> GVT-1995: Korkeuskaavion zoomaaminen touchpadilla vierittämällä koittaa vierittää koko Geoviitettä

- ui/src/map/layers/geometry/geometry-km-post-layer.ts
- ui/src/map/layers/geometry/geometry-switch-layer.ts
- ui/src/selection-panel/geometry-plan-panel/geometry-plan-panel.tsx
- ui/src/selection-panel/selection-panel-geometry-section.tsx
- ui/src/selection/selection-model.ts
- ui/src/selection/selection-store.ts
- ui/src/tool-panel/tool-panel.tsx
Tämä ei itse asiassa oleellisesti muuttanut paljoakaan koodin kannalta, joten olen hiukan epävarma onko tästä oikeastaan hyötyä. Se tuntuu silti jollain tapaa oikeammalta - kun kerran puhutaan geometriapuolen asioiden valinnoista niin miksipä ei puhua niistä geometriapuolen asioiden id:llä.
Taustatietona: Näissä ID:ssä on siis kyse siitä millä id:llä merkataan geometriapuolen valintoja. Kun geometriaolioita näytetään kartalla jne, niille muodostetaan lennossa layout-versio ja ne saavat sieltä stabiilit temp-id:t (id ei ole kannassa mutta generoidaan geometria-id:n pohjalta niin että se on samalla geometriaoliolla aina sama). Noita on käytetty paikoin historiallisista syistä sillä näin generoitu olio käyttäytyy aivan kuten layout-olio frontin kannalta. Layout-oliolla on sourceId-kentässä …
> GVT-826 Use geometry-id to denote geometry selection (rather than temp layout-id)

- ui/src/map/layers/km-post/km-post-layer.ts
In this case (unlike GVT-1948), there was no consequence to getting the distinctification wrong, because km posts would have to hit a map tile border exactly in order to be fetched through multiple map tiles anyway.
The problem, as in the other case, is that Set does the usual sort of comparison in JavaScript, which doesn't look inside objects.
> General: Fix bad distinctification in km post layer

- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/pagemodel/common/Button.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/testgroup1/BasicMapTestUI.kt
Näyttäisi lokaaliajojen perusteella siltä, että ainoa tästä odotuksesta saatava etu on, että yhdessä testissä uusi toasti ehtii odotettaessa korvata vanhan, ja siitähän selviää vaan sulkemalla vanhan toastin pois erikseen.
> GVT-1954 Remove button pressing wait

- ui/src/tool-panel/track-number/track-number-infobox.tsx
- ui/src/track-layout/track-layout-react-utils.tsx
Yksinkertaisuudessaan tästä hausta puuttui muutosajan käyttäminen depsuna. Ka. depsu lisätty optionaalisena, sillä tuota hakua käytetään myös muutosdialogissa arvon hakemiseen, ja  järkeilin ettäsen auki ollessa ei haluttane että kenttien muuttuvat siellä
> GVT-2011: Ratanumeron alkuosoitteen muuttaminen ei päivity toolpaneeliin automaattisesti

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutKmPostController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchController.kt
- ui/src/tool-panel/km-post/km-post-infobox.tsx
- ui/src/tool-panel/location-track/location-track-infobox.tsx
- ui/src/tool-panel/switch/switch-infobox.tsx
- ui/src/tool-panel/track-number/track-number-infobox.tsx
- ui/src/tool-panel/translations.fi.json
- ui/src/track-layout/layout-km-post-api.ts
- ui/src/track-layout/layout-switch-api.ts
- ui/src/track-layout/track-layout-react-utils.tsx
Lisätty samalla myös paikannuspohjan kilometripylväille, sillä niiltäkin puuttui.
> GVT-2001: Vaihteen Lokitiedot-infoboksi on tyhjä

- ui/src/vertical-geometry/vertical-geometry-diagram-holder.tsx
Pitkällisen debuggaamisen lopputuloksena selvisi, että syntipukkina oli wanha logiikka, jolla pääteltiin ettei kaavio saa piirtyä yli rajojensa kun kaavion leveys kasvaa. Ka. tilanne tarkastellaan nykyään myös jossain muualla, niin poistin tämän ongelmallisen logiikan.
> GVT-2005: Pituusgeometriakaavion zoomaaminen käyttäytyy väärin ikkunan resizaamisen jälkeen

- ui/src/vayla-design-lib/datepicker/datepicker.tsx
Ideaalisessa maailmassa nämä olisi parametrisoitu jotenkin. En tosin oikein keksinyt mitään fiksua tapaa lähteä automatisoimaan importtien parametrisointia ja luulisin että tarvetta muille kielille ei ole ihan välittömästi, niin en lopulta jaksanut käyttää tähän sen takia mielettömästi aikaa.
> GVT-2022: Päivämäärävalitsin näkyy englannin kielisillä termeillä

- infra/src/main/kotlin/fi/fta/geoviite/infra/common/ChangeTimeController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/util/DaoBase.kt
- ui/src/common/change-time-api.ts
- ui/src/common/common-slice.ts
- ui/src/geometry/geometry-api.ts
- ui/src/infra-model/view/dialogs/new-project-dialog.tsx
- ui/src/infra-model/view/form/fields/infra-model-project-field.tsx
- ui/src/infra-model/view/form/infra-model-form.tsx
Previously the whole list of projects was loaded via an API request every time the project selection dropdown was opened in the infra-model edit page. Changes to the list of projects should be rare, so they can be cached client (browser) side instead.
The projects cache will be invalidated immediately upon adding a new project within the local browser and external updates are checked every 15 seconds also for the projects cache. If the projects cache is invalidated, the whole list of projects will be loaded from the API to the cache once again.
Similarly it is unnecessary to fetch a single project's information from the API if all project data is already cached in the browser. The `getProject`-function that is responsible for fetching a single project's data was refactored to use the …
> GVT-1764: Implement frontend caching for projects

- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/CsvTranslations.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/VerticalGeometryListing.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/VerticalGeometryListingFileDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/integration/LockDao.kt
- infra/src/main/resources/application.yml
- infra/src/main/resources/db/migration/prod/V44__add_vertical_geometry_listing_file_table.sql
- infra/src/test/kotlin/fi/fta/geoviite/infra/geometry/VerticalGeometryListingFileDaoIT.kt
- ui/src/data-products/data-product-view.scss
- ui/src/data-products/translations.fi.json
- ui/src/data-products/vertical-geometry/entire-rail-network-vertical-geometry-listing.tsx
- ui/src/data-products/vertical-geometry/vertical-geometry-view.tsx
- ui/src/geometry/geometry-api.ts
Previously downloading the entire track network's horizontal geometry was supported. Given that a user may also want to explore the vertical geometry data in an external application, download support for the entire track network's vertical geometry was deemed useful.
> GVT-1951: Add support for downloading the entire track network's vertical geometry

- ui/src/vertical-geometry/km-heights-fetch.ts
- ui/src/vertical-geometry/vertical-geometry-diagram-holder.tsx
Tämä johtui siitä, että haun depsuina olleet `alignmentId` ja `startM`/`endM` päivittyivät eri aikoihin, koska `alignmentId` tuli parametrina ja `startM`/`endM` asetettiin `setState`:lla. Ne on nyt groupattu yhteen `setState`:lla asetettavaan objektiin, eikä mitään haun depsuja tuoda enää parametreina. Korkeuskaavion hakuja/piirtoja voisi tosin muutenkin käydä jossain kohtaa ajatuksella läpi, sillä oma mututuntumani on, että täällä on edelleen jonkin verran outouksia.
> GVT-1926: Korkeuskaavio suorittaa alignment-heights-haun useaan kertaan raidetta vaihtaessa

- infra/src/main/resources/application-ratkotest.yml
- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/SeleniumTest.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/pagemodel/frontpage/FrontPage.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/pagemodel/frontpage/FrontPageElement.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/testgroup1/FrontPageTestUI.kt
- ui/src/ratko/ratko-publish-button.tsx
Uusi ratkotest-profiili kertoo Infra-TEST-konfigilla ajettaessa geoviitteelle että täältä löytyy Ratko. Sitä varten envirepossa erikseen https://github.com/finnishtransportagency/geoviite-env/commit/7c70f2c1efb4547517b69ad1cb29583396cc80a7 asettamaan profiilin päälle. Tämä siis tarvitaan siksi, koska testi itsessäänhän sörkkii vaan selainta, eli sen profiili ei kerro mitään siitä, mitä mieltä testattava Geoviite on siitä, mistä löytää Ratkon. Tätä pitää sitten viljellä muihinkin paikkoihin, missä aiotaan E2E-testejä ajella.
> GVT-1959 E2E test for front page & Ratko send

- ui/src/map/layers/switch/switch-layer.ts
Tämä selventää vähän isoilla ratapihoilla toimimista, kun vaihdelista ei heti katoa näkyvistä liian monen vaihteen takia.
Tässä oli aiemmin arveltu syylliseksi samojen vaihteiden tulemista useamman MapTilen kautta, mutta sehän bugi oli korjattu jo GVT-1948:ssa.
> GVT-2000 List visible switches based on main visible joint, not all joints

- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryService.kt
This unifies the file naming style for the data products of the entire track network.
> GVT-2037: Add file generation date for the entire rail network's vertical geometry

- infra/src/test/resources/application-test.yml
Jokainen erilainen Springin konfiguraatio testeissä luo uuden ApplicationContextin, ja näyttäisi, että Hikarin yhteysaltaat ovat juurikin kontekstikohtaisia. Näitä kun on riittävästi, ja käytetään application.yml:n oletusta eli että altaaseen tehdään heti 20 yhteyttä, riittävä määrä konfiguraatioita vetää yli postgressin 100 yhteyden rajasta.
0 tuntui loogiselta numerolta, koska miksipä luoda lainkaan yhteyttä sellaisissa testeissä, jotka eivät satu käyttämään tietokantaa.
> General: Don't spam database connections in tests

- ui/src/geoviite-design-lib/demo/examples/badge-examples.tsx
- ui/src/tool-panel/location-track/dialog/location-track-edit-dialog.tsx
- ui/src/tool-panel/location-track/dialog/translations.fi.json
- ui/src/tool-panel/location-track/location-track-infobox.tsx
- ui/src/tool-panel/translations.fi.json
- ui/src/track-layout/track-layout-model.tsx
Tämä on periaatteessa tehty tiketin GVT-1910 (https://extranet.vayla.fi/jira/browse/GVT-1910) yhteydessä, mutta tämä ei oikeastaan liity siihen suoraan. Tämän lisäksi ka. tiketin jutut tulevat menemään niin täysin eri tavalla kuin mitä alkuperäinen speksi tiketillä sanoi, että sen kanssa otettaneen vähän lisäaikaa. Näistä johtuen päädyin tekemään tämän täysin omana, virallisesti tikettiin liittymättömänä pullarinaan.
> General: Raiteen topologiavaihteet näkyviin UI:hin

- infra/build.gradle.kts
- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/util/Browser.kt
Siirrytään käyttämään uusia Seleniumin omaa selainten ja selainajurien hallintaa, kts. https://www.selenium.dev/blog/2022/introducing-selenium-manager/ . Juuri tämä uusin versio 4.11.0 osaa myös käyttää vastajulkaistua Chrome for Testingiä, jonka pitäisi osaltaan auttaa versiojärjestelyiden kanssa: https://www.selenium.dev/blog/2023/whats-new-in-selenium-manager-with-selenium-4.11.0/
Tämä ei varmastikaan poista kaikkia selain- ja ajurisäätöjä, esim. minulla näillä konffeilla toimii lokaalisti vain chrome-puoli kun taas Firefox-puolen tekosista en tiedä mitään. Mutta tuurilla voisi olla niin, että tämä riittää AWS-ympäristön selainversio-ongelmien hallintaan.
Gradle-filussa Spring Bootin riippuvuuksienhallinta sörkkii asioita aivan Gradlen ohi, siksi sille pitää erikseen kertoa haluttu …
> GVT-2041 Use Selenium's native driver manager

- infra/src/main/resources/application-ratkotest.yml
Selkeysfiksi. Infran tarvitsee tietää vain ratko.url, testien taas vain ratko.test-port, ja tämä on infralle menevä konffi.
> General: Don't pass unnecessary test-port

- infra/src/main/kotlin/fi/fta/geoviite/infra/error/ClientException.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackService.kt
- infra/src/main/resources/db/migration/prod/V46__add_unique_layout_name_constraints.sql
- infra/src/test/kotlin/fi/fta/geoviite/infra/NoTransactionTemplate.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/integration/CalculatedChangesServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationDaoIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/DraftIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchDaoIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/TrackLayoutDomainTestData.kt
- ui/src/i18n/fi/fi.json
- ui/src/preview/translations.fi.json
Samassa kommitissa sievästi sekaisin kahta eri asiaa: Yhtäältä julkaisuvalidoinnissa varoitetaan (mutta ei anneta virhettä) päällekkäisistä nimistä, toisaalta varsinaisessa julkaisussa vältetään constrainteilla päällekkäiset viralliset nimet, ja parsitaan sitten tietokannan virheistä, mitä sen mielestä julkaisussa oikeasti meni pieleen.
Validointi antaa vain varoituksen mutta ei virhettä, jotta käyttäjä saa julkaisun temppuilematta läpi, jos tarvitsee vaihtaa nimiä päittäin. Samasta syystä myös varsinaisen julkaisun virheenkäsittely tapahtuu vasta kommitissa: Konstrainttien tarkistus kun pitää myös jättää loppuun, jotta päittäin vaihtamiset kerkiää menemään läpi.
> GVT-2024 Prevent duplicate official names

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberDao.kt
- ui/src/preview/translations.fi.json
Vielä duplikaattinimijuttuja. Virheenkäsittelyn puolella i18n-viestit oli paikoillaan, mutta olin sattunut tekemään tämän niin, että validoinnin puolella on omat viestinsä, ja siellä oli puutteita. Ja ratanumeron päivityksen rietale vieläpä varoitti siitä, että ihan normaalisti päivitettiin olemassaolevaa ratanumeroa.
> GVT-2024 Add missing i18ns, fix overeager track number duplicate name detection

- ui/src/infra-model/projektivelho/pv-file-list.tsx
Ehkä vähän turhan tarkkaa nysväystä, mutta devaus vaan on hauskempaa, jos voi suunnilleen luottaa, ettei React mylvi selainkonsoliin spämmiä ihan täysin tunnetuista ja helposti korjattavista syistä.
Muutos pääosin melkein pelkkää koodinsiirtoa, tosin korvasin samalla nuo dangerouslySetInnerHtml:t kun näemmä react-i18nextissä on mahdollisuus käyttää i18n-viesteissä HTML:ää ihan integroidulla tavalla.
> GVT-2055 Fix DOM nesting

- ui/src/tool-panel/km-post/dialog/km-post-edit-store.ts
- ui/src/tool-panel/location-track/dialog/location-track-edit-store.ts
Näitä dialogeja avattessa merkkijonokentät renderöidään ensiksi undefined-arvolla, ts. Reactin näkemyksestä kuin value-propsulle ei olisi annettu lainkaan arvoa, ja heti perään sitten oikealla arvolla, mistä React sitten mölisee kun näkee mielestään kontrolloimattoman komponentin muuttuvan kontrolloiduksi.
Korjataan selkeyttämällä muokkausdialogien tilanhallintaa niin, että merkkijonokenttien sisällöt ovat alusta lähtien merkkijonoja.
> GVT-2057 Define edit dialogs' initial states better

- ui/src/vertical-geometry/km-heights-fetch.ts
- ui/src/vertical-geometry/vertical-geometry-diagram-holder.tsx
Geometriasuunnitelmien muutosaikoja pitää vetää aika monestakin paikasta läpi, jotta auki olevassa kaaviossa osaa geometriasuunnitelman muutoksista päivittyä sekä otsikkotiedot, että korkeusjärjestelmän muutoksesta myös korkeusviiva.
> GVT-2054 Update height diagram on geometry plan changes

- ui/src/tool-panel/km-post/km-post-infobox.tsx
* Piilotetaan ratakilometrin pituus hakemisen ajaksi (konsistentti muiden bäkkäriltä erillisellä haulla haettavien asioiden kanssa)
* Lisätty yksikkö kentän loppuun
> GVT-2081: Ratakilometrin pituuden jälkiparannukset

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/TrackLayout.kt
- infra/src/main/resources/i18n/translations.fi.json
- ui/src/tool-panel/location-track/dialog/location-track-edit-dialog.tsx
- ui/src/tool-panel/location-track/location-track-infobox.tsx
- ui/src/track-layout/layout-location-track-api.ts
- ui/src/track-layout/track-layout-model.tsx
- ui/src/track-layout/track-layout-react-utils.tsx
Oman cachensa kautta menevä toteutus siksi, että pyritään yhtäältä ainakin vähän välttämään sellaisia tilanteita, että käyttäjä vaihtaa katsottavaa raidetta mutta näissä kentissä on väärää tietoa, mutta toisaalta että nämä vaihteiden nimet ei ainakaan kovin pahasti välkkyisi raiteita vaihdettaessa.
> GVT-2066 Display segment-linked switches as ends in track infobox

- infra/src/main/kotlin/fi/fta/geoviite/infra/projektivelho/PVClientConfiguration.kt
- infra/src/main/resources/application.yml
- infra/src/test/resources/application-test.yml
Integraatio ei toiminut dev- ja test-ympäristöissä, koska niissä muilutettiin arvo `PROJEKTIVELHO_AUTH_URL`-nimiseen muuttujaan, mutta koodi oletti sen olevan `PROJEKTIVELHO_LOGIN_URL`-nimen takana. Yhdistetty nyt nimeämiset `AUTH_URL`:iksi
> Projektivelhon auth-urlin parametrin rename

- infra/src/main/kotlin/fi/fta/geoviite/infra/integration/CalculatedChangesService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationValidation.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/TrackLayoutDomainTestData.kt
Previously the publication state of the switches that were connected topologically to a location track were not validated. However, this did not cause critical issues during publication: Another part of the topological switch reference fetching functionality did not find these switches, which in turn resulted in a `throw`. This `throw` related error was displayed to a user opening the publication staging view in a with a "404" snackbar error in case a location track and switch(es) were created in specific order.
* Topologically connected switches are considered valid when they are officially published or in draft state in the same publishing group as a draft location track that is referencing them.
* Test for the previously missing validation was added.
* Tests to ensure that valid switch …
> GVT-2039: Add publication state validation for topologically connected switches of location track

- ui/src/infra-model/projektivelho/pv-file-list.tsx
- ui/src/infra-model/view/form/infra-model-form.tsx
Linkit tällä hetkellä a) eivät toimi (tuottavat urleja jotka eivät ole saatavilla isosta pahasta interwebsistä) ja b) rikkovat E2E-testit, joten disabloidaan ne väliaikaisesti. Näiden korjaamisesta on ollut jo pidempään tiketti https://extranet.vayla.fi/jira/browse/GVT-1958
> General: (Temporarily) replace Projektivelho links with plain text

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutAlignmentDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutGeometry.kt
- infra/src/main/resources/db/migration/prod/V49__remove_geometry_alignment_id_from_layout_alignment.sql
- infra/src/test/kotlin/fi/fta/geoviite/infra/linking/SwitchLinkingTest.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutAssertions.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/TrackLayoutDomainTestData.kt
GVT-2086: Fix layout alignment segment's containing null sourceId values
Additionally, the geometry_alignment_id was removed as a concept from LayoutAlignments: It was deemed unnecessary as a layout can be formed from multiple different geometry alignments via segments, which have their own geometry_alignment_id field.
The LayoutAlignment's field only had nulls stored in the database, and it was also not used during any proper business logic as a non-null value.
> GVT-2086: Fix layout alignment segment's containing null sourceId values

- ui/src/tool-panel/geometry-alignment/geometry-alignment-linking-infobox.tsx
Täällä on selkeästi tapahtunut jossain yhteydessä joku epähuomio, koska id:t oli parametreina, mutta niitä ei käytetty. Säädetty tämä niin, että uutena luodut ratanumerot ja sijaintiraiteet valitaan automaagisesti luontinsa jälkeen (joka lienisi muutenkin varmaan fiksua, koska niille saatettaneen haluta tehdä jotain operaatioita lopullisesta linkityksestä riippumatta)
> GVT-2097: Linkitystoiminnon aikana luotava raide pitäisi valita automaattisesti

- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationValidation.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/switchLibrary/SwitchStructure.kt
- infra/src/main/resources/i18n/translations.fi.json
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationValidationTest.kt
Uusi validaatiokoodi vastaa nyt paremmin totuutta siitä, mitä asioita vaihteiden validoinnissa oikeasti voi mennä vikaan, ja mistä ei tarvitse välittää:
- validateFrontJointTopology on kokonaan uusi; en löytänyt paikannuspohjasta yhtään kohtaa, missä se olisi ollut väärässä, ts. vaihde olisi oikeasti järkevästi jossain kohdassa, mutta etujatkokselta vaan ei lähde raidetta (mutta tämä, samoin kuin muut validaatiot, on ainakin tähän hätään vain varoitustasoinen). Näissä oli yleistä, että puute johtui siitä, että väärä raide oli merkitty duplikaatiksi; siksi otin sen validaatiossakin huomioon.
- validateExcessTracksThroughJoint on myös uusi: Tarkistetaan, että kunkin vaihdepisteen läpi menee enintään yksi ei-duplikaattiraide (paitsi pisteen 5 läpi, se kun löytyy raideristeysten keskeltä)
- …
> GVT-1980 Adjust and extend switch topology validation

- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryPlan.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/inframodel/InfraModelApi.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/inframodel/InfraModelService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/util/ResultSetExternal.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/util/SanitizedString.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/util/StringUtils.kt
- infra/src/main/resources/i18n/translations.fi.json
- infra/src/test/kotlin/fi/fta/geoviite/infra/geometry/GeometryDomainTestData.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/util/SanitizedStringTest.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/util/StringUtilsTest.kt
- ui/src/infra-model/view/form/infra-model-form.module.scss
- ui/src/infra-model/view/form/infra-model-form.tsx
- ui/src/infra-model/view/formgroup/formgroup-textarea.tsx
- ui/src/infra-model/view/formgroup/formgroup.module.scss
- ui/src/vayla-design-lib/text-area/text-area-autoresizing.tsx
The free text field is now also using the pen method to enable editing of the field as all are other fields in the infra model edit form.
> GVT-2060: Allow newlines in infra model observations free text field

- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationValidation.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/switchLibrary/SwitchStructure.kt
Teoriassa logiikkakin muuttuu nyt hieman, koska validateFrontJointTopology näkee nyt raiteet, jotka menevät raideristeyksen keskeltä läpi, mutta sepä ei niistä välitä. Lähinnä poistetaan valheet siitä, että muka olisi jokin yksittäinen piste, joka on aina matikkapiste.
> General: Remove incorrect mention of math point in switch validation

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/MapAlignmentService.kt
Teoriassa transaktioraja getAlignmentPolylines()in päällä on aika kookas, sisältäähän se sentään toAlignmentPolyline()n ja sen kautta simplify()n, joka on sentään jonkin verran ei-triviaalia laskentaa.
Käytännössä sillä lienee tuskin kovin isoa merkitystä, ja koodia pitäisi pyöritellä enemmän kuin tämän triviaalin määrän verran, jotta saisi oikeasti eroteltua laskennat ja tietokantahaut erikseen (tosin ei sekään nyt vaikeaa olisi). Tällä muutoksella kuitenkin saa aikaan jo mojovan edun kartan nopeudessa isoille liikennepaikoille zoomatessa.
> GVT-2107 Add transaction boundaries around listing alignment polylines or switches

- ui/src/utils/array-utils.ts
- ui/src/utils/math-utils.ts
- ui/src/vertical-geometry/util.ts
- ui/src/vertical-geometry/vertical-geometry-diagram.tsx
GVT-1918: Fix vertical geometry diagram height axis bounds calculation
Previously the calculation did not account for height values in between known values at the edges of the vertical geometry diagram, which resulted in the height transfer lines being drawn to the top or bottom edge of the diagram in cases with relatively large changes in the horizontal (track-km) and vertical (track height) axes.
> GVT-1918: Fix vertical geometry diagram height axis bounds calculation

- ui/src/vertical-geometry/vertical-geometry-diagram.tsx
Vaihdettu hiirispesifeistä eventeistä pointer-eventteihin, sillä ne tukevat capturea (ts. eventin saa laukeamaan ka. eventille vaikka pointteri liikkuisi sen ulkopuolelle)
> GVT-2114: Sisään zoomatun pystygeometrian kuvaajan draggaaminen loppuu kun kursori siirtyy ulos kuvaajan alueelta

- ui/src/geoviite-design-lib/geometry-plan/plan-name-link.tsx
Tämä aiheutti Reactin DOM-validaatiossa mölinää a-elementistä a-elementin sisällä.
> General: Remove redundant linkness from plan name links

- infra/src/main/kotlin/fi/fta/geoviite/infra/FlywayConfiguration.kt
Muilla tätä ongelmaa ei vaikuta olleen kertaakaan, mutta minulla jostain syystä testiajoja rikkoo joskus se, että Flyway-migrojen ajo yrittää tapahtua ennen kuin SpringContextUtility#setApplicationContext()ia on kutsuttu, ja menee rikki kun CsvMigration#getChecksum yrittää käydä kontekstia hakemassa.
En lähtenyt debuggaamaan, mistä syystä järjestys sattui joskus olemaan tuo, kun näemmä asia korjaantuu vaan kertomalla Springille riippuvuudesta.
> General: Initialize springContextUtility before flywayConfiguration

- infra/src/main/resources/i18n/translations.fi.json
- ui/package.json
- ui/src/api/api-fetch.ts
- ui/src/cache/cache.ts
- ui/src/common/change-time-api.ts
- ui/src/common/common-api.ts
- ui/src/common/geocoding-api.ts
- ui/src/geometry/geometry-api.ts
- ui/src/infra-model/infra-model-api.ts
- ui/src/linking/linking-api.ts
- ui/src/publication/card/publication-card.tsx
- ui/src/publication/publication-api.ts
- ui/src/ratko/ratko-api.ts
- ui/src/track-layout/layout-km-post-api.ts
- ui/src/track-layout/layout-location-track-api.ts
- ui/src/track-layout/layout-map-api.ts
- ui/src/track-layout/layout-reference-line-api.ts
- ui/src/track-layout/layout-switch-api.ts
- ui/src/track-layout/layout-track-number-api.ts
- ui/src/user/user-api.ts
- ui/src/utils/react-utils.tsx
API-kutsujen virheenkäsittely menee nyt huomattavasti mielipiteellisemmäksi kuin ennen. Toteutus eroaa aika paljon alkuaan taskille suunnitellusta.
Jätin lopulta oletusarvojen passaamisen api-fetchin metodeille kokonaan pois: Jos kutsuja haluaa korvata virhetilanteessa paluuarvon oletusarvolla, se on hänen vastuunsa. Tämä siksi, koska koodissa oli niin paljon tapauksia, joissa annettiin oletusarvoja cachetetuille kutsuille, joissa siis tämä oletusarvo jäisi mahdollisen väliaikaisen virheen jälkeen cacheen roikkumaan.
Tosin noin yleensäkinhän noita oletusarvoja ei pitäisi juuri tarvita.Jos halutaan vaan näyttää frontilla jokin tieto, joka ladataan dynaamisesti, niin järjestään elementit toteutetaan niin, että ne voivat näyttää tyhjää, jos tietoa ei ole vielä ladattu, ja jos lataaminen ei …
> GVT-2014 Refactor front-end API call error handling

- ui/src/vertical-geometry/displayed-position-guide.tsx
- ui/src/vertical-geometry/vertical-geometry-diagram.tsx
GVT-2127: Draw vertical geometry diagram display position guide when viewing a geometry plan
Previously the position guide was not displayed when viewing the vertical geometry of a specific *geometry plan*. The guide was only displayed when viewing the vertical geometry of a *location track*.
> GVT-2127: Draw vertical geometry diagram display position guide when viewing a geometry plan

- ui/src/geometry/geometry-model.ts
- ui/src/utils/math-utils.ts
- ui/src/vertical-geometry/pvi-geometry.tsx
- ui/src/vertical-geometry/snapped-point.ts
- ui/src/vertical-geometry/util.ts
- ui/src/vertical-geometry/vertical-geometry-diagram-holder.tsx
- ui/src/vertical-geometry/vertical-geometry-diagram.tsx
Previously the vertical geometry diagram sometimes drew lines based on invalid points which were from another context. These points were also used for the height axis bounds calculation, resulting in possibly invalid bounds being used, causing the vertical geometry diagram to have buggy rendering in some specific cases.
Additionally, this pull request includes some review fixes related to GVT-1918 (#718).
---
Korjausperiaate:
1. Määritellään pystygeometriadiagrammia varten derivoitu tyyppi aiemmasta `VerticalGeometryItem`-tyypistä. Tälle uudelle `VerticalGeometryDiagramDisplayItem`-tyypille .start/.point/.end-kentät voi asettaa undefineksi verrattuna alkuperäiseen. Nämä kentäthän ovat sinällään ihan hyvän nimisiä, mutta niihin päätyy oletusarvoisesti oikeaa dataa vain tietyn …
> GVT-2116: Fix vertical geometry diagram drawing related edge cases

- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationDao.kt
En lähtenyt lisäämään tälle testiä vaikka olisikin teoriassa regressiotestauskelpoisesta bugista kyse, tämähän kun on rakenteeltaan tasan samanlainen tiedonhaku kuin nuo kaikki muutkin: Voihan nuo kaikki olla ihan hyvin null.
> GVT-2130 Allow change with null descriptionSuffix

- ui/src/data-products/element-list/element-list-view.tsx
- ui/src/data-products/element-list/element-table.tsx
- ui/src/data-products/kilometer-lengths/kilometer-lengths-table.tsx
- ui/src/data-products/kilometer-lengths/kilometer-lengths-view.tsx
- ui/src/data-products/vertical-geometry/vertical-geometry-table.tsx
- ui/src/data-products/vertical-geometry/vertical-geometry-view.tsx
Vaikutus näkyy käytännössä varmaan parhaiten siinä, että jos on iso lista jotain tietotuotetta auki (vaikkapa sijaintiraiteen geometriaelementtien lista), niin fokuksen vieminen vaikka sijaintiraidevalintaboksiin ja siitä pois ei aiheuta näkyvää kälin pysähdystä.
> General: Memoize data product lists

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/TrackLayout.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/TrackLayoutDomainTestData.kt
- ui/src/tool-panel/location-track/dialog/location-track-edit-dialog.tsx
- ui/src/tool-panel/location-track/location-track-infobox-duplicate-of.tsx
- ui/src/tool-panel/location-track/location-track-infobox.tsx
- ui/src/track-layout/layout-location-track-api.ts
- ui/src/track-layout/track-layout-model.tsx
- ui/src/track-layout/track-layout-react-utils.tsx
- ui/src/vertical-geometry/vertical-geometry-diagram-holder.tsx
Ainoa varsinainen funktionaalinen muutos on, että sijaintiraiteen duplikaattien järjestely menee nyt duplikaatin alun rataosoitteen mukaan, eikä nimen mukaan.
Mutta samassa tuli mukana aika kasa muutosta sille, miten sijaintiraiteen infoboksin tiedot ladataan, siihen kun oli alkanut kertyä aika paljon eri dynaamisten tietojen lataamista pienissä osissa (esim. nyt aiemmin ensiksi päissä olevien vaihteiden id-tietojen lataaminen, sitten erikseen vaihteiden lataaminen id:n perusteella). Tämä aiheuttaa tarpeetonta kellottelua. Nyt ylimääräiset tiedot tulevat yhdessä pompsissa LocationTrackInfoboxExtras-oliossa, ja koko infoboksi näytetään vasta kun se on ladattu.
> GVT-2108 Combine infobox extra info loading, +sort duplicate tracks

- ui/src/infra-model/infra-model-main.scss
- ui/src/infra-model/list/infra-model-list-store.ts
- ui/src/infra-model/list/infra-model-list.module.scss
- ui/src/infra-model/projektivelho/pv-file-list.tsx
- ui/src/infra-model/tabs/infra-model-tabs.scss
- ui/src/infra-model/tabs/infra-model-tabs.tsx
Tallennetaan taulukoiden sorttaus reduxiin ja luetaan sieltä.
Lisäbonuksena ärsyynnyin inframodel-näkymän tabien scrollaamiseen sisällön mukana ja tappelin sen nyt sellaiseksi, että ainoastaan taulukot scrollaavat sivusuunnassa. Koitin säätää myös pystysuuntaisen scrollin toimimaan niin, että pelkästään taulukot scrollaisivat ja tabit jäisivät näkyviin ylös, but alas, it was once again not meant to be :pepehands:
> GVT-2129: ProjektiVelhonäkymissä taulukon järjestyksen pitäisi säilyä navigoidessa

- ui/src/vayla-design-lib/dialog/dialog.tsx
- ui/src/vayla-design-lib/dropdown/dropdown.scss
Z-indeksithän ne siellä. Suoraa syytä en tosin lyhyellä penkomisella löytänyt sille, että miksi aikaisemmin vain luontidialogin dropdownit bugasivat. Enivei nyt ne on korjattu.
Otin myös käyttöön kaikkien dialogien portaloinnin `<body>`-elementtiin. Olen miettinyt sitä jo aiemminkin, koska sillä saadaan dialogit rendaamaan konsistentisti samaan paikkaan, ja siten varmasti aina saman DOM:in ja tyylien vaikutusalueen alle. Tätä myötä sillä polulla mitä kautta mikäkin dialogi avataan ei pitäisi olla enää merkitystä sen toimivuuteen tai tyyleihin.
> GVT-2148: Luo uusi -dialogien dropdown-valikot eivät avaudu

- infra/src/main/kotlin/fi/fta/geoviite/infra/common/ChangeTimeController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/util/DaoBase.kt
- ui/src/common/common-slice.ts
- ui/src/infra-model/infra-model-main.scss
- ui/src/infra-model/view/form/infra-model-form.tsx
- ui/src/infra-model/view/infra-model-edit-loader.tsx
- ui/src/infra-model/view/infra-model-import-loader.tsx
- ui/src/infra-model/view/infra-model-upload-loader.tsx
- ui/src/infra-model/view/infra-model-view.tsx
Suurimpana juttuna tässä Authorien hakemisen refaktorointi ulos useEffectistä. Nyt ne haetaan changeTimen mukaan. Se aikaisempi logiikka oli muutenkin jotenkin todella härö.
Devmodessa haetaan edelleen asioita tuplana, mutta tämä johtuu siitä, että `<StrictMode>` päällä React ajaa kaikki Effectit tuplana. Näitä en lähtenyt korjaamaan sillä se menisi vaikeaksi, sillä myös `useLoader`-kutsut jne. ajetaan tuplana. Näihin pitäisi kehittää jonkinlainen "älä aja hakua uusiksi jos vanha haku on jo päällä" -logiikka, joka enivei tod.näk. toimisi ainoastaan jos bäkkäri vastaa tarpeeksi hitaasti.
> GVT-2135: Bäkkäriin lähtee useita API-kutsuja kun tiedostoa tuodaan ProjektiVelhosta

- infra/src/main/kotlin/fi/fta/geoviite/infra/geography/GeoToolsGeometries.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/Publication.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationUtils.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationValidation.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/util/List.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/util/ResultSetExternal.kt
- infra/src/main/resources/i18n/translations.fi.json
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationUtilsTest.kt
- ui/src/publication/publication-model.ts
- ui/src/publication/table/publication-table-details.tsx
Plus bugifiksiä, ja pari muuta asiaan liittyvää muutosta. Pääteemat:
- Julkaisulokin remarkkien rakenne meni vähän liian monimutkaiseksi viitsiä yrittää viedä frontille rakenteellisena; viedään siis vain tekstinä, ja siksi PublicationChangeRemark poistuu kokonaan
- Geometrioiden haku julkaisulokia näyttäessä vaati hieman perffimiettimisiä, tosin ei isoja
- Varsinainen algoritmi erojen laskemiseen omana mötikkänään
> GVT-2110 Expand publication log remarks about alignment geometry changes

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutAlignmentService.kt
Aiemmin sectioneiden alku- ja loppu-m-arvot laskettiin pituusmittauslinjaa pitkin. Raiteilla tämä johti siihen, että kun raiteen ja pituusmittauslinjan geometriat on kuitenkin usein vähintään hieman eriävät, niin highlightit piirtyivät vääriin paikkoihin
> GVT-2134: Raiteen geometriat -näkymän mukainen korostus näkyy kartalla väärin

- infra/src/main/resources/db/migration/prod/V49__fix_broken_refence_line_draft_refs.sql
This migration fixes any broken reference lines cause by migration
V43__generates_missing_reference_lines.sql
The issue there was that it handled inter-object references via row ID rather than official ID:
- Correct: reference_line.track_number_id = coalesce(track_number.draft_of_track_number_id, track_number.id)
- Actual: reference_line.track_number_id = track_number.id
> Remove broken reference lines

- infra/src/main/kotlin/fi/fta/geoviite/infra/geocoding/GeocodingDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationValidation.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/ReferenceLineController.kt
- infra/src/main/resources/i18n/translations.fi.json
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationValidationTest.kt
- ui/src/common/common-model.ts
- ui/src/geoviite-design-lib/track-meter/track-meter.tsx
- ui/src/geoviite-design-lib/track-number/track-number-link.tsx
- ui/src/preview/preview-table.tsx
- ui/src/tool-panel/location-track/dialog/location-track-edit-dialog.tsx
- ui/src/tool-panel/switch/switch-infobox-track-meters.tsx
- ui/src/tool-panel/switch/switch-infobox.tsx
- ui/src/tool-panel/tool-panel.tsx
- ui/src/tool-panel/track-number/dialog/track-number-edit-dialog.tsx
- ui/src/tool-panel/track-number/track-number-geometry-infobox.tsx
- ui/src/tool-panel/track-number/track-number-infobox-linking-container.tsx
- ui/src/tool-panel/track-number/track-number-infobox.tsx
- ui/src/track-layout/layout-map-api.ts
- ui/src/track-layout/layout-track-number-api.ts
- ui/src/track-layout/track-layout-model.tsx
- ui/src/track-layout/track-layout-react-utils.tsx
- ui/src/utils/array-utils.ts
- ui/src/utils/date-utils.ts
- ui/src/vayla-design-lib/field-layout/field-layout.tsx
- ui/src/vayla-design-lib/layers.scss
Tätä tutkiessa törmäsin joukkoon muita ongelmia joita paljastui aina edellisen takaa seuraava. Korjattu nämä:
- Ratanumeron pituusmittauslinja ei poistu heti kartalta kun se merkkaa poistetuksi
- Ratanumeron poistuessa sen toolpanelin infoboxin tiedot eivät päivity kaikilta osin (validointi, geometria, jne)
- Validointi valittaa poistettuun ratanumeroon viittaavastakm-pisteestä ja raiteesta vaikka nekin olisi jo poistettu
- Ratanumeron poiston seurauksena vaihteen tietojen katselussa lensi virheitä johtuen osoitteiden haun epäonnistumisesta
- Poistettu ratanumero ei näy esikatselun raiteiden/km-pisteiden tiedoissa ratanumero-columnissa
- Kun ratanumero on poistettu, raiteen ratanumero-kenttä toolpanelissa näyttää loputonta spinneriä
- UI:lla esitetty ratanumerolinkki poistettuun …
> GVT-2077 Recreating a previously deleted tracknumber

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/DraftableObjectDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/DraftableObjectService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutKmPostController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/ReferenceLineController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/TrackLayout.kt
- ui/src/common/common-model.ts
- ui/src/track-layout/layout-km-post-api.ts
- ui/src/track-layout/layout-location-track-api.ts
- ui/src/track-layout/layout-reference-line-api.ts
- ui/src/track-layout/layout-switch-api.ts
- ui/src/track-layout/layout-track-number-api.ts
- ui/src/track-layout/track-layout-react-utils.tsx
Meillä on frontissa 2 luokkaa nimellä ChangeTimes: toinen on se johon kerätään kaikkien käsitteiden muutosajat reduxiin ja toinen on se joka kuvaa yhden objektin luonti/muutos aikoja. Sama nimi on johtanut harhaan sen verran monta kertaa että jälkimmäinen noista on nyt nimetty uudelleen.
> Rename second changetimes

- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationUtils.kt
- infra/src/main/resources/i18n/translations.fi.json
Suurin osa geometriamuutosten laskennan koodista jää elämään, koska se kyllä näyttäisi toimivan perffiä lukuunottamatta ainakin oikeahkosti, ja vaihdelinkitysten laskenta käyttää siitä muutenkin isohkoa osaa. Varsinainen ominaisuus pitää vaan ottaa pois, koska se käyttää minuuttitolkulla aikaa geokoodauslaskentoihin pitempiä julkaisulokisivuja avattaessa.
> GVT-2110 Disable detailed geometry change calculation in publication log

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberServiceIT.kt
- ui/src/tool-bar/tool-bar.tsx
- ui/src/track-layout/layout-track-number-api.ts
- ui/src/track-layout/track-layout-slice.ts
GVT-2159: Add support for searching track numbers in the map view
Previously the search bar supported searching for location tracks and switches.
> GVT-2159: Add support for searching track numbers in the map view

- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationDao.kt
Selkein hyöty on että PublicationServiceIT#fetchingPublicationListingWorks()in ajaminen tulee vähemmän jännittäväksi, mutta taitaahan tämä tehdä myös ihan julkaisulokinkin järjestelystä luotettavamman.
> General: Order publication fetch deterministically

- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/Publication.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationUtils.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/TrackLayoutDomainTestData.kt
Vaihdelinkkien muutosten haku on suht monimutkainen ja eroteltu nyt omaksi massahaukseen, tosin postgressi osaisi näemmä hoitaa sen nyt melkein kohtuudella julkaisu kerrallaankin haettaessa, mutta silti selvästi nopeammin näin.
fetchPublicationLocationTrackSwitchLinkChanges-haun logiikka ylätasolla:
- haetaan aikavälin julkaisut
- niistä haetaan sijaintiraiteille tehdyt suorat muutokset (epäsuorilla ei ole merkitystä, tässä kun katsotaan vaihdelinkkejä, kun taas epäsuorien muutosten käsittely on osoitemuutoksia varten)
- niistä haetaan vanhan ja uuden version vaihdelinkityksiin liittyvät tiedot, rikastettuna sillä, oliko kyseessä nyt siis muutoksen vanha vai uusi puoli
- nämä puretaan varsinaisiksi vaihde-iideiksi
- näille haetaan switch_versionista kaikki versiot, joista tietenkin vain …
> GVT-2177 Julkaisulokin laskemisesta rinnakkaisuus pois + selkeämpi samannimisten vaihteiden käsittely

- ui/src/map/layers/switch/switch-linking-layer.ts
GVT-2176: Disable displaying deprecated switch linking joints
The older switch linking joint layer (red circles with crosses) should no longer be displayed, but the code regarding it is not yet determined to be removed completely (see GVT-2176).
> GVT-2176: Disable displaying deprecated switch linking joints

- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/SwitchLinkingService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/linking/SwitchLinkingServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/TrackLayoutDomainTestData.kt
GVT-2113: Snap slightly overlapping switch segments to nearby segments when linking
Previously the existing switch linking was removed when the new switch had even a slight overlap with the previous switch. If the overlap is too large or a nearby segment without switch information is not found, the previous switch linking is still removed.
> GVT-2113: Snap slightly overlapping switch segments to nearby segments when linking

- ui/src/tool-panel/switch/geometry-switch-linking-infobox.tsx
geometrySwitch:iä ei oikeasti käytetty tässä infoboksissa lainkaan, paitsi siihen, että jos sen lataamiseen meni aikaa, niin se esti suggestedSwitchin latautumisen; ja suggestedSwitchin latauksen riippuvuuslistassa sitä ei ollut, vaan siellä oli vain geometrySwitchId.
> GVT-2197 Fix dependencies for geometry switch infobox linking state loader

- ui/src/preview/preview-view.tsx
- ui/src/publication/publication-utils.ts
- ui/src/track-layout/track-layout-slice.ts
- ui/src/utils/array-utils.ts
Samassa syssyssä koottu vähän yhteen kasaa PublishRequestIds-tietoja käsitteleviä funktiota.
Se, että revertedCandidatesSoFar on refissä, menee vähän Reactin ohi, mutta tässä tapauksessa sillä sattuu saamaan parhaiten tilanhallinnan pysymään synkassa, ja muuten vaatisi enemmän kiemuroita välttää listojen välkkymiset.
> GVT-2174 Hide reverted items in preview view

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/DraftableObjectService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSearchController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackService.kt
- ui/src/tool-bar/tool-bar.tsx
- ui/src/track-layout/layout-switch-api.ts
- ui/src/track-layout/layout-track-number-api.ts
- ui/src/track-layout/track-layout-api.ts
- ui/src/track-layout/track-layout-search-api.ts
* The toolbar search now creates a single API request to a new backend API route instead of multiple.
* The backend search functionality was modified to be in an abstract class instead of multiple similar implementations.
* Unnecessary UI and backend code was removed as it was no longer used anywhere.
Muuteltu aiemman pullarin kommenttien perusteella, ks. https://github.com/finnishtransportagency/geoviite/pull/801
> GVT-2159 Review: Map view search functionality refactors

- ui/src/tool-bar/tool-bar.tsx
- ui/src/vayla-design-lib/dropdown/dropdown.scss
Hakuehto vie nyt kaiken mahdollisen tilan mitä se vaan voi (eli ikoniin saakka, aiemmin se vei vaan noin puolet). Tämän lisäksi roplattu tulosjoukon maksimikorkeutta siten, että nyt meillä viimeisestä näkyvästä hakutuloksesta näytetään vaan osa. Tämä antaa operaattorille paremman indikaation siitä, että listalla on vielä enemmänkin nähtävää ja että sitä voi scrollata.
> GVT-2185 & GVT-2186: CSS-korjauksia dropdowneihin

- infra/detekt.yml
General: Increase detekt constructor parameter amount warning threshold
The amount of dependency injected resources to class constructors is very often already more than the default limit of detekt.
In the future it might be useful to split classes requiring large amount of external resources (such as services), but for now increasing the constructor parameter amount threshold of detekt seemed like a sane option in order to reduce the amount of detekt-related noise.
> General: Increase detekt constructor parameter amount warning threshold

- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryController.kt
- ui/src/geometry/geometry-api.ts
- ui/src/map/layers/geometry/geometry-alignment-layer.ts
- ui/src/map/layers/geometry/geometry-km-post-layer.ts
- ui/src/map/layers/geometry/geometry-switch-layer.ts
- ui/src/map/layers/utils/layer-utils.ts
- ui/src/map/map-view.tsx
- ui/src/track-layout/track-layout-model.tsx
Teoriassa nyt jos sivun refreshaa, niin suunnitelmien lataamiseen voi juuri sopivassa tilanteessa mennä hetken verran pidemmän kuin ennen, koska nyt käydään ensiksi katsomassa (jo olemassaolevalla suunnitelman alueiden haulla) että mitä suunnitelmia kartalla näkyvällä alueella on, ja vasta sitten käydään hakemassa niistä ne, jotka olivat sekä näkyvällä alueella että silmällä valittuja; mutta useimmissa refreshauksissa latauksien määrä vähenee.
> GVT-2218 Filter trackLayoutPlan loading by displayed tiles

- infra/src/main/resources/i18n/translations.fi.json
- ui/src/tool-panel/geometry-alignment/geometry-alignment-linking-infobox.tsx
- ui/src/tool-panel/km-post/dialog/km-post-edit-dialog.tsx
- ui/src/tool-panel/km-post/km-post-infobox.tsx
- ui/src/tool-panel/location-track/dialog/location-track-edit-dialog.tsx
- ui/src/tool-panel/location-track/location-track-infobox.tsx
- ui/src/tool-panel/switch/dialog/switch-edit-dialog.tsx
- ui/src/tool-panel/switch/switch-infobox.tsx
- ui/src/tool-panel/track-number/dialog/track-number-edit-dialog.tsx
- ui/src/tool-panel/track-number/track-number-infobox.tsx
Pääasiallisina muutoksina:
* Poistonapeissa teksti "Poista luonnos" typistetty vain muotoon "Poista"
* Muutettu dialogeista tallentamatta poistumisen nappuloissa "Poistu"-tekstimuodot "Peruuta":ksi
* Yksipalstaisissa dialogeissa alareunan tallenna- ja peruuta-nappulat tasattu oikeaan reunaan silloin jos luonnoksen poistonappula on näkyvissä
* Muutettu satunnaisesti vastaan tulleena myös linkitystilassa "Poistu"-napin tekstimuoto "Peruuta":ksi
> GVT-2225: Parannuksia muutosdialogeihin

- ui/src/tool-panel/geometry-alignment/geometry-alignment-linking-infobox.tsx
- ui/src/vayla-design-lib/dropdown/dropdown.scss
- ui/src/vayla-design-lib/text-field/text-field.scss
Täällä syyllinen oli desimaaliarvojen käyttäminen paksuutena. Aiempien tapaan tämä näyttäytyi ainoastaan sopivan selaimen ja sopivan zoomitason combona (jos selaimena oli Chrome ja/tai Firefoxissa oli käytössä 100%:n monikerta zoomitasona, niin kaikki näkyi ok.)
Samalla revertattu myös yksi edellisellä tiketillä tehty käännösmuutos joka rikkoi E2E-testit
> GVT-2230: Syöttökentän punaisen korostuksen paksuus vaihtelee

- infra/src/main/kotlin/fi/fta/geoviite/infra/geocoding/Geocoding.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geocoding/GeocodingService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/geocoding/GeocodingTest.kt
Varsin simppeli muutos, geokoodauskontekstihan ei tarvitse varsinaisia kilometritolppia, joten miksipä pitää niitä mukana. Kaikki muu data näytti olevan ihan oikeasti tarpeen, tai järkevintä pitää mukana nykymuodossaan.
> GVT-2191 Remove km posts from geocoding context

- infra/src/test/kotlin/fi/fta/geoviite/infra/geocoding/GeocodingTest.kt
GeocodingContext's constructor no longer takes a km posts argument at all.
> GVT-2191 Remove outdated unit test

- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/ElementListing.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/geometry/ElementListingTest.kt
Lisäsin pikaisen testin, koska kyseessä regressio GVT-1687 toteutuksesta. Geometriapuolella on oma elementtilistausfunktio, johon en nyt lähtenyt lisäämään samaa duplikaattien poistoa, koska siinä ei ole riskiä, että duplikaatteja alkuunkaan luotaisiin.
> GVT-2243 Remove duplicates from element list

- ui/src/map/layers/alignment/location-track-duplicate-endpoint-indicator-layer.ts
Härpäkkeet piirtyivät lounaaseen menevillä rataosilla väärälle puolelle viivaa. Tehty nyt käsittely, joka laskee paremmin missä tilanteissa härpäkkeet kuuluu piirtää viivan yläpuolelle ja missä alapuolelle
> GVT-General: Korjaa raiteiden pilkkomisen härpäkkeiden piirtopaikka lounaaseen menevillä osuuksilla

- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryService.kt
- ui/src/geometry/geometry-api.ts
Review korjaus liittyen aiempaan PR:ään: https://github.com/finnishtransportagency/geoviite/pull/736
Eli ei käytetä backendissä kovakoodattua fi-arvoa, vaan valutetaan oikea arvo frontin puolelta.
> GVT-2120 Review fixes: allow using other languages than Fi

- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationValidation.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackDao.kt
- infra/src/main/resources/i18n/translations.fi.json
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationValidationTest.kt
Lisätään tarkistus, että tuleeko julkaisuun raiteita, jotka ovat itse duplikaatteja, ja joihin on duplikaattiviittauksia jostain sellaisesta raiteesta, joka olisi tulossa julkaistuksi (joko nyt jo julkaistu, tai mukana julkaistavassa joukossa).
> GVT-2202 Tighten duplicate location track validation

- infra/src/main/resources/i18n/translations.fi.json
- ui/src/preview/preview-confirm-revert-changes-dialog.tsx
- ui/src/preview/preview-view.tsx
- ui/src/preview/publication-request-dependency-list.tsx
- ui/src/publication/publication-model.ts
- ui/src/tool-panel/track-number/dialog/track-number-delete-confirmation-dialog.tsx
- ui/src/tool-panel/track-number/dialog/track-number-edit-dialog.tsx
- ui/src/tool-panel/track-number/track-number-deletion.ts
- ui/src/tool-panel/track-number/track-number-infobox.tsx
Isohko määrä koodimuutoksia, koska yksinkertaistin tässä hieman ratanumerodialogin logiikkaa:
- Uutta ratanumeroa luotaessa poistettu-tila on disabloitu (mutta selkeyden vuoksi silti näkyvillä); uuden dialogissa luodun ratanumeron tallentamiseen poistettu-tilaisena ei ole mitään käsittelyä, koska käyttäjä ei pysty sellaista tekemään
- varsinainen ratanumeroiden draftien delete-api ja sen JS-puoli on yhä olemassa, mutta niitä ei tällä hetkellä käytetä lainkaan (ehkä voisi poistaakin)
- Riippuvuuslista näytetään samalla koodilla kuin julkaisupuolella
> GVT-2203 Use publication revert code for deleting track numbers

- ui/src/app-bar/app-bar.scss
- ui/src/app-bar/data-products-menu.tsx
- ui/src/infra-model/projektivelho/pv-file-list.scss
- ui/src/infra-model/projektivelho/pv-file-list.tsx
- ui/src/publication/table/publication-table-row.tsx
- ui/src/publication/table/publication-table.scss
Täällä korjattu seuraavat:
* Julkaisuloki-näkymän taulukoissa liikaa bordereita
* Tietotuotteet-linkistä kadonnut highlight
* PV-dokumentin latauslinkki on koko solun levyinen
> GVT-2245 & GVT-2249 & GVT-2250: UI-korjauksia

- ui/src/tool-panel/km-post/dialog/km-post-edit-dialog.tsx
GVT-2261: Disable assignment of PLANNED-state for km-posts
This PLANNED-state is not yet considered to be a possible assignment for any resources, but the restriction is currently only done in the UI-side as the PLANNED-state will be allowed in the near future (and the users of this application are trusted in general).
> GVT-2261: Disable assignment of PLANNED-state for km-posts

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutKmPostController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutKmPostDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutKmPostService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/TrackLayout.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutKmPostServiceIT.kt
- ui/src/tool-panel/km-post/km-post-infobox.tsx
- ui/src/tool-panel/tool-panel.tsx
- ui/src/track-layout/layout-km-post-api.ts
- ui/src/track-layout/track-layout-model.tsx
Varsinainen alkuperäinen bugi oli puuttuvat depsut infoboksin kilometripituuden loaderissa.
Mutta toteutusta testatessa tuli vähän sellainen olo, että olisipa jees, jos päivityksen jälkeen uusi kilometripituus latautuisikin silmänräpäyksessä eikä sekunnin murto-osassa. Isosta optimoinnista tuossa getSingleKmPostLength()issa siis ei ole kyse, mutta ero on kuitenkin selvä.
> GVT-2241 Update km post infobox km lengths promptly

- infra/src/main/kotlin/fi/fta/geoviite/infra/configuration/CacheConfiguration.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geocoding/AddressPointsCache.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geocoding/GeocodingService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationService.kt
Hieman pomppimista koodissa, koska halusin pitäytyä siinä, että AddressPointCache olisi GeocodingServicen toteutusdetalji, vaikka onkin periaatteessa oma palvelunsa.
precacheLocationTrackAlignmentAddresses palauttaa paluutietonsa ainoastaan AddressPointCachen kakutuksen kautta. Periaatteessa parallelStream()ikin on sille siksi ylimääräistä työtä, koska voisihan tehdä myös vaan niin, että rinnakkaistaa vaan kaikki pois ja jatkaa eteenpäin mitään odottelematta, ja cachesta löytyy sitten myöhemmin sijaintiraiteita validoitaessa niiden raiteiden osoitepisteet, jotka rinnakkaisajot sattui ehtimään laskea: Jätin kokeilun perusteella sen kuitenkin tekemättä, koska siitä tulee enemmän koodillista outoutta kuin perffiä, eritoten jos kakut on muutenkin kuumina validointiin tultaessa.
> GVT-2259 Precalculate location track alignment addresses for publication validation

- ui/src/data-products/data-product-table.scss
- ui/src/data-products/data-products-utils.ts
- ui/src/data-products/element-list/element-table.tsx
GVT-2244: Assign context-specific min-widths and centering for element table columns
Previously the element table column headings were displayed with somewhat odd text-alignment. Data rows were also often broken up to multiple lines, making the table possibly more difficult to read.
The column min-widths are based on "maximum possible current length", expect for the plan file name column were somewhat of an average width was chosen due to some plan file names being much longer than the usual ones. This means that the plan file name column can sometimes still end up being multiple rows in height.
> GVT-2244: Assign context-specific min-widths and centering for element table columns

- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryCant.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryValidation.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/inframodel/InfraModelConversion.kt
- infra/src/main/resources/i18n/translations.fi.json
- infra/src/test/kotlin/fi/fta/geoviite/infra/geometry/ValidationTest.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/inframodel/InfraModelParsingIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/inframodel/InfraModelServiceIT.kt
- infra/src/test/resources/inframodel/testfile_simple_without_cant_rotation_point.xml
GVT-2250: Allow uploading inframodels with empty or undefined cant rotationPoint field
Empty rotationPoint values are however validated as invalid.
> GVT-2250: Allow uploading inframodels with undefined cant rotationPoint

- infra/src/main/kotlin/fi/fta/geoviite/infra/geocoding/Geocoding.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationValidation.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberService.kt
- infra/src/main/resources/i18n/translations.fi.json
- infra/src/test/kotlin/fi/fta/geoviite/infra/geocoding/GeocodingTest.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationValidationTest.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/TrackLayoutDomainTestData.kt
Varsinainen pihvi varsin suoraan nähtävissä oleva muutos (tuo startKmIsTooLong-tarkistus itsessään, ja validaation lisäys), mutta tämän myötä tulee mahdolliseksi ensimmäistä kertaa, että geokoodauskontekstille löytyy kyllä kaikin puolin dataa, mutta luomisvaiheessa nähdään, että eipä se nyt onnistunutkaan, ja sitä varten piti vielä tehdä GeocodingContextCreateResult#geocodingContextista nullable. Suurin osa koodimuutoksista siitä tulevaa noisea.
> GVT-2263 Validate reference line start km sanity

- .github/workflows/pull_request.yml
Defaulttina katkaisee vasta 360 minuutin kohdalla
> GVT-2187: Cancel Github Actions job at 60 minute mark

- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/pagemodel/map/TrackLayoutPage.kt
Hieman mälsää käyttää sleeppiä, mutta joillakin zoomitasoilla skaalan arvo säilyy samana vaikka zoomaiskin ulos/sisään, jotenka siihen ei voida luottaa. Ja taas ilman sleeppiä on pienen pieni riski, että zoomataankin kahdesti koska arvo ei ole ehtinyt päivittyä.
> General: Map scale does not always change when zooming in or out

- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/Linking.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/LinkingService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/SwitchLinkingService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackServiceIT.kt
- ui/src/linking/linking-model.ts
- ui/src/linking/linking-utils.ts
- ui/src/tool-panel/switch/geometry-switch-linking-infobox.tsx
- ui/src/tool-panel/switch/switch-joint-infobox-container.tsx
- ui/src/tool-panel/switch/switch-joint-infobox.tsx
GVT-2143: Display actual topological connections that will be created during switch linking
Previously the switch linking view did not always display the topological connections that would actually be created after the user clicked the "Link" button having confirmed the suggested switch linking. It was not possible to calculate the exact expected topological switch connections without actually linking a switch to the database. This was due to the topological connections being defined in the backend after the database had already been modified to contain switch data for segments. 
The frontend previously used another algorithm for expected topological connections for switches during linking, sometimes leading to incorrect results.
This PR includes a way to calculate the expected …
> GVT-2143: Display actual topological connections that will be created during switch linking

- ui/src/infra-model/list/infra-model-list.module.scss
Ylemmältä elementiltä päätyvä overflow-käyttäytyminen toteuttaa jo halutunlaisen scrollauksen (testattu chromiumilla ja firefoxilla).
> GVT-2271: Fix horizontal scrollbar being visible only at the bottom of the inframodel list

- .github/workflows/pull_request.yml
GVT-2257: Cache Postgres docker image in GitHub actions
> GVT-2257: Cache Postgres Docker image in GitHub actions

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutKmPostController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutKmPostService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/TrackLayout.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutKmPostServiceIT.kt
- ui/src/tool-panel/km-post/km-post-infobox.tsx
- ui/src/track-layout/layout-km-post-api.ts
- ui/src/track-layout/track-layout-model.tsx
Näinhän tehdään muidenkin olioiden kanssa: Jos haku olisi muuten oikein, mutta haettavaa oliota ei vaan ole lainkaan olemassa, niin tulos on HTTP 204-tilainen.
> GVT-2284 Report nonexistent km post's length with HTTP 204 as usual

- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/DraftableObjectDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/DraftableObjectService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutKmPostController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutKmPostService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/ReferenceLineController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/TrackLayout.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/util/DaoBase.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/geometry/GeometryDaoIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutKmPostServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/ReferenceLineServiceIT.kt
- ui/src/preview/publication-request-dependency-list.tsx
- ui/src/tool-panel/km-post/km-post-infobox.tsx
- ui/src/tool-panel/location-track/location-track-infobox.tsx
- ui/src/tool-panel/switch/switch-infobox.tsx
- ui/src/tool-panel/track-number/track-number-infobox.tsx
- ui/src/track-layout/layout-km-post-api.ts
- ui/src/track-layout/layout-location-track-api.ts
- ui/src/track-layout/layout-reference-line-api.ts
- ui/src/track-layout/layout-switch-api.ts
- ui/src/track-layout/layout-track-number-api.ts
- ui/src/track-layout/track-layout-api.ts
- ui/src/track-layout/track-layout-model.tsx
- ui/src/track-layout/track-layout-react-utils.tsx
Täällä korjattu useampikin bugi. Merkkailen korjaukset koodiin.
Huom.: Täällä ei ole vielä toteutettuna a) indeksiä kantaan `DraftChangeInfo`:n haulle (ei ole kauhean hidas näinkään ainakaan lokaalisti) ja b) selection-muutoksia. Taidan ehkä tehdä näistä oman ja erillisen tiketin kun tämä paisui näinkin isoksi jutuksi muutenkin.
> GVT-2285, GVT-2295: Bugeja draft-only-reverteissä

- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/SwitchLinkingService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutGeometry.kt
Oleellista perffivaikutusta tällä ei ole, mutta kyllähän tällä periaatteessa säästää hyvin lyhytikäisen allokaation, ja nuo asSequence()-kutsut on asetettu niin, että isoja taulukoita ei pitäisi arvita kopioida missään vaiheessa.
Erillisenä juttuna vielä getMaxDirectionDeltaRads()issa osoittautui, että siellähän oli ylimääräisiä null-tarkistuksia. Muuten sen toteutus ei olisi sequencen käytön myötä muuttunut lainkaan.
> General: Simplify and do getMaxDirectionDeltaRads in-place

- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryValidation.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/inframodel/InfraModelService.kt
- infra/src/main/resources/db/migration/repeatable/R__07.01_feature_type_data.sql
- infra/src/main/resources/i18n/translations.fi.json
Korjattu 500-error joka aiheutui tyyppikoodista jota ei ole kannassa. Oikeastaan korjaus on tehty 2 kertaa, mutta se tuntui järkevältä:
- Päivitetty tunnettujen tyyppikoodien lista kattavammaksi buildingsmartin dokumentaation mukaan -> sisältää tuonkin tiedoston koodin
- Muutettu tallennusta niin että jos koodi on tuntematon, tallennetaan se nullina sen sijaan että heitetään 500 error koska viite on rikki
- Päivitetty muutenkin validointivirheitä feature type codejen ympärillä
> GVT-2265 Update known feature type codes + allow saving with unknown feature type

- ui/src/tool-panel/km-post/dialog/km-post-edit-dialog.tsx
- ui/src/tool-panel/location-track/dialog/location-track-edit-dialog.tsx
- ui/src/tool-panel/switch/dialog/switch-edit-dialog.tsx
- ui/src/tool-panel/track-number/dialog/track-number-edit-dialog.tsx
Tämä sama toistui kaikilla muillakin assettityypeillä, joten korjattu kaikkialle. Korjaus on sinällään todella simppeli (suljetaan dialogi aina manuaalisesti tallentamisen jälkeen.) Meni pitkään keksiä että miksi suorat poistot toimivat mutta navigoinnin jälkeiset eivät, mutta vastauksena tähän oli se, että aiemmin poistettava asset on aina ollut valittuna, poiston läpimenon seurauksena ka. asset on samalla myös unselectattu, assetin infoboksi on kadonnut näkyvistä assetin unselectauksen myötä, ja poistodialogi on ollut Reactin komponenttipuussa infoboksin lapsena. Navigoiduissa poistoissa valintaan ei kosketa, joten dialogia ei voi sulkea tuolla tavalla.
> GVT-2305: Tasakilometripisteen editointidialogi jää "Poisto"-operaation jälkeen näkyviin

- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/pagemodel/common/E2EDropdown.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/pagemodel/map/ToolPanelDialog.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/testgroup1/LocationTrackDialogTestUI.kt
- ui/src/vayla-design-lib/dropdown/dropdown.scss
- ui/src/vayla-design-lib/dropdown/dropdown.tsx
Isohko yksinkertaistus Dropdownin toimintaan.
Peruskäytössä ei tapahdu käyttäjille mitään muutosta: Käyttäjä vaan valitsee dropdownin ja alkaa kirjoittaa hakuehtoa. Visuaalinen ero on, sen kokoinen, että siinä, missä ennen aiempi valinta jäi kenttään ikään kuin placeholderina (mutta ei oikeana placeholderina) kun käyttäjä fokusoi kentän, nyt fokusointi maalaa automaattisesti tekstisisällön.
Samoin varsinainen placeholder kentässä nyt on ihan oikeasti inputin placeholder, tämä näkyy esim. toolbarin "Hae..."-tekstinä.
Muutoksen myötä tosin ei jäänyt oikein selkeää hyvää paikkaa esittää valitun arvon qa-id:tä suljetussa kentässä. Päätin tähän hätään, että en lähde keksimällä keksimään tuotantokoodissa paikkoja DOMiin tällaisille vain testien tarvitsemille arvoille, vaan jos ei ola selvää …
> GVT-2233 Use actual placeholder, +auto-select input text on focus in Dropdown

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberDao.kt
En enää muista, miksi en käyttänyt pullarissa https://github.com/finnishtransportagency/geoviite/pull/879 sitä vaihtoehtoa, että sorttaa nyt nuo ratanumerot vaan tietokannassa. Perffivaikutuskaan ei voi olla muuta kuin vainoharhaa, sorttaukseen menevä aikahan on aivan epäoleellista verrattuna kaikkeen muuhun, mitä track_number_publication_viewin näyttämisessä muutenkin tehdään.
Käyttöpaikkapohjaiseksi en tuota haluaisi, minusta on kohtuullista että ratanumeroilla on oletuksena järkevä järjestys.
> GVT-2231 Order track numbers by number whenever listed

- ui/src/track-layout/track-layout-react-utils.tsx
Päivitetään kaikki changetimet, sillä jos selection päivitetään sen vuoksi että ratanumero poistettiin, niin sen mukana on saattanut kadota muunkintyyppisiä assetteja. Ilman tätä ne jäisivät elämään frontille seuraavaan automaattipäivitykseen saakka.
> GVT-2285: Vielä yksi korjaus

- infra/src/main/resources/i18n/translations.fi.json
- ui/src/tool-panel/geometry-plan-infobox.tsx
Lienee kääntynyt epähuomiossa julkaisulokijuttujen yhteydessä, koska siellä huomioista puhutaan remarkkeina. Kannassahan kenttä on tuo entinen `message`, mutta nykyisellään sille keksisi varmaan paljon parempiakin nimiä. InfraModel-näkymässä huomioista puhuttiin observationseina, joten päädyin muuttamaan nämäkin sille nimelle.
> GVT-2307: Suunnitelman toolpanelista puuttuu käännösavain

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackService.kt
Ongelma juontui siitä, että splittauksessa vaihteiden m-arvot laskettiin ratanumeron alusta eikä raiteen alusta. Koko muu splittausmaailma pelaa sillä oletuksella, että m-arvot ovat raiteen alusta.
> GVT-2303: Splitatun raiteen badge piirtyy väärin splitin jälkeen

- ui/src/tool-panel/switch/switch-infobox.tsx
- ui/src/tool-panel/switch/switch-joint-infobox.tsx
- ui/src/tool-panel/tool-panel-container.tsx
- ui/src/tool-panel/tool-panel.tsx
GVT-2270: Allow location track selection from badges in switch joint listing
This should ease the selection navigation for the user. It is also more intuitive, as badges are clickable elsewhere in the UI.
> GVT-2270: Allow location track selection from badges in switch joint listing

- ui/src/geoviite-design-lib/track-meter/navigable-track-meter.tsx
- ui/src/geoviite-design-lib/track-meter/track-meter.scss
- ui/src/geoviite-design-lib/track-meter/track-meter.tsx
- ui/src/map/map-utils.ts
- ui/src/tool-panel/alignment-plan-section-infobox-content.tsx
- ui/src/tool-panel/location-track/location-track-geometry-infobox.tsx
- ui/src/tool-panel/location-track/location-track-infobox.tsx
- ui/src/tool-panel/location-track/splitting/location-track-split.tsx
- ui/src/tool-panel/location-track/splitting/location-track-splitting-infobox.tsx
- ui/src/tool-panel/switch/switch-infobox-track-meters.tsx
- ui/src/tool-panel/switch/switch-infobox.tsx
- ui/src/tool-panel/track-number/alignment-plan-section-infobox.scss
- ui/src/tool-panel/track-number/track-number-geometry-infobox.tsx
- ui/src/tool-panel/track-number/track-number-infobox.tsx
* A new navigable track meter component, which is basically just a container for the actual track meter component was created to reduce the amount of noise in usage places. 
* As an additional refactor, the passing of showArea was also removed to the usage places of the NavigableTrackMeter component for now, as the NavigableTrackMeter-component is now also responsible for getting the reference of the delegated showArea method. This also reduces code noise.
* The pin icon vertical alignment was modified to be more inline with the actual track address text.
* As an additional fix, the cursor style used in the plan listing of a given location track or reference line in the tool panel was modified from pointer to default as it was displayed on top of values that were not actually links or …
> GVT-2269 (part 2): Modify styling, simplify usage of navigable track meter component

- infra/src/main/kotlin/fi/fta/geoviite/infra/authorization/Privileges.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/inframodel/InfraModelController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberController.kt
- infra/src/main/resources/db/migration/repeatable/R__01_role_data.sql
- ui/src/data-products/element-list/element-list-view.tsx
- ui/src/data-products/element-list/entire-rail-network-element-listing.tsx
- ui/src/data-products/element-list/location-track-element-listing-search.tsx
- ui/src/data-products/element-list/plan-geometry-element-listing-search.tsx
- ui/src/data-products/kilometer-lengths/entire-rail-network-km-lengths-listing.tsx
- ui/src/data-products/kilometer-lengths/kilometer-lengths-search.tsx
- ui/src/data-products/kilometer-lengths/kilometer-lengths-view.tsx
- ui/src/data-products/vertical-geometry/entire-rail-network-vertical-geometry-listing.tsx
- ui/src/data-products/vertical-geometry/location-track-vertical-geometry-search.tsx
- ui/src/data-products/vertical-geometry/plan-vertical-geometry-search.tsx
- ui/src/data-products/vertical-geometry/vertical-geometry-view.tsx
- ui/src/infra-model/list/infra-model-search-result.tsx
- ui/src/infra-model/projektivelho/pv-file-list.tsx
- ui/src/infra-model/tabs/infra-model-tabs.tsx
- ui/src/publication/log/publication-log.tsx
- ui/src/tool-panel/geometry-plan-infobox.tsx
- ui/src/user/privileged-link.tsx
- ui/src/user/user-model.ts
Erotettu selaaja käyttäjä kahteen:
- Viraston käyttäjä: Vapaat lukuoikeudet käyttöliittymältä mutta ei pääsyä lataamaan IM-tiedostoja tai tietotuotteita
- Konsultit: Näiden oikeudet määritellään tarkemmin myöhemmin. Tässä kohtaa tein roolin jo valmiiksi mutta sillä ei ole mitään oikeuksia
Nykyinen selaaja säilytetty ja se antaa viraston käyttäjää vastaavat oikeudet. Kun saadaan AD:hen uudet roolitukset, tuo vanha voidaan poistaa.
Itse oikeudet on repeatable migraatiossa. Suurin osa muutoksista on ei-sallittujen UI-toimintojen piilottamista, sillä ilman oikeuksia backend vastaisi niihin vain 403.
> GVT-2317 Separate authority browser from consultants and deny browser access to csv downloads

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackDao.kt
- infra/src/main/resources/db/migration/prod/V55__setup_location_track_owners_schema_and_base_owners.sql
- infra/src/main/resources/db/migration/prod/V56__infer_base_location_track_owners.sql
- ui/src/tool-panel/location-track/dialog/location-track-edit-dialog.tsx
Hyvin heittopullari. Tällä hetkellä tämä ei edes toteuta taskin speksistä sitä osaa, että "Ei tiedossa"-omistajaa tulisi lainkaan, koska en ole ihan varma, oliko se nyt edes ihan oikeasti oleellinen asia.
Oleelliset muutokset:
- Suurin osa tiedosta siitä, että jokin omistaja on nyt toisia erikoisempi, on nyt sort_priority-kentässä kantataulussa: Tämä yksinkertaistaa kälikoodia jonkin verran (tosin se asia tämän kommitin ulkopuolella kälikoodissa vielä on olemassa, että Väylävirasto on oletusomistaja)
- Migrassa asetetut vaihtoehdot on nyt siis Väylävirasto, "Muu yksityinen", ja se välitila, tuon yksityisten osien pituuksia katsovan logiikan perusteella. Tuotantoonmenon aikaan voi sitten samalla koodilla rakennella ritoille raportin siitä, kuinka paljon yksityistä pituutta milläkin …
> GVT-2200 Raiteiden omistajien päättely, toinen yritys

- infra/src/main/resources/i18n/translations.fi.json
- ui/src/geoviite-design-lib/message-box/message-box.scss
- ui/src/geoviite-design-lib/message-box/message-box.tsx
- ui/src/map/layers/alignment/location-track-split-location-layer.ts
- ui/src/map/layers/switch/switch-layer.ts
- ui/src/map/map.module.scss
- ui/src/tool-panel/infobox/infobox-text.tsx
- ui/src/tool-panel/location-track/location-track-infobox-linking-container.tsx
- ui/src/tool-panel/location-track/location-track-infobox.scss
- ui/src/tool-panel/location-track/location-track-infobox.tsx
- ui/src/tool-panel/location-track/split-store.ts
- ui/src/tool-panel/location-track/splitting/location-track-split.tsx
- ui/src/tool-panel/location-track/splitting/location-track-splitting-infobox.tsx
- ui/src/tool-panel/tool-panel.tsx
Täällä tehty seuraavat asiat:
* Raiteen splittausta ei voi aloittaa mikäli raiteesta on olemassa draft
* Jos splittaaminen on jo aloitettu, disabloidaan splittauksen jatkaminen
* Raiteen vaihteet päivittyvät nyt splittauksessa kartalle reaaliajassa (aiemmin vaihteiden poistot ym. eivät päivittyneet ollenkaan.) Poistetut splitit näytetään punaisella
* Näytetään virhe ja disabloidaan splittauksen lopettaminen mikäli splittauksessa mukana oleva vaihde katoaa muokkauksen seurauksena
* Lisähuomiona korjattu tiketin GVT-2333 asiat, eli nyt ei enää pääse sijaintiraiteen muokkausdialogiin kun linkitys- tai splittaustila on auki
> GVT-2330 & GVT-2333: Raiteen splittauksen UI-parannuksia

- ui/src/tool-bar/tool-bar.tsx
- ui/src/tool-panel/geometry-alignment/geometry-alignment-infobox.tsx
- ui/src/tool-panel/geometry-alignment/geometry-alignment-linking-container.tsx
- ui/src/tool-panel/geometry-alignment/geometry-alignment-linking-infobox.tsx
- ui/src/tool-panel/location-track/dialog/location-track-edit-dialog.tsx
- ui/src/tool-panel/location-track/location-track-infobox-linking-container.tsx
- ui/src/tool-panel/location-track/location-track-infobox.tsx
- ui/src/tool-panel/tool-panel.tsx
- ui/src/track-layout/track-layout-react-utils.tsx
- ui/src/utils/date-utils.ts
Syyllisenä oli raiteen alku- ja loppupisteiden haku, joka ei päivittynyt ratanumeron päivittyessä. Refaktoroitu alun ja lopun hakumekanismi siten, että sille voi antaa useamman changeTimen. Samalla korjattu vastaava fiba InfoboxExtras-hausta
> GVT-2336: Raiteen infoboxissa näkyy vanha osoite

- infra/src/main/resources/i18n/translations.fi.json
- ui/src/geoviite-design-lib/km-post/km-post-badge.tsx
- ui/src/selection-panel/km-posts-panel/km-posts-panel.tsx
- ui/src/selection-panel/selection-panel.tsx
- ui/src/tool-panel/km-post/geometry-km-post-linking-infobox.scss
- ui/src/tool-panel/km-post/geometry-km-post-linking-infobox.tsx
- ui/src/tool-panel/location-track/location-track-infobox.tsx
Kilometripylväille lisätty tooltip, jossa lukee mille kilometripylväälle ne kuuluvat. Samalla lisätty KM-pylväiden linkityslistauksessa näytettäviin badgeihin ratanumero, jotta niistä olisi helpompi nähdä mille ratanumerolle ne kuuluvat.
Näiden lisäksi lisätty EnvRestricted splittauksen ympärille
> GVT-1807 & GVT-2339: Tasakilometriä linkittäessä ei näe mille ratanumerolle se kuuluu + EnvRestrict raiteiden splittaukselle

- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationService.kt
Huomionarvoista: Jos aiemman ratanumeron nimi muuttuu tässä julkaisussa, Vanha arvo -kentässä näytetään ratanumeron *uusi* nimi. Testailin tätä itse jonkin verran, ja se tuntui olevan ainakin omaan silmään selkeämpi kuin wanhan nimen näyttäminen. Eriäviä mielipiteitä saa toki esittää.
> GVT-2325: Raiteen ratanumeron muutos ei näy julkaisulokissa oikein

- ui/src/tool-panel/location-track/splitting/location-track-splitting-infobox.tsx
Bugi oli pieni kompastuskohta massa-fetchejä tekevissä koukuissa, ehkä sellainen, jota voisi miettiä enemmänkin. Haettava id-lista on joka renderillä uusi, ja koska se on uusi, niin koukun useLoader kutsuu lataajafunktiota, joka taas käy poimimassa cachesta pyydetyt id:t, eli vaikka mitään ei varsinaisesti haeta (kaikki on jo cachessa), niin palautettava lista on myös uusi. Tällöin siis komponentti luulee joka renderillä listan muuttuneen, ja renderöityy jatkuvasti uusiksi.
Periaatteessahan useSwitches voisi itsekin tukea alkuperäistä käyttötapaa "suoraan", mutta ilmaista se ei olisi, eli tein tässä tapauksessa perffin suhteen korrektimman paikallisratkaisun.
> GVT-2350 Fix render loop

- infra/src/test/kotlin/fi/fta/geoviite/infra/integration/CalculatedChangesServiceIT.kt
Testi luo vaihteen ja raiteet, lisää topologialinkin, ja poistaa sen; ja tarkistaa lopulta, että näkyihän poisto muutoksena. Mutta oikeasti se toimi vain sattumalta: Koska testi ei julkaissut topologialinkillistä välitilaa, se vertaisi oikeasti lopputilaa tuon alun testidatan generoinnin luomaan tilaan.
Samassa kohdassa (siis tasan samassa kohdassa (100.0, 0.0)) voi olla monien testiajojen jälkeen satoja vaihdepisteitä, joista nykyinen linkityskoodi "lähimpää" etsiessä sattuu tuurilla valitsemaan uusimman ja sattumalta siksi oikean. Jos linkityskoodia muuttaa sellaisella tavalla, että se muuttaa jotenkin näiden vaihtoehtojen järjestystä, se rikkoo myös tämän testin alkutilan luonnin, vaikka muutoksessa ei oikeasti olisi mitään vikaa.
> GVT-2325 Fix test that only incidentally worked

- infra/src/main/kotlin/fi/fta/geoviite/infra/error/ClientException.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/inframodel/InfraModelService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/localization/LocalizationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/Publication.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationUtils.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationValidation.kt
- infra/src/main/resources/i18n/translations.fi.json
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationDaoIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationServiceIT.kt
Ongelma oli, että jos sijaintiraiteen linkityksen raiteelle rikkoo, validaatio valitti siitä vain vaihteen julkaisun yhteydessä, vaikka linkit on raiteelle liittyviä asioita. Ratkaisu on kaksipuolinen:
- Vaihteiden julkaisu huomioi nyt korrektisti julkaisuyksikön, eli jos raiteen muutos jätetään vaihteen julkaisusta pois, niin vaihteen validointi ei näe sitä lainkaan
- Raiteiden julkaisussa katsotaan, olisiko julkaisu rikkomassa linkityksen johonkin vaihteeseen. Näistä joudutaan luonnostaankin katsomaan, että eihän käy niin, että rikkoutuva linkitys on sellainen, jota ei julkaistavalla raiteella ole enää lainkaan, ja siksi julkaistaviin raiteseen liittyvät vaihteet haetaan niiden julkaisutilasta riippumatta
Topologiatarkistukset jäävät kuitenkin olemaan vaihteidenkin puolelle, koska …
> GVT-2287 Do switch-location track link topology validation on both sides

- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryAlignment.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryKmPost.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/inframodel/InfraModelConversion.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/PlanLayoutTransformation.kt
- infra/src/main/resources/db/migration/prod/V59__set_geometry_track_number_fkey_to_null_on_delete.sql
- infra/src/main/resources/db/migration/prod/V60__fix_lost_geometry_tracknumber_refs.sql
- infra/src/test/kotlin/fi/fta/geoviite/infra/geocoding/GeocodingServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/geometry/DataProductsTestData.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/geometry/ElementListingTest.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/geometry/GeometryDomainTestData.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/geometry/GeometryServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/geometry/TestGeometryPlanService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/geometry/ValidationTest.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/geometry/VerticalGeometryListingTest.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/linking/LinkingServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/linking/SwitchLinkingServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ratko/RatkoServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/testdata/CommonTestData.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/testdata/HelsinkiTestData.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/testgroup2/VerticalGeometryDiagramTestUI.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/testgroup2/VerticalGeometryElementListTestUI.kt
- ui/src/geometry/geometry-model.ts
The point of the logic was to avoid reference errors when reverting a new draft tracknumber that is referred to by a geometry plan. The bug is that it's done on all reverts, not just new-draft reverts. Replaced the logic by simply making the foreign key references "on delete set null".
Also fixed links that has already been removed due to the bug.
Also removed tracknumber links from geometry.alignment & geometry.km_post, as those only duplicate their plan's data. The columns existed because originally, it was possible to have multiple tracknumbers in a single plan, but that is no longer the case.
Changed file-count is somewhat large but the majority of that is removing the tracknumber-links from test data generation. It was not relevant to the tests themselves and was only there because …
> GVT-2359 Don't remove geometry tracknumber links on all reverts

- ui/src/app-bar/app-bar.tsx
- ui/src/common/navigate.ts
- ui/src/frontpage/frontpage-container.tsx
- ui/src/frontpage/frontpage.tsx
- ui/src/main/main.tsx
- ui/src/publication/card/publication-card.tsx
- ui/src/publication/card/publication-list.tsx
- ui/src/publication/log/publication-log.tsx
- ui/src/publication/publication-details-container.tsx
- ui/src/publication/publication-model.ts
- ui/src/publication/publication-utils.ts
- ui/src/publication/publication.tsx
- ui/src/selection/selection-model.ts
- ui/src/selection/selection-store.ts
- ui/src/tool-panel/switch/dialog/switch-edit-dialog.tsx
GVT-2273: Refactor frontpage & publication log state handling
* Back/front navigation now works properly in the frontpage/publication log.
* Publication log URL was defined for a specific publication.
* Publication log search URL can now be accessed directly.
* Specific publication URL can now be shared and even modified in the address bar to view or share a specific publication.
* Header bar "Frontpage" link is now stateful and depends on the frontpage state. The previous content that was displayed will be shown when the user clicks the "Frontpage" link again from the address bar regardless of the currently viewed page.
* Previously displayed publication log search won't be lost after navigating again to the frontpage/publication-log "tab". While a specific publication was shown …
> GVT-2273: Refactor frontpage & publication log state handling

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/TrackLayout.kt
- infra/src/main/resources/i18n/translations.fi.json
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackServiceIT.kt
- ui/src/tool-panel/location-track/location-track-infobox-duplicate-of.tsx
- ui/src/tool-panel/location-track/location-track-infobox.scss
- ui/src/tool-panel/location-track/location-track-infobox.tsx
- ui/src/track-layout/track-layout-model.tsx
Alkuperäisen tiketin descriptionissa puhuttiin pelkästään duplikaattiraiteiden ratanumeroiden validoinnista, joten täällä tehty se. Tämän lisäksi lienee järkevää validoida myös ratanumeron draftius (tai ainakin se, että sillä ei ole julkaisemattomia geometriamuutoksia.) Tätä ei ole kuitenkaan vielä speksattu ihan loppuun, joten jätetään se myöhemmäksi.
> GVT-2338: Validoi jaettavan raiteen ratanumero - Part 1

- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/Linking.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/LinkingController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/SwitchLinkingService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/linking/SwitchLinkingServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/linking/SwitchLinkingTest.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/TrackLayoutDomainTestData.kt
Molemmat muutokset pompsissa, käytännössä siksi koska toteutettukin pompsissa. Pääajatuksena nyt siis vaihteen linkityksen tallennus on käännetty käymään uuden getLocationTrackChangesFromLinkingSwitch()in kautta, joka ei tee enää operaatioita suoraan tietokantaan, vaan luo muistinvaraisena kaikki uudet raiteet, ja niiden tallennus sitten tehdään erikseen. Raiteen kaikkien vaihteiden uudelleenlinkitys ja validointi sitten toimii tämän päällä.
> GVT-2153/GVT-2325 Vaihteiden linkitys muistinvaraiseksi, ja validateRelinkingTrack

- ui/src/tool-panel/location-track/splitting/location-track-splitting-infobox.tsx
Tässä kohdassa initialSplit on erillään todellisista spliteistä, eli sitä ei tarvitse laskea mukaan.
> GVT-2371 Only require one split

- ui/src/publication/log/publication-log.tsx
- ui/src/publication/publication-model.ts
- ui/src/publication/publication-utils.ts
- ui/src/selection/selection-store.ts
- ui/src/utils/date-utils.ts
Ongelmanahan oli, että jos käyttäjä oli käynyt julkaisulokihakusivulla ja sen jälkeen vaikkapa päivittänyt selaimen sivun, niin julkaisulokihakukomponentti ei enää renderöitynyt lainkaan (`Can't perform a React state update on a component that hasn't mounted yet...`)
Julkaisulokikomponentti käytti aiemmin kahta eri tilaa, joiden synkkaus osoittautui hieman ongelmalliseksi. Tässä pullarissa tuo aiemmin jaettu tila (päivämääräväli) muutetaan pelkästään Reduxissa tallennetuksi tilaksi.
Julkaisulokikomponentti käytti myös aiemmin useEffectiä päätelläkseen milloin näytettyä lokitaulukkoa tulee päivittää. Tämä aiheutti vielä lisää tilasynkkausprobleemaa. Tämän pullarin jälkeen taulukko päivitetään vain komponentin mounttaamisen yhteydessä ja silloin, kun käyttäjä päivittää valittuja …
> GVT-2273 (part 2): Fix publication log rendering failure due to invalid redux state

- infra/src/main/resources/i18n/translations.fi.json
- ui/src/tool-panel/location-track/location-track-infobox.tsx
Koitin käydä läpi eri tapoja siirtyä linkitystilaan frontissa splittauksen ollessa päällä ja löysin ainoastaan raiteen lyhennysnappulan. Se disabloituu nyt splittaustilassa olemisen mukaan.
> GVT-2329: Linkityksen estäminen pilkonnan ajaksi (fronttipääty)

- infra/src/main/resources/i18n/translations.fi.json
- ui/src/tool-panel/km-post/km-post-infobox.tsx
- ui/src/tool-panel/location-track/location-track-infobox.tsx
- ui/src/tool-panel/switch/switch-infobox.tsx
- ui/src/tool-panel/track-number/track-number-infobox.tsx
KM-pylväälle ja vaihteelle tämä olikin jo disabloituna. Samalla lisätty kaikille tooltip, joka kertoo miksi nappi on disabloitu
> GVT-2377: "Kohdista kartalla" -nappia pystyy painamaan vaikka raiteella ei ole geometriaa

- ui/src/map/layers/switch/switch-layer.ts
- ui/src/tool-panel/location-track/location-track-infobox.tsx
- ui/src/tool-panel/location-track/split-store.ts
Täällä ongelmana oli, että alku- ja loppuvaihteita ei oltu mitenkään eroteltu muista vaihteista. Täten niihinkin pystyi luomaan katkaisukohtia. Tein tälle tarkastelun joka on ainakin toistaiseksi puhtaasti fronttipohjainen, sillä en katsonut tämän olevan niin bäkkärin asiaa, varsinkin kun varsinainen splittaustyö tehdään muutenkin puhtaasti fronttipäässä.
> GVT-2378: Splittauksessa alkuperäisen raiteen loppupään vaihteen voi lisätä katkaisukohdaksi

- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryPlan.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/util/Paging.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/util/PagingTest.kt
- ui/src/data-products/data-products-utils.ts
- ui/src/geometry/geometry-api.ts
- ui/src/infra-model/tabs/infra-model-tabs.tsx
- ui/src/selection-panel/selection-panel-geometry-section.tsx
Valintapaneelin geometrialistan yhteinen silmäikoni tulee nyt näkyviin aina jos näkyvillä on geometrioita, ja toimii kolmella tavalla toisin kuin ennen:
- Näkyy, jos kartalla näkyvällä alueella on suunnitelmia (ennen oli: Näkyi, jos kartalla näkyvällä alueella on enintään 50 suunnitelmaa)
- Näkyy sinisenä, jos kartalla näkyvällä alueella on valittuja suunnitelmia (ennen oli: Näkyi sinisenä, jos missään oli valittu suunnitelma)
- Poistaa valinnan kaikilta kartalta näkyviltä suunnitelmilta aina, jos niitä on (ennen oli: Poisti valinnan suunnitelmilta, jotka näkyivät sekä kartalla että valintapaneelin listassa; eli ei miltään, jos suunnitelmia oli kartalla näkyvällä alueella yli 50)
Näistä viimeinen toteutettu sillä, että getPlanHeaders palauttaa pyydetyn määrän suunnitelmien otsikoita, ja …
> GVT-2375 Simplify hiding all geometry plans in view

- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationUtils.kt
- infra/src/main/resources/i18n/translations.fi.json
Previously the user reading the publication log had to figure out the directionality of the length change by themselves.
> GVT-2310: Show directionality of track/refline length change in publication log

- infra/src/main/kotlin/fi/fta/geoviite/infra/configuration/CacheConfiguration.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geography/CoordinateTransformationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geography/GeoToolsGeometries.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/PlanLayoutCache.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/PlanLayoutService.kt
Pääasiana perffin suhteen tuo rinnakkaistus, mutta nuo getGeometryFactory()-kutsut oli myös vähän turhan kalliita ottaen huomioon sen, että GeometryFactory-luokka on ainakin dokumentaation mukaan säieturvallinen, ja nähdäkseni tilaton -> yksi instanssi riittää.
> GVT-2379 Geometriasuunnitelmien layouttien laskemisen optimointeja

- infra/src/main/resources/i18n/translations.fi.json
Muutetaan huomiota vastaamaan paremmin varsinaista tilannetta: Keskilinjalle ei määritellä kallistusta, kallistus määritellään raiteelle.
> GVT-2382: Modify InfraModel cant remark

- ui/src/tool-panel/location-track/splitting/location-track-splitting-infobox.tsx
- ui/src/track-layout/track-layout-react-utils.tsx
Fetch-looppeja pääsi syntymään, koska Reactille annettiin `getMany()`:issä arrayllinen id:itä. React tarkistelee niiden yhtäsuuruuden reference-equalsilla, joka altisti kaikki massahaut tällaisille vaaran paikoille. Korjasin massahakuja nyt niin, että massahauissa depsut aina `JSON.stringify()`:ataan, jolloin React vertailee niitä stringeinä.
> General: Korjaa fetch-loopit splittaus-infoboksissa

- ui/src/tool-panel/location-track/location-track-infobox.tsx
- ui/src/tool-panel/location-track/split-store.ts
- ui/src/tool-panel/location-track/splitting/location-track-split.tsx
- ui/src/tool-panel/location-track/splitting/location-track-splitting-infobox.tsx
Täällä:
* Jakamisen alussa ja uusia splittejä lisätessä focusoidaan uuden splitin nimikenttä
* En lähtenyt toteuttamaan mitään sen kummempaa highlight-mekanismiä lisätyille spliteille. Ajattelin että focus riittää ainakin alkuun.
Tämän lisäksi turhauduin `InitialSplit`:in ja `Split`:in tyyppien käyttöön, joten muutin ne discriminated type unioniksi
> GVT-2207: Pilkoittujen raiteiden näyttämiseen selkeytysparannuksia

- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/SwitchLinkingService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/linking/SwitchLinkingServiceIT.kt
Olihan siinä linkityskoodissa vielä parikin bugia, ja kirjoitan vielä pari testiä näidenkin jälkeen. Oleellisin vika oli, että originalTracks käytti tarkkoja locationTrackService.getWithAlignment()in palauttamia iideitä, jotka sitten meni vikaan, koska muu koodi osasi käyttää oikein virallisia, mutta nämä saattoi olla drafti-iideitä; ja että topologialinkkejä ilmestyi vain uusina.
> GVT-2380 Fix remaining oddity with topological links, improve tests

- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/SwitchLinkingService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/linking/SwitchLinkingServiceIT.kt
- Hyvin oleellinen fiksi: Jos ehdotuksia ei ole, palautetaan nyt null kuten aiemminkin
- Logiikkamuutos: Jos ollaan korjaamassa tilannetta, jossa oli aiemmin linkitetty vaihde segmentille, mutta uudelleenlinkitys haluaisikin siirtää sen topologialinkitetyksi, niin osataan oikeasti poistaa segmenttilinkki ja lisätä topologialinkki
> GVT-2380 Vielä vaihdelinkitysfiksejä

- infra/src/main/resources/i18n/translations.fi.json
- ui/src/api/api-fetch.ts
- ui/src/geoviite-design-lib/demo/examples/snackbar-examples.tsx
- ui/src/geoviite-design-lib/snackbar/snackbar.scss
- ui/src/geoviite-design-lib/snackbar/snackbar.tsx
- ui/src/track-layout/layout-switch-api.ts
Tässä tuli tehtyä yleisön pyynnöstä vähän muitakin asioita kuin pelkkä kopiointinappi, timestamp ja correlationId. Täällä tehtyä kokonaisuudessaan:
- Virhetoasteilta otettu bodyn näyttämien pois. Aiemmin tätä käytettiinkin ainoastaan siihen, että siinä näytettiin bäkkäriltä tullut ihmisluettava virheviesti, joka monesti oli vielä englanniksi
- Virhetoasteille voi nyt antaa `ApiErrorResponse`-tyyppiä olevan virheolion, jonka olemassaolon perusteella toastissa näytetään a) kopiointinappi virheviestin oikealla puolella (tästä lisää myöhemmin), b) pohjalla aikaleima (bäkkäriltä, mutta käännetty lokaaliin aikaan) ja c) bäkkärin correlationId. Jos errorResponsea ei anneta (esim. puhtaasti frontin sisäisissä virheissä), nappia, aikaleimaa ja correlationId:tä ei näytetä
- Bäkkärivirheet voi nyt …
> GVT-2410: Virhetoasteihin korrelaatio-id tai timestamp näkyviin/kopioitavaksi

- infra/src/main/resources/db/migration/repeatable/R__08.01_fix_table_comments.sql
Korjaus repeatable migraationa: tuonne voi halutessaan aina lisätä/muokata taulu-kommentteja ilman että joka muutoksesta tarvitsee tehdä oma versioitu migra.
> General: Some table comments were placed on the wrong table. Fix as repeatable migration

- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/inframodel/InfraModelApi.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/inframodel/InfraModelController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/inframodel/InfraModelService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/DBTestBase.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/inframodel/InfraModelServiceIT.kt
- ui/src/infra-model/infra-model-api.ts
Suunnitelmien tallennus-api:n paluuarvot oli vanhaa perua varsin eri näköinen ja kuin muut. Sille ei oikeasti ollut mitään tarvetta, jäänyt vain tuollaiseksi. Bongasin sen aikanaan jonkun isomman rempan yhteydessä mutten halunnut sotkea sen reviewiä joten jätin TODO:n... ja unohdin sen. Nyt korjattu.
> General: fix return values in geometryplan insert/update

- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationUtils.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationUtilsTest.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/TrackLayoutDomainTestData.kt
Isoin ja oleellisin muutos tietenkin tuo, että geometriamuutokselliset välit tunnistetaan nyt oikeasti geometriasta eikä ainoastaan siitä, että koko segmentti on joko uusi tai ei. Tällä logiikalla löytyi joulukuiselta dumpilta seitsemän tapausta, joissa samalla sijaintiraiteella samassa julkaisussa on useampi muutos.
> GVT-2311 Julkaisulokin geometriamuutosten tunnistuksen korjauksia

- ui/src/tool-panel/location-track/splitting/location-track-splitting-infobox.tsx
Aiemmin frontti luotti että bäkkäri saa splitit järjestettyä oikein eikä miettinyt niiden järjestystä sen kummemmin, but as it turns out, bäkkäri tarvitseekin splitit järjestyksessä
> General: Splittien järjestäminen splittauksen tekemisen bäkkärikutsussa

- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/Publication.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationValidation.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchDao.kt
Vaihteiden validointi päätyi monissa tilanteissa tekemään hyvin agressiivista datan uudelleenhakua jotta se pystyi varmistamaan ettei virallisella puolella ole duplikaattinimeä. Muutettu niin että viralliset haetaan vain kerran ja niistäkin vain ne rivit jotka ovat duplikaatteja.
> GVT-2428 Optimize switch duplicate-name validation

- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/split/SplitService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/split/SplitValidation.kt
- infra/src/main/resources/i18n/translations.fi.json
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/split/SplitServiceIT.kt
Täällä tehty:
- Mekanismi, jolla erotetaan ollaanko tekemässä validointia stagetetuille (tai julkaistaville) muutoksille
- Validaatio tilanteelle, jossa koitetaan stagettaa useampi erillinen raiteen jako
- Lisätty käännöksiä puuttuneille jakamisen validaatiovirheille
- Yhdistelty jakamisen lähtö- ja lopputulosraiteita jos käännöksissä ei ole ollut järkeä erottaa näitä toisistaan
> GVT-2437 & GVT-2438: Splittauksen julkaisuvalidointijuttuja

- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/LinkingService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/split/SplitDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/split/SplitService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/TrackLayout.kt
- ui/src/tool-panel/location-track/location-track-infobox.tsx
- ui/src/track-layout/track-layout-model.tsx
Täällä estetty tämä kaksivaiheisesti:
- Disabloidaan "Lyhennä alkua ja/tai loppua" -nappi sijaintiraiteen infoboksista, tooltippinä tieto siitä että geometriamuutoksia ei sallita kun splitti on kesken
- Jos joku nyt kuitenkin on päässyt lyhennystilaan (esim. operaattori A on lyhentämässä raidetta ja operaattori B ehtii ottaa tämän raiteen mukaan splittiin ennen kuin A on valmis,) niin bäkkäri heittää virheen kun jakamista yritetään tallentaa.
Tuo suora bäkkärivirheen esittäminen on sinällään hieman meidän nykyisiä suuntaviivoja vastaan, mutta nykyään tuosta bäkkärivirheestä tulee oikeasti jopa luettava virheilmoitus, jossa lukee selkeästi suomeksi mikä meni vikaan. Näiden käytön suuntaviivoista voidaan jutella myöhemminkin, mutta omasta mielestäni niitä voidaan alkaa suosimaan enemmänkin …
> GVT-2441: Pilkkomiseen liittyvän raiteen lyhentämisen ei pitäisi onnistua

- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationUtils.kt
- infra/src/main/resources/i18n/translations.fi.json
Previously it was possible for a user of the publication log to be confused about a change that was not manually made.
> GVT-2094: Clarify automatically calculated changes in publication log

- ui/src/tool-panel/infobox/infobox.module.scss
- ui/src/tool-panel/tool-panel.tsx
Täällä korjattu tabien liian suuri fonttikoko, sekä yksi vanhempi bugi ensimmäisen tabin näyttämiseksi fallbackina (tabin sisältö näkyi oikein, mutta itse tab-header ei näkynyt valittuna)
> GVT-2422: Tabikorjauksia

- ui/src/map/layers/switch/switch-layer.ts
Raidemuutokset voivat vaikuttaa vaihteiden validiuteen lähinnä sen kautta, ovatko merkittynä duplikaateiksi.
> GVT-2450 Update tiled switch validation on location track changes

- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/Publication.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationUtils.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationServiceIT.kt
Pääkorjaus on, että käytetään yhdenmukaisesti segmenttipistettä vaihteen pisteen sijaintina raiteella. Ja kun kerran tämän tiedon hakemisen takia pitää joka tapauksessa hakea vanhoja alignmentteja ja raiteita, samalla kerkesi korjaamaan hyvin myös entiset linkitettyjen raiteiden nimet, jotta niistä ei tule muutoslokiin noisea.
> GVT-2425 Korjauksia julkaisulokin vaihdemuutoksiin

- ui/src/preview/preview-container.tsx
- ui/src/preview/preview-store.tsx
- ui/src/preview/preview-view.tsx
- ui/src/track-layout/track-layout-slice.ts
Previously the user had to re-enable the filter if they only wanted to view their own unstaged changes.
---
Loin näitä varten uuden tiedoston jo vähän jatkoa ajatellen. Esikatselunäkymään liittyvät asiat- ja tilankäsittely voisivat elää ihan omassa paikassaan (en vielä kuitenkaan siirrellyt tässä yhteydessä nykyisiä esikatseluun & Reduksiin liittyviä asioita uuteen paikkaan).
> GVT-2461: Store preview view 'show only own changes' filter state in Redux

- infra/src/main/kotlin/fi/fta/geoviite/infra/common/ChangeTimeController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/split/SplitDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/split/SplitService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/util/DaoBase.kt
- infra/src/main/resources/i18n/translations.fi.json
- ui/src/common/change-time-api.ts
- ui/src/common/common-slice.ts
- ui/src/frontpage/frontpage-container.tsx
- ui/src/frontpage/frontpage.tsx
- ui/src/publication/card/publication-card.tsx
- ui/src/publication/card/publication-list-row.tsx
- ui/src/tool-panel/location-track/splitting/location-track-splitting-infobox.tsx
Massasiirron tilan muuttaminen ei muuta itse julkaisua -> siihen liittyvä aikaleima ei muutu. Täten lisätty spliteille oma aikaleima, jonka perusteella julkaisut haetaan uudelleen.
> GVT-2462: Massasiirron tila tulisi näyttää heti suoritetuksi merkitsemisen jälkeen

- ui/src/tool-panel/infobox/infobox.module.scss
- ui/src/tool-panel/tool-panel.tsx
Korvattu divit buttoneilla. Meidän `<Button>` ei tuohon käyttöön oikeastaan taipunut, niin käytin sitten ihan vaan HTML:n perus-nappia (ja sitäkin sai säätää hieman lisää että se näytti oikealta.) Jos meillä olisi koskaan tarvetta näyttää tab-headereita muualla, niin tuosta kannattaisi eriyttää oma komponenttinsa, mutta en katsonut sitä tarpeelliseksi pelkästään tälle käyttötapaukselle.
> GVT-2422: Review-korjauksia

- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/Publication.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationService.kt
- infra/src/main/resources/i18n/translations.fi.json
- ui/src/preview/change-table-entry-mapping.ts
- ui/src/preview/preview-confirm-revert-changes-dialog.tsx
- ui/src/preview/preview-container.tsx
- ui/src/preview/preview-footer.tsx
- ui/src/preview/preview-table-item.tsx
- ui/src/preview/preview-table.tsx
- ui/src/preview/preview-view-data.ts
- ui/src/preview/preview-view-filters.ts
- ui/src/preview/preview-view-revert-request.ts
- ui/src/preview/preview-view.scss
- ui/src/preview/preview-view.tsx
- ui/src/preview/publication-request-dependency-list.tsx
- ui/src/publication/publication-model.ts
- ui/src/tool-panel/track-number/dialog/track-number-delete-confirmation-dialog.tsx
- ui/src/tool-panel/track-number/dialog/track-number-edit-dialog.tsx
- ui/src/tool-panel/track-number/track-number-deletion.ts
- ui/src/tool-panel/track-number/track-number-infobox.tsx
- ui/src/track-layout/track-layout-slice.ts
- ui/src/utils/array-utils.ts
Previously it was time consuming to move each change to the staged publications individually as well as to revert multiple changes as it also had to be done individually in most cases.
Additionally the concept of "publication group" was added. It will initially be used for location track split groups.
---
Luokittelisin tämän megapullariksi, sorgen. Laitoin kuitenkin runsaasti mainintoja.
> GVT-2418: Implement move and revert operations for groups of changes in preview view

- ui/src/geoviite-design-lib/dialog/dialog.scss
- ui/src/geoviite-design-lib/dialog/dialog.tsx
- ui/src/preview/preview-confirm-revert-changes-dialog.tsx
- ui/src/preview/preview-view.scss
Previously the dialog scaled to the entire viewport height when there were many changes which was unexpected/unwanted behavior.
> GVT-2460: Restrict height of publication change revert dialog

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutGeometry.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutGeometryTest.kt
GVT-2423:ta toteutettaessa hoksattu juttu, joka näytti kohtuulliselta putsata. En siis tiedä mitään paikkaa, missä tuo yleistys olisi tarpeen juuri tämän hetken kutsujilla, mutta aika ikävää olisi, jos jokin kutsuja haluaisi kolmea pistettä, ja se menisi rikki juuri jos päässä onkin kaksipisteinen segmentti.
> GVT-General: Allow LayoutAlignment#takeFirst and #takeLast to cross segment boundaries

- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/Publication.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationValidation.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/ValidationContext.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/DraftableObjectDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutKmPostController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutKmPostDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/ReferenceLineDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/TrackLayout.kt
- infra/src/main/resources/i18n/translations.fi.json
- infra/src/test/kotlin/fi/fta/geoviite/infra/linking/LinkingDomainTestData.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationDaoIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationValidationTest.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/ValidationContextIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutKmPostDaoIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackDaoIT.kt
- ui/src/track-layout/layout-km-post-api.ts
- ui/src/track-layout/layout-location-track-api.ts
- ui/src/track-layout/layout-switch-api.ts
- ui/src/track-layout/layout-track-number-api.ts
Alunperin aloitin tutkimaan bugia, jossa väärät versiot päätyivät validointiin ja totesin että siinä on useassa paikkaa vähän erikoisuuksia. Korjattu luomalla erillinen validointikonteksti joka tarjoaa validointilogiikalle yhtenäisen "universumin jota validoidaan" ja hoitaa samalla hakutulosten kakutuksia sekä preloadeja.
Pahoittelut isosta pullarista, mutta tämä vaikuttaa vähän kaikkeen :see_no_evil:
> GVT-2442 Publication validation context refactor

- ui/src/tool-panel/tool-panel-container.tsx
Näyttäisi pudonneen GVT-2423 toteutuksessa pois.
> GVT-2471 Show switch linking layer once again when linking switch

- ui/src/publication/publication.tsx
Näkymä itsessään odottaa lisäspeksiä, joten lopulta poistettu pelkkä nappula.
> GVT-2467: Poistetaan "Vie Ratkoon" toiminto yhden julkaisun näkymästä

- ui/src/tool-panel/infobox/infobox-field.tsx
- ui/src/tool-panel/location-track/location-track-infobox.tsx
The edit icon displayed next to the list of duplicates can be confusing to a user: Clicking this edit icon will not lead the user to edit the actual duplicates of a given location track, but instead opens the location track edit dialog where changes to the duplicates of the track cannot be made.
> GVT-2497: Hide edit icon from the list of duplicates of a location track

- infra/src/main/kotlin/fi/fta/geoviite/infra/error/ClientException.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/split/SplitService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackService.kt
- infra/src/main/resources/i18n/translations.fi.json
- infra/src/test/kotlin/fi/fta/geoviite/infra/split/SplitServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/TrackLayoutDomainTestData.kt
Previously the duplicate references were removed for every duplicate that was part of the split, regardless if the duplicate was used or not.
> GVT-2478: Reference newly created split target location tracks for unused duplicates

- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/split/SplitDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/split/SplitService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationServiceIT.kt
When there was an unfinished, but published split, reverting at least one later draft modification to a resulting target location track of the unfinished split resulted in the published split being deleted incorrectly during the later draft reversion operation of a location track.
For example: Split a location track to two: (Original) -> (StartTrack, EndTrack) -> Publish this split -> Modify the name of "StartTrack", but decide to revert this change -> this meant that the split was deleted as well.
(target-haara vaihtuu mainiin toisen pullarin mergen yhteydessä)
> GVT-2498: Fix incorrectly deleting a published split when later reverting a modified target track

- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/split/Split.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/split/SplitDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/split/SplitService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackService.kt
- infra/src/main/resources/db/migration/prod/V66__add_split_updated_duplicates_table.sql
- infra/src/test/kotlin/fi/fta/geoviite/infra/DBTestBase.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/linking/LinkingServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/split/SplitDaoIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/split/SplitServiceIT.kt
Previously the publication groups did not include the duplicates that were removed or modified during a location track split.
Additionally as an optimization, publication groups are now queried directly in SQL instead of setting them individually for each unpublished asset within Kotlin code.
--
Target-haara on hassu: Tässä on pohjana toisen pullarin haara, ja tuon toisen pullarin haaran tunnus on väärin (pitäisi olla GVT-2478). Targettina se, että näkyy ainoastaan tähän pullariin liittyviä muutoksia. Laitan tuon toisen haaran ennen tätä pullaria mainiin, jolloin tämänkin targetiksi muuttuu maini.
> GVT-2476: Add duplicates related to a split to publication groups

- ui/src/app-bar/app-bar-more-menu.tsx
- ui/src/app-bar/data-products-menu.tsx
- ui/src/infra-model/projektivelho/pv-file-list.tsx
- ui/src/infra-model/view/dialogs/charset-select-dialog.tsx
- ui/src/infra-model/view/form/infra-model-form.tsx
- ui/src/infra-model/view/infra-model-toolbar.tsx
- ui/src/preview/preview-table-item.tsx
- ui/src/publication/card/publication-list-row.tsx
- ui/src/tool-bar/tool-bar.tsx
- ui/src/vayla-design-lib/demo/examples/button-examples.tsx
- ui/src/vayla-design-lib/demo/examples/menu-example.tsx
- ui/src/vayla-design-lib/menu/menu.scss
- ui/src/vayla-design-lib/menu/menu.tsx
- ui/tsconfig.json
Täällä pääasiassa refaktorointia menuihin. Menuihin voi nyt asettaa dividereita, jotka renderöidään aiemman tyylisinä menuitemien välisinä bordereina (jotka on sellaisinaan otettu pois nykyisistä menuista.) Lisäksi refaktoroitu menuitemien luonti ja pakotettu `qaId`:t osalle menuitemeistä (loppujen pakottamisesta on erillinen tiketti.)
Samalla laitettu hetkellisesti taas `noUncheckedIndexedAccess` takaisin pois päältä, että buildit tokenisivat.
> GVT-2501: Dividerit esikatselunäkymän rivikohtaiseen menuun + noUncheckedIndexedAccess tilapäisesti pois päältä

- ui/src/app-bar/app-bar-more-menu.tsx
- ui/src/vayla-design-lib/closeable-modal/closeable-modal.tsx
- ui/src/vayla-design-lib/menu/menu.tsx
`CloseableModal` ei ollut ottanut huomioon tilannetta, jossa menu haluttiin avata kohti vasenta. Ne otetaan nyt huomioon, ja se on parametrisoitavissa `CloseableModal`:ille ja `Menu`:lle. Varmaan olisi ollut jotenkin mahdollista laskeakin meneekö menun toinen reuna ruudusta yli ja päätellä siitä kumpaan suuntaan menu pitää avata, mutta kun meillä on tällä hetkellä tasan tuo yksi vasemmalle aukeava menu, niin en katsonut vaivan arvoiseksi (plus jotain menuja saatettaisiin muutenkin haluta joskus avata vasemmalle riippumatta siitä ovatko ne näytön oikeassa reunassa vai eivät)
> GVT-2513: Lisenssi- ja uloskirjautumisvalikko piirtyy osittain ruudun ulkopuolelle

- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationValidation.kt
Tämä lienee hajonnut kakutusmuutoksissa. Täällä tarkasteltiin aiemmin muiden duplikaattitarkastelujen tapaan pelkästään että löytyykö vastaavaa duplikaattia, mutta unohdettiin ratanumero tarkastelusta.
> GVT-2494: Sijaintiraiteen nimen yksilöllisyyden tarkistus pitäisi olla per ratanumero

- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationValidation.kt
Edellinen PR oli hotfixiin, tämä mainiin.
> GVT-2494: Sijaintiraiteen nimen yksilöllisyyden tarkistus pitäisi olla per ratanumero (v1.13)

- infra/src/main/kotlin/fi/fta/geoviite/infra/split/SplitService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/split/SplitValidation.kt
- infra/src/main/resources/i18n/translations.fi.json
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationServiceIT.kt
Previously if the track number of a resulting track was changed, the geometry validation did not work properly and through a HTTP 500 error.
> GVT-2493: Fix split location track geometry validation during track number mismatch

- infra/src/main/resources/i18n/translations.fi.json
- ui/src/tool-panel/location-track/dialog/location-track-edit-dialog.tsx
- ui/src/vayla-design-lib/dropdown/dropdown.tsx
Tälle olikin jo virhe julkaisuvalidoinnissa, mutta nyt lisätty myös se, että itse dropdown pysyy disabloituna jos editoitavalla raiteella on duplikaatteja
> GVT-2529: Estetään duplikaattiraiteiden ketju

- infra/src/main/kotlin/fi/fta/geoviite/infra/ratko/RatkoClient.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/ratko/RatkoController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/ratko/RatkoLocalService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/ratko/RatkoOperatingPointDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/ratko/RatkoService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/ratko/model/RatkoOperationalPointModel.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ratko/RatkoServiceIT.kt
- ui/src/map/layers/operating-point/operating-points-layer.ts
- ui/src/map/map-store.ts
- ui/src/map/map-view.tsx
- ui/src/track-layout/layout-operating-point-api.ts
Oleellisia bugifiksejä: ChangeTime-passaaminen, joka oli jäänyt kokonaan pois; ja getOperatingPoints-metodin siirtäminen palveluun, jonka olemassaolo ei riipu siitä, että RatkoClient-bean on konffattu. Muuten pienempiä bugifiksejä ja putsauksia.
> GVT-2469 Joukko fiksejä liikennepaikoille

- infra/src/main/resources/i18n/translations.fi.json
- ui/src/map/layers/background-map-layer.ts
- ui/src/map/layers/utils/switch-layer-utils.ts
- ui/src/map/map-model.ts
- ui/src/map/map-store.ts
- ui/src/map/map-view.tsx
- ui/src/map/map.module.scss
- Päädyin näkemään parhaaksi, että ilmakuvataso piilottaa tavallisen taustakartan kokonaan taakseen, muuten ilmakuvat näyttävät oudon haalistuneilta
- Samalla säädetty myös virheellisten vaihteiden kylttien taustojen koot oikeiksi (ainakin Firefoxilla ja Chromella), ja säädetty raiteiden taustat läpinäkyviksi, jotta ilmakuva ei jää ihan kokonaan niiden taakse
> GVT-832 Ilmakuvataso

- infra/src/main/kotlin/fi/fta/geoviite/infra/integration/CalculatedChangesService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/integration/CalculatedChangesServiceIT.kt
Ongelma oli siis, että tämä osaa yleensä yhdistää eri segmenteiltä tulevat samaan vaihtepisteeseen liittyvät muutokset, mutta eipä osaakaan, jos geometria on sellainen, että segmenttien päätepisteiden välillä on aukkoa.
Periaatteessa tuo aiempi distinct() oli kai siitä hyvä, että siitä tiesi, että se räjäyttää julkaisun, jos yhdistettävissä muutoksissa on mitään vääränlaista eroa => saadaanpahan ainakin sisäisiä virheitä julkaisusta, sen sijaan että tallennettaisiin julkaisuun bugisen muutoslaskennan tulosta. Mutta käytännössä muutoslaskennasta alkaa olla toivottavasti aika hyvin bugit taputeltu, joten ajattelin järkevimmäksi vaan olettaa riittävän, että tehdään nyt vaan ihan raakasti tuo distinct() vain pisteen tunnistetiedoilla.
> GVT-2546 Relax joint distinctness requirement in merging switch changes

- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/pagemodel/map/PreviewChangesPage.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/testgroup1/BasicMapTestUI.kt
- ui/src/preview/preview-table.tsx
- ui/src/vayla-design-lib/spinner/spinner.tsx
After the preview view has opened, it fetches the currently unpublished changes from the API. After this fetch call, it sends another validation api call based on the changes it received.
Usually the UI operations accomplished by an E2E test trying to revert a change were accomplished before the ongoing validation api call managed to finish. Sometimes it was possible for the asynchronous validation call of the preview view component to finish before the ongoing revert operation of the E2E test, leading to an update of the preview view component and further causing the test code to no longer finding the element that it was looking for during the .revertChange()-call.
This PR provides functionality to synchronize E2E tests for the validation state of the preview view component and enables …
> General: Fix flaky E2E test by waiting for change validations to complete in preview view

- ui/src/vayla-design-lib/checkbox/checkbox.tsx
The element listing data product page was using JS-style attribute names which React does not recognize. The qaId-attributes were also duplicated due to passing an unmodified props-object to a child element.
These errors were noticed during E2E-test development.
Fixes error resulting in console error such as:
>Warning: React does not recognize the `qaId` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `qaid` instead. If you accidentally passed it from a parent component, remove it from the DOM element
> General: Fix invalid Checkbox-component qaId attributes

- ui/src/common/common-model.ts
- ui/src/tool-bar/tool-bar.tsx
- ui/src/tool-panel/location-track/location-track-location-infobox.tsx
- ui/src/tool-panel/tool-panel.tsx
- ui/src/track-layout/layout-km-post-api.ts
- ui/src/track-layout/layout-location-track-api.ts
- ui/src/track-layout/layout-reference-line-api.ts
- ui/src/track-layout/layout-switch-api.ts
- ui/src/track-layout/layout-track-number-api.ts
- ui/src/track-layout/track-layout-react-utils.tsx
Loput renamet. Tämä branchi oli ollut roikkumassa että saadaan preview muutokset ensin mergettyä ja meinasi unothua. Onneksi Jira-tiketti roikkui muistutuksena. Kyseessä muuttujien/luokkien renameja uuteen termistöön.
> GVT-2407 front-end draftable & publishtype renames

- ui/src/tool-panel/location-track/split-store.ts
Liikennepaikkatiedon hyödyntämisen perua: Tarvitsin splittilistan järjestyksessä, ja näytti loogisemmalta vaan ylläpitää sitä järjestyksessä sen sijaan että sorttaisi sen vasta juuri ennen käyttöä, mutta jätin sitten ottamatta sen tässä kohti huomioon.
> GVT-2570 Retain split list order in updateSplit

- ui/src/store/hooks.ts
- ui/src/vertical-geometry/vertical-geometry-diagram-holder.tsx
Pullari ehdolla heittona, ajatus ei ole valmis ja hyväksytty: Pystygeometrian kuvaaja yrittää näyttää käyttäjille korkeusgeometrian elementtejä ja linkitystietoja (ja niiden kautta geometriasuunnitelmien nimiä).
Speksin mukaan halutaan, että konsulttikäyttäjäkin näkisi pystygeometrian kuvaajan, mutta ei geometriatietoja. Jätetään ne siis kokonaan lataamatta: Kuvaaja toimii muuten normaalisti, siinä vaan näkyy ainoastaan korkeusviiva ja kilometrit/metrit viivoittimella.
> GVT-2567 Hide geometry info from prying eyes in vertical geometry diagram

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/SwitchLocationTrackLink.kt
Teoriassa varsinaisesta bugista itsestään selviäisi pienemmälläkin muutoksella. Käytännössä tuossa sai miettiä kuin peukkuileva Timo Soini konsanaan, että mitähän tässä nyt oli tarkoitettu tehdä kummalla raiteella, ja ajattelin, että kyllä asia voisi olla selkeämminkin sanottu.
En lähtenyt tekemään muutoksia isompaan määrään koodia, jonka kanssa Jyrki on juuri hääräämässä, mutta kun duplikaattien kanssa pitää varmasti vielä jonkin verran ährätä, niin voisi ährätä vaikka tällä käsitteistöllä.
> GVT-2558 Slightly straighten out duplicate parent/child reference directions

- ui/src/publication/card/publication-list-row.tsx
Päädyin tekemään tämän pelkästään UI:hin. Tiketillä ehdoteltiin myös tämän estämistä backendillä, mutta en itse nähnyt tätä niin järkeväksi, sillä on mahdollista että useampi operaattori koittaisi syystä tai toisesta tehdä tätä yhtä aikaa, ja Geoviitteessä yleisenä patternina on ollut, että näissä tilanteissa bäkkärin kannalta jälkimmäiselle ei saa lävähtää virhettä ruudulle
> GVT-2573: Raiteen jakamisen kohteiden siirron voi merkata onnistuneeksi monta kertaa

- infra/src/main/kotlin/fi/fta/geoviite/infra/common/KmNumber.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geocoding/Geocoding.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/split/Split.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/split/SplitController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/split/SplitDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/split/SplitService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/split/SplitValidation.kt
- infra/src/main/resources/db/migration/prod/V74__fix_split_source_version.sql
- infra/src/main/resources/i18n/translations.fi.json
- infra/src/test/kotlin/fi/fta/geoviite/infra/common/KmNumberTest.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/geocoding/GeocodingTest.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/geometry/ElementListingTest.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/linking/LinkingServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationUtilsTest.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/split/SplitDaoIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/split/SplitServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/TrackLayoutDomainTestData.kt
- ui/src/tool-panel/location-track/splitting/location-track-split.tsx
Pullarin targettina tuo toinen branch (josta on oma reviewinsä) jotta näkyy vain mikä oikeasti muuttuu tässä. Käytännössä molemmat kannattaa mergetä mainiin kerralla koska kumpikin edellyttää dev/test ympäristöjen kannan resettiä.
Tässä pointtina kiinnittää source locationtrackin rowversio splittiin, jolloin:
- Splittiin voi joinata suoraan versiotaulun rivin ja tietää saavansa aina juuri sen mikä oli splitin hetkellä oikea versio
- Source trackia ei voi muuttaa ilman että päivittää splittiä -> ei voi vahingossa mennä palauttamaan sitä delete-merkattujen limbosta tai muokata muutoin
> GVT-2564 fix source location track version to split

- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/switches/SwitchLinkingService.kt
- infra/src/main/resources/i18n/translations.fi.json
- infra/src/test/kotlin/fi/fta/geoviite/infra/linking/SwitchLinkingServiceIT.kt
- ui/src/tool-panel/location-track/location-track-task-list/location-track-task-list-container.tsx
- ui/src/tool-panel/location-track/location-track-task-list/location-track-task-list.scss
- ui/src/tool-panel/location-track/splitting/location-track-split-relinking-notice.tsx
- ui/src/tool-panel/location-track/splitting/location-track-splitting-infobox.tsx
- ui/src/tool-panel/location-track/splitting/split-utils.ts
Tämä tilanne oltiin huomattu jo aiemminkin, sillä kaikki vaihteiden uudelleenlinkityksiä validoidaan jo ennen splittauksen loppua - tältä nimenomaiselta tianteelta puuttui vaan järkevä käsittely. Täällä parannettu asiaa seuraavilla toimenpiteillä:
* Jos vaihde-ehdotusta ei saada muodostettua, ka. tilanteesta palautetaan validaatiovirhe.
* Disabloidaan koko splittaus-UI jos tällainen tilanne ilmestyy (linkitykset validoidaan heti splittauksen alussa, mutta myös aina kun jokin sijaintiraide tai vaihde muuttuu)
* Näytetään tässä tilanteessa operaattorille vahvempi virheilmoitus (punainen pohja ja pelkän kehotuksen sijasta ilmoitetaan että vaihteet pitää korjata)
* Näytetään tehtävälistalla varoituskolmio kriittisen virheen merkkinä mikäli ka. vaihteen automaaginen uudelleenlinkitys …
> GVT-2563: Raiteen poistaminen estää toisen raiteen splittauksen (HTTP 400)

- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/util/AssertionUtil.kt
The map tiles are not configured to work in the AWS environment during E2E tests. That is considered a non-severe error for now.
> General: Skip map tile related 404 during e2e testing

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutAssetService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSearchController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSearchService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackService.kt
- infra/src/main/resources/i18n/translations.fi.json
- ui/src/tool-bar/tool-bar.tsx
- ui/src/tool-panel/location-track/splitting/location-track-splitting-infobox.tsx
- ui/src/track-layout/track-layout-search-api.ts
Tiketin varsinaisen asian lisäksi täällä siis muokattu hakulaatikon toimintaa siten, että splittauksen ollessa aktiivinen haku palauttaa ainoastaan splittaukseen liittyvää tavaraa (splitattava raide, sen duplikaattiraiteet, raiteen vaihteet)
> GVT-2559: Splittiin ei tulisi syntyä katkaisukohtaa valittaessa vaihde haun kautta + muita hakuparannuksia

- infra/src/main/resources/i18n/translations.fi.json
- ui/src/preview/preview-table-item.tsx
- ui/src/preview/preview-table.tsx
- ui/src/preview/preview-view.tsx
- ui/src/publication/publication-utils.ts
Previously the "Revert all/Move all" operations moved performed the action to literally all changes, even though the user had selected the "Display only my changes" option. This was unintuitive, and it was possible for users to accidentally stage/revert changes that were not their own.
> GVT-2576: Fix staging/reverting only own changes when only own changes are displayed

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutAssetService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSearchController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSearchService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSearchServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/TrackLayoutDomainTestData.kt
- ui/src/tool-bar/tool-bar.tsx
- ui/src/track-layout/track-layout-search-api.ts
Täällä suurimpana juttuna on Jyrkin ehdotuksen mukaisesti hakujuttujen siirtäminen pois kunkin assettityypin omasta servicestä `LayoutSearchService`:en. Myös hakufunktionaalisuuden testit siirtyivät siinä samalla uuteen IT-filuun. Tämän kattauksen lisäksi on tehty muita kovimpia refaktorointihittejä, kuten asioiden splittausta funktioihin ja uudelleennimeämisiä.
> GVT-2559: Review-korjauksia

- infra/src/main/kotlin/fi/fta/geoviite/infra/util/ResultSetExternal.kt
Tällä tavalla kirjoitettuna LocalDaten lukeminen ei käy lainkaan sellaisen olion kautta, jossa päivämäärä olisi esitetty tarkempana ajanhetkenä (ja jonka kanssa voi miettiä että voikos tämä nyt rikkoa jotain aikavyöhykkeillä), vaan tietokanta antaa päivämäärän ISO-muodossa tekstinä, joka sitten parsitaan.
> General: Use less sweat-inducing way to read LocalDates from DB

- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationService.kt
- infra/src/main/resources/db/migration/prod/V75__add_design_context.sql
- Jokaiselle paikannuspohjan oliolle tulee nyt tietokannassa populoitu layout_context_id-kenttä
- Versiotauluille lasketaan alkutila tälle kentälle, mutta kaikki uudet arvot migran jälkeen tulee live-tauluista
- Kannan uniikkiusrajoitteet menee pitkälti uusiksi suunnitelmatilalliseen maailmaan
- Uniikkeja indeksejä käytetään oletettavasti useinkin olioiden hakuun kannasta, ja esim. external_id:hän on erittäin hyvin diskriminoiva kenttä silloinkin, kun oliosta voi olla pari eri versiota eri konteksteissa; mutta tietokantahaut on yleensä helpompi kohdistaa varsinaisiin design- ja draft-kenttiin kuin layout_context-kenttään. Tästä syystä layout_context on aina monisarakkeisissa indekseissä viimeisenä: Haut eivät koskaan kohdistu siihen, mutta indeksistä saa olioiden hakuun reilusti hyötyä …
> GVT-2597 Redo layout design columns with layout_context_id and constraints

- infra/src/main/kotlin/fi/fta/geoviite/infra/geocoding/GeocodingController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/LinkingController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutKmPostController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/MapAlignmentController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/ReferenceLineController.kt
Tein näitä aina muun koodin ohessa, mutta irrotin koko setin nyt vain omaksi pullarikseen. Eli sisältää pelkkää turhan quotetuksen poistoa, ei mitään toiminnallista muutosta.
> General: Clean up detekt warnings: there's no need to string-template a variable that is a string

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutAlignmentDao.kt
Otetaan erikseen pois päältä tämän CTE:n inlinetys, kts. https://www.postgresql.org/docs/current/queries-with.html#QUERIES-WITH-CTE-MATERIALIZATION
Katson vielä ylihuomenna uusilla silmillä, millä tavalla postgres oikeasti saa tämän haun solmuun silloin, kun se keksii inlinettää orig_metadata_planin. Periaatteessa se tekee ihan perinteisen virheen, siis sen, että se luulee, että jossain haussa luotavassa relaatiossa on vain yksi rivi, mutta oikeasti niitä on moniakymmeniä, ja sen perusteella hakuoptimointi menee päin honkia; mutta en saanut vielä haun rakennetta niin kunnolla kiinni, että käsittäisin, mistä virhe alkuaan juontuu, ja että olisiko sitä mitenkään mahdollista korjata jollakin vähemmän hakuoptimointia vääntävällä tavalla.
> GVT-2602 Ensure fetchSegmentGeometriesAndPlanMetadata runs fast

- ui/src/preview/preview-footer.tsx
- ui/src/preview/preview-table-item.tsx
- ui/src/preview/preview-table.tsx
- ui/src/preview/preview-view-filters.ts
- ui/src/preview/preview-view.tsx
Samalla rukattu muutakin spinnerien näyttämistä esikatselunäkymän taulukoissa. Nyt ylemmässä taulukossa näytetään spinnerit aina kun jotain assettia validoidaan, ja alemmassa ylipäätään kun validaatio ajautuu
> GVT-2584: Esikatselunäkymän "Julkaise"-nappia voi painaa vaikka julkaisuvalidointi on kesken

- infra/src/main/kotlin/fi/fta/geoviite/infra/localization/LocalizationLanguage.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/localization/LocalizationService.kt
... Turns out että kielten nimethän pitää kirjoittaa pienellä kun haetaan käännöstiedostoa. En tosin tiedä yhtään miksi kaikki toimi mulla lokaalisti ilman tuotakin 🤷 GitHub ja AWS tuohon räjähtivät.
> GVT-2575: Bäkkärin kielen enumisointi - Part Deux

- infra/src/main/resources/db/migration/repeatable/R__09.01_layout_segment_version_statistics.sql
Mietin, tekisikö näitä statistiikkoja muihinkin tauluihin, ja päädyin siihen, että eihän niitä lopulta tarvita. Tämä taulu tarvitsee erikseen statistiikkojen laskentaa, koska _molemmat_ näistä on totta:
- `(alignment_id, alignment_version)` ei ole avain, vaan samalla alignmentilla voi olla paljon segmenttejä
- `alignment_version`in arvot ei ole alignment_id:stä itsenäisiä, vaan osalle alignmentteja tulee enemmän muutoksia ja siten korkeampia versioita kuin useimmille
... joista siis ensimmäinen ehto tarkoittaa, että haussa on solmuja, joiden todellinen rivimäärä on enemmän kuin 1, ja toinen, että postgressi aliarvioi suunnitelmassa rivimääriä hakuehtojen itsenäisyysoletuksen takia. Varmaan meillä voi olla muitakin hakuja, joihin molemmat ehdot pätee, mutta koska tähän tauluun tehtävät on …
> GVT-2602 Collect statistics on layout.segment_version

- infra/src/main/kotlin/fi/fta/geoviite/infra/ratko/RatkoLocalService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/ratko/RatkoOperatingPointDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/ratko/model/RatkoOperationalPointModel.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSearchController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSearchService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ratko/RatkoLocalServiceIT.kt
- ui/src/map/map-utils.ts
- ui/src/tool-bar/tool-bar.tsx
- ui/src/track-layout/track-layout-model.tsx
- ui/src/track-layout/track-layout-search-api.ts
Previously track numbers, location tracks and switches could be searched in the map view. As operating points are now also available in the database of Geoviite, it seemed useful for the user to be able to also search for operating points.
> GVT-2599: Add support for searching operating points

- infra/src/main/resources/db/migration/repeatable/R__04.06_track_number_in_layout_context.sql
- infra/src/main/resources/db/migration/repeatable/R__04.07_reference_line_in_layout_context.sql
- infra/src/main/resources/db/migration/repeatable/R__04.08_location_track_in_layout_context.sql
- infra/src/main/resources/db/migration/repeatable/R__04.09_switch_in_layout_context.sql
- infra/src/main/resources/db/migration/repeatable/R__04.10.km_post_in_layout_context.sql
Perffifiksi. Ei funktionaalista muutosta, mutta tuo postgresql ei osaa vetää tuota "row.design_id is null"-ehtoa ylemmäs itse, joten kyseinen optimointi pitää tehdä käsin (ja puu siitä alaspäin duplikoida). Olin tuomassa tätä sisään aluksi pullarissa https://github.com/finnishtransportagency/geoviite/pull/1253 , mutta koska devi on tämän perffiongelman takia juntturassa, tuon nyt tämän muutoksen kiireemmällä mainiin.
> GVT-2403 Fix extremely slow in_layout_context functions

- ui/src/vertical-geometry/vertical-geometry-diagram.tsx
Ulompaa diviä on kaunistettu lisäämällä pari pikseliä paddingia, ja sen myötä laskutoimitukset, jotka käyttivät kursorin sijaintia elementin sisällä, menivät mönkään.
> GVT-2583 Point vertical geometry diagram ref at correct element

- ui/src/vayla-design-lib/datepicker/datepicker.scss
- ui/src/vayla-design-lib/datepicker/datepicker.tsx
Aiemmin `DatePicker` ei siis suostunut piirtymään kivasti silloin jos sen parenttikomponentilla oli tosi vähän tilaa käytössä (kuten esim. dialogeissa.) Ratkaisu tähän löytyi sen siirtämisestä `CloseableModal`:in sisälle, mutta tämä johti aikamoiseen komponentin sisäiseen refaktorointiin.
> GVT-2605: DatePickerin refaktorointi

- infra/src/main/kotlin/fi/fta/geoviite/infra/common/ChangeTimeController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutDesign.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutDesignController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutDesignDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutDesignService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/util/DaoBase.kt
- infra/src/main/resources/db/migration/prod/V75__add_design_context.sql
- infra/src/main/resources/i18n/translations.fi.json
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutDesignDaoIT.kt
- ui/src/common/change-time-api.ts
- ui/src/common/common-slice.ts
- ui/src/map/layer-menu/map-layer-menu.tsx
- ui/src/tool-bar/tool-bar.tsx
- ui/src/tool-bar/workspace-delete-confirm-dialog.tsx
- ui/src/tool-bar/workspace-dialog.scss
- ui/src/tool-bar/workspace-dialog.tsx
- ui/src/track-layout/layout-design-api.ts
- ui/src/vayla-design-lib/closeable-modal/closeable-modal.tsx
- ui/src/vayla-design-lib/dropdown/dropdown.tsx
Täällä siis käytännössä tehty vaadittavat uudet controllerit ja servicet sekä DAO-tason muutokset että työtiloja pystyy luomaan frontilta. Fronttipuolelle siis tehty wiretykset työtilojen luontidialogiin ja laajennettu sitä kattamaan olemassaolevan työtilan muokkaaminen, sekä lisätty varmistusdialogi työtilan poistoon. Tähän tikettiin liittyy myös `DatePicker`-komponentin sisäinen refaktorointi, joka on irrotettu omaksi reviewikseen ihan sen monimutkaisuuden takia.
> GVT-2605: Työtilojen luonti, muokkaus, poisto frontilta

- infra/src/main/kotlin/fi/fta/geoviite/infra/ratko/RatkoOperatingPointDao.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ratko/RatkoLocalServiceIT.kt
Previously all other assets could be found by their oids. As it was also simple to add support for searching operating points by their oids, support for them was also added to the search.
> GVT-2559 (part 2): Add support for searching operating points by their oids

- ui/src/tool-panel/km-post/dialog/km-post-delete-confirmation-dialog.tsx
- ui/src/tool-panel/km-post/dialog/km-post-edit-dialog.tsx
- ui/src/tool-panel/location-track/dialog/location-track-edit-dialog.tsx
- ui/src/tool-panel/location-track/location-track-delete-confirmation-dialog.tsx
- ui/src/tool-panel/switch/dialog/switch-edit-dialog.tsx
- ui/src/track-layout/layout-km-post-api.ts
- ui/src/track-layout/layout-location-track-api.ts
- ui/src/track-layout/layout-switch-api.ts
- ui/src/track-layout/layout-track-number-api.ts
Noista *adt-metodien käytöistähän ei ollut tässä mitään etua, koska nämä polut palauttavat muutenkin vain joko ID:n tai sisäisen virheen. Suoristetaan kaikki siis käyttämään promiseja enemmän tai vähemmän yhdenmukaisesti.
Osasta tallennuksessa tapahtuvista virhetilanteista tulee nyt kaksi toastia, minkä en ajatellut tässä olevan haitaksi: Toisesta näkee, että serverillä meni jotain vikaan, ja toisesta, että joo juuri tämä nyt yritetty tallennusoperaatio on se, joka meni rikki. Eli siis rumalta se näyttää, mutta silti informatiiviselta, ja jos kaikki toimii, niin näitähän tilanteita ei tule koskaan.
> GVT-2589 Straighten out error handling in asset updates

- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/ValidationContext.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationDaoIT.kt
Totta puhuen enemmän optimointia kuin LayoutBranchifiointia, varsinainen uuden tiedon tuominenhan tässä on ihan triviaalius.
Mutta kun fetchLinkedLocationTracks itse näkyi ikävästi profilerissa jo ennen mitään muutoksia kun heiluin Ilmalassa, joten optimoin sitä käsittelemään hieman paremmin erikokoisia switch_id-joukkoja (ja optimoimisvaraa olisi vielä jäljelläkin, mutta menisi jo yksittäisten millisekuntien tiristämiseksi). Hyvin paljolti sama temppu kuin aiemmin https://github.com/finnishtransportagency/geoviite/pull/1263 kanssa, eli että ollaan vaan tarkkoja sen kanssa, että segment_version-taulusta tehtävät massahaut ei tee mitään ylimääräistä vaan hakevat ainoastaan juuri tarvittavan tiedon.
> GVT-2616 LayoutBranchify and optimize fetchLinkedLocationTracks

- ui/src/geoviite-design-lib/snackbar/snackbar.scss
Previously it was for example not possible to directly copy the error message/correlationId/timestamp etc info from the toast, even though the user was able to copy and paste the json-formatted error info from the icon button of the error toast.
Long messages were previously also partially hidden as the toast header forcefully cut off too long text strings, this was also fixed.
> GVT-2613: Allow copying text from toasts, display full message

- ui/src/preview/preview-table-item.tsx
- ui/src/preview/preview-view.scss
En vieläkään tiedä mistä tuo alkuperäinen ongelma johtui ihan täysin, mutta uskon tuon aiemmin olemassaolleen `*:not(:first-child):before`-määritykseen olleen osa ongelmaa. Sen poistamisella ongelma myös korjaantui, ja nyt väli virheiden ja varoitusten väliin tehdään hieman konventionaalisemmalla metodilla.
> GVT-2622: FJulkaisunäkymän Tila-sarakkeen sisältö tasautuu oudosti rivittyessään

- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/Linking.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/switches/SwitchLinkingService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationValidation.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/TrackLayout.kt
- infra/src/main/resources/i18n/translations.fi.json
- infra/src/test/kotlin/fi/fta/geoviite/infra/linking/SwitchLinkingServiceIT.kt
- ui/src/infra-model/infra-model-slice.ts
- ui/src/preview/change-table-sorting.ts
- ui/src/tool-panel/location-track/location-track-task-list/location-track-task-list-container.tsx
- ui/src/tool-panel/location-track/splitting/split-utils.ts
- ui/src/utils/validation-utils.ts
Täällä tiketin varsinainen pihvi. Validaatiota on nyt muutettu siten, että uudelleenlinkitys tarkistaa löytyykö raiteelta varmasti linkit kaikkiin sen entisiin sijaintiraiteisiin. Jos ei löydy, niin nostetaan punainen virhe. Samalla täällä on muutettu splittauksen error-käsittelyä siten, että uudelleenlinkityksessä kaikki "tavalliset" julkaisuvalidaatiovirheet muutetaan varoituksiksi - ne eivät estä splittausta ja voidaan korjata jälkeenpäin, - ja ainoastaan vaihde-ehdotuksen uupumaan jääminen sekä tämä täällä lisätty linjojen puuttuminen aiheuttavat virheen. Täten voidaan hyödyntää frontilla virheiden näyttämisessä puhtaasti issuen tasoa.
Samalla täällä on jatkettu error-nimien muuttamista issueiksi, sekä sitä mukaa kun niitä on tullut vastaan että review-kommenttien perusteella.
HUOM! …
> GVT-2580: Jos vaihteen uudelleenlinkitys poistaa splitattavan raiteen linkityksen, tämä saisi näkyä kriittisenä virheenä

- ui/src/vertical-geometry/vertical-geometry-diagram.tsx
The position cross/cursor indicator of the vertical geometry diagram was previously modified in GVT-2583 as it was improperly drawn to the right side of the actual position of the mouse. While the fix made during GVT-2583 did work for the position indicator, it also modified the positioning of the km-numbers drawn to the bottom of the vertical geometry diagram resulting in them being drawn off or not being drawn at all to the vertical geometry diagram's svg.
The changes in this PR should...
* Keep the previous fix to the cursor position still in place
* Draw all other elements as before to the svg
It should be noted that the container used for the svg has 8px padding (on all sides) which means that the container is a little larger than the actual svg image being drawn. This is probably …
> GVT-2624: Fix drawing km-numbers in vertical geometry diagram while still handling cursor position properly

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchDao.kt
Puhdasta optimointia. Perinteiseen tapaan pyritään rajaamaan segment_version-tauluun tehdyt haut tehokkaasti, mikä vetää ajoajan jostain sekunnin luokasta 80-90 millisekunnin luokkaan.
Tässä tulee myös "offset 0"-jekku. Tämä on hyvin pitkään elänyt PostgreSQL:n ~~outous~~ ominaisuus: Postgres ei yritä inlinettää tällaista hakua. Ei millään muotoa välttämätön mikro-optimointi tässäkään tapauksessa, mutta se pudottaa ajoajan sitten ylläolevasta vielä noin 10 millisekunnin luokkaan. Syy on, että tavallisella joinilla postgressi yrittää ajaa in_layout_context-funktion ajoa massana, kun taas estämällä inlinetyksen se käy vaan hakemassa ne pari sijaintiraidetta, joille vaihde on linkitetty. Arvelen, että en osaa tässä tapauksessa saada samaa korjausta hakusuunnitelmaan aikaan kauniimmalla …
> GVT-2631 Optimize fetchSegmentSwitchJointConnections

- ui/src/tool-bar/tool-bar.tsx
- ui/src/tool-bar/workspace-selection.tsx
- ui/src/tool-panel/infobox/infobox-field.tsx
- ui/src/tool-panel/location-track/location-track-validation-infobox-container.tsx
Tämä menikin helpommin kuin luulin, sillä edit-nappien piilottamista oli selkeästi yritetty jo aiemmin, mutta vähän huonoin lopputuloksin. Lisäksi piilotettu esikatselunäkymään meno EDIT_LAYOUT-oikeuden taakse, sillä siellä tehdään lähinnä muutostoimenpiteitä.
> GVT-2627: Part 2 - Muokkaustoiminnallisuuksien piilottaminen luonnostilassa muokkausoikeuksien puuttuessa

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutDesignController.kt
- ui/src/tool-bar/tool-bar.tsx
- ui/src/tool-bar/workspace-selection.tsx
- ui/src/tool-panel/infobox/infobox-field.tsx
- ui/src/tool-panel/location-track/location-track-validation-infobox-container.tsx
Täällä on toteutettuna nyt minimi siihen, miten näiden halutaan toimivan 1.14:ssa: Luonnostila- ja Suunnitelmatila-tabit näkyvät ja ovat valittavissa ainoastaan, jos käyttäjällä on oikeudet katsella luonnostilaa. Jo tämä aiheutti kevyitä refaktorointeja:
- `LayoutDesignController`:ista puuttui kokonaan `@PreAuthorize`-annotaatiot, joten ne eivät tarkistelleet oikeuksia ollenkaan. Ne on nyt lisätty
- Edellämainitusta johtuen työtilojen haut alkoivat heittää virhettä kaikilla niillä käyttäjäryhmillä, joilla ei ole oikeutta katsella luonnostilaisia asioita -> jouduin wrappaamaan ne omaan komponenttiinsa, joka näytetään ainoastaan kun Luonnostila-tabi on aktiivinen
Tästä jäi vielä jatkotyöksi seuraavat:
- Tiketillä mainittu E2E-kliksuttelutestin päivitys (tutkitaan että ei näy mitään väärää) …
> GVT-2627: Karttanäkymän tila-tab-headerien piilotus oikeuksien mukaan (Part 1)

- infra/src/main/resources/i18n/translations.fi.json
- ui/src/geoviite-design-lib/split-button/split-button.scss
- ui/src/geoviite-design-lib/split-button/split-button.tsx
- ui/src/tool-panel/location-track/location-track-location-infobox.tsx
- ui/src/vayla-design-lib/demo/examples/button-examples.tsx
Täällä luotu alustava versio `SplitButton`-komponentista. Tämä poiki myös isohkon, ei-pakollisen mutta mielestäni fiksuhkon refaktoroinnin meidän menuihin ja dropdowneihin, joka lähti liikkeelle siitä, että `SplitButton`:in (ja siten kaikkien menujen) olisi ehkä kiva tietää parametrin tasolla että suljetaanko menu jonkin itemin klikkauksen jälkeen vai ei (tähän mennessä menun sulkeminen a) tehtiin jokaisessa menu itemissä koko koodipesässä ja b) oli menuitemin itsensä vastuulla kaikkialla.) Pistän tuon kuitenkin omana pullarinaan. Tämä ei siten ole siis täysin valmis versio aiheesta (vaikka aika lähellä jo onkin.) Refaktorointipullari ja tämä ovat kuitenkin yksi yksikkö: mikäli refakkijutut halutaankin rejectata, niin tämä komponetti tarvii vielä vähän lisäsäätöä.
> GVT-2628: SplitButton-komponentti

- ui/src/app-bar/app-bar-more-menu.tsx
- ui/src/app-bar/data-products-menu.tsx
- ui/src/geoviite-design-lib/split-button/split-button.tsx
- ui/src/infra-model/projektivelho/pv-file-list.tsx
- ui/src/infra-model/view/dialogs/charset-select-dialog.tsx
- ui/src/infra-model/view/form/infra-model-form.tsx
- ui/src/infra-model/view/infra-model-toolbar.tsx
- ui/src/preview/preview-table-item.tsx
- ui/src/publication/card/publication-list-row.tsx
- ui/src/tool-bar/tool-bar.tsx
- ui/src/vayla-design-lib/demo/examples/button-examples.tsx
- ui/src/vayla-design-lib/demo/examples/menu-example.tsx
- ui/src/vayla-design-lib/dropdown/dropdown.tsx
- ui/src/vayla-design-lib/menu/menu.tsx
Tämä refaktorointi lähti pullarilla https://github.com/finnishtransportagency/geoviite/pull/1278 esiin nousseesta tarpeesta sulkea `SplitButton`:in menu sen jälkeen kun jotain sen itemiä klikataan. Keksin tähän pari vaihtoehtoa:
a) Tehdä aiemmalla mallilla ja säilyttää tieto `SplitButton`:in menun auki olemisesta jossain ulkoisessa tilassa joka välitetään SplitButtonille ja koodata menun sulkeminen jokaiseen sen menuitemiin (kuulostaa turhalta koodin monistamiselta ja siltä, että vastuu menun auki olemisesta on väärässä paikassa)
b) Refaktoroida `Menu`:a siten, että menuitemeille voidaan antaa tieto siitä suljetaanko menu jonkin sen itemin klikkauksen jälkeen ja menulle sulkemisfunktio (Menu ei edelleenkään tiedä aukiolostaan mitään,) ja parametrisoidaan nämä SplitButtonissa ja muissa …
> GVT-2628: Menun refaktorointia (pesäero Dropdownin ja Menun välille, autoclose-parametrisaatio menuitemeille)

- infra/src/main/kotlin/fi/fta/geoviite/infra/error/ClientException.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackService.kt
- infra/src/main/resources/i18n/translations.fi.json
- infra/src/test/kotlin/fi/fta/geoviite/infra/split/SplitTestDataService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackServiceIT.kt
Tässähän olisi siis ainakin pari tapaa tämä virhe huomata:
* Otetaan kantavirhe kiinni ja muutetaan se mielekkäämmäksi (joka toteutettu)
* Tarkistetaan ennen raiteen päivittämiskantakutsun suorittamista, että onko raide minkä tahansa splitin lähderaide. Tämä vaikutti aluksi mielekkäämmältä, mutta alkoi tuntua melko raskaalta tehdä kantahaku tätä varten jokaisen raiteen päivityksen yhteydessä.
Mielipiteitä?
> GVT-2588: Handle split source track update error more gracefully

- infra/src/main/kotlin/fi/fta/geoviite/infra/geocoding/Geocoding.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryValidation.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationValidation.kt
- infra/src/main/resources/i18n/translations.fi.json
- ui/src/api/api-fetch.ts
- ui/src/infra-model/infra-model-api.ts
- ui/src/infra-model/view/infra-model-upload-loader.tsx
Täällä siis korjattu varsinainen tuotannossa esiintynyt ongelma, ja sen lisäksi korjattu seuraavia juttuja:
- InfraModelin tallentamisen epäonnistuminen ei näytä virhettä
- Puuttuvan ratanumeron käännösavain on väärin inframallin validoinnin confirm-dialogissa
- Kaikenlaisia muita käännösjuttuja
> GVT-2635: Geoviite heittää 500-errorin elementtiluettelossa jos geometriatiedosto sisältää duplikaatti km-pylväitä + muita InfraModel-korjauksia

- infra/src/main/resources/i18n/translations.fi.json
- ui/src/tool-panel/location-track/location-track-location-infobox.tsx
Samalla refaktoroitu muutenkin hiukan raiteen lyhennys- ja splittausnappien disablointeja. Ne on nyt otettu ulos JSX:stä omiin muuttujiinsa, ja lisätty samalla hover tilanteelle, jossa raidetta ei voida lyhentää koska siltä puuttuu geometria.
Huom! Tuo sama lyhennystoiminnallisuus löytyy myös ratanumeroilta, mutta ratanumeron poiston yhteydessä koko tuon napin sisältävä infoboksi menee piiloon -> en lisännyt sille omaa disablointia.
> GVT-2562: Estetään poistetun raiteen alun/lopun lyhentäminen

- ui/src/tool-panel/location-track/dialog/location-track-switch-relinking-dialog.tsx
- ui/src/tool-panel/location-track/location-track-task-list/location-track-task-list-container.tsx
- ui/src/tool-panel/location-track/splitting/location-track-splitting-infobox.tsx
- ui/src/tool-panel/tool-panel-container.tsx
- ui/src/tool-panel/tool-panel.tsx
- ui/src/track-layout/track-layout-slice.ts
- ui/src/track-layout/track-layout-view.tsx
Tiketti ei ollut täysin selkeä siitä miten piilotus halutaan suorittaa, joten tein tänne oman intuitioni mukaisen arvauksen asiasta. Käytännössä tämän myötä tehtävälista sulkeutuu seuraavissa tapauksissa:
1. Operaattori siirtyy valitsemaan suunnitelmaa (ts. navigoi "Suunnitelmatila"-tabiin toolbarista)
2. Karttanäkymän `LayoutContext` vaihtuu osoittamaan eri designiin kuin missä tehtävälista avattiin
Protoilin myös seuraavia vaihtoehtoja, mutta niistä mikään ei oikeastaan tuntunut oikealta:
* Tehtävälistaa ei suljeta automaattisesti Suunnitelmatilaan mentäessä, se vain piilotetaan. Jos työlistan haluaa sulkea, se pitää sulkea yläkulman ruksinappulasta. Käyttäjän palatessa Luonnostila-tabiin piilotettu tehtävälista palautetaan näkyviin (Avautuva tehtävälista saattaa herättää ihmetystä jos …
> GVT-2608: Tehtävälista jää näkyviin aktivoitaessa suunnitelmatila

- ui/src/publication/log/publication-log.scss
- ui/src/publication/log/publication-log.tsx
Tiketillä pyydettiin miettimään lopullinen indikaatio itse ja ehdotettiin spinneriä. Lisätty spinneri tiketin mukaisesti, sillä se näytti ihan fiksulta kokeilun perusteella.
> GVT-2560: Julkaisulokihaku ei indikoi latauksesta ensimmäisen haun yhteydessä

- infra/src/main/kotlin/fi/fta/geoviite/infra/authorization/AuthorizationDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/authorization/UserData.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/configuration/RequestFilter.kt
- infra/src/main/resources/db/migration/prod/V78__remove_name_and_description_columns_from_roles.sql
- infra/src/main/resources/db/migration/repeatable/R__01_role_data.sql
- infra/src/test/kotlin/fi/fta/geoviite/infra/MetaDataIT.kt
- ui/src/user/user-card.tsx
- ui/src/user/user-model.ts
Alkuperäinen review-kommentti oli siis että oikeuksilla on turha olla käännösavaimia kannassa sillä ne voidaan päätellä koodin perusteella. Tällä tiketillä poistettu ka. columnit (`common.privilege`:n `name` ja `description`) sekä poistettu roolien nimikenttä (`common.role`:n `name`.) Roolien nimille olikin jo aiemmalta käännökset joten niiden poisto ei aiheuttanut fronttiin minkäänlaisia muutostarpeita, mutta yksi IT-testi perustui roolien nimien puljaamista, joten se piti reworkata käyttämään muita arvoja.
> GVT-2614: Roolien ja oikeuksien käännösavainten poisto kannasta

- infra/build.gradle.kts
- infra/src/main/kotlin/fi/fta/geoviite/infra/aspects/GeoviiteController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/aspects/GeoviiteDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/aspects/GeoviiteService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/aspects/ReflectedLogging.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/logging/LoggerExternal.kt
These aspects will initially be used for automated logging of controller/service/dao calls,
which will ease required effort for a developer to remember to add and update manual logger
calls.
_Note: Actual usage (removal of current manual logger calls) will be done in another pull request._
--
Lisähuomiona vielä, että 1.14 oli tarkoitus paketoida ennenkuin tämä (ja tuleva käyttöpaikkapullari) nakataan mainiin.
> GVT-2611 (part 1): Add Geoviite-aspects for Controller, Service and Dao layers

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutAssetDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/util/DaoBase.kt
- infra/src/main/resources/application.yml
Varsinainen alkuperäinen ajatus: Nyt kun [GVT-2629](https://extranet.vayla.fi/jira/browse/GVT-2629) on sisässä, [GVT-2630](https://extranet.vayla.fi/jira/browse/GVT-2630) toteutuksen voi viedä loppuun asti: Koska annettujen id:den voi olettaa nyt olevan virallisia, haussa ei tarvitse enää erikseen vaihetta, missä virallinen id haetaan.
Mutta kesän aikana tähän asti tuntemattomasta syystä sekä optimoituun että optimoimattomaan hakuun on pesiytynyt uusi ongelma: Postgressin hakujen JIT-kääntäminen tarttuu nyt näihin hakuihin, ja turhaan, koska oikeasti kaikista isoimpiinkin in_layout_context-hakuihin menee varsinaiseen ajoon ehkä 10 millisekuntia, mutta kovimpaan JIT-kääntämiseen 700 millisekuntia.
JIT-kääntämisen disablointi hidastaa hieman isoja monimutkaisia massahakuja, joissa tehdään …
> GVT-2659 Optimize fetchVersions(), disable postgresql JIT

- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/LinkingDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackDao.kt
- infra/src/main/resources/db/migration/prod/V80__index_alignment_bounding_box.sql
Sivuoptimointi, joka tuli toteutettua GVT-2673:n osana, vaikka ei olekaan sinällään ihan oleellinen. Tai hyvin lähelle tämä siihen liittyy, mutta koska fetchVersionsNear()ia saatetaan taskin bugin takia kutsua turhaan monia tuhansia kertoja, se, että se menee nyt lähemmäs 50 millisekunnissa kuin 250 millisekunnissa auttaa kyllä, mutta ei vielä riitä siihen, että toiminto toimisi nopeasti.
Jos annettu bbox leikkaa jonkin alignmentin segmentin bounding boxia, niin silloin se leikkaa alignmentinkin bboxia, joten edellisten hakua voi aina rajata tarkistamalla ensin jälkimmäisen; sillä erolla, että live-taulussa on alignmentteja vain viitisentuhatta, kun taas segmenttiversioita on kohta varmaan yli miljoona. Postgressi osaa onneksi käyttää tätä määräeroa varsin hyvin hyödykseen …
> GVT-2673 Optimize queries with alignment bounding boxes

- ui/src/map/layers/switch/switch-linking-layer.ts
- ui/src/map/map-view.tsx
Koko vaihdelinkitys kaipaa käytännössä vähän isompaa putsausta, jossa heittää pois kaikki hämärät aikaisemmat ajatukset siitä, mitä kaikenlaisia tapauksia niiden kanssa olisi, mutta tekisin sen mieluiten silloin, kun tiimiä on paikalla hieman enemmän varmistamaan ajatuksia.
Tässä nyt kuitenkin selkein ja suorimmin tärkeä, switch-linking-layerin putsaus. Tuo getSuggestedSwitchesByTile-haku ei tehnyt yhtikäs mitään, paitsi että spämmäsi hakuja, joilla sai koko tietokannan tukkoon pienellä zoomauksella. Todellisuudessahan vaihteiden linkitystapauksia on vain kaksi, ja niissä:
- geometriavaihteen linkityksessä vaihde-ehdotuksen haku tehdään jo geometriavaihde valittaessa GeometrySwitchLinkingInfoboxissa (ja sielläkin huonosti, koska käytettävissä olevaa geometriavaihde-ID:tä ei lähetetä …
> GVT-2673 Just display the suggested switch in the linking state, if it exists

- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationDao.kt
- infra/src/main/resources/db/migration/repeatable/R__05.01_layout_functions.sql
Pääteema jälleen haun esittäminen tavalla, joka on postgressille selkeä. En lukenut tässä tapauksessa hakusuunnitelmia niin tarkkaan, että osaisin sanoa, miksi entinen muoto toimi huonosti, se vaan oli selvästi paljon hitaampi.
Korjattu myös vaihteen ID-viittaus.
> GVT-2676 Fix slow query in loading publication candidates

- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/LinkingDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/switches/SwitchFittingService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationService.kt
- infra/src/main/resources/db/migration/prod/V81__remove_live_table_fk_reference_from_publication_table.sql
- infra/src/test/kotlin/fi/fta/geoviite/infra/linking/LinkingDomainTestData.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationServiceIT.kt
Jonkin verran bugifiksejä paikkoihin, missä haaratietoja ei viety tai käsitelty oikein.
Julkaisussa julkaistujen olioiden haku ei yritä vielä etukenossa tehdä mitään järkevää, jos niitä yritetään kutsua suunnitelmien sisäisille julkaisuille, vaan ainostaan mainin julkaisuille, joissa on suunnitelmissa tehtyjä muutoksia (olivat sitten suunnitelmassa luotuja olioita tai mainista tulleita suunnitelmassa muokattuja).
> GVT-2618&GVT-2672 Korjauksia suunnitelmatilaisiin linkityksiin + suunnitelmassa luotujen olioiden näkyminen julkaisulistalla

- ui/src/selection-panel/geometry-plan-panel/geometry-plan-panel.tsx
Previously the accordion toggle was displayed correctly depending on the previous selection. However, if it was in the "open" state, the actual content was not displayed without clicking twice to open the plan's content again.
> GVT-2650: Fix geometry plan losing content after a refresh in the selection panel

- ui/src/common/navigate.ts
- ui/src/version-holder/version-holder-view.tsx
Most of the pages contain information that can be re-fetched even without local browser cache. The upload page contains non-uploaded content, meaning that it will be lost on cache purge, which lead to a broken page layout.
> GVT-2639: Fix local browser cache purge missing redirect in inframodel upload page

- doc/paikannuspohjan_kontekstit.md
Lisätty: 
- Design-Draft konteksti-siirtymien kuviin. Näistä tuli mermaidissa entistä rumempia mutta ei nyt ihan lukukelvottomia.
- Kuvaus kontekstien tietokantaesityksestä
> GVT-2541 Layout Context dokumentaation päivitys

- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/LinkingDao.kt
Haun rakenne muuttuu aika paljon, ja integraatiotestejä ei ole, mutta ainakin nykyisellä suunnitelmien ja paikannuspohjan tilalla tulokset on ilman plan_id-suodatusta tasan samat kuin entisellä toteutuksella. Mutta paljon nopeammin.
Suunnitelmatilaisuuden kanssa paikannuspohjan olioiden kantahauissa näyttää tulevan jatkuvaksi kuvioksi, että jos halutaan hakea olioita jonkin kentän perusteella, mutta virallista ID:tä ei ole vielä tiedossa:
- Haetaan live-taulusta kaikki versiot, jotka löytyvät kentän haun perusteella
- Haetaan lateral joinilla kunkin rivin virallisen ID:n perusteella oikean kontekstin versio
- Tarkistetaan rivi-id:n (ja rivin version, vaikkei kyllä tarvitsisi) perusteella, oliko live-taulusta löytynyt rivi se, joka oikeasit on oikeassa kontekstissa
Tällä kuviolla haut …
> GVT-2685 Optimize fetchSwitchLinkStatus

- ui/src/tool-panel/location-track/location-track-infobox-duplicate-of.tsx
Aiempi tila johtui siitä, että duplikaattilistaus vain iteroi bäkkäriltä tulleen duplikaattiustietotaulukon läpi tutkimatta sen sisältöä sen kummemmin. Sama raide saattaa kuitenkin esiintyä taulukossa useaan kertaan mikäli sen on jonkin raiteen duplikaatti useammassa eri kohdassa. Bäkkärin puolesta tämä on enemmän ominaisuus kuin bugi (tuota tietoa käytetään hyväksi esim. splittauksessa,) joten päädyin muokkaamaan raiteen infoboksin duplikaattilistausta ja varmistamaan että siellä kukin duplikaatti listataan vain kertaalleen. Mietin muitakin vaihtoehtoja (esim. listauksen muuttamisen vähän esim. Raiteen geometriat -infoboksin tyyliseen muotoon, jossa duplikaattius ilmoitetaan aina rataosoiteväleittäin,) mutta tulin siihen tulokseen että tämä lienee se mitä oikeasti halutaan.
> GVT-2621: Raiteen duplikaattilistaus näyttää duplikaattiduplikaatteja

- infra/src/main/kotlin/fi/fta/geoviite/infra/error/ClientException.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/error/ErrorHandling.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutDesignDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutDesignService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/util/SanitizedString.kt
- infra/src/main/resources/db/migration/prod/V82__add_design_name_uniqueness_constraint.sql
- infra/src/main/resources/i18n/translations.fi.json
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutDesignDaoIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackDaoIT.kt
Isoin juttu täällä on, että nimen uniikkiustarkastelu on muutettu kantarajoitukseksi (kiitokset tässä Arille EXCLUDE-esimerkistä, joka meni ajoon about sellaisenaan.) Tämän myötä myös refaktoroitu ja yhtenäistetty errorkäsittelyä paikoissa joissa tehdään nyt samoja asioita ja korjattu testit.
> GVT-2671: Review-korjauksia designien nimen uniikkiustarkasteluun

- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/Publication.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/ratko/RatkoController.kt
- infra/src/main/resources/i18n/translations.fi.json
- infra/src/test/kotlin/fi/fta/geoviite/infra/integration/RatkoPushDaoIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationDaoIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationServiceIT.kt
- ui/src/common/common-model.ts
- ui/src/frontpage/frontpage.scss
- ui/src/frontpage/frontpage.tsx
- ui/src/linking/linking-api.ts
- ui/src/preview/preview-footer.tsx
- ui/src/preview/preview-merge-to-main-confirmation-dialog.tsx
- ui/src/publication/card/publication-card.scss
- ui/src/publication/card/publication-card.tsx
- ui/src/publication/card/publication-list-row.tsx
- ui/src/publication/card/publication-list.scss
- ui/src/publication/publication-api.ts
- ui/src/publication/publication-model.ts
- ui/src/publication/split/split-api.ts
- ui/src/ratko/ratko-api.ts
- ui/src/ratko/ratko-publish-button.tsx
- ui/src/ratko/ratko-push-error.scss
- ui/src/ratko/ratko-push-error.tsx
- ui/src/track-layout/layout-design-api.ts
- ui/src/track-layout/track-layout-api.ts
- ui/src/track-layout/track-layout-react-utils.tsx
- ui/src/user/user-card.scss
Päämuutos, että frontin layout muutettu uuteen kuosiin, ja julkaisukorttiin lisätty ominaisuus, että se pystyy hakemaan design-puolen julkaisulistaa. "Design-puoli" tässä tapauksessa tarkoittaa siis, että kaikki designien muutokset menee samaan listaan. Ratko-puskua design-puolella ei vielä yritetäkään.
Frontin tyypitystä muutettu vastaamaan enemmän bäkkäriä niin, että nyt käytetään enemmän DesignBranch-tyyppiä, jota pystyy sitten käyttämään suorempaan urleissa.
> GVT-2674 Rework front page layout, add design publications

- infra/build.gradle.kts
Koitetaas jos tämä korjaisi AWS:n ongelmat. Samalla korjaantuu GeoToolsissa ollut critical-tason haavoittuvuus
> Ad-hoc: GeoToolsin päivitys 31.3:een

- ui/tsconfig.json
Vaatii frontin uudelleenkäynnistyksen. Ja jos IDEA alkaa valittamaan jostain tai jotain uutta featurea ei löydy (eivät vielä käytössä, mutta tulevaisuudessa,) kannattaa varmistaa että IDEA käyttää varmasti frontin tsconfigia. Testattu käsin ja ajamalla lokaalisti E2E-testit Chromella ja Firefoxilla
> GVT-2691: ECMAScript-päivitys

- infra/src/main/resources/i18n/translations.fi.json
- ui/src/geoviite-design-lib/tab-header/tab-header.scss
- ui/src/geoviite-design-lib/tab-header/tab-header.tsx
- ui/src/tool-bar/tool-bar.tsx
- ui/src/tool-panel/location-track/location-track-location-infobox.tsx
Täällä tehtynä:
* Nykytila- ja Suunnitelmatila-tabien disablointi silloin kun raiteen jakaminen on päällä
* "Aloita raiteen jakaminen" -napin disablointi silloin kun ollaan suunnitelmatilassa. Tätähän olisi sinällään toiminnallisuutena mahdollista tukea meidän puolelta, mutta se vaatisi tuen myös Ratkolle -> disabloidaan toistaiseksi
> GVT-2682 & GVT-2617: Splittaus- ja tilasiirtymäparannuksia UI-puolelle

- infra/src/main/resources/db/migration/prod/V86__relax_design_row_id_uniqueness_constraints.sql
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutAssetServiceIT.kt
Lavennetaan design_row_id-viittausten uniikkiustarkistuksia niin, että mainista ja design-maailmasta saa olla yhtä aikaa olemassa viittaus. Tällä tavalla ei käyttäjän näkökannasta ihan sivusta ei tule teknisiä rajoituksia estämään suunnitelmatilan paikannuspohjan muokkaamista.
> GVT-2683 Relax design_row_id uniqueness constraints

- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/LinkingDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/LinkingService.kt
- infra/src/main/resources/db/migration/prod/V87__create_empty_type.sql
- infra/src/main/resources/db/migration/repeatable/R__04.06_track_number_in_layout_context.sql
- infra/src/main/resources/db/migration/repeatable/R__04.07_reference_line_in_layout_context.sql
- infra/src/main/resources/db/migration/repeatable/R__04.08_location_track_in_layout_context.sql
- infra/src/main/resources/db/migration/repeatable/R__04.09_switch_in_layout_context.sql
- infra/src/main/resources/db/migration/repeatable/R__04.10.km_post_in_layout_context.sql
- infra/src/test/kotlin/fi/fta/geoviite/infra/geometry/GeometryDomainTestData.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/linking/LinkingServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/TrackLayoutDomainTestData.kt
Hieman sivusta tullut hakuoptimointijuttu sisältää varsin ison ehdotuksen siitä, miten layout-kontekstia käyttäviä hakuja voitaisiin tehdä.
Vaihtoehtoja olisi nyt (esimerkkinä sijaintiraidehaku, main-draft-kontekstissa):
- Jos haetaan virallisen id:n perusteella: `select * from layout.location_track_in_layout_context('DRAFT', null, 123)`, kuten aiemminkin. Toimii luotettavasti nopeasti.
- Jos haetaan jonkin muun kentän perusteella, esim. ratanumeron: `select * from layout.location_track, layout.location_track_is_in_layout_context('DRAFT', null, location_track) where track_number_id = 123`. Toimii myös luotettavan nopeasti, ehkä. Ainakin sen verran luotettavan nopeasti, että sain sillä korjattua tämän taskin varsinaisen perffiongelman.
- Muita vaihtoehtoja on, ja niitä käytetään, mutta …
> GVT-2685 Optimize plan status fetching harder

- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/PlanLayoutService.kt
- ui/src/geometry/geometry-api.ts
Käytännössä GVT-2685 toteutuksen osana hoksattu ärsyttävyys: Suunnitelmien geometrioiden haussa ei ole juurikaan sellaista overheadia, jonka takia niitä olisi tarvetta tehdä massana, mutta täysin puhtaalta pöydältä ajoajasta kaksi kolmasosaa menee JSON-serialisointiin.
Siinä olisi varmasti optimoimisen varaa (ensisijaisesti kai siinä, että geometrioitakin yksinkertaistettaisiin zoomaustason mukaan), mutta ensihätään rinnakkaistuksen siirto selaimen tasolle nopeuttaa huomattavasti ison suunnitelmajoukon lataamista kerralla, koska serialisoinnit (ja deserialisoinnit) rinnakkaistuvat näin.
> Float plan layout fetching parallelism to browser

- .github/workflows/pull_request.yml
- infra/build.gradle.kts
- infra/run_it_tests.sh
- infra/src/main/kotlin/fi/fta/geoviite/infra/configuration/CacheConfiguration.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/configuration/CachePreloader.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/switchLibrary/SwitchLibraryService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/switchLibrary/SwitchStructureDao.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/common/SwitchStructureIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/integration/CalculatedChangesServiceIT.kt
- infra/src/test/resources/application-test.yml
Pullarin nimen mukaisesti integraatiotestejä ajetaan tästä eteenpäin Springin kakutus päällä. Jotta voidaan varmistua siitä, että kaikki kanta-access toimisi varmasti myös ilman kakutusta, täällä lisättiin myös tuki DAO-testien ajamiselle ilman cachea, ja nämä ajot on lisätty myös testiajoskribuloihin ja GitHub Actions -workflow'hun.
Tämän lisäksi korjattu ongelma mistä näiden korjailu alunperin johtui, eli parin `SwitchStructureIT`:n käyminen kannassa niin paljon, että round-tripit rupesivat timeouttailemaan. SwitchStructuret kakutetaan nyt service-tasolla DAO-tason sijaan, sillä SwitchStructuret ovat aina (migraatioiden ajoa lukuunottamatta) täysin muuttumattomia koko bäkkärin eliniän ajan.
> Integraatiotesteihin Springin cache päälle + testikorjauksia

- infra/detekt.yml
Previously we have often had warnings for functions with over 6 parameters and sometimes also for service classes containing more than 21 injected dependencies in their constructors.
As modifications have not been made during the warnings, this warning has seemed somewhat unnecessary in terms of noise, even though it does notify about complex functions and large service-classes.
> General: Disable detekt's LongParameterList check

- ui/src/track-layout/layout-map-api.ts
- ui/src/track-layout/layout-switch-api.ts
Mietin, pitäisikö nuo kaikki `${layoutContext.publicationState}_${layoutContext.branch}`t ympäri koodikantaa yhdistää joksikin layoutContextKey-funktioksi, mutta päätin että no ainakin aivan tähän hätään YAGNI.
> GVT-2694 Fix context ignorance in validation caching

- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/PlanLayoutService.kt
- ui/src/geometry/geometry-api.ts
- ui/src/selection-panel/selection-panel-geometry-section.tsx
Kaikki paikannuspohjamuutokset aiheuttavat jokaisen valintapaneelissa näkyvillä olevan suunnitelman linkitystilan tarkistuksen, eli jos käyttäjällä on paljon suunnitelmia auki ja paikannuspohjaan tehdään usein muutoksia, linkitystilojen haku pyörii jatkuvasti (kuten tuli testaussessiossa todennettua). Nämä haut toimivat paremmin massana, eli vaihdetaan massa-ajooṇ. Samalla toisaalta yksinkertaistettu huomattavasti suunnitelmien geometrioiden hakujen koodipolkuja, kun heitä taas ei yritetä enää hakea massahaulla.
> GVT-2715 Parallelize plan layout and status fetching better

- infra/src/main/kotlin/fi/fta/geoviite/api/frameconverter/v1/FrameConverterControllerV1.kt
- infra/src/test/kotlin/fi/fta/geoviite/api/frameconverter/v1/FrameConverterAddressIT.kt
Laitettu eksplisiittisesti (ns. jokainen urli bindattu erikseen), kun kerta normaalissa backendissä näitä ei tueta niin päätyy devaajan silmille herkemmin näkyviin tällä tavoin. (Voisi sinänsä yhtä hyvin toteuttaa myös esim. filtterillä [=middleware], joka ottaisi ne vaan veks, joka olisi ns. implisiittistä)
> GVT-2741: Add support for trailing slashes in frame converter api

- infra/src/main/kotlin/fi/fta/geoviite/infra/geocoding/GeocodingDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/LinkingDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/split/SplitDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutAssetDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutKmPostDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/ReferenceLineDao.kt
- infra/src/main/resources/db/migration/prod/V89__add_official_id_as_generated_column.sql
- infra/src/main/resources/db/migration/repeatable/R__04.06_track_number_in_layout_context.sql
- infra/src/main/resources/db/migration/repeatable/R__04.07_reference_line_in_layout_context.sql
- infra/src/main/resources/db/migration/repeatable/R__04.08_location_track_in_layout_context.sql
- infra/src/main/resources/db/migration/repeatable/R__04.09_switch_in_layout_context.sql
- infra/src/main/resources/db/migration/repeatable/R__04.10.km_post_in_layout_context.sql
Lisätty official id laskettuna columnina ja otettu se käyttöön coalescejen tilalle. Tämä mahdollistanee myös optimointia/yksinkertaistusta joihinkin nykyisiin hakuihin, mutta niitä ei ole tässä yhteydessä muokattu.
Tämä siis korjaa tuon 500-virheen samalla koska se johtui inserttien puutteellisesta official_id päättelystä, joka ei ottanut huomioon että myös design_row_id voi olla se official.
> GVT-2716 fix some official ids ignoring design_row_id

- infra/src/main/resources/i18n/translations.fi.json
- ui/src/tool-panel/km-post/dialog/km-post-edit-dialog-gk-location-section.tsx
- ui/src/tool-panel/km-post/km-post-infobox.tsx
- ui/src/utils/string-utils.ts
Korjattu pienet huomiot:
- KM-pylvään infoboxissa ei enää näytetä undefined-koordinaatteja. Muutkin puuttuvat arvot on yleisemmin korjattu muotoon '-' kuten joissain kentissä jo oli
- Kun koordinaattia ei ole, edit-dialogilla tyhjäksi jäänyt layout-koordinaatin näyttökohta näyttää nyt viestin "Sijaintia ei ole määritelty"
- Jos layout-muunnos tuottaa infinity-arvoja, niitäkään ei näytetä, vaan edelleen näytetään tuo sama virhe
Yleisemmin nuo kentät kannattaisi validoida inputtien osalta vähän fiksumminkin jotta käyttäjää ohjattaisi paremmin. En kuitenkaan tehnyt sitä tässä yhteydessä vaan tein sille erillisen tiketin: https://extranet.vayla.fi/jira/browse/GVT-2747
> GVT-2724 Fix display issues for invalid coordinate values in km-post edit dialog & infobox

- infra/src/main/resources/i18n/translations.fi.json
- ui/src/tool-bar/tool-bar.tsx
- ui/src/tool-bar/workspace-dialog.tsx
- ui/src/tool-bar/workspace-selection.tsx
Täällä lisätty puuttuva käännös bäkkärivirheelle jos työtila on jo olemassa (GVT-2727) sekä varmistuttu että työtilan muokkausdialogin nappeja ei voi painella kun tallennuspyyntö on matkalla (GVT-2731)
> GVT-2727 & GVT-2731: Parannuksia työtilojen luonnin/muokkauksen virhekäsittelyyn

- infra/src/main/kotlin/fi/fta/geoviite/infra/error/ClientException.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/Linking.kt
- infra/src/main/resources/i18n/translations.fi.json
Ei poista virhettä, mutta tekee siistä siistin virhe-toastin internal server errorin sijaan.
> GVT-2695 Fix internal server error on invalid gk-coordinates

- infra/src/main/kotlin/fi/fta/geoviite/infra/authorization/UserData.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/configuration/WebConfiguration.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/inframodel/InfraModelService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/util/ResultSetExternal.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/util/SanitizedString.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/util/StringUtils.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/geometry/GeometryDomainTestData.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/inframodel/InfraModelServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/integration/RatkoPushDaoIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/linking/LinkingDomainTestData.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationDaoIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ratko/RatkoServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/split/SplitDaoIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/testgroup1/FrontPageTestUI.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/testgroup1/PublicationLogSearchTestUI.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/util/SanitizedStringTest.kt
Muutos itsessään on pieni. Tiedostomäärä johtuu siitä että noita luodaan aika monessa paikassa ja rakentaja piti vaihtaa factory-metodiin.
> GVT-2387 Canonize linebreaks in FreeTextWithNewLines

- infra/src/main/kotlin/fi/fta/geoviite/infra/util/StringUtils.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/util/SanitizedStringTest.kt
Aiempi loggerin limit length teki tähän tarkoitukseen väärää asiaa -> korjattu sanitize yksinkertaisempaan malliin jotta hoitaa myös pituuden oikein.
> GVT-2387 Fix length sanitizing & include it in tests

- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryValidation.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/switches/SwitchFittingService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/switchLibrary/SwitchStructure.kt
Vaihteiden live-linkityksen muut optimoinnit (jotka tulevat myöhemmissä, isommissa pullareissa) saivat aikaan sen, että poikkeusten heitto tästä funktiosta alkoi näkyä profiileissa aika isona. Poikkeustiedolla ei missään tehdä oikeasti mitään, ja kaikki kutsujat korvasivat poikkeuksen nullilla, eli sama palauttaa näissä ihan vaan suoraan nullia näissä tilanteissa, jotka eivät sitten kai olekaan niin poikkeuksellisia.
> GVT-2357 Optimize calculateSwitchLocationDelta

- ui/src/publication/log/publication-log.tsx
- ui/src/vayla-design-lib/datepicker/datepicker.tsx
Täällä säädetty päivämäärän asettamista siten, että asetetun päivämäärän mukana tulee myös tieto siitä kumpaa kautta päivämäärä on asetettu (picker vs. tekstimuoto.) Tämä mahdollistaa erilaisen käsittelyn näille (esim. debouncataan vain tekstillä syötetyt päivämäärät, joka toteutettu täällä julkaisulokiin.)
> GVT-2728: DatePicker: Asetetun päivämäärän propagointirefaktorointi

- infra/gradle.properties
Huomasin että gradlessa ei ollut build cachet käytössä. Jos havaitsette näistä jotain ongelmia niin sanokaa, mutta tuon pitäisi nopeuttaa rebuildeja.
> General: Enable gradle caches by default

- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/LinkingController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/switches/SwitchFittingService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/switches/SwitchLinkingService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/math/Line.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/TrackLayout.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/linking/FittedSwitchTest.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/linking/SwitchLinkingServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/linking/SwitchLinkingTest.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchServiceIT.kt
Möhkäle, jossa mukana sekä silkkaa vaihdelinkityksen optimointia (jotta se tapahtuu riittävän nopeasti, että live-linkitys on lainkaan järkevää), parin muun vaihdelinkityksen sivussa olevan asian optimointia (koska linkityksen itsensä optimoimisen jälkeen eritoten raiteen tehtävälistan laskemisessa alkoi näyttää profilerissa hassulta, että ajoaika meni aivan muualle kuin linkitykseen), ja ehkä olennaisimpana muutoksena PointAssociation/SamplingGridPoints-luokat ja niiden käyttö siihen, että live-linkitystä varten vaihdelinkitykseen menevissä laskutoimituksissa voi yhdistää asiat, joissa tehdään toisiaan lähellä olevissa pisteissä samaa asiaa.
Tässä kommitissa on pelkästään bäkkärimuutoksia. Uuden frontin käyttämä kontrollerirajapinta tulee mukaan, vanha ei poistu, eli näkyviä muutoksia ei …
> GVT-2357 Optimize switch linking, introduce switch linking on grids

- ui/package-lock.json
- ui/package.json
- ui/src/publication/publication-utils.ts
Ei itse asiassa kummempaa syytä päivittää juuri tällä hetkellä, satuin vaan katsomaan että onpas taas näppäriä ominaisuuksia saatu. En lähtenyt https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-5.html#inferred-type-predicates myötä vielä poistamaan filterNotEmptyjä pois, eikä kai kannatkaan.
> General: Bump TypeScript version

- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/pagemodel/common/E2EInfoBox.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/pagemodel/inframodel/InfraModelElement.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/testgroup1/UserRoleTestUI.kt
- ui/src/infra-model/infra-model-api.ts
- ui/src/infra-model/infra-model-slice.ts
- ui/src/infra-model/view/formgroup/formgroup-field.tsx
- ui/src/infra-model/view/formgroup/formgroup-textarea.tsx
- ui/src/infra-model/view/infra-model-edit-loader.tsx
- ui/src/infra-model/view/infra-model-import-loader.tsx
- ui/src/infra-model/view/infra-model-upload-loader.tsx
- ui/src/infra-model/view/infra-model-view-container.tsx
- ui/src/infra-model/view/infra-model-view.tsx
- ui/src/tool-panel/infobox/infobox-field.tsx
- ui/src/tool-panel/infobox/infobox.module.scss
Tiketillä mainittu alkuperäinen bugi oli siis, että jos ensin ProjektiVelhon InfraModel-importissa on käyty katsomassa inframallia A, navigoidaan takaisin inframallilistaukseen ja mennään ProjektiVelhon listauksesta InfraModel-tiedoston B importtiin, niin inframallin A tiedot näkyvät hetken inframallinäkymässä ennen B:n tietojen latautumista. Tämä on korjattu (yksittäisen inframallin näkymän tila clearataan nyt aina näkymään mentäessä.)
Tällä sivuvaikutuksena oli se, että kun aiemmin inframallin uploadissa (ja vain inframallin uploadissa) on pystynyt navigoimaan toisiin näkymiin ja tulemaan takaisin selaimen backilla siten että näkymässä tehdyt tallentamattomat muutokset pysyvät olemassa, niin nyt ne muutokset katoavat. Tästä tilanteesta on kysytty Karilta, jonka mukaan tämä muutos on …
> GVT-2702: Yksittäisen InfraModelin detaljinäkymän parannuksia + edit-ikonien napittaminen

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutAlignmentDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/MapAlignmentService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutAlignmentDaoIT.kt
Optimointivaraa ei aivan mielettömiä määriä ollut ilman isompia remontteja, suodatuksia vaan on viety mahdollisimman lähelle suodatettavaa tietoa. Ikkunointimagialla saisi pystygeometriattomien jaksojen laskemisen kokonaan tietokantaan, mutta sillä olisi iso kompleksisuusvaikutus, iso riski tehdä joistakin hauista todella hitaita, ja vain pieni hyöty yleisen tapauksen perffissä.
> GVT-2763 Optimize fetchProfileInfoForSegmentsInBoundingBox

- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/LinkingDao.kt
Toivottavasti näitä väellä ja vängällä tehtäviä hakuja ei tule paljoa, koska vaikka haku ei sinällään ole niin monimutkainen kuin miltä se näyttää, on siinä kyllä paljon melua vähästä.
Alkuperäinen ongelma siis oli, että:
- suunnitelmassa voi olla paljon vaihteita
- vaihteeseen voi viitata useampi suunnitelman elementti
- suunitelman elementtiin voi viitata paljon paikannuspohjan segmenttien versioita
- ... ja vaikka nämä kaikki lopulta liittyvät pieneen joukkoon paikannuspohjan vaihteita, postgresql katsoo ylläolevan rytäkän jokaisen rivin kohdalta, että onkos tämä nyt oikeassa paikannuspohjan kontekstissa olemassaoleva vaihde. Voi olla vaikka 30 eri switch_id:tä, mutta 10,000 riviä, jos raiteita on säädetty paljon.
Ja ongelma on korjattu niin, että rivit ryhmitellään paikannuspohjan …
> GVT-2765 fetchSwitchLinkStatuses() optimointi jälleen

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutAlignmentDao.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutAlignmentDaoIT.kt
Jälleen ärsyttävän paljon melua haussa, samalla tekniikalla kuin https://github.com/finnishtransportagency/geoviite/pull/1410 . Teoriassa voisi olla ehkä tehtävissä vähemmälläkin melulla, mutta tällä ainakin nopea toiminta on varmaa. Varsinaisena oleellisena bugifiksinä tuon vertical_intersection-taulun tarkistuksen lisäys, jolla löytyy tieto siitä, onko tällä geometriaraiteella nyt olemassa oikeasti profiili.
> GVT-2775 Re-optimize and fix finding profile info on segments

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutAlignmentDao.kt
Testit sattui menemään näemmä tuurilla läpi viime pullarissa ilmankin tätä, mutta segment_indexin perusteella sorttaus on ihan oikeasti tässä tarpeen, ja sen puute aiheuttaa ainakin testifleikkejä ja saattaa ehkä rikkoa ominaisuuden itsensäkin.
> GVT-2775 Fix missing ordering in fetchProfileInfoForSegmentsInBoundingBox

- doc/ajoitetut_tehtavat.md
- infra/src/main/kotlin/fi/fta/geoviite/infra/projektivelho/PVIntegrationServiceScheduler.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationGeometryChangeRemarksUpdateTask.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/ratko/RatkoOperatingPointsFetchTask.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/ratko/RatkoPushTask.kt
* Scheduled functions are now private (this causes detekt warnings, but is more correct)
* Fixed md-file wrapping
> GVT-2665 & GVT-2722 (part 2): Review fixes

- infra/src/main/resources/application.yml
Due to ProjektiVelho being enabled in the application-test.yml (Spring test) profile, the new scheduler structure expected to find a default value for initial-delay of the search-poll -configuration variable when starting the application with the "test" profile. As the value couldn't be found when ProjektiVelho was enabled (in the test profile), it caused a failure to start the Spring application with the "test" profile, used by E2E (ui) tests. This meant that E2E tests could not be run at all.
Enabling the 1 hour initial delay of ProjektiVelho shouldn't cause issues even when running the application normally (as it's going to be run in 4h intervals anyway when enabled). This also standardizes the default application profile to have standard form (no commented out configuration and "sane …
> GVT-2532 (part 3): Uncomment initial PV-schedule to fix test startup error

- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/switches/SwitchLinkingService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/ReferenceLineDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/ReferenceLineService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/TestDBService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/geocoding/GeocodingDaoIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackDaoIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/ReferenceLineDaoIT.kt
Katselmointikommentteja fiksaillessa päätin kirjoittaa pari testiä, ja hyötyä oli, kun ne löysivät ihan juuri tekemäni buginkin: LocationTrackDao#fetchVersionsNear()issa oli ylimääräinen deleted-tilan tarkistus, minkä takia sen includeDeleted-parametri ei toiminut.
> General: Fix, clarify, and add tests for fetchVersionsNear()s

- infra/src/main/kotlin/fi/fta/geoviite/infra/projektivelho/PVClient.kt
V1 ja V2 toimivat tarpeeksi samalla tavalla, että versiopäivityksen pystyi vaan tekemään koskematta tyyppeihin
> GVT-2777: Projektirekisterin rajapinnan päivitys

- ui/src/map/layers/alignment/location-track-split-alignment-layer.ts
Splitin ei tarvitse osua segmenttipisteelle, joten alignmenttien piirtymistä ei pysty saamaan osumaan tarkkaan splittikohtiin asti pelkällä pisteiden suodatuksella. Päätepisteet pitää siis interpoloida.
> GVT-2706 Draw split alignments exactly up to split point

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutAssetDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutAssetService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSearchServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/ReferenceLineServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/TrackLayoutDomainTestData.kt
Ongelman sai toistumaan stepeillä:
1. Luo suunnitelma ja julkaise siellä joku käsite (esim uusi ratanumero tai km-pylväs)
2. Vie suunnitelmassa luotu olio varsinaisen paikannuspohjan draftiin (älä julkaise vielä)
3. Tee suunnitelmassa uusi julkaisematon muutos kyseiseen käsitteeseen
4. Julkaise varsinaisen paikannuspohjan draft-versio
Tämän jälkeen alkaa lentämään virheitä kun palaa tarkastelemaan suunnitelmaa. Tämä johtui siitä että suunnitelma-draft viittasi edelleen viralliseen suunnitelmaolioon vaikka se olikin prosessin myötä siirtynyt viralliseksi main-puolen olioksi (viite väärää kautta).
> GVT-2768 Fix design publishing potentially leading to 2 rows in one context

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutAssetDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutAssetService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberServiceIT.kt
Eli tulipa mieen tästä edellisestä bugista (https://github.com/finnishtransportagency/geoviite/pull/1422) toinen variantti: jos design-rivi on tuotu jo main-puolella olevan rivin pohjalta tilanne muuttuu hiukan. Nyt design-rivi ei muutu officialiksi vaan se poistuu ja tiedot kopioidaan main-riville. Design-draft rivi täytyy silti päivittää, mutta se pitää tehdä ennen design-officialin poistoa koska muuten poistosta aiheutuu reference-error. 
Korjauksena riittää siis pyöräyttää komentojen järjestys toisin päin, mutta samalla lisätty IT-testi tällekin caselle.
> GVT-2768 part 2: adjust design row references when implementing an updated (non-new) design row

- ui/src/tool-bar/workspace-selection.tsx
- ui/src/vayla-design-lib/dropdown/dropdown.scss
- ui/src/vayla-design-lib/dropdown/dropdown.tsx
* Add vertical display limit css
* Add alphabetical sorting
* Search now checks the entire string for substring matches instead of from the beginning of the string values (workspace names).
> GVT-2729: Improve workspace selector

- infra/src/main/kotlin/fi/fta/geoviite/infra/common/KmNumber.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geocoding/Geocoding.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/geocoding/GeocodingTest.kt
Alkutila oli, että jos jokin km-tolppa on raiteella päin honkia sopivasti, niin käänteinen geokoodaus (koordinaateista osoitteeksi) ennen tätä tolppaa raiteella toimii, mutta tavallinen geokoodaus (osoitteesta koordinaateiksi) aiheutti sisäistä virhettä, koska jollekin projektioviivalle tulisi rataosoite, jolla metriosa on yli 10000.
Muutettu tavallinen geokoodaus palauttamaan vaan aina nullia (minkä kutsujat jo osasavatkin käsitellä), jos projektioviivojen rataosoitteissa on häikkää.
> GVT-2755 Avoid creating projection lines with invalid addresses

- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationValidation.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/switchLibrary/SwitchStructure.kt
- infra/src/main/resources/i18n/translations.fi.json
- infra/src/test/kotlin/fi/fta/geoviite/infra/linking/SwitchLinkingServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/SwitchTopologicalConnectivityTest.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/TrackLayoutDomainTestData.kt
Hieman koomisen iso muutos siihen nähden, että varsinainen alkuperäinen ongelma oli regressio siinä, miten validaatio käsittelee vanhoja Ratko-peräisiä yhdellä pisteellä linkitettyjä vaihteita; mutta regression syy oli puuttuvat testit, ja testejä kirjoittaessa tuli sitten löydettyä kaikenlaista parannettavaa ja selkeytettävää.
Funktionaaliset muutokset:
- Validaatio tunnistaa nyt yhdellä pisteellä linkitetyt vaihteet omana tapauksenaan, josta antaa varoituksen
- Ylimääräisten linkityksien validointi menee nyt vaihdelinjoittain koottuna, alkuperäinen muoto (missä ylimääräiset linkitykset oli listattu vaihdepisteittäin) oli vähän liikaa noisea
- Pelkästään topologialinkeillä, ei lainkaan segmenttilinkeillä kiinni oleva vaihde aiheuttaa nyt vain varoituksen (näitä on paikannuspohjassa 24, …
> GVT-2786 Redo switch topological connectivity validation

- infra/src/main/kotlin/fi/fta/geoviite/infra/geocoding/Geocoding.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/split/SplitService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/split/SplitValidation.kt
Lisäfiksi false positive geometriavirheisiin split-validoinnissa. Tämänkin jälkeen löytyy vielä hassuja, joita pitää vähän tutkia lisää, mutta näyttäisi että ne liittyy transfer-caseihin, joten niissä voi olla oikeita ongelmia
> GVT-2758 (Take 2) Split validation: produce comparable start/end points for source track segment

- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationDao.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationServiceIT.kt
Alussa löytyi yksi bugi, sille testejä kirjoittaessa toinen:
- Logiikka sille, että haetaan muutoksia joko julkaisu-id:llä tai design-id:llä, oli väärinpäin, ja siksi julkaisulokista katosi vaihdelinkkimuutokset kokonaan
- Vaihteiden design-julkaisut saattoivat rynniä mainin vaihdejulkaisujen päälle ja hämmentää hakua
Haku ei edelleenkään kokonaisuutena yritäkään tukea millään lailla design-puolen julkaisulokien tekoa, mutta jätin nyt siitä huolimatta tuon vaihteiden design-julkaisujen erottelun rakenteen ainakin alustavasti sellaiseksi, että se toimii (ehkä, ei lainkaan testattu) yhdenmukaisesti eri suuntiin.
> GVT-2795 Fix branch confusions in switch link change query

- infra/gradle.properties
Näyttäisi toistaiseksi aiheuttavan enemmän problematiikkaa kuin hyötyä
> General: Disable gradle config cache for now

- infra/src/main/resources/i18n/translations.fi.json
- ui/src/app-bar/app-bar.tsx
- ui/src/geoviite-design-lib/form-layout/form-layout.scss
- ui/src/geoviite-design-lib/form-layout/form-layout.tsx
- ui/src/tool-bar/tool-bar.tsx
- ui/src/tool-panel/km-post/dialog/km-post-edit-dialog-gk-location-section.tsx
- ui/src/tool-panel/km-post/dialog/km-post-edit-dialog.scss
- ui/src/tool-panel/km-post/dialog/km-post-edit-dialog.tsx
- ui/src/tool-panel/km-post/dialog/km-post-edit-store.ts
- ui/src/tool-panel/km-post/geometry-km-post-linking-infobox.tsx
- ui/src/tool-panel/km-post/km-post-infobox.scss
- ui/src/tool-panel/km-post/km-post-infobox.tsx
- ui/src/vayla-design-lib/dropdown/dropdown.scss
- ui/src/vayla-design-lib/field-layout/field-layout.scss
- ui/src/vayla-design-lib/field-layout/field-layout.tsx
- ui/src/vayla-design-lib/radio/radio.scss
- ui/src/vayla-design-lib/radio/radio.tsx
Tämän pullarin pääjuttuna oli tehdä kilometripylvään GK-sijainnista optionaalisesti pakollinen (GVT-2766). Siihen liittyen täällä tehty:
* Muutettu kilometripylvään muokkausdialogi kaksipalstaiseksi, josta oikea puoli sisältää GK-sijainnin
* Mahdollistettu GK-sijainnin "kytkeminen" päälle/pois. Kun sijainti on kytketty päälle, GK-sijainnin kentät ovat pakollisia
* Mahdollistettu GK-sijainnin nollaaminen kytkemällä sijainti pois päältä KM-pylväälle, jolla sellainen on jo asetettu
* Lisätty GK-sijainnin esitäyttö sunnitelman datasta linkitettäessä
* Tehty valmistelevia töitä kilometripylvään GK-kaistan automaattiseen korjaamiseen liittyen. Loput tästä tulevat omalla tiketillään myöhemmin kun selviää tehdäänkö sitä vai ei, ja jos tehdään, niin missä muodossa. Samoin paremmat virheiden …
> GVT-2761 & GVT-2766 & GVT-2784: Kilometripylvään GK-sijainnin parannuksia ja rekisterisivun poisto (part 1)

- infra/src/test/kotlin/fi/fta/geoviite/api/frameconverter/v1/FrameConverterExamplesTest.kt
Responseille vastaavan testin tekeminen meneekin hankalammaksi, koska nykyrakenteella noita vastaustyyppejä ei oikein ole mietitty deserialisointia ajatellen. Jackson ei nimittäin osaa tehdä mitään hyödyllistä ilman että tekee käytännössä koko deserialisointilogiikan itse 😄
Also VKM:n vastaukset on GeoJsonia jossa ei ole sitä diskriminaattorikenttää -- jos joku koodaa jotain yleisempää vastauskäsittelijää kuin käsittely-per-pyyntö, niin törmää siihen diskriminointiärsyttävyyteen (eli "arvaa mikä properties-kenttä-kombinaatio milläkin vastaustyypillä on uniikki"). Meillä voisi siis olla siellä properties-kentässä jokin "type/kind/vastaava"-kenttä kertomassa, että minkälaisesta muunnostuloksesta on kysymys käyttäjäkoodarin ergonomian parantamiseksi. Silloin myös näiden response-esimerkkien …
> GVT-2800: Add unit test for frame converter example request deserialization

- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationGeometryChangeRemarksUpdateService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationService.kt
Tämä oli aikoinaan tuotu mukaan transaktioon sillä oletuksella, että olkoonkin, että tämä laskutoimitus on liian raskas tehtäväksi julkaisulokia lukiessa, ei siihen todellisuudessa mene pahimmillaankaan kuin pari sekuntia, joten olkoon vaan samassa syssyssä.
Eipä ollutkaan, vaan kyllä tähän pystyy menemään useampi minuutti, ja osumaan siten transaktioiden aikakatkaisuun. Kokonaisvaltainen ratkaisu varmaan vaatisi heittää koko laskennan sivuun omaan säikeeseensä tjms., koska eipä tätä julkaisulokin lisätietojen laskemista voi oikeastaan pitää asiana, jota käyttäjänkään pitäisi tarvita odottaa, mutta tässä nyt minimiratkaisu sitä varten, että saadaan tuotanto kuntoon.
> GVT-2819 Move geometry change remark calculation out of transaction

- ui/src/publication/table/publication-table-row.tsx
- ui/src/publication/table/publication-table.tsx
Julkaisulokissa piti kliksutella aikaisemmin aikas paljon jos halusi saada näkyviin paljon tietoa kerralla. Nyt riittää yksi painallus kaikkien tarkempien tietojen avaamiseen ja jos sattuu olemaan esim. pari auki, niin tuosta napista klikkaamalla saa suljettua avattuna olevat.
> GVT-2814: Add toggle for all publication item details in publication log

- ui/src/common/navigate.ts
- ui/src/publication/card/publication-list-row.tsx
- ui/src/publication/card/publication-list.scss
- ui/src/publication/card/publication-list.tsx
Tuo aiempi toimintalogiikkahan ei ollut edes tarpeellinen, lähti myös lisää turhuuksia veks näin uusilla silmillä
Unohdinkin jo että tein aiemmin [GVT-2346](https://extranet.vayla.fi/jira/browse/GVT-2346) (meillä on kaksi eri Link-komponenttia samalla nimellä..)
Korjailee siis pilvessä refresh-bugin.
> GVT-2809 (part 2): Use react-router Link

- infra/src/main/resources/db/migration/beforeMigrate.sql
Teen lisäksi dokumentaation tietokannan päivityksestä env-puolelle. Tässä koodipuolelle rajoitin joka varmistaa ennen migraatioiden ajoa että ollaan vähintään halutussa versiossa. BeforeMigrate on siinä mielessä hyvä että tiedostoa voi vain päivitittää ja toisaalta se kuitenkin ajetaan ennen kun lähdetään migroimaan mitään. Ainakin tässä extension update tapauksessa riittää hyvin varmistaa että ollaanhan jo 16-sarjassa ennen kun päivitetään extensiot ja tämä hoitaa sen.
> GVT-2812 Ensure in backend launch that we have a supported postgres version in use

- ui/src/publication/table/publication-table-utils.ts
- ui/src/utils/array-utils.ts
This should be more intuitive to the user when compared to organizing publication table items related to for example a specific track number by random/unspecified order (as it previously was).
> GVT-2829: Use publication time as secondary sort order for publication log columns

- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationUtils.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/util/FreeText.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/util/SanitizedStringTest.kt
Previously the exported csv had new lines in unexpected places, making the csv more difficult to use.
> GVT-2826: Escape new lines in publication log csv export

- infra/src/main/kotlin/fi/fta/geoviite/infra/configuration/RequestFilter.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/error/ClientException.kt
- infra/src/main/resources/i18n/translations.fi.json
- ui/src/api/api-fetch.ts
- ui/src/common/common-slice.ts
- ui/src/main/main.tsx
Periaate: Välitetään frontilta `x-geoviite-ui-version`-header kaikissa rajapintapyynnöissä, ja bäkkäri tarkistaa tämän headerin pehmeästi `RequestFilter`'n aikana: Jos kyseistä headeriä ei ole tai se on tyhjä, ei varsinaista tarkistusta tehdä. Jos taas header on epätyhjä, niin bäkkäri tekee vertauksen omaan versioonsa ja heittää poikkeusta tarvittaessa.
Problematiikkaa aiheuttaa:
* Frontti tekee pyyntöjä ennen kuin se tietää ensimmäisen bäkkärin version, jolla käyttöliittymä on ollut aktiivinen. Meillä ei sinänsä ole "ui-bundlen versiota" (pitäisikö olla?), niin sitä ei voi välittää. Tässä siis ainakin yksi syy pehmeään tarkistukseen. Toki tuon voisi synkata, ettei esim. /environment-polkuun tehtäisi versiotarkistusta, ja kaikki muut pyynnöt olisivat nk. hard-faileja. Kaikkihan meidän …
> GVT-2821: Handle stale frontend version during backend update

- infra/src/test/kotlin/fi/fta/geoviite/api/frameconverter/v1/MixedRequestIT.kt
Mixed frameconverter requests are no longer supported, so these tests won't have to be created.
> General: Remove unnecessary and empty integration test file

- infra/src/main/kotlin/fi/fta/geoviite/api/frameconverter/v1/FrameConverterControllerV1.kt
- infra/src/main/kotlin/fi/fta/geoviite/api/frameconverter/v1/FrameConverterServiceV1.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/util/Either.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/util/EitherTest.kt
Kolme oleellista muutosta:
- FrameConverterServicessä on montakin paikkaa missä saattoi joko mennä kaikki hyvin tai sitten tulla virhettä, ja molemmista halutaan jonkinlaisen käsittelyn jälkeen palautusarvoon tieto; ja osassa vielä niin, että hyvin menneet tapaukset halutaan käsitellä massana. Nämä sopivat luonnostaan Either-tyypin muottiin sen verran hyvin, että ajattelin että tehdään nyt lopulta sellainen. Mutta ehkä pitäisi käyttää kirjastoa eikä omaa, jotta käytetään standardimpeja käsitteitä?
- Koko raideosuman haku tehdään nyt kannassa massana. Periaatteessa postgissillä saisi tehtyä nekin käsittelyt, että palauttaa sen lähimmän pisteenkin, mutta päädyin siihen, että tehdään se Kotlinissa, koska se on siellä halpaa tehdä uusiksi (sitä ei juuri profiileissa näy), ja näin vastaukset …
> GVT-2804 Optimize coordinate->track address mass conversions

- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationDao.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/TestDBService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationServiceIT.kt
Tämä ei siis korjaa nyt sitä perusongelmaa, että kun julkaisujen muutostauluihin (esim. publication.location_track) tallennetaan rivejä, niissä käytetään riviversiota mutta virallista id:tä, ja siksi niillä ei pysty erottamaan versiotaulusta suoraan, mikä versio oikeasti juuri tässä julkaisussa meni.
Riittävä tieto erotteluun kyllä on olemassa, koska sekä julkaisuilla että versio-olioilla on design-haaratieto. Eli kriisiä tämän suhteen ei ole, myöhemmin pystyy tekemään migraation, joka oikeasti vaihtaa nämä muutostaulut käyttämään oikeita riviversioviittauksia: Mutta toteutuksellisesti se menee sen verran monimutkaiseksi, että 1.15.0:n menevään minimiratkaisuun sellaista ei kannattanut tehdä. Filtteröidään vaan tähän hätään julkaisulokia lukevissa hauissa versiotauluhauista pois kaikki …
> GVT-2796 Filter out design object versions from publication change queries

- infra/src/main/kotlin/fi/fta/geoviite/infra/geography/CoordinateTransformationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/Linking.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutKmPostService.kt
- infra/src/main/resources/i18n/translations.fi.json
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutKmPostServiceIT.kt
- ui/src/linking/linking-model.ts
- ui/src/tool-panel/km-post/dialog/km-post-edit-dialog-gk-location-section.tsx
- ui/src/tool-panel/km-post/dialog/km-post-edit-dialog.scss
- ui/src/tool-panel/km-post/dialog/km-post-edit-dialog.tsx
- ui/src/tool-panel/km-post/dialog/km-post-edit-store.ts
- ui/src/tool-panel/km-post/geometry-km-post-linking-infobox.tsx
- ui/src/tool-panel/km-post/km-post-infobox.scss
- ui/src/tool-panel/km-post/km-post-infobox.tsx
Täällä käytännössä toteutettu GK-kaistan automaattinen valinta linkitettäessä ja linkityksen purkaminen jos kilometripylvään sijaintia välppää käsin. Härmäisemmät UI-ongelmat, kuten paikannuspohjan sijainnin virheellisyyden näyttäminen GK:sta muuntamisen jälkeen jätetty myöhemmäksi, sillä ne vaativat oman mietintänsä.
> GVT-2824: GK-kaistan automaattinen valinta KM-pylvään linkityksessä ja linkityksen purku muutettaessa sijaintia käsin

- infra/src/main/kotlin/fi/fta/geoviite/infra/configuration/CacheConfiguration.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/configuration/CachePreloadScheduler.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/configuration/CachePreloadService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geocoding/Geocoding.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutAlignmentDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutAssetDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutKmPostDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/ReferenceLineDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/util/NamedParameterJdbcTemplateExternal.kt
- infra/src/main/resources/application-ext-api.yml
- infra/src/main/resources/application.yml
Testailin samalla myös vain official-main cachetusta jne, mutta ei niissä ole järkeä sillä konffaus lisää monimutkaisuutta ja hyöty jää olemattomaksi koska valtaosa datast on joka tapauksessa official-main. Tässä siis vain vähän lisää konfiguroitavuutta siihen mitä kakkuja esilämmitetään (planHeaders, geocodingContexts), tuo geokoodauskontekstien esilämmitys yleensä ottaen ja vähän detaljimpaa logitusta preloadista.
> GVT-2711 Make pre-caching more configurable + pre-cache geocoding contexts

- ui/src/environment/environment-info.ts
Without caching the environment was fetched again during every component render. The environment info should only be fetched once.
Liittyen siis https://github.com/finnishtransportagency/geoviite/pull/1475
> General: Add environment caching to UI

- infra/src/main/kotlin/fi/fta/geoviite/api/frameconverter/v1/FrameConverterControllerV1.kt
- infra/src/main/kotlin/fi/fta/geoviite/api/frameconverter/v1/FrameConverterServiceV1.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/common/KmNumber.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geocoding/Geocoding.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/util/Either.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/geocoding/GeocodingTest.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/TrackLayoutDomainTestData.kt
Konseptuaalisesti varsin yksinkertaista juttua, kaikki geokoodaukseen liittyvät asiat nyt vaan ryhmitellään niin, että asiat, joita tarvitsee tehdä vain kerran, tehdään vain kerran:
- validoinnin osana tehtävät ratanumerohaut tehdään vain kerran per eri ratanumeron nimi, muut osat rinnakkaistetaan
- pyynnöt ryhmitellään ratanumeroittain
- raiteelle suodatetaan pyynnöittäin, mitkä pyynnöt osuvat nimen/tyypin mukaan tälle raiteelle, ja haetaan osoitteet vain niille
- raiteelle osuvat geokoodauspyynnöt tehdään massana; raiteen alku- ja loppupisteen käänteinen geokoodaus on itse asiassa yksi kalleimmista kohdista koko haussa, eli on iso voitto tehdä ne vain kerran per pyyntöön liittyvä raide (ja jos niitä voisi tulevaisuudessa kakuttaa, se olisi vielä parempi)
Geokoodauksen itsensä laskentaan …
> GVT-2825 Optimize forward geocoding in VKM

- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/testgroup1/PublicationLogSearchTestUI.kt
- ui/src/publication/log/publication-log.tsx
The searchable date range was restricted to 180 days and the previous E2E test was using ranges longer than 180 days.
> GVT-2840 (part 2): Fix broken E2E, rename header to heading

- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/switches/SwitchLinkingService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutGeometry.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchService.kt
Pientä profilerin nokasta löytyneiden asioiden nysväysoptimointia pitkän raiteen tehtävälistan lataukseen, ei funktionaalisia muutoksia. Eikä meidän 16-ytimisillä tehokoneilla kyllä juuri perffimuutoksiakaan, koska vaikka nämä jutut nielivät itse asiassa aika paljon prosessoriaikaa, rinnakkaistus peittää vaikutuksen.
mapCopyOnWrite oli tarpeeton jäänne aiemmasta raiteiden vaihteiden uudelleenlinkityksen optimoinnista, joka oli sittemmin korvattu eri toteutuksella.
> General: Optimize validating track relinking

- infra/src/main/kotlin/fi/fta/geoviite/api/frameconverter/v1/FrameConverterServiceV1.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/configuration/CachePreloadScheduler.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/configuration/CachePreloadService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackSpatialCache.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/util/Functional.kt
Pääjuttu: muistinvarainen spatiaalinen (r-puu) cache sijaintiraiteiden haulle vkm:ään.
Samalla toteutett GVT-2834 ko. haun osalta, eli käsitellään vain IN_USE tilaisia raiteita. Tuon tiketin koko kuvaus on vähän laajempi joten loput tulee perästä.
> General: Optimize VKM reverse geocoding + implement GVT-2834

- infra/src/main/kotlin/fi/fta/geoviite/api/frameconverter/v1/FrameConverterServiceV1.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackSpatialCache.kt
- trackNumberService.mapById on hyvä massakutsuihin, mutta vähän ylimääräistä työtä, jos hakuja ropisee yksi kerrallaan
- LazyMappien käytöllä vältytään Springin transaktiohötäkän läpi kulkemisesta jokaista osumasegmenttiä kohden: Pitkällä raiteella pitkillä segmenteillä tällä ei ole juuri merkitystä, mutta Ilmalassa tämä muutos moninkertaistaa nopeuden
> GVT-2804 Optimize some more reverse geocoding cases

- infra/src/main/kotlin/fi/fta/geoviite/infra/geocoding/Geocoding.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/geocoding/GeocodingTest.kt
referenceLineAddresses:n haku räjähtää, jos loppuosoitteen metri olisi liian iso. On räjähtänyt jo pitkään, mutta nyt tämän tilan saa huomattavasti helpommin aikaan asettamalla km-pisteen sijainnin käsin.
Ratkaistaan jatkamalla historian kehitystä siihen suuntaan, että osittainkin toimiva geokoodauskonteksti on hyvä: Julkaisuvalidointi osaa kyllä näistä valittaa. Kaikki paitsi yksi kutsuja sattuivat olemaan jo valmiiksi sellaisessa muodossa, etteivät vaatineet ainuttakaan koodimuutosta, koska kontekstin itsensä muodostaminenhan on voinut jo pitempään epäonnistua.
> GVT-2857 Allow GeocodingContext#referenceLineAddresses to be null

- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/switches/SwitchFittingService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/switches/SwitchLinkingService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/linking/SwitchLinkingServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/linking/SwitchLinkingTest.kt
Päittäin linkitetyt YV-vaihteet ovat tähän asti uudelleenlinkityksessä saattaneet heitellä ärsyttävästi puolelle tai toiselle. Mahdollisena lääkkeenä ehdotettiin ohjata niitä vaihteen pisteytyksessä pysymään kiinni samoilla raiteilla kuin millä olivat jo aiemmin.
Ratkaisu vaikuttaisi ainakin minun testailun perusteella toimivan, tosin ärsyttävästi niin, että jostain syystä linkitys ei muutu ainoastaan näillä päittäin linkitetyillä tapauksilla, vaan monissa kohdin mikrometrien verran muillakin vaihteilla. Mutta sellaista kohtaa en löytänyt, jossa olisi mitään näkyvän kokoista muutosta muualla kuin siellä, missä pitikin olla.
> GVT-2853 Encourage switches to maintain their original links

- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/switches/SwitchFittingService.kt
Koodin puolesta hyvin selkeä (ja aika hölmö) regressio, jonka käytännön vaikutus kylläkin on todella pieni. Tässä siis haetaan vaihdelinkitykseen tulevista raiteista (joita haetaan vain kahden metrin säteeltä) pareja joilta hakea risteyskohtia: Jos jossain kohdassa risteää kolme tai ehkä neljä raidegeometriaa, ja geometriat on läheskään oikein, niin aikalailla riippumatta siitä, missä järjestyksessä raiteet satuttiin tälle funktiolle passaamaan, niistä kyllä löytyy jokin pari, jolla on järkevä risteyskohta. (Risteyskohdaksi kelpaa mikä tahansa kohta, jossa raiteet ovat enintään puolen metrin päässä toisistaan)
Mutta koska tämä bugi ei ole vielä mennyt tuotantoon, tuodaan nyt hotfix-haaraan ihan jotta vaihdelinkityksen toiminta pysyy vakaana huonompilaatuistenkin geometrioiden kanssa.
> GVT-2864 Pair up all tracks in pairsOf()

- ui/src/tool-panel/km-post/dialog/km-post-delete-confirmation-dialog.tsx
- ui/src/tool-panel/km-post/dialog/km-post-edit-dialog.tsx
- ui/src/tool-panel/location-track/dialog/location-track-edit-dialog.tsx
- ui/src/tool-panel/location-track/location-track-delete-confirmation-dialog.tsx
- ui/src/tool-panel/switch/dialog/switch-delete-confirmation-dialog.tsx
- ui/src/tool-panel/switch/dialog/switch-edit-dialog.tsx
- ui/src/tool-panel/track-number/dialog/track-number-delete-confirmation-dialog.tsx
- ui/src/tool-panel/track-number/dialog/track-number-edit-dialog.tsx
Tiketin kuvauksesta poiketen, puhuttiin Karin kanssa ja päätettiin vain disabloida deleted-tilan asetus new-draft olioilta sen sijaan että toteutettaisi kolmas erilainen delete-confirm dialogi. Samalla yhtenäistetty noita dialogeja toimimaan samalla tavoin eri tyyppien välillä. Muutokset itsessään näyttää pitkälti samoilta kaikissa.
> GVT-2751 Disallow deleted-state for new-draft items + unify edit dialogs

- ui/src/infra-model/list/infra-model-search-result-row.tsx
- ui/src/infra-model/list/infra-model-search-result.tsx
- ui/src/tool-bar/tool-bar.tsx
- ui/src/tool-bar/workspace-selection.tsx
- ui/src/vayla-design-lib/closeable-modal/closeable-modal.tsx
- ui/src/vayla-design-lib/datepicker/datepicker.tsx
- ui/src/vayla-design-lib/dropdown/dropdown.tsx
- ui/src/vayla-design-lib/icon/Icon.tsx
- ui/src/vayla-design-lib/text-field/text-field.tsx
Täällä pääasiassa pyritty poistamaan frontilta klikkieventtien `stopPropagation()`-kutsuja, jotta klikit toimisivat niinkuin niiden olettaisi toimivan. Ihan kaikkia en saanut poistettua, mutta suurimman osan. Lisäksi korjattu työtilan valinta -dropdownin jääminen näkyviin uuden työtilan luontidialogin ollessa näkyvissä.
> GVT-2815 & GVT-2749: Dropdown-parannuksia ja `stopPropagation()`-poistoja

- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/LinkingController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/switches/SwitchFittingService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/switches/SwitchLinkingService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/switches/SwitchTrackRelinkingValidationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/math/BoundingBox.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackSpatialCache.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/linking/SwitchLinkingServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/math/BoundingBoxTest.kt
Isohko(?) määrä muuttunutta koodia, mutta testattu ajamalla tämä validaatio kaikille paikannuspohjan raiteille ja toteamalla, että tulos on bitilleen sama.
Isoimmat muutosteemat:
- Koko validaatio siirtyi omaan tiedostoonsa, SwitchLinkingService kun tuntuu olevan sen verran iso kokonaisuus että se poikii näitä lapsukaisia. Koodi on suurelta osin kokonaan uutta, toimintaperiaatteet kylläkin korkealla tasolla samat kuin ennen.
- Vaihdelinkityksen raiteiden sijaintihaut tehdään nyt spatial cachesta
- Linkityksessä useita optimointeja, osa yleiskäyttöisiä (raiteiden risteyskohtien etsimisen nopeutus boundingboxeilla pönkittämällä), osa mikro-optimointeja juuri pitkän raiteen tehtävälistan laskemiseen
> GVT-2852 Optimize and separate out track switch relinking validation

- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/Linking.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/LinkingService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutKmPostDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutKmPostService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/PlanLayoutTransformation.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/TrackLayout.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/geometry/PlanLayoutCacheIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/integration/AddressChangesServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/linking/LinkingServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutKmPostServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/TrackLayoutDBTestData.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/TrackLayoutDomainTestData.kt
- ui/src/data-products/kilometer-lengths/kilometer-lengths-table-item.tsx
- ui/src/data-products/kilometer-lengths/kilometer-lengths-table.tsx
- ui/src/geoviite-design-lib/demo/examples/badge-examples.tsx
- ui/src/linking/linking-model.ts
- ui/src/tool-panel/km-post/dialog/km-post-edit-dialog-gk-location-section.tsx
- ui/src/tool-panel/km-post/dialog/km-post-edit-store.ts
- ui/src/tool-panel/km-post/geometry-km-post-linking-infobox.tsx
- ui/src/tool-panel/km-post/km-post-infobox.tsx
- ui/src/track-layout/track-layout-model.tsx
Täällä korjauksia pääasiassa kilometripylvään muokkausdialogin "Sijainti vahvistettu" -radionappeihin. Aiemmin radionapit elivät hieman omaa elämäänsä, ja niistä saattoi mm. kadota arvo kokonaan joissain tietyissä tilanteissa. Nyt näytetään aina joku arvo (käytännössä jos arvo löytyy kannasta näytetään se, muuten defaultataan "Ei vahvistettu":un.)
Tuo paljastikin sitten taas kaninkolon GK-sijainneista ja kilometripylväiden tietotyypeistä - aiempi flätti rakenne jossa kaikki GK-kentät olivat vain fieldeinä itse kilometripylväällä on nyt korvattu erillisellä alitietotyypillä, joka kuvastaa kilometripylvään GK-sijaintia.
> GVT-2865 Part 1: KM-pylvään sijainnin vahvistus käyttäytyy oudosti manuaalisessa asetuksessa

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/PlanLayoutTransformation.kt
Osassa suunnitelmista (useissa, jotka nimen mukaan on "muutettu") tulee ensimmäisenä kilometritolppana outous, jolla onkin tavallisen nullin sijasta sijaintina (0, 0). Tehdään perinteiset ATK-tepposet ja hämmennetään tätä nolla-nulli-soppaa lisää käsittämällä vaan nämäkin sijainnittomiksi, jotta saadaan nämäkin suunnitelmat piirtymään kartalla.
> GVT-2883 Treat zero geometry km post locations as null

- infra/src/main/kotlin/fi/fta/geoviite/infra/configuration/RequestFilter.kt
- infra/src/main/resources/application.yml
Aiemmin sama toiminnallisuus on ollut ympäristökonffissa (cloudfront), ja nyt kun ympäristö yksinkertaistuu, niin tällaista pikkutoiminnallisuutta päätyy monoliitin puolelle
> GVT-2577 (part 5): Add root path redirect & automatic index.html serving

- infra/src/main/kotlin/fi/fta/geoviite/infra/geocoding/Geocoding.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/TrackMeterHeights.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/util/List.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/util/ListTest.kt
Tämä funktio oli aikoinaan Geoviitteen huonous-aatelia, nyt räjäytetty selkeämmin nimetyiksi ja kommentoiduiksi kokonaisuuksiksi. Ei funktionaalisia muutoksia, mutta optimointimuutoksia kyllä: Laskutoimituksia tehdään nyt huomattavasti tarkemmin niin, että pyydetyn ratakilometrivälin ulkopuoliset asiat ja raiteelle osumattomat asiat suodatetaan aikaisin pois, ja geokoodaukset pyritään tekemään yhdessä isossa getTrackLocations()-pompsissa. Aiemmalle rinnakkaistukselle ei näin ole enää tarvetta.
> General: Refactor and optimize collectTrackMeterHeights

- ui/src/tool-bar/tool-bar.scss
- ui/src/tool-bar/tool-bar.tsx
Täällä ongelmana oli, että kaikki `<ToolBar>`:in `<TabHeader>`:it flexbox-itemeinä laskivat korkeutensa korkeimman tabheaderin mukaan. Suunnitelmatilan valinta-dropdownin kadotessa näkyvistä `<TabHeader>`:eilla ei ole enää syytä olla yhtä korkeita kuin jos se olisi näkyvissä, mutta itse `<ToolBar>`:in korkeus pysyi (on joko määritetty staattisesti tai lasketaan hakulaatikon perusteella, en tarkastanut.) Tämä näkyi käytännössä tuona tiketin mainitsemana välinä. Jumppasin nyt toolbarin tabheaderien sisällöille minimikorkeuden ja yhdenmukaistin muutenkin tabien sisältöjä -> nyt joka näkymässä tabien pitäisi olla yhtä korkeita, ja suunnitelmatilan valintatabi on nyt tekniseltä rakenteeltaan vähemmän special snowflake.
> GVT-2874: Virasto- ja konsulttikäyttäjille näytetään yläpalkissa ekstraväli

- ui/src/tool-panel/infobox/infobox-field.tsx
- ui/src/tool-panel/infobox/infobox.module.scss
- ui/src/tool-panel/infobox/infobox.tsx
- ui/src/tool-panel/km-post/km-post-infobox.tsx
- ui/src/tool-panel/location-track/location-track-basic-info-infobox.tsx
- ui/src/tool-panel/switch/switch-infobox.tsx
- ui/src/tool-panel/track-number/track-number-infobox.tsx
Täällä siis poistettu kynäikonit infobokseista yksittäisten kenttien yhteydestä ja korvattu ne infoboksin headerissa asuvalla kynäikonilla
> GVT-2813: Kynäikonien karsinta

- infra/src/main/kotlin/fi/fta/geoviite/infra/projektivelho/PVClient.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/testing/GeoviiteTestingController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutContextData.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutDesignDao.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/ReferenceLineServiceIT.kt
The Kotlin standard error-function does not support using lazily-evaluated values. These kinds of blocks were logged as "() -> String)" instead of the actual error message.
> GVT-2897: Fix improper usage of error-blocks

- .env
- Dockerfile
These images are synchronized from the public and default Docker repo, but AWS has softer ratelimits.
> General: Use public AWS ECR images, bump Selenium image version

- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationDao.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationServiceIT.kt
Koodista bongattu epäyhdenmukaisuus ID-hässäkkää toteutettaessa. Ei funktionaalista vaikutusta, koska suunnitelmien julkaisulokeja ei vielä ole, mutta jos olisi, vaikutus olisi, että jos suunnitelmassa julkaistaan jokin jonkin vaihteen oma muutos, mutta samassa suunnitelmassa ei ole olemassa muokattua versiota jostain sijaintiraiteesta, johon vaihde on linkitetty, tästä vaihteen muutoksesta ei tulisi ratanumerotietoja julkaisulokiin.
> GVT-2896 Fix location track lookup in saveSwitchChanges

- ui/webpack.config.js
Korjaa nillityksen:
```
DeprecationWarning: Invalid proxy configuration:
{
"context": "/redirect/projektivelho/files",
"logLevel": "debug",
"changeOrigin": true
}
The use of proxy object notation as proxy routes has been removed.
```
> GVT-2901: Fix deprecation warning

- infra/src/main/kotlin/fi/fta/geoviite/infra/integration/IntegrationModels.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/ratko/RatkoClient.kt
- infra/src/main/resources/db/migration/prod/V98__add_fetch_ratko_push_error_operation.sql
- infra/src/main/resources/i18n/translations.fi.json
- ui/src/ratko/ratko-model.ts
- ui/src/ratko/ratko-push-error.tsx
- ui/src/utils/enum-localization-utils.ts
Täällä käytännössä lisätty virheidenkäsittely Ratko-puskussa tehtäville Ratkon assettien hauille. Testasin tämän käsin (sikäli kun pystyin, en koittanut saada mitään oikeaa Ratko-ympäristöä palauttamaan virhettä.) Automaattitestit tämä kuitenkin kaipaisi, ja `FakeRatko`:lla ne pitäisi kyllä pystyä tekemään - nyt vaan loppui vähän aika. Jäävät työlistalle loman jälkeiseen maailmaan
> GVT-2892: Ratko-puskun virhekäsittely ei huomioi hauissa aiheutuvia virheitä

- infra/src/main/resources/db/migration/prod/V99_03__redo_id_structure_for_track_number.sql
- infra/src/main/resources/db/migration/prod/V99_07__redo_id_structure_for_location_track.sql
Draftissa olevat ratanumerot rikkoivat migran, koska se loi vahingossa niiden foreign key-tarkistuksen id-tauluun liian aikaisin (ts. ennen iideitten uudelleenkirjoittamista).
> GVT-2867 Create foreign keys to ID tables from layout asset tables more consistently

- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationLogService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/ratko/RatkoClient.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/ratko/RatkoLocalService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/ratko/RatkoService.kt
- infra/src/main/resources/i18n/translations.fi.json
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationLogServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ratko/RatkoClientIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/testgroup1/FrontPageTestUI.kt
- ui/src/publication/card/publication-card.tsx
- ui/src/publication/publication-api.ts
- ui/src/ratko/ratko-api.ts
- ui/src/tool-panel/location-track/dialog/location-track-ratko-push-dialog.tsx
Tällä pullarilla tehty käytännössä kaksi täysin erillistä asiaa:
* Etusivun julkaisulistaukseen on toteutettu parempi sivutus. Bäkkäriltä palautuu nyt julkaisujen oikea kokonaismäärä
* Korjattu edellisten korjausten jälkeen failaava E2E-testi. Failuret johtuivat Ratkon statuksen huonosta tarkastelusta
> General: Korjauksia etusivun julkaisulistaukseen ja failaaviin E2E-testeihin

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutAlignmentDao.kt
Putsailen pikkuhiljaa näitä hakuja, joita piti aiemmin tehdä aivan yltiömonimutkaisessa muodossa, mutta jotka ID-remontin jälkeen (tai itse asiassa varmaan lähinnä in_layout_context-funktioiden remontin jälkeen) postgressi osaa ymmärtää oikein hyvin ilman hämäriä pyörittelyjä. Tämä muoto näyttäisi olevan ainakin kokeilemassani tapauksessa (boksi Ilmalan ratapihan ympärillä) myös nyt hieman nopeampi kuin monimutkaisempi muoto.
> General: Edit fetchProfileInfoForSegmentsInBoundingBox back into simple form

- infra/src/main/resources/i18n/translations.fi.json
- ui/src/tool-panel/geometry-alignment/geometry-alignment-linking-infobox.tsx
- ui/src/tool-panel/km-post/geometry-km-post-linking-infobox.tsx
- ui/src/tool-panel/switch/geometry-switch-linking-initiation.tsx
- ui/src/tool-panel/switch/switch-infobox.tsx
- ui/src/tool-panel/track-number/track-number-infobox.tsx
Tällä pullarilla käyty läpi kaikki paikat missä toolpanelissa on linkitysnappuloita tai geometrian muokkauksia ja pakotettu ne disabloiduiksi nykytilassa. Tiketin yhteydessä on myös ollut puhe siitä, että layoutcontext-tabeihin voisi tehdä jonkinlaisen takalaudan sille, että jos jotenkin ulkoisesti onnistutaan vaihtamaan eri kontekstien välillä. Katson tätä myöhemmällä tiketillä
> GVT-2912: Loppujenkin linkitysten disablointi nykytilassa

- ui/src/linking/linking-store.ts
- ui/src/tool-panel/location-track/split-store.ts
- ui/src/track-layout/track-layout-slice.ts
Päädyin nyt vaan lisäämään nuo asettamiset käsin kaikkialle missä niitä tehdään, mutta en ole tuohon ratkaisuun mitenkään tyytyväinen. Problematiikka on siis ollut siinä, että frontilla on erikseen tallessa `layoutContext` sekä tieto siitä mikä tabi on valittuna (`layoutContextMode`, joka kertoo käytännössä mikä karttanäkymän vasemman yläkulman tabi on valittuna.) Näiden tarvii olla jotenkin eroteltuna käytännössä pakosta, sillä vaikka `LayoutContext` pystyy kuvaamaan kaikki validit branch-publicationState-combot joissa voidaan tehdä muutoksia, sillä on käytännössä mahdotonta kuvata tilannetta jossa ollaan suunnitelmatilassa mutta suunnitelmaa ei ole vielä valittu. Ideaalitilanteessa näitä haluttaisiin varmaankin käyttää siten, että aina kun reduxiin tallennettu `layoutContext` muuttuu, …
> GVT-2912 (Part 2): Varmista että kaikissa frontin kontekstisiirtymissä vaihdetaan myös `layoutContextMode`

- ui/src/tool-panel/km-post/dialog/km-post-edit-dialog-gk-location-section.tsx
- ui/src/tool-panel/km-post/dialog/km-post-edit-dialog.tsx
- ui/src/tool-panel/km-post/km-post-infobox.tsx
Koordinaatistomuunnosinformaatio näytettiin edit-dialogissa aiemmin siis pelkästään linkityksen yhteydessä. Nyt se näytetään myös kun ollaan muokkaamassa olemassaolevaa kilometripylvästä jonka GK-sijainti on muunnettu
> GVT-2909: Muunnetun koordinaatiston näyttäminen olemassaolevalla km-pylväällä

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutKmPostDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/ReferenceLineDao.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutAssetServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberServiceIT.kt
Suosittelen tarkastelemaan kommiteittain.
- Fix has_official lookup for reference lines: Ilmiömäisen simppeli logiikkabugi, yksi tarkistus vaan vaati että pitää olla jossain designissa, kun olisi pitänyt vaatia että ei ole missään designissa
- Fix track number reference_line_id lookup: Pituusmittauslinjojen reference_line_id-tieto tuli vähän väärällä tavalla. Oikealla tavalla haku on varsin yksinkertainen, ja yksinkertaistaa hakuja vähän rakenteeltaankin, kun mahdollisuus, että pituusmittauslinjarivejä on useita, koskee niissä enää ainoastaan reference_line_id:n hakuun
- Fix has_official fetches causing duplicate rows: Näissä hauissa oli jäljellä mahdollisuus, että jos on sekä design-official että main-official-rivi, joini aiheuttaa hakutulosten duplikaatiota. Korjattu samalla tavalla …
> GVT-2914 Useita korjauksia ID-remontin regressioihin

- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutContextData.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationDaoIT.kt
Perinteinen versiohämmennys. Näiltä pitäisi onneksi alkaa olla nyt tästä asti aika helppoa välttyä, kun in_layout_context-funktioiden kutsumisesta on tullut riittävän kevyttä, eikä tarvitse enää tehdä niinkään paljoa hämäriä joineja kuin ennen, mutta kyllä näitä ID-remontin kokoisesta myrskystä tulee.
"not materialized" haun CTE:ssä tarkoittaa, että postgressin hakumoottori vaan inlinettää "lt":n määritelmän jokaiseen paikkaan, missä sitä haussa käytetään, ja sitten tekee hakuoptimoinnit ilmaan mitään tietoa että näillä eri käyttöpaikoilla oli mitään yhteistä. Se sattuu tässä tapauksessa olemaan oikein, koska koko sijaintiraidetaulussa on tuhansia rivejä, mutta niissä kolmessa paikassa, joissa lt:tä käytetään, on kaikissa aika tiukka suodatusehto, ts. käytännössä haussa päädytään tekemään …
> GVT-2910 Fix version confusion in fetchLinkedLocationTracks

- infra/build.gradle.kts
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryValidation.kt
Mukavan yllättävän vähän mitään rikkova tai oikeastaan juuri mihinkään vaikuttava juttu. Päämuutos on, että K2-kääntäjä on ainakin mainoslauseiden perusteella selvästi aiempaa nopeampi.
Versiopäivityksestä ei tullut käännösvirheitä, mutta varoituksia tuli, ne korjattu myös. Koodimuutoksen aiheuttava uusi varoitus oli https://youtrack.jetbrains.com/issue/KT-57417 , ts. kääntäjä ei enää suostu varoituksetta olettamaan, etteikö tuolla radiusStartin tai radiusEndin delegoinnin takana olisi jotain pahantahtoista hähmää joka päättääkin palauttaa ensiksi ei-nullia ja sitten nullia: Korjataan tavalliseen tapaan kysymällä niitä vain kerran.
> General: Bump Kotlin version to 2.0.20

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutAlignmentDao.kt
Satunnainen testifaili onneksi löysi tämän sorttauksen, joka jäi vahingossa jätettyä pois hakua yksinkertaistaessa.
> General: Restore sorting in fetchProfileInfoForSegmentsInBoundingBox

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutContextData.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutKmPostDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/ReferenceLineDao.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberServiceIT.kt
ID-remontista sivuun jäänyt detalji.
Tämän myötä myös suunnitelmamuokkauksen mainissa-julkaisun yhteydessä tapahtuva design-officialin poisto alkaa oikeasti toimia, ja pari testiä, jotka olettivat, että sitä ei tapahdu, menivät siitä rikki. Jätin tähän hätään niistä pois eksplisiittisen kannanoton siitä, mitä pitää oikeasti tapahtua: Olen tällä hetkellä sillä kannalla, että se poistaminen on oikein ja kannattaa tehdä, mutta näkyvyys siihen kokonaisuuteen on vielä hieman heikko.
> General: Remember to actually save origin_design_id

- infra/src/main/kotlin/fi/fta/geoviite/infra/geocoding/Geocoding.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/geocoding/GeocodingTest.kt
Rempatessa m-arvoja topolgiajutun yhteydessä huomasin issuen osoitepisteiden luonnissa koko raiteen matkalta. Meillä oli aiemmin oliotason alignment validointi joka esti zigzagit geometrioissa mutta se poistui jossain kohtaa matkalla, en muista tarkalleen miksi. Nyt tietyt testit tekee niitä  ja toimi oikeastaan lähinnä sattumalta.
> General: Fix full locationtrack geocoding with zig-zag geometries

- infra/src/main/resources/db/migration/prod/V99_10__redo_id_structure_for_switch_version.sql
Fiksi ID-remonttiin, vaihdepisteiden versiotaulun migraatioon. Pullaroin tämän kylläkin nyt, mutta taidan vielä katella läpi kaikki paikannuspohjan oliotyypit että jokaisesta saa migroitua luonnokset oikein, ennen kuin rikon tällä devin.
> GVT-2925 Fix migrating draft switches

- infra/src/main/kotlin/fi/fta/geoviite/infra/integration/CalculatedChangesService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/Publication.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationLogService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/ratko/model/RatkoCommonModel.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutAssetService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutContextData.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutDesign.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutDesignDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutDesignService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/ReferenceLineService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/util/ResultSetExternal.kt
- infra/src/main/resources/db/migration/prod/V101__add_design_ratko_push_support.sql
- infra/src/test/kotlin/fi/fta/geoviite/infra/integration/RatkoPushDaoIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/linking/LinkingDomainTestData.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationDaoIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationTestSupportService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ratko/FakeRatko.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ratko/RatkoServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/split/SplitDaoIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutAssetServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutDesignServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/TrackLayoutDomainTestData.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/testgroup1/FrontPageTestUI.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/testgroup1/PublicationLogSearchTestUI.kt
Hieman monen jutun pullari, toteutussuunta kun yhä elää designien Ratko-puskua tehdessä.
Tietomalliin lisätään:
- designeille uusi ratko_id-tieto, jota ei vielä osata varsinaisesti hakea Ratkosta, mutta onpahan olemassa
- julkaisuille julkaisusyy (olemassaolevilla kaikilla että oli käyttäjän käsin tekemä julkaisu), ja suunnitelmajulkaisuille designin versio
Funktionaaliset muutokset lähtee käytännössä siitä, kun tehdään muutos suunnitelmaan (joko johonkin suunnitelman tietoon, tai suunnitelman tilaan, ml. poisto eli deleted-tilaan asettaminen). Tällöin:
- Jos suunnitelmasta on tehty julkaisu: Tehdään tyhjä julkaisu, jossa tietona vaan että suunnitelma (nykyversiollaan) on muuttunut. Tämä siksi, että Ratkoon päätyy tieto suunnitelmaan tehdystä tiedosta, vaikka sen sisältöä ei välttämättä …
> GVT-2726 Ratko push for designs, part 1

- infra/src/main/kotlin/fi/fta/geoviite/infra/integration/CalculatedChangesService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/Publication.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/integration/CalculatedChangesServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationRatkoIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/TrackLayoutDBTestData.kt
Suunnitelmatilaisuus voi vaikuttaa laskennallisten muutosten hakuun kahdella tavalla:
- Suunnitelman julkaisu voi aiheuttaa laskennallisia muutoksia johonkin mainin olioon, jota ei ole julkaistu suunnitelmassa. Tällöin sille haetaan suunnitelman OID, ja tallennetaan julkaisutauluun muutos tällä OIDilla mutta mainin olioversiolla. Olion suunnitelma-OIDin hakeminen tarkoittaa käytännössä, että tästä lähtien tämän olion tila tässä suunnitelmassa Ratkossa on asia, jota pitää Geoviitteen hallita.
- Mainin julkaisu voi vaiheuttaa laskennallisia muutoksia johonkin olioon, jonka tila suunnitelmassa on viety Ratkoon. Tällöin tallennetaan suunnitelman julkaisu, jossa kirjataan suunnitelmaan periytyneet muutokset; nämä lasketaan kontekstissa, joka on muuten suunnitelman virallinen konteksti, mutta …
> GVT-2726 Main-to-design and design-to-self inheritance for calculated changes

- ui/src/geoviite-design-lib/dialog/dialog.tsx
GVT-2951 toteutuksessa esiintynyt juttu, jonka ajattelin heittää omana ehdotuksenaan, koska en ole ihan varma, onko tästä odotettavissa outouksia.
Kyseisessä taskissa tuli ongelmia siitä, että:
- Lähtötilassa fokus vaihteiden muokkauslomakkeessa on nimikentässä, joka on tyhjä
- Tyhjästä nimikentästä poistuttaessa (onBlur) se otetaan validoitavaksi, ja tyhjästä nimestähän tulee virheitä
- Virheet kasvattavat dialogin korkeutta
- Tämä layoutEffecti keskittää dialogin uuden koon perusteella, ja siksi siirtää sen yläpäätä siksi vähän ylemmäksi
- ... mutta tässä tapauksessa syy miksi kentästä poistuttiin oli, että käyttäjä painoi OIDin "Aseta nyt"-nappia... mutta nyt tämä nappi siirtyykin klikin aikana ylemmäs pois hiiren kursorin alta, ja siksi sen onClick()ia ei kutsutakaan.
Ajattelin, että …
> GVT-2951 Only center dialogs initially upon display

- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/switches/SwitchLinking.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationValidation.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationValidationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/ratko/ExternalIdDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitch.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/PlanLayoutTransformation.kt
- infra/src/main/resources/db/migration/prod/V104__add_draft_oid_to_switch.sql
- infra/src/main/resources/i18n/translations.fi.json
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationLogServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationRatkoIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationValidationServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/TrackLayoutDomainTestData.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/testdata/CommonTestData.kt
- ui/src/linking/linking-model.ts
- ui/src/preview/preview-view.tsx
- ui/src/tool-panel/switch/dialog/switch-draft-oid-field.tsx
- ui/src/tool-panel/switch/dialog/switch-edit-dialog.scss
- ui/src/tool-panel/switch/dialog/switch-edit-dialog.tsx
- ui/src/track-layout/layout-switch-api.ts
- ui/src/track-layout/track-layout-model.tsx
- ui/src/utils/react-utils.tsx
Vaihteille lisätään draft_oid-tieto, jolla käyttäjä voi viitata Ratkossa-mutta-ei-Geoviitteessä olevaan vaihteeseen suoraan. Ei juuri yllätyksiä taskin https://extranet.vayla.fi/jira/browse/GVT-2951 speksiin verrattuna, paitsi että: 
- Tyhjä draftOid käyttöliittymällä tulkitaan tarkoituksella nulliksi ja siten hyväksyttäväksi arvoksi
- draftOidin olemassaolo Ratkossa tarkistetaan erikseen vielä julkaisua ennen tapahtuvassa OIDien haun yhteydessä (mutta normaalitoimilla käyttäjän ei pitäisi pystyä saamaan sillä julkaisua rikki, koska käli sallii vain Ratkossa olemassaolevien draft-oidien asettamisen)
> GVT-2951 Add draft OID to switches

- infra/src/main/resources/db/migration/prod/V99_02__redo_id_structure_for_track_number_version.sql
- infra/src/main/resources/db/migration/prod/V99_04__redo_id_structure_for_reference_line_version.sql
- infra/src/main/resources/db/migration/prod/V99_06__redo_id_structure_for_location_track_version.sql
- infra/src/main/resources/db/migration/prod/V99_08__redo_id_structure_for_switch_joint_version.sql
- infra/src/main/resources/db/migration/prod/V99_10__redo_id_structure_for_switch_version.sql
- infra/src/main/resources/db/migration/prod/V99_12__redo_id_structure_for_km_post_version.sql
ID-remontin versiohistorioiden uudelleenlaskennat tehdään tauluittain yksittäisillä update-komennoilla, eli sellaista ongelmaa niissä ei postgressissa ajettuna voi olla, että komento semanttisella tasolla sotkeutuisi jalkoihinsa rivejä päivittäessään (kts. klassinen Halloween problem); mutta se on mahdollista, että riippuen siitä, missä järjestyksessä päivitys sattuu rivejä käsittelemään, taulu sisältää väliaikaisesti useamman rivin samalla avaimella.
Tämä ongelma sattui näkymään switch_joint_version-taulussa, mutta ihan yhtä hyvinhän jokaisella oliotyypillä on mahdollista, että vaikkapa aiemmin oli olemassa jostain oliosta main_officialin versiot 3, 4, ja 5, ja päivityksen jälkeen 1, 2, ja 3; ja päivitys sattuu trollaamaan päivittämällä ensimmäiseksi alkuperäisen version 5 versioksi 3, …
> GVT-2957 Defer recreating primary keys after asset re-versioning

- ui/src/publication/split/split-details-dialog.tsx
Näille oli näköjään aiemmin ollut erillistä mäppäystä, käännösten enum-rakenteen muutoksen jälkeen aiempi menettely ei enää toiminut.
> GVT-2956: Fix missing split translations

- ui/src/publication/card/publication-card.tsx
- ui/src/publication/card/publication-list-row.tsx
- ui/src/publication/publication-model.ts
- ui/src/ratko/ratko-push-error.tsx
Main-branchin julkaisukortin linkit olivat kadonneet ja suunnitelmajulkaisujen kortti heitti bäkkärivirhettä tietyillä käyttäjärooleilla. Ne korjattu täällä. En tosin korjannut tuota suunnitelajulkaisujen korttien bäkkärivirhettä mitenkään eksplisiittisesti -- tuntui siltä, että se vain korjautui tuon linkkikorjauksen yhteydessä ainakin lokaalisti. Testataan main-mergen jälkeen miten oikeasti kävi
> GVT-2956 & GVT-2959: Etusivun julkaisukorttien korjaus

- ui/src/vayla-design-lib/demo/examples/menu-example.tsx
Probably an earlier oversight which caused the cloud build to fail.
> General: Fix broken ui build

- infra/build.gradle.kts
- infra/src/main/kotlin/fi/fta/geoviite/infra/logging/LoggerExternal.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/integration/ThreadContextMiddlewareIT.kt
Additionally some tests were added
> GVT-2893 (part 2): Fix ThreadContext not being cleared/restored correctly in reactive context

- infra/src/main/kotlin/fi/fta/geoviite/infra/integration/CalculatedChangesService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationUtils.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationValidationService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/integration/CalculatedChangesServiceIT.kt
Palautetaan PublicationValidationService#createValidationContext privaatiksi, koska niinhän se juurikin on, että validointikonteksti ei satu olemaan juuri oikealla tavalla toimiva olio tätä laskutoimitusta varten: Sehän kun räjäyttäisi tämän koodin, jos yritettäisiin laskea, mitä muutoksia tulee suunnitelmassa tehdyn olion luomisen hylkäämisestä.
Muuten siis sama logiikka kuin mitä aiemminkin yritin: Ratko-integraatio lähettää kaikki vaihteet, jotka ovat linkitetty samalle ratakilometrille kuin mikä tahansa muutos raiteella, vaikka vaihteella itsellään ei olisi varsinaisesti muuttunut mitään; ja koska päätös siitä, mille olioille haetaan suunnitelman OIDit, tehdään jo tässä julkaisun yhteydessä, tässä pitää myös tietää osata hakea näille vaihteille OIDit.
> GVT-2726 Fix detecting changed switches from same km location track changes

- ui/package-lock.json
- ui/package.json
- ui/webpack.config.js
SWC (https://swc.rs/) is a drop-in replacement for typescript transpiling, while being a lot faster (2-3x speedup on my machine in this codebase compared to normal ts-transpiler).
> General: Use SWC as the TypeScript loader in webpack

- infra/src/main/resources/i18n/translations.fi.json
- ui/src/geoviite-design-lib/km-post/km-post-badge.tsx
- ui/src/geoviite-design-lib/linking-status/linking-status-label.scss
- ui/src/geoviite-design-lib/linking-status/linking-status-label.tsx
- ui/src/tool-panel/geometry-alignment/geometry-alignment-infobox.scss
- ui/src/tool-panel/geometry-alignment/geometry-alignment-linking-infobox.tsx
- ui/src/tool-panel/km-post/geometry-km-post-linking-infobox.scss
- ui/src/tool-panel/km-post/geometry-km-post-linking-infobox.tsx
Alkuperäisellä tiketillä oltiin mainittu seuraavat bugit, jotka korjattu täällä:
- Listaus näyttää myös poistettuja layout-puolen km-pylväitä (enää näytetään vain olemassaolevat)
- Jos sama geometriapuolen km-pylväs on linkitetty useampaan layout-puolen kilometripylvääseen, kilometripylväät piirtyvät kiinni toisiinsa (piirtyvät nyt gridiin samoin kuin layout-puolen kilometripylväät vasemmassa palkissa)
Tämän lisäksi huomattu muutama erillinen issue, jotka korjattu:
- Badgeista ei pystynyt navigoimaan linkitettyyn kilometripylvääseen klikkaamalla badgea (nyt pystyy)
- KM-pylvään Linkitetty-kentän arvot oli kirjoitettu aiemmin all-capseilla ("KYLLÄ"/"EI"), kun muualla ne olivat kirjoitettu "Kyllä"/"Ei" (yhdistetty "Kyllä"/"Ei"-muotoon)
- Sekä geometrian kilometripylväiden että alignmentien …
> GVT-2746: Bugeja raidegeometrian kilometripylvään infoboksissa

- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/pagemodel/map/SelectionPanelElement.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/testgroup2/LinkingTestUI.kt
- ui/src/geoviite-design-lib/km-post/km-post-badge.tsx
KM-badgevälppäys aiheutti parin E2E-testin failaamisen. Korjattu täällä
> General: E2E-testien korjaus

- ui/package-lock.json
- ui/package.json
- ui/webpack.config.js
The swc-loader only transpiles the typescript code that it touches. This means that typescript code was not typechecked during build.
It is possible to use eg. https://www.npmjs.com/package/fork-ts-checker-webpack-plugin to also type-check the typescript code while using SWC. This plugin was tested and it works, but the performance improvements are then relatively marginal compared to just using the earlier ts-loader (swc-loader+fork-ts-checker is ~15% faster in entire ui-build compared to ts-loader, few seconds). 
=> Revert back to just using ts-loader, at least for now
> General: Revert swc-loader back to ts-loader

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchDao.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchDaoIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchServiceIT.kt
En lähde hotfiksissä poistamaan näitä ajanhetkihakufunktioita (switch_at(), location_track_at()), ja ehkä voisi miettiä, pystyisikö ne korjaamaan kohtuudella vaikka jollakin konteksti+ajanhetki-hauilla, mutta siis pelkässä ajanhetkihaussahan ei ole ID-remontin jälkeen ikinä mitään järkeä. Tässä kommitissa poistuvatkin niiden viimeiset varsinaiset käytöt: Loput mitä koodikannasta löytyy, ovat migraatiohistoriassa.
> GVT-2976 Fix findLocationTracksLinkedToSwitchAtMoment draft handling

- infra/src/main/resources/db/migration/prod/V110_recreate_timed_fetch_functions.sql
Nämä funktiot näemmä tosiaan toimii aikalailla suoriltaan niin kuin pitäisikin, olisi siis voinut uudelleenluoda jo ID-remontin yhteydessä.
Sillä tavalla nämä kylläkin sopivat huonosti yhteen uuden rakenteen ja Geoviitteen kehityshistorian kanssa, että jos hakee luonnostilaisia olioita, niin näistä funktioista tulee nyt ulos historian aikana (ennen ID-remonttia) Geoviitteessä luodut ja julkaistut oliot: Niiden viimeinen luonnosversio ennen julkaisuahan muuttui suoraan viralliseksi versioksi, eli niistä ei tullut deleted-lipullisia rivejä versiotauluun.
(Poistojen keksiminen versiotauluun olisi tietenkin ihan täysin mahdollista tehdä vieläkin, mutta tuskin maksaa vaivaa.)
> GVT-2976 Recreate timed fetch functions

- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/switches/SwitchLinkingService.kt
- infra/src/main/resources/i18n/translations.fi.json
- infra/src/test/kotlin/fi/fta/geoviite/infra/linking/switches/SwitchLinkingServiceIT.kt
- ui/src/common/common-model.ts
- ui/src/linking/linking-model.ts
- ui/src/tool-panel/geometry-alignment/geometry-alignment-linking-infobox.tsx
- ui/src/tool-panel/infobox/infobox.tsx
- ui/src/tool-panel/location-track/location-track-basic-info-infobox.tsx
- ui/src/tool-panel/location-track/location-track-infobox.tsx
- ui/src/tool-panel/location-track/location-track-location-infobox.tsx
- ui/src/tool-panel/switch/geometry-switch-linking-infobox.tsx
- ui/src/tool-panel/switch/switch-infobox.tsx
- ui/src/tool-panel/switch/switch-joint-infobox.tsx
- ui/src/tool-panel/tool-panel.tsx
- ui/src/tool-panel/track-number/track-number-infobox.tsx
- ui/src/track-layout/layout-map-api.ts
- ui/src/track-layout/track-layout-model.tsx
Perus pikkutiketin kaninkolopullari. Tiketin alkuperäinen pointti oli se, että on mahdollista linkittää uudestaan vaihde, joka on jo poistettu. Tuo on estetty tällä pullarilla sekä frontin että bäkkärin puolelta, mutta sen lisäksi liitännäisinä ja liitännäisten liitännäisinä täällä on tehty seuraavat jutut:
* Disabloitu vaihteen, sijaintiraiteen ja pituusmittauslinjan muokkausnappulat infobokseissa linkitystilan ollessa päällä (aiemmin niitä pystyi painamaan, joten esim. vaihteen pystyi poistamaan itse kesken linkityksen)
* Toteutettu fiksumpi disabled-syyn näyttäminen infoboksien muokkausnappuloille (syy oli aiemmin kovakoodattu sellaiseksi, että luultiin että napit olisi disabloitu vain nykytilassa)
* Ratanumeron toolpanelin tab lukitaan nyt kunnolla kun ratanumeroa ollaan poistamassa …
> GVT-2783: Poistettua vaihdetta ei pitäisi voida linkittää ++

- infra/src/main/kotlin/fi/fta/geoviite/infra/geocoding/Geocoding.kt
- infra/src/main/resources/i18n/translations.fi.json
- ui/src/geoviite-design-lib/track-meter/track-meter.tsx
- ui/src/tool-panel/location-track/location-track-location-infobox.tsx
- ui/src/tool-panel/switch/switch-infobox-track-meters.tsx
- ui/src/tool-panel/track-number/track-number-infobox.tsx
Toinen kaninkoloinen muka-pikkutiketti. Alkuperäinen tiketti siis kuului, että geometriattomille pituusmittauslinjan rataosoitteille näkyi kohdistusikoni vaikka geometriaa ja siten alun ja lopun rataosoitteita ei ollut. Tämä korjattu universaalimmin varsinaiseen `<TrackMeter>`-komponenttiin. Tämän lisäksi korjailtu liitännäisinä seuraavat:
* Lisätty pituusmittauslinjan ja vaihteen rataosoitetietoihin placeholderit, jotka kertovat osoitteen puuttumisesta sen sijaan, että näyttäisivät vain tyhjää
* Pituusmittauslinjalle lisätty myös placeholder mikäli alun ja lopun koordinaattisijainnit puuttuvat
* Parannettu sijaintiraiteen alun ja lopun rataosoitteiden placeholdereita:
* Mikäli raiteelta puuttuu geometria kokonaan, rataosoitesijainnit sanovat "Raiteella ei ole geometriaa" (aiemmin niissä …
> GVT-2919: Ratanumeron alku- ja loppusijainnille näytetään kohdistusnappulat vaikka ratanumerolla ei olisi geometriaa ++

- ui/jest.config.json
- ui/package.json
- ui/tsconfig.json
* SWC is only a transpiler meaning that TS type-check errors from tests were not reported.
* SWC usage in tests seems to cause some issues when running node 20 with new ui package versions
* => Reverted to previous ts-node
* TS compiler options were added as the newer TS version seems to warn about js imports (which are configured to be used in jest tests for resources)
> General: Disable SWC in jest unit tests

- ui/package-lock.json
- ui/package.json
- ui/src/geoviite-design-lib/snackbar/snackbar.scss
- ui/src/geoviite-design-lib/snackbar/snackbar.tsx
The default stylesheet is auto-injected in the new version of react-toastify and uses css-parameters. The goal was keep the previous look, feel and functionality of the toasts.
Migration changes are described here: https://fkhadra.github.io/react-toastify/migration-v11/
> GVT-2977 (part 3): Bump react-toastify to 11.0.3

- ui/package-lock.json
- ui/package.json
- ui/src/map/map-view.tsx
- ui/src/utils/use-resize-observer.ts
- ui/src/vayla-design-lib/closeable-modal/closeable-modal.tsx
- ui/src/vertical-geometry/vertical-geometry-diagram-holder.tsx
This package seemed to be relatively small & unmaintained -> same functionality implemented without a dependency
> GVT-2977 (part 4): Remove React 19 blocking use-resize-observer dependency

- infra/src/main/resources/i18n/translations.fi.json
Satunnaisesti huomattu editorivaroitus. Rivillä 699 on sama avain, joten tämä ei ole toiminut varmaan kovin järkevästi. Jätin tarkemman/pidemmän muodon eli `"no-geometry": "Sijaintiraiteella ei ole geometriaa"`
> General: Remove non-unique translation key

- ui/src/vayla-design-lib/icon/Icon.tsx
- ui/src/vayla-design-lib/icon/icon.scss
En huomannut paikkaa, jossa oikeasti olisi hyödynnyttä ikonin pointer eventtejä 🤔 
=> Selvempää vaan disabloida defaulttina
> GVT-2992: Fix dialog close icon capturing pointer events, disable icon pointer events by default

- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/testgroup1/FrontPageTestUI.kt
Apparently this works now, maybe due to package updates?
> GVT-2918: Enable previously flaky E2E test

- infra/src/main/kotlin/fi/fta/geoviite/infra/geocoding/Geocoding.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/GeometryPlanLayout.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/PlanLayoutTransformation.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/TrackLayoutDomainTestData.kt
- ui/src/track-layout/track-layout-model.tsx
- ui/src/vertical-geometry/util.ts
- ui/src/vertical-geometry/vertical-geometry-diagram-holder.tsx
Tässä on vielä aika hyvänkin refaktorin varaa, koska tällä hetkellä koko pystygeometriakuvaajan koodin geometriapuoli asuu yksi jalka PlanLayoutAlignment-maailmassa (missä m-arvot alkavat aina nollasta) ja toinen GeometryAlignment-maailmassa (missä alignmentin sisältö alkaa vasta staStart-arvon kohdalta), ja staStart-arvo salakuljetetaan frontille vähän epämääräistä kautta.
Paremmassa maailmassa olisi niin, että nämä maailmat olisivat kunnolla erillään, eikä pystygeometrian kuvaajan koodi tekisi näitä mäppäyksiä lainkaan... mutta sinne pääseminen vaatisi vähän omaa miettimistään.
> GVT-2986 Map between zero-based and staStart-based m-values for vertical geometry diagram

- ui/src/map/map-view.tsx
- ui/src/tool-panel/tool-panel.tsx
- ui/src/track-layout/track-layout-slice.ts
En saanut toistettua alkuperäistä issueta, mutta löysin kyllä muita pystygeometriakuvaajaan liittyviä issueita. Lopulta kaikki fiksit päätyivät selection-logiikkaan, ei pystygeometriakuvaajaan. Käytännössä pystygeometrian kuvaaja näytetään silloin kun kaksi ehtoa täyttyy:
1. Pystygeometrian kuvaaja on pistetty päälle infoboksin togglesta
2. Toolpanelissa valittuna tabina on joko geometria-alignment tai paikannuspohjan sijaintiraide
Valittu toolpanelin tab on meillä tallessa reduxissa (`trackLayoutSlice`:ssa oleva propsu `selectedToolPanelTab`.) Tämä ei kuitenkaan päivittynyt lähellekään joka tilanteessa joissa näytetyt tabit saattoivat vaihtua (esim. suunnitelman, tai yksittäisten suunnitelmakäsitteiden piilottamiset). Tällöin toolpanel arpoi itse ensimmäisen tabin valituksi, mutta ei …
> GVT-2811: Selection-jumppaa (oli: Pystygeometrian kuvaaja ei mene joskus päälle)

- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutContextData.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutKmPostDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/ReferenceLineDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/TrackLayout.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/util/ResultSetExternal.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/TestDBService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutAssetServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutContextDataIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/TrackLayoutDomainTestData.kt
- ui/src/geoviite-design-lib/demo/examples/badge-examples.tsx
- ui/src/tool-panel/geometry-alignment/geometry-alignment-linking-candidates.tsx
- ui/src/tool-panel/km-post/dialog/km-post-edit-dialog.tsx
- ui/src/tool-panel/location-track/dialog/location-track-edit-dialog.tsx
- ui/src/tool-panel/location-track/splitting/location-track-splitting-infobox.tsx
- ui/src/tool-panel/switch/dialog/switch-edit-dialog.tsx
- ui/src/tool-panel/tool-panel.tsx
- ui/src/tool-panel/track-number/dialog/track-number-edit-dialog.tsx
- ui/src/track-layout/track-layout-model.tsx
Pitkälti triviaaleja muutoksia. Parikin käyttöpaikkaa oli sellaisia, että eipä siellä oikeasti ole voitu tehdä mitään hyödyllistä hasOfficial-tiedolla alkuunkaan, joten heitin ne vaan pois. Taustana siis se, että ID-remontin myötä tieto siitä, onko oliosta olemassa virallista versiota, ei pitäisi olla enää liitettynä olioon itseensä.
> GVT-2923 Banish has_official from existence

- infra/src/main/kotlin/fi/fta/geoviite/infra/ratko/RatkoService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutDesign.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutDesignDao.kt
- infra/src/main/resources/db/migration/prod/V111__move_design_ratko_id_to_separate_table.sql
- infra/src/test/kotlin/fi/fta/geoviite/infra/ratko/RatkoServiceIT.kt
Pienenpieni rakenteenselkiytysjuttu. Jyrki oli jo alkuaan suunnitellut että tämänhän pitäisi mennä omaan tauluunsa, ja niinhän sen pitäisi, kun kyseessä ei ole tieto, joka voi muuttua ajan kanssa suunnitelmissa, vaan oikeastaan vain Ratko-integraation tieto.
> GVT-2981 Move design Ratko ID to separate table

- ui/src/vayla-design-lib/icon/Icon.tsx
Hieman heittoehdotus sen ratkaisemiseen, että saadaan SVG-ikonit olemaan syömättä napsauksia: Oletetaan tähän hätään, että jos on annettu onClick-handleri ikonille itselleen, niin sitä halutaan käytettävän, mutta jos ei ole, niin ikonin ei haluta syövän kursoritapahtumia lainkaan. Periaatteessa hieman takavasemmalta tuleva logiikka, mutta tällä pitäisi toimia suoriltaan sekä ikonin sisältävä klikattava nappi että klikattava ikoni.
> GVT-3013 Handle icon clickability more automatically

- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/testgroup2/LinkingTestUI.kt
The issue was caused by an update changing the height limit of displayed location tracks on the map. This lead to the selection panel not having the expected location track label element available at the default zoom level. This was solved by zooming close enough to the map so that the location track will be displayed on the map & selection panel before trying to select it via the E2E test.
> GVT-3017: Fix broken E2E tests

- ui/src/geoviite-design-lib/dialog/dialog.tsx
- ui/src/geoviite-design-lib/eye/eye.scss
- ui/src/geoviite-design-lib/eye/eye.tsx
Previously these were simply div & span elements, which also meant that the commonly used styling for buttons did not function properly.
> GVT-3003: Refactor dialog close button and eye button to semantic Button elements

- ui/src/map/layers/alignment/location-track-alignment-layer.ts
- ui/src/map/layers/alignment/location-track-selected-alignment-layer.ts
- ui/src/map/layers/alignment/location-track-split-alignment-layer.ts
- ui/src/map/layers/alignment/reference-line-alignment-layer.ts
- ui/src/map/layers/alignment/reference-line-selected-alignment-layer.ts
- ui/src/map/layers/utils/alignment-layer-utils.ts
- ui/src/map/layers/utils/publication-candidate-highlight-utils.ts
- ui/src/map/map.module.scss
Tällä pullarilla järjestetty sijaintiraiteet kartalla tilan perusteella: Rakennettu-tilaiset päällimmäiseksi, Käytöstä poistettu -tilaiset seuraavaksi ja Käytössä-tilaiset kaiken alle. Tämän lisäksi Rakennettu-tilaisille toteutettu valkoinen pohjaviiva, jotta jos sellainen raide on päällekkäin jonkun muun raiteen kanssa, niin se erottuu sieltä alta (tällainen tilanne on hyvin mahdollinen esim. esikatselussa, jossa näytetään myös virallinen tila.)
Päädyin myös tekemään aika paljon refaktorointia kartan sijaintiraiteiden tyyleille. Tarve tälle johtui alunperin siitä, että Z-indeksilaskenta oli fiksuinta tehdä yhteisesti eri karttatasojen välillä, mutta sen siirtäminen utilsiin johti circular referenceihin. Riippuvuuksia on järkeistetty nyt siten, että enää ei pitäisi olla circular …
> GVT-3016: Raiteiden tilojen visualisointi: Päällekkäisten raiteiden järjestäminen tilojen mukaan

- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryPlan.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/PlanMetaData.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/inframodel/InfraModelApi.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/inframodel/InfraModelController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/inframodel/InfraModelConversion.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/inframodel/InfraModelService.kt
- infra/src/main/resources/db/migration/prod/V113__add_geometry_plan_applicability.sql
- infra/src/main/resources/i18n/translations.fi.json
- infra/src/test/kotlin/fi/fta/geoviite/infra/geometry/GeometryDomainTestData.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/geometry/GeometryServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/inframodel/InfraModelServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/testdata/HelsinkiTestData.kt
- ui/src/geometry/geometry-model.ts
- ui/src/infra-model/infra-model-api.ts
- ui/src/infra-model/infra-model-slice.ts
- ui/src/infra-model/view/form/fields/infra-model-decision-phase-field.tsx
- ui/src/infra-model/view/form/fields/infra-model-elevation-measurement-method-field.tsx
- ui/src/infra-model/view/form/fields/infra-model-field-model.ts
- ui/src/infra-model/view/form/fields/infra-model-measurement-method-field.tsx
- ui/src/infra-model/view/form/fields/infra-model-plan-applicability.tsx
- ui/src/infra-model/view/form/infra-model-form.tsx
- ui/src/tool-panel/geometry-plan-infobox.scss
- ui/src/tool-panel/geometry-plan-infobox.tsx
- ui/src/tool-panel/geometry-plan/geometry-plan-applicability.tsx
- ui/src/tool-panel/infobox/infobox.module.scss
- ui/src/utils/enum-localization-utils.ts
Täällä lisätty suunnitelmille soveltuvuustieto. Käytännössä tehty siis seuraavat:
* Lisätty soveltuvuustiedolle uusi enum ja kentät kantaan
* Lisätty bäkkärille uusi endpoint, jonka kautta se voidaan asettaa erillisenä tietona
* Lisätty frontille geometriasuunnitelman infoboksiin tieto suunnitelman soveltuvuudesta ja mahdollisuus editoida sitä suoraan siitä
* Lisätty frontille inframallinäkymään vastaava muokkaustoiminto suunnitelman laatutietoihin
Lisäksi vähän refaktorointia inframallinäkymän tyyppeihin, kun niissä oli päällekkäisyyttä
> GVT-3007: Soveltuvuus-tieto geometriasuunnitelmille

- ui/src/data-products/data-products-utils.ts
Fiksaa bugin tilanteessa, jossa hakusanalla löytyy useampi kuin 10 tulosta (esim. haettaessa ratanumeron tunnuksella, kuten 001).
Rajasin tuon nyt kuitenkin sataseen, jotta jokin raja on olemassa
> GVT-3004: Increase data product geometry plan search result limit

- ui/src/geoviite-design-lib/eye/eye.scss
- ui/src/geoviite-design-lib/eye/eye.tsx
- ui/src/tool-panel/alignment-plan-section-infobox-content.tsx
- ui/src/tool-panel/infobox/infobox-list.tsx
- ui/src/tool-panel/infobox/infobox.module.scss
- ui/src/tool-panel/location-track/location-track-geometry-infobox.tsx
- ui/src/tool-panel/track-number/alignment-plan-section-infobox.scss
- ui/src/tool-panel/track-number/track-number-geometry-infobox.tsx
- ui/src/track-layout/layout-location-track-api.ts
- ui/src/vayla-design-lib/checkbox/checkbox.tsx
Tämähän lähti siitä, että raiteen ja pituusmittauslinjojen silmä ja "vain kartalle osuvat geometriat"-checkboxi olivat eri kohtiin tasattuna. Tuo geometrialistauskomponentti vaikutti keränneen sen verran monimutkaisuutta, että pilkoin hallittavimmiksi blokeiksi samalla.
* Muutettu myös geometrialistauksen silmä napiksi, eli sillekin päätyy esimerkiksi nyt tausta selectionpanelin silmien tavoin.
* Checkboksi ja silmä ovat nyt visuaalisesti päällekkäin riippumatta layoutcontextista. Checkboxi on tätä nappikokoa hiukan pienempi, mutta silmäikoni on normaalisti ghostina eli sillä ei ole taustaa, joten eroa on vaikea huomata. Checkboxin keskilinjan pitäisi kuitenkin olla tasattuna silmäikoninkin keskilinjaan pystysuunnassa.
* Luotu myös uusi yleiskäyttöisempi `<InfoboxList>`-komponentti. …
> GVT-2885: Refactor alignment geometry listing to smaller components & fix eye positioning

- ui/src/geoviite-design-lib/breadcrumb/breadcrumb.tsx
- ui/src/geoviite-design-lib/link/anchor-link.tsx
- ui/src/geoviite-design-lib/link/router-link.tsx
- ui/src/geoviite-design-lib/switch/switch-link.tsx
- ui/src/geoviite-design-lib/track-number/track-number-link.tsx
- ui/src/infra-model/projektivelho/pv-redirect-link.tsx
- ui/src/preview/preview-view-design-drafts-exist-error.tsx
- ui/src/publication/card/publication-card.tsx
- ui/src/publication/card/publication-list-row.tsx
- ui/src/publication/log/publication-log.tsx
- ui/src/publication/publication.tsx
- ui/src/tool-panel/alignment-plan-section-infobox-content.tsx
- ui/src/tool-panel/geometry-plan-link.tsx
- ui/src/tool-panel/km-post/dialog/km-post-edit-dialog.tsx
- ui/src/tool-panel/km-post/km-post-infobox.tsx
- ui/src/tool-panel/location-track/dialog/location-track-edit-dialog.tsx
- ui/src/tool-panel/location-track/location-track-basic-info-infobox.tsx
- ui/src/tool-panel/location-track/location-track-link.tsx
- ui/src/tool-panel/location-track/splitting/location-track-split-notices.tsx
- ui/src/tool-panel/location-track/splitting/location-track-split-relinking-notice.tsx
- ui/src/tool-panel/switch/dialog/switch-draft-oid-field.tsx
- ui/src/tool-panel/switch/dialog/switch-edit-dialog.tsx
- ui/src/tool-panel/track-number/dialog/track-number-edit-dialog.tsx
- ui/src/user/privileged-link.tsx
- ui/src/vayla-design-lib/demo/examples/table-examples.tsx
Aiemmin meillä oli eri komponenteissa kahta eri `<Link>`-elementtiä -> tehty välikomponentit eri nimillä
> GVT-2346: Create aliases to React router's link and anchor element to prevent confusion

- ui/src/map/map-view.tsx
When map layers are recreated, they may also create new searchItems closures which capture outside state. These closures need to be rebound to event handlers when the outside state of the closures has changed and the closure has been recreated.
For example, in the aligment-linking-layer, a searchItems closure is created. This closure checks if the outside drawLinkingDots state is enabled and potentially immediately returns an empty search result if the linking dots are not drawn:
```
...
return {
name: layerName,
layer: layer,
searchItems: (hitArea: Rectangle, _options: SearchItemsOptions): LayerItemSearchResult => {
if (!drawLinkingDots) {
return emptySearchResult();
} else {
// Normal search
}
},
};
```
In the example above, the drawLinkingDots variable is not an argument to the closure …
> GVT-3022: Fix improper dependency array for map tool useEffect hook

- infra/src/main/kotlin/fi/fta/geoviite/api/frameconverter/v1/FrameConverterControllerV1.kt
- infra/src/main/kotlin/fi/fta/geoviite/api/frameconverter/v1/FrameConverterDataV1.kt
- infra/src/main/kotlin/fi/fta/geoviite/api/frameconverter/v1/FrameConverterErrorV1.kt
- infra/src/main/kotlin/fi/fta/geoviite/api/frameconverter/v1/FrameConverterRequestDataV1.kt
- infra/src/main/kotlin/fi/fta/geoviite/api/frameconverter/v1/FrameConverterServiceV1.kt
- infra/src/main/resources/i18n/translations.fi.json
- infra/src/main/resources/static/frameconverter/openapi-rata-vkm-v1-dev.yml
- infra/src/main/resources/static/frameconverter/openapi-rata-vkm-v1.yml
- infra/src/test/kotlin/fi/fta/geoviite/api/frameconverter/v1/TrackAddressToCoordinateIT.kt
This change should be backwards compatible. The earlier problem with the different field for the decimals is that the user would not be able to specify the scale of the decimal (eg. would the number 1 mean decimal 0.1, 0.001 or something else) -> BigDecimal can just be used directly instead of an int for the track address meters. The user can also choose to submit the field as an int, number or a string and all of these should parsed correctly to the BigDecimal.
> GVT-2837 (part 2): Use BigDecimal directly as the track address meters parameter

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSearchController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSearchService.kt
- ui/src/tool-bar/search-dropdown.tsx
- ui/src/tool-bar/tool-bar.tsx
- ui/src/track-layout/track-layout-search-api.ts
Suunnitelmien latausnäkymässä on tarve hakea samalla hakuboksilla sekä ratanumeroita että sijaintiraiteita. Meillähän on tuollainen hakuboksi jo ennestään, se oli vaan kiinteä osa `<ToolBar>`:ia. Tällä tiketillä erotettu se omakseen sekä mahdollistettu hakutulosten rajaaminen assettityypin mukaan.
P.S. Huomasin tarpeen tälle ihan kesken matkan toteuttaessani latausnäkymää. Tämä on irrotettu omakseen siitä isommasta kokonaisuudesta, jota olen jo koodannut lokaalisti mutta en vielä puskenut, joten jos tällä pullarilla näkyy jotain outoutta tai jänniä viittauksia, niin tuo saattaa olla syynä siihen. Tätä ei ole tarkoitus mergata mainiin sellaisenaan.
> GVT-3009 Esivalmistelu: Assettihaun erottaminen omaksi komponentikseen

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutAlignmentDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutAssetDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutKmPostDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackSpatialCache.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/ReferenceLineDao.kt
Varsinainen :cut_of_meat: tässä on LazyMappien poisto LocationTrackSpatialCachesta, niistä tärkeämpänä alignmentDao#fetch()in edessä elävä: Siihen kertyi hakujen tekemisen myötä alignmenteista (ja siten niiden paljon muistia vievistä geometrioista) ne instanssit, jotka alignmentDao sattui hakuhetkellä palauttamaan, mutta alignmentDaon cachen virkistyshän sitten luo myöhemmin uudet instanssit edustamaan samoja alignmentteja, ja siten sama iso määrä tietoa on edustettuna muistissa useamman kerran.
Siinäkin tapauksessa, että näin ei olisi, niin onhan tuo LazyMap muutenkin väärä olio cachen ylläpitoon, koska siihen jää myös oikeasti vanhat versiot olioista olemaan koko softan ajoajaksi.
Mutta alkuperäinen syy, miksi tuota LazyMappia tarvittiin, oli että alignmentDao#fetch()issä hyppääminen …
> GVT-3050 Use common alignment cache in locationTrackSpatialCache + redo transaction boundaries

- infra/src/main/kotlin/fi/fta/geoviite/infra/geocoding/Geocoding.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/math/Line.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/math/Math.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutGeometry.kt
Nimet selkiytetty, katsoin järkevimmäksi nimetä metodit paluuarvon tyypin perusteella, koska onhan ihan mahdollista että halutaan interpoloida kahden SegmentPointin väliltä Point. Selkiytyksellä vältetään yksi SegmentPoint#toPoint()-kutsu geokoodauksessa.
> General: De-overload interpolate() methods + optimize call

- infra/src/main/kotlin/fi/fta/geoviite/infra/geocoding/Geocoding.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/util/List.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/geocoding/GeocodingTest.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationValidationTest.kt
Tässä on yhdessä sekä hieman monimutkaista uutta toteutusta että vanhan uudelleenkirjoitusta vähän faktoroituumpaan muotoon.
Taustana siis, geokoodauksesta (osoitteesta sijainniksi) on ennen ja nykyään meillä kaksi toteutusta:
- getTrackLocation(): Otetaan osoitteen projektioviiva, etsitään sen lähin osuma raiteelle (yleensähän osumia on vain yksi, mutta raide ja pituusmittauslinja voi käydä silmukan), palautetaan tämän osuman sijainti
- getAddressPoints(): Kävellään rinnakkain pituusmittauslinjaa (tai tarkemmin siis siitä tehtyä projektioviivalistaa) ja raidetta pitkin, niin että kaikki projektioviivojen osumat raiteelle löytyy hyvin vähällä vaivalla
getTrackLocations() teki ennen tasan saman asian kuin getTrackLocation() ja vältti siksi vain vähän työtä, koska se joutui etsimään …
> GVT-3038 Optimize getTrackLocations()

- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/VerticalGeometryListing.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/util/Either.kt
getTrackLocations()in optimoinnin mahdollistamia juttuja. Ei funktionaalisia muutoksia, mutta geokoodauksen siirtäminen yhteen nopeaa algoritmia käyttämään pompsiin nopeuttaa tätä funktiota niin paljon, että rinnakkaistus ei enää käytännössä tee mitään.
> GVT-3038 Optimize getTrackLocations() use in loading vertical geometries

- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/AlignmentHeights.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/TrackMeterHeights.kt
Kaksi oleellista muutosta:
- collectTrackMeterHeights()in rajapintaa on yksinkertaistettu, periaatteessa aika huomattavasti. Voisi yksinkertaistaa vielä pitemmällekin, nimittäin tämä koodihan ei lopulta oikeastaan liity millään tavalla suoraan noihin pystygeometrioihin, vaan ainoastaan geokoodaukseen, siis niin, että se se hakkaa raiteen sopivan näppärän tasaisena kaaviolla näkyviin pisteisiin tasametripisteiden kohdalla (ja geometrioiden muutoskohdilla). Varsinainen korkeuksien hakeminen on sitten täysin asia erikseen.
- Se oletus, että kyllä kaikki raiteen alku- ja loppuosoitteen väliset osoitteet löytyy raiteelta, on poistettu, koska sehän tosiaan ei nykyisellä geokoodauksen toimintaperiaatteella ole totta. Tämä oli bugi GVT-3064.
Rajapinnan yksinkertaistaminen on sitten mahdollistanut …
> GVT-3038/GVT-3064 Adapt KmHeights to getTrackLocations()s behavior better

- infra/src/main/kotlin/fi/fta/geoviite/infra/inframodel/InfraModelService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/inframodel/InfraModelServiceIT.kt
Luulin että tämä olisi ollut isompikin työmaa, mutta menikin lopulta yllättävän kohtuuella. `PlanApplicability`-arvo lähetetään aina frontilta vaikka siihen ei olisi siellä koskettukaan -> voidaan hyvillä mielin luottaa siihen, että jos frontilta tulee `null`, niin se on haluttua.
Lisäksi korjattu testejä tarkastamaan tämä nullaustilanne muun päivityksen sijasta, ja sen lisäksi korjattu se, että applicability ylipäätään tarkastetaan (aiemmin ei tarkastettu)
> GVT-3052: Suunnitelman soveltuvuus -tietoa ei voi asettaa "Ei tiedossa"-arvoon inframallilomakkeen kautta

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackServiceIT.kt
Mahdollisia rajatapauksia on tässä useita, mutta onneksi niistä kaikki on sellaisia, että käyttäjän pitää tehdä jotain todella outoa, tai paikannuspohjassa olla tosi huono tuuri:
- Alkupäässä annettu kirjainpäätteellinen ratakilometri, jota ei ole raiteella, mutta joka olisi raiteen osoitevälillä, jos se olisi olemassa: Aiemmin kaaduttiin siihen, että getTrackLocation() palautti nullia, nyt palautetaan ei-oota
- Sama mutta loppupäässä: Koska koodi ei hakenut varsinaista pyydettyä ratakilometriä, vaan ainoastaan ensimmäisen KmNumber-järjestyksen mukaan sen jälkeen tulevan, loppupää löytyi, vaikka ei olisi pitänyt löytyä. Nyt palautetaan ei-oota
- Raiteelta puuttuu oudon geometrian takia siihen alku-loppu-osoitevälin mukaan kuuluva alku- tai loppu-km-tolppa: Onneksi nämä vaativat sen verran …
> GVT-3069 Handle inexistent track kilometers in plan loading

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutAssetService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationServiceIT.kt
"Completion"/toteutuminen tarkoittaa siis, että kirjataan suunnitelma puolelle tieto siitä, että sieltä mainiin tuotu olio on nyt julkaistu viralliseen paikannuspohjaan. Tämä ei ole mitenkään täydellinen prosessi, koska olioitahan pystyy ihan vapaasti muokkaamaan luonnostilassa suunnitelmasta tuomisen jälkeen, eli koko originBranch-tiedon merkitys ei ole erityisen suuri: Mutta on siinä nyt se, että jos toteutuminen menee normaaliprosessin mukaisesti, niin ainakin saadaan suunnitelman versio lopuksi pois paikannuspohjan live-tilan tauluista.
> GVT-2995 Handle merged objects being cancelled before merger completion

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutAlignmentDao.kt
Yllätyin, että postgres ajoi haun alkuperäistä muotoa huonosti, koska eipä se erityisen monimutkainen monsteri ole, mutta kyllä tämä vaan nopeuttaa hakua minun koneella noin kuudesta ja puolesta sekunnista alle neljään sekuntiin. Se alkuperäisen erikoisuus, että postgressin rinnakkaistus hidastaa hakua, katoaa myös: Uusi haku toimii nopeammin meidän kontin oletusarvoilla, joissa rinnakkaistus on päällä.
Mutta lähinnä kai hyvä ottaa sitten myös graafihaarassa huomioon, että tämä tosi iso preloadi on ihan oikeasti iso.
> GVT-3070 Write segment geometry preload query as semijoin

- ui/src/store/hooks.ts
- ui/src/tool-panel/alignment-plan-section-infobox-content.tsx
- ui/src/tool-panel/location-track/location-track-geometry-infobox.tsx
- ui/src/tool-panel/location-track/location-track-infobox.tsx
useSelector()in käyttöjen korjaamiset on ehkä oleellisin osa, ja niissä on aika paljonkin potentiaalia saada hyötyä aikaan. useSelector()han siis toimii niin, että se muistaa palautusarvonsa (olion identiteetin), ja jos palautusarvo ei ole muuttunut, ei itsessään triggaa uudelleenrenderöintiä, ja tämän takia siitä kannattaa palauttaa aina mahdollisimman harvoin muuttuva tieto. Tai en itse asiassa edes tiedä, mitä kaikkea magiaa se tekeekään, mutta tämä nyt on oleellisin osa sen oikeaoppisesta käytöstä.
Komponenttien määrittely render-funktioissa aiheuttaa ongelmia, siksi PlanVisibilityToggle siirretty ylätasolle: https://www.developerway.com/posts/react-re-renders-guide#part3.1
Näiden muutosten jälkeen jäljellä vain selkeää memottelua ja useCallback-veivausta.
> GVT-3074 Various React performance bugfixes

- ui/src/geometry/geometry-model.ts
- ui/src/vertical-geometry/height-tooltip.tsx
- ui/src/vertical-geometry/pvi-geometry.tsx
- ui/src/vertical-geometry/util.ts
Suurimmaksi osaksi refaktoria PviGeometryssä, tosin perffi voi olla muuttunut suuntaan tai toiseen, kun nyt:
- Todnäk huonona asiana: React-komponenttirakennetta on enemmän ja varsinainen luotujen komponenttien määrä on isompi
- Hyvänä asiana: Apuviivat ja niiden kulmat piirrettiin aiemmin koko geometrialle, nyt ainoastaan näkyvälle välille
- Ehkä huonona tai hyvänä asiana: React-keyt asetetaan nyt oikeaoppisesti datan, eli niiden pystygeometriaelementtien tosi pitkien iideitten, perusteella
Koko pvi-geometry.ts on tietenkin yhäkin aikamoinen otus, mutta nyt se sentään näyttää rakenteeltaan miltei tavalliselta React-komponentilta. Tosin en ole yhäkään erityisen varma, oliko tätä koko kaaviota alkuunkaan järkeä tehdä Reactilla ja SVG:llä, vai pitäisikö vaan piirtää kaikki …
> General: Parempaa Reactin käyttöä

- infra/src/main/resources/i18n/translations.fi.json
- ui/src/tool-bar/workspace-dialog.tsx
- ui/src/tool-bar/workspace-selection.tsx
- ui/src/vayla-design-lib/dropdown/dropdown.tsx
Varsinaisen pihvin lisäksi refaktoroitu myös dropdownista pakkosuomea pois ja lisätty työtilan luontidialogin avaukseen focus nimikenttään
> GVT-2939: Haetun suunnitelman nimen automaattisiirto "Lisää uusi"-dialogiin

- infra/src/main/kotlin/fi/fta/geoviite/infra/geocoding/Geocoding.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/TrackMeterHeights.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationGeometryChangeRemarksUpdateService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/util/List.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/RemarksUpdaterServiceTest.kt
Uusi geometriamuutosten laskenta tuo nyt kylläkin tuloksiin muutoksia, mutta sikäli kuin niiden vaikutusta kävin läpi prosessoimalla vaan koko julkaisuhistorian uudestaan läpi, uusi toteutus toimi kyllä vaan ainoastaan paremmin kuin entinen.
Entinen toteutus siis käveli raiteen vanhan version segmenttipisteitä, haki jokaiselle käänteisellä geokoodauksella osoitteen, geokoodasi osoitteet raiteen uudelle versiolle, ja sitten vertasi näiden sijainteja. Tämä on siis sekä erinomaisen hidas että jo ihan logiikaltaan aika änkyrä, koska geokoodaukset tehdään raiteen vanhalle ja uudelle versiolle eri suuntaan.
Uusi toteutus yksinkertaisesti hakee vaan molempien versioiden osoitepisteet ja vertaa niiden osoitteiltaan yhteistä väliä. Heitin myös tarkan etäisyyden laskennan pois, kun tässä joka …
> GVT-3038 Reimplement geometry changes summarization with getAddressPoints

- ui/package-lock.json
- ui/package.json
- ui/src/utils/array-utils.ts
Mietin review-kommenttien perusteella hieman tämän riippuvuuden tarpeellisuutta, ja niihnhän se on, että jos tätä käytetään Reactin suhteen oikeaoppisesti (ts. ei render-metodeissa vaan ainoastaan settereissä/redux-tilan päivityksissä), niin aika eipätodennäköistä on, että stringify-pohjainen yhtäsuuruustarkistus aiheuttaisi ikinä ongelmia => otetaan ylimääräinen riippuvuus pois.
> GVT-3012 Remove not strictly necessary fast-deep-equals dependency

- infra/src/main/resources/i18n/translations.fi.json
- ui/src/geoviite-design-lib/message-box/message-box.scss
- ui/src/geoviite-design-lib/message-box/message-box.tsx
- ui/src/preview/preview-view-design-drafts-exist-error.tsx
- ui/src/tool-panel/km-post/dialog/km-post-edit-dialog-gk-location-section.tsx
- ui/src/tool-panel/km-post/dialog/km-post-edit-store.ts
- ui/src/tool-panel/km-post/geometry-km-post-different-gk-source-warning.tsx
- ui/src/tool-panel/km-post/geometry-km-post-linking-infobox.tsx
- ui/src/tool-panel/km-post/geometry-km-post-non-gk-source-warning.tsx
- ui/src/tool-panel/location-track/splitting/location-track-split-notices.tsx
- ui/src/tool-panel/location-track/splitting/location-track-split-relinking-notice.tsx
- ui/src/tool-panel/switch/geometry-switch-linking-infobox.tsx
- ui/src/tool-panel/switch/switch-infobox.tsx
Yllättävän paljon löytyi refaktorointitarpeita näinkin simppelin kuuloisen jutun myötä, eikä tässäkään välttämättä vielä kaikki. Täällä käytännössä siis erotettu aiemmin pelkästään kilometripylvään linkityksen luontidialogissa näytetyt GK-sijainnin muunnosvaroitukset linkitysinfoboksissa mikäli sijainti pitää muuntaa (itse varoitustekstit erotettu omiksi komponenteikseen, muu DOM on käyttöpaikkakohtaista).
Tämä poiki muutostarpeita myös `MessageBox`-komponenttiin (uusi `GHOST`-tyyppi hieman samaan tyyliin kuin meidän `GHOST`-napit). Lisäksi refaktoroin tämän myötä `MessageBox`:ia sisäisesti jonkin verran, sillä aiemman kahden tyyppiarvon sijasta nykyään pitää ottaa huomioon kolme, ja sen tekeminen fiksummin vaikutti, noh, fiksulta.
> GVT-2937: Muunnetun koordinaatiston näyttäminen infoboksissa linkityksessä olemassaolevaan kilometripylvääseen

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackService.kt
- ui/src/map/map-view-container.tsx
- ui/src/map/map-view.tsx
- ui/src/map/plan-download/confirm-move-to-main-official-dialog.tsx
- ui/src/map/plan-download/plan-download-area-section.tsx
- ui/src/map/plan-download/plan-download-popup.scss
- ui/src/map/plan-download/plan-download-store.ts
- ui/src/selection-panel/selection-panel-container.tsx
Varsinainen pihvi oli aika simppeli korjaus: Popupin avaamislogiikka ei dialogin kautta tullessa katsonut ollenkaan valittua toolpanelin tabia. Logiikka yleistetty ja otettu käyttöön sielläkin. Tämän myötä myös huomattu, että overlappaavien sunnitelmien haku heitti poikkeusta mikäli sitä kutsuttiin olemattoman ratanumeron tai sijaintiraiteen id:llä (esim. tämän korjauksen myötä tilanne, jossa ratanumero/sijaintiraide oltiin luotu draftissa mutta sitä ei oltu julkaistu vielä ollenkaan.) Bäkkäri pistetty palauttamaan näissä tilanteissa tyhjän listan suunnitelmia. 
Näiden lisäksi tehty seuraavanlaista kevyttä refaktorointia sekä korjauksia pikkubugeihin:
* Edellämainittu toolpanelissa valitun assetin perusteella popupin alkuassetin valitseva logiikka muutettu if-elsestä switch-caseksi
* …
> GVT-3075: Radan/raiteen automaattinen valinta siirryttyessä suunnitelmien latausikkunaan luonnostilasta ++

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/ReferenceLineController.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationValidationServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ratko/RatkoServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberServiceIT.kt
Päädyin MVP-mielessä siihen, että vaikka periaatteessa onkin niin, että ratanumeron luomisen perumisen yhteydessä pitää aina perua myös sen pituusmittauslinjan luominen, ei yritetä tehdä sitä automaattisesti. Tämä automatisointi nimittäin aiheuttaa monta muuta nysvättävää asiaa: Julkaisun esikatselunäkymä ei osaa hoksata pituusmittauslinjan muutoksen peruutuneen kuin vasta muutosajan päivittymisen jälkeen, pituusmittauslinjan perumisen pitäisi oikeasti tarkistaa, onko nyt kysessä suunnitelmassa luotu linja, ja ehkä testauksen jälkeen löytyisi muitakin juttuja.
> GVT-2989/GVT-3085 Remove automatic reference line cancellation special case

- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationValidation.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationValidationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutKmPostDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberDao.kt
- infra/src/main/resources/i18n/translations.fi.json
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationValidationServiceIT.kt
Kilometritolpilla ja ratanumeroilla on layout-konteksteittain uniikki nimi/tunnus riippumatta tilasta. Siksi niitä validoitaessa pitää ottaa mahdollisesti poistetutkin viralliset versiot mukaan.
> GVT-2744/GVT-2717 Correctly validate name uniqueness upon merge

- infra/src/main/kotlin/fi/fta/geoviite/api/frameconverter/v1/FrameConverterControllerV1.kt
- infra/src/main/kotlin/fi/fta/geoviite/api/frameconverter/v1/FrameConverterErrorV1.kt
- infra/src/main/kotlin/fi/fta/geoviite/api/tracklayout/v1/ExtLocationTrackControllerV1.kt
- infra/src/main/kotlin/fi/fta/geoviite/api/tracklayout/v1/ExtTrackLayoutErrorHandlingV1.kt
- infra/src/main/kotlin/fi/fta/geoviite/api/tracklayout/v1/ExtTrackLayoutExceptionsV1.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/configuration/RequestFilter.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/error/ApiErrorHandler.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/error/ApiErrorResponse.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/error/ClientException.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/error/ErrorHandling.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/error/ServerException.kt
- infra/src/main/resources/i18n/translations.fi.json
Pointtina jakaa yleinen virhekäsittely siten, että aiempi geoviitteen rajapinta käyttää aiempaa, mutta virheenkäsittelijöitä voi wirettää muuallekin pyynnön polun perusteella.
> GVT-3078: Add localized error handling to ext-api

- infra/src/main/kotlin/fi/fta/geoviite/api/openapi/SwaggerController.kt
Näköjään typoiltu aiemman swagger-refakin yhteydessä. Ei siis päätynyt tuotantoon.
> General: Fix invalid rata-vkm swagger url

- infra/src/main/resources/db/migration/prod/V117__fix_broken_segment_switch_history.sql
Näitä on historiallisessa datassa muutama (ei yhtään aktiviisilla raiteilla), joten korjataan pohjalle ennen kuin tehdään graafimalli tuosta. Nämä siis näyttäytyisi edgeinä jotka päätyvät takaisin samaan noodiin, missä ei ole mitään järkeä.
> GVT-2934 Fix segments in alignment history that have the same switch joint at both ends

- ui/src/track-layout/track-layout-slice.ts
Context:
* The current git main-branch UI doesn't always display the vertical geometry diagram: The diagram does not always open depending on the asset selection order.
* This is tested via an E2E test, which is sometimes failing, leading to builds not always completing properly.
* Switch linking UI functionality was recently modified.
* Switch linking tab has different selection/forced selection functionality compared to other asset tabs. Only one switch linking tab should also ever exist, so it doesn't particularly make sense to duplicate the switch being active linked also to the selected tab state (although this could also be done to re-standardize tab selection).
Bug:
* The constant 'SUGGESTED_SWITCH_TOOL_PANEL_TAB_ID' is always defined, checking tab priority order based on this will …
> GVT-3136: Fix broken asset tab selection

- infra/src/main/kotlin/fi/fta/geoviite/api/tracklayout/v1/ExtLocationTrackControllerV1.kt
- infra/src/main/kotlin/fi/fta/geoviite/api/tracklayout/v1/ExtLocationTrackGeometryServiceV1.kt
- infra/src/main/kotlin/fi/fta/geoviite/api/tracklayout/v1/ExtLocationTrackServiceV1.kt
- infra/src/main/kotlin/fi/fta/geoviite/api/tracklayout/v1/ExtTrackLayoutConstantsV1.kt
Noille /muutokset-pinnoille tulee vastaavat dokuilut/muutetut vastauskoodit toisen tiksun yhteydessä.
Kommentteja voi heittää varsinkin vastausdokuilun ymmärrettävyydestä. Annotaatiodokut toki päätyvät aika monirivisiksi, ja niiden pitää olla staattisesti muodostettavissa käännösvaiheessa, eli esimerkiksi noita ApiResponse-instansseja ei voi jakaa eri rajapintojen kesken, vaikka ne ovatkin identtistä muotoa.
> GVT-3147: Modify location track response codes in certain states, add openapi documentation

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/ReferenceLineDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/util/NamedParameterJdbcTemplateExternal.kt
Korjaus on hiukan haxy, mutta sentään täsmä ja vaikuttaa vain noihin pariin kyselyyn joista hidastelun löysin. 
Dokumentoin tuon itse issuen löydökset tiketille jos tämä ihmetyttää myöhemmin: https://extranet.vayla.fi/jira/browse/GVT-3181
> GVT-3181 Fix for spatial referenceline/locationtrack queries slowing down after a while

- ui/src/track-layout/track-layout-model.tsx
Muuttuja oli siis jäänyt UI-koodin formatoinneista vain uupumaan.
Halutessaan voi verrata bäkkäripuolen formatointifunkkariin: https://github.com/finnishtransportagency/geoviite/blob/89976229c09617cdf5ffb6386baec7fedd3f7e62/infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrack.kt#L194-L209
> GVT-3178: Fix location track description display format in edit dialog

- infra/src/main/kotlin/fi/fta/geoviite/api/tracklayout/v1/ExtLocationTrackGeometryServiceV1.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geocoding/AddressPointsCache.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geocoding/GeocodingCacheService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geocoding/GeocodingDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geocoding/GeocodingService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/integration/AddressChangesService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/integration/ChangeContext.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationValidationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/ValidationContext.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/integration/AddressChangesServiceIT.kt
Koitin katsella tiettyjä juttuja noissa m-arvoissa että voisiko castailuja ja ylimääräisiä tyypityksiä jostain vähentää. Kokeilin paria eri polkua ja ne ei ihan mutkitta menneet, mutta tämä vaikutti suhteellisen harmittomalta muutokselta. Muutama muu ajatus olisi vielä kokeiltavaksi mutta katsotaan kerkiääkö niitä kokeilla.
> General: Use stricter types in geocoding contexts to avoid casts and extraneous template types

- ui/src/map/layer-menu/map-layer-menu.tsx
Bäkkärillä oli siis käytössä tuo VIEW_LAYOUT_DRAFT-privilege raidegraafi-karttatasolle, joka esti sen näyttämisen konsultti- ja virastokäyttäjille jo aiemmin (dev-ympäristössä). Aktivoinnista päätyi siis toast-virhe, joskin nähtävästi tämä bugi olikin olemassa vain dev-ympäristössä. 
Toki voisi miettiä, että haluttaisiinko raidegraafi-tasoa(/muita debug-työkaluja) käyttää myös tuotannossa (ilman redux-tilan manuaalikikkailua, jolla se olisi jo nytkin mahdollista).
> GVT-3198: Add privilege gate to display debug layer menu

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutDesignController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutDesignService.kt
- ui/src/tool-bar/workspace-dialog.tsx
- ui/src/tool-bar/workspace-selection.tsx
- ui/src/track-layout/layout-design-api.ts
Aiempi ongelma johtui siitä, että peruutettuja ja poistettuja suunnitelmia ei ylipäätään palautettu frontille tuossa haussa. Parametrisoin tuon haun nyt siten, että ne saa välitettyä frontille ja otin sen käyttöön etusivun julkaisukortilla. Karttanäkymän hauissa ja luontinäkymissä näytetään edelleen pelkästään aktiiviset suunnitelmat
> GVT-3171: Poistettujen suunnitelmatilojen nimet eivät näy julkaisukortissa

- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationLogService.kt
- infra/src/main/resources/i18n/translations.fi.json
- ui/src/publication/log/publication-log.tsx
- ui/src/publication/publication-api.ts
- ui/src/publication/publication.tsx
Ajattelin järkeväksi käytettävyysominaisuudeksi tunkea julkaisulokifiluun tiedoston nimeen tutkittavan olion nimen. Olkoonkin, että pienellä laiskuudellahan se frontista tulee, missä se sattuu tässä tapauksessa olemaan kätevästi saatavilla.
> GVT-3187 Handle specificObjectness in publication log CSV export path

- ui/src/publication/publication.tsx
Hyvin laiskasti tehty, mutta täysin toimiva toimintatapa: Haut takana on riittävän nopeita, että eipä ne oikeastaan tuosta päivämäärävälistä edes juuri välitä. Koska tässä ei ole helposti käsillä olion luontihetkeä tai viimeisintä muokkaushetkeä, käytetään siis vaan koko historiaa muutosaikavälinä.
> GVT-3194 Reset publication log search date range upon clicking in from a publication

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrack.kt
- infra/src/main/resources/i18n/translations.fi.json
- ui/src/tool-panel/location-track/dialog/location-track-edit-dialog-name-section.tsx
- ui/src/tool-panel/location-track/dialog/location-track-edit-dialog.tsx
- ui/src/tool-panel/location-track/dialog/location-track-validation.ts
- ui/src/track-layout/track-layout-model.tsx
Tällä pullarilla tehty siis useampia pieniä juttuja. Monet niistä olivat joko niin pieniä tai liittyivät toisiinsa niin voimakkaasti etten katsonut järkeväksi jakaa niitä omiin pullareihinsa. Merkkaan kommenteilla mikä muutos liittyy mihinkin. Muutokset ovat pääosin fronttijuttuja, mutta osa niistä piti duplikoida myös bäkkärille
> Useita pieniä korjauksia sijaintiraidetarkenteeseen (GVT-3180 & GVT-3199 & GVT-3210 & GVT-3229 & GVT-3231)

- ui/src/geoviite-design-lib/elevation-measurement-method/elevation-measurement-method.tsx
- ui/src/vertical-geometry/plan-linking-header-item.tsx
Släkissä mainittua SVG-nysväystä: HTML:ssä voi luottaa siihen, että jos elementissä on useampi tekstinoodi, niin ne piirtyy kyllä ihan vaan yhteen lyötynä. SVG:ssä ei näemmä ole näin, ainakaan Firefoxilla ja Chromella vilkuilun perusteella, vaan eri tekstinoodit piirtyvät varmaan jollain tavalla erillisinä elementteinä niin, että tulos näyttää hieman oudolta. Siksi joudutaan vähän tökerösti rakentamaan koko näytettävä merkkijono yhdeksi pompsiksi.
> GVT-3212 Also fix happy case rendering

- infra/src/main/kotlin/fi/fta/geoviite/infra/dataImport/CsvFile.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/Publication.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationLogService.kt
Pikku remppa dailyn sivuhuomiona: muutetaan julkaisuluokka dataluokaksi. Samalla bongattu kääntäjän deprekoinnit CSVFile-luokassa ja arveluttava autoclose-logiikka -> pikkuremppaa ilman toiminnallista muutosta. Tuosta CSVFileähän ei nykyisellään käytetä (tuon avulla tehtiin aikanaan alkumigroja), mutta se lienee ihan hyödyllistää säilyttää jos jatkossa tehdaan myös tuonteja CSV:llä.
> General: Refactor Publication as a data class + CSVFile deprecations & questionable autoclose

- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/switches/SwitchFittingService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/math/Range.kt
Pihvi: Lisätty tarkistus `segmentCrop.length().distance <= CROP_SLICE_SNAPPING_TOLERANCE`, ja jos on näin, annetaan vastauksena null. Funktion logiikka menee muuten niin, että tämä ei voi aiheuttaa aukkoja keskellä alignmenttia, eli ei tarvitse erikseen miettiä, pitäisikö tämä tarkistus jotenkin rajata vain reunimmaisiin segmentteihin.
> GVT-3204 Skip segments that end up too short in cropAlignment

- infra/src/main/kotlin/fi/fta/geoviite/infra/math/Angle.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/math/AngleTest.kt
interpolateAngleRads on uuden geokoodauksen kanssa tarvittava funktio. Ajattelin tuoda tämän jo mainiin, vaikka muuten uusi geokoodaus tulee vasta myöhemmin (ehkä paljon myöhemmin), koska tämä yhtenäistää Angle.kt:n funktioita:
- Kun interpolateAngleRads on olemassa, angleAvgRads on selvästikin sen erikoistapaus, ja varmaan ihan perffisyistäkin jees toteuttaa niin (entistoteutuksessa on monta trigonometriafunktiokutsua)
- ... mutta jotta angleAvgRads()ista tulisi yhä tasan oikea tulos, piti korjata normalizeDirectionRads toimimaan tarkemmin juuri speksinsä mukaan
- Ja tämä "tasan" oikea tulos on nyt yhdenmukaisesti niin, että myös angleAvgRads palauttaa tulokset aina juuri jaksolla [-PI,PI).
> GVT-3087 Introduce interpolateAngleRads

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/ReferenceLineService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationServiceIT.kt
Funktio salli jo aiemmin sellaisen tapauksen, että pituusmittauslinja löytyy mutta vain virallisesta paikannuspohjasta, joten ajattelin kohtuulliseksi synniksi sallia myös sen, että sitä ei löydy lainkaan: Tällä tavalla pysytään siinä, että ratanumeroilla on vain yksi draftinpoisto-operaatio, ja sillä päästään hyvään tilaan. Ongelma siis oli, että revertPublicationCandidates kaatuu siitä, että se kerkiää ensiksi poistaa pituusmittauslinjan, ja sitten ratanumeroa poistaessaan luulee pystyvänsä poistamaan sen jälleen.
> GVT-3259 Allow not finding a reference line in deleteDraftByTrackNumberId

- infra/src/main/kotlin/fi/fta/geoviite/api/tracklayout/v1/ExtLocationTrackCollectionServiceV1.kt
- infra/src/main/kotlin/fi/fta/geoviite/api/tracklayout/v1/ExtLocationTrackControllerV1.kt
- infra/src/main/kotlin/fi/fta/geoviite/api/tracklayout/v1/ExtLocationTrackServiceV1.kt
- infra/src/main/kotlin/fi/fta/geoviite/api/tracklayout/v1/ExtLocationTrackV1.kt
- infra/src/main/kotlin/fi/fta/geoviite/api/tracklayout/v1/ExtTrackLayoutConstantsV1.kt
- infra/src/main/kotlin/fi/fta/geoviite/api/tracklayout/v1/ExtTrackLayoutLoggingV1.kt
- infra/src/main/kotlin/fi/fta/geoviite/api/tracklayout/v1/ExtTrackNumberCollectionServiceV1.kt
- infra/src/main/kotlin/fi/fta/geoviite/api/tracklayout/v1/ExtTrackNumberControllerV1.kt
- infra/src/main/kotlin/fi/fta/geoviite/api/tracklayout/v1/ExtTrackNumberServiceV1.kt
- infra/src/main/kotlin/fi/fta/geoviite/api/tracklayout/v1/ExtTrackNumberV1.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationService.kt
Näiden kenttien käyttö koettiin hankaliksi käyttäjille, ja niiden uudelleennimeäminen on tässä vaiheessa vielä yksinkertaista.
Pari bugikorjausta ohessa, kommentoitu erikseen
> GVT-3267: Refactor track layout api parameter naming to reference start/end versions

- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/PlanLayoutCache.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationValidation.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationValidationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackGeometry.kt
- infra/src/main/resources/i18n/translations.fi.json
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationRatkoIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationValidationTest.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ratko/RatkoServiceIT.kt
Lisätty 3 uutta julkaisuvalidointia uuden malliselle raidegeometrialle:
- Jos edge on sisä-linkillä kiinni vaihteessa, toisenkin pään sisä-linkin täytyy olla kiinni samassa vaihteessa. Tämä oli alunperin init-tason validointi, mutta näitä on sekä historiadatassa että uudelleenlinkityksen välitiloissa (draftissa täytyy olla sallittu)
- Sama vaihde ei saa esiintyä useammassa eri kohdassa raidetta. Tämä olisi käytännössä tilanne jossa vaihteen osuuden keskellä on kohta joka ei liitykään vaihteeseen tai jossa sama vaihde olisi tupla-linkitettynä eri osiin raidetta. Tätä ei pysty nykyversiolla tuottamaan käyttöliittymältä
- WARN-tasolla: varoitetaan alle 1m raiteista, sillä niille ei voi laskea topologialinkkejä
Lisäksi raidegeometrian init-tason validointina nämä, eli tällaisia virheitä ei …
> GVT-3076 Topologiamallin uudet julkaisuvalidoinnit

- infra/src/main/resources/i18n/translations.fi.json
- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/testgroup1/PublicationLogSearchTestUI.kt
Julkaisulokin testi tutkii nyt aiempaan tapaan myös että julkaisuloki näyttää julkaisut vain valitulta aikaväliltä.
Kävin kaikki validaatioviestit läpi ja typistin "Sijaintiraide"-termit "Raide"-termiksi _kaikkialla muualla paitsi_ hiljattain tulleissa sijaintiraidetunnusvalidaatioissa. Näissä jätin "Sijaintiraidetunnus"-termin eloon siksi, että mielestäni kyseessä on kentän nimi. Tästä saa toki olla eri mieltä
> General: Julkaisulokin E2E-korjauksia ja "Sijaintiraide"-termin typistäminen "Raide"-termiin julkaisuvalidoinnin huomioissa

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrack.kt
- infra/src/main/resources/db/migration/prod/V122_03__restore_precalculated_location_track_description.sql
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackServiceIT.kt
- ui/src/track-layout/track-layout-model.tsx
Heitto. Epäilen vähän että tuleekohan tämäkään nyt olemaan lopullinen totuus, mutta onpahan nyt ainakin tässä haarassa kaikki tapaukset samassa paikassa. Tämä siis uusimman Karin sanoman mukaan, että "liikennepaikat tulevat tosiaan vapaatekstiosaan".
Migra on luonteeltaan tosin vähän tämänhetkistä SwitchName-parseria sallivampi, koska se ottaa mahdolliset vaihdenumeroiden jälkeiset merkkijonot vaan orjallisesti mukaan.
> GVT-3258 Make all dynamic location track descriptions consistent

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutAlignmentDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackService.kt
Oikeastaan ratkaistu 2 erillistä ongelmaa:
- Vaihdelinkitys linkitti kaikki vaihteeseen liittyvät raiteet ja koska nykyään raiteen poistossa ei poisteta vaihdelinkkejä, se käsitteli myös poistetut vaihteet. Tätä ei toki pitäisi muutenkaan tehdä, mutta erityisen ongelmallinen se oli jos kyseessä sattui olemaan splitattu raide, jolloin splitin kanta-tason varmistu source-trackin muuttumattomuudelle räjähti.
- Tein topologiamalliin noodeille & edgeille backariin hash->id cachen jolloin Tmp..Node ja Tmp..Edge tallennus osana locationtrack geometryä ei joutunut käymään kannassa lainkaan jos kyseessä oli sisällöltään sellainen Node/Edge että se löytyy jo kannasta jollain ID:llä. Tuo on kuitenkin ongelmallinen transaktioissa sillä se jää cacheen jos transaktio päädytään rollbackaamaan ja sen …
> General: Don't relink switches on deleted tracks + remove node/edge hash-id-cache as it's troublesome in transactions

- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutKmPostDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackDao.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationServiceIT.kt
Tässä funktiossa ei pidä käyttää tavallisia in_layout_context-sääntöjä käyttäviä hakuja, koska ne piilottavat cancelled-tilaiset rivit, ts. suunnitelmien muutosten perumiset. Toisaalta eipä noita fetchOnlyDraftVersions-funktioita myöskään tarvita, koska tämän funktion perffivaatimukset on sen verran olemattomat. Siksi voidaan yhtenäistää kaikki haut fetchCandidateVersions-pohjaisiksi. Pyörittelin myös tämän funktion järjestystä vähän muuten loogisemmaksi.
> GVT-3279&GVT-3280 Find revertable publication candidates with fetchCandidateVersions

- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/Publication.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationLogService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationLogServiceIT.kt
Täällä toteutettuna käytännössä tiketin varsinaiset pihvijutut. Ideana siis se, että julkaisulokin assettikohtainen haku on nyt muutettu palauttamaan ratanumerolla haettaessa myös pituusmittauslinjan rivit. Tämän lisäksi mahdollisuus ylipäätään hakea pelkän pituusmittauslinjan lokirivejä on poistettu. Näistä tosiaan aiheutui jonkin verran tyyppimuutoksia ja rename-tarpeita, joten vaikka uudet toiminnallisuudet ovatkin suht. simppeleitä, niin muutoksia on melko paljon. Näistä lisää kommenteissa ka. tiedostoissa.
Frontti jätetty ennalleen vielä tällä pullarilla. Aion tosin tehdä sinnekin vielä jonkinasteisia paranteluja (mm. linkit assettikohtaiseen julkaisulokiin myös pituusmittauslinjoille, joilta ne nyt vielä puuttuvat.) Nämä tosiaan tulevat myöhemmin omalla pullarillaan.
> GVT-3216: Pituusmittauslinjan käsittely ratanumeron julkaisulokinäkymässä

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutAlignmentDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackGeometry.kt
- infra/src/main/resources/db/migration/repeatable/R__10.01_layout_node_insert.sql
- infra/src/main/resources/db/migration/repeatable/R__10.02_layout_edge_insert.sql
Postgressi ei ole kovin hyvä käsittelemään isoja määriä temppitauluja, joten hillitään niiden käyttöä. Varsinainen asioita kaatava ongelma oli, että jos samassa transaktiossa tallennetaan riittävä määrä riittävän pitkiä raidegeometrioita (eli uusia noodeja ja edgejä), postgres luo temppitaulujen käsittelyjä varten niin määrättömästi lukkoja, että se alkaa paukkua muistirajoitteisiin.
Tosin toisin kuin alkuun suunnittelin, tässä ratkaisussa ei poisteta temppitauluja ihan kokonaan, koska en saanut paria vaihtoehtoa pyörittelemälläkään aikaan hyvää perffiä saveEdgesistä ilman että segmentit viedään omaan indeksoituun tauluunsa. Mutta tässäkin varmaan useimmissa tapauksissa on aika iso voitto, että temppitauluja luodaan kaksi per raide, eikä yksi per edge.
Eli perusajatus: Tehdään …
> GVT-3285 Raidegeometrian tallentamisen optimointeja

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutKmPostService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSearchController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSearchService.kt
- infra/src/main/resources/i18n/translations.fi.json
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSearchServiceIT.kt
- ui/src/main/main.tsx
- ui/src/map/plan-download/plan-download-area-section.tsx
- ui/src/publication/log/publication-log.tsx
- ui/src/publication/publication-details-container.tsx
- ui/src/publication/publication.tsx
- ui/src/publication/table/publication-table-row.tsx
- ui/src/publication/table/publication-table.tsx
- ui/src/tool-bar/search-dropdown.tsx
- ui/src/tool-bar/tool-bar.tsx
- ui/src/tool-panel/km-post/km-post-infobox.tsx
- ui/src/tool-panel/track-number/track-number-change-info-infobox.tsx
- ui/src/track-layout/track-layout-search-api.ts
Alkuperäisenä lisäkeideana part 1:n pihvin rinnalle oli lisätä pituusmittauslinjojen julkaisulokiriveille linkit ratanumerojen julkaisulokiin. Tämän myötä lähdin miettimään että oikeastaan kilometripylväillekin voisi sellaiset lisätä samaan rahaan, ja sen jälkeen totesin että niistä kannattaisi tehdä myös haettavia. Näistä viimeinen päätyikin olemaan aika paljon isompi eskalaatio kuin alunperin uskoinkaan.
> GVT-3216 Part 2: KM-pylväät haettaviksi, pituusmittauslinjoille ja km-pylväille linkit assettikohtaiseen julkaisulokiin

- infra/src/main/resources/i18n/translations.fi.json
- ui/src/publication/log/publication-log.tsx
- ui/src/publication/publication-model.ts
- ui/src/publication/publication-utils.ts
- ui/src/publication/publication.tsx
- ui/src/selection/selection-store.ts
- ui/src/tool-panel/km-post/km-post-infobox.tsx
- ui/src/tool-panel/location-track/location-track-change-info-infobox.tsx
- ui/src/tool-panel/switch/switch-change-info-infobox.tsx
- ui/src/tool-panel/track-number/track-number-change-info-infobox.tsx
- ui/src/utils/react-utils.tsx
- ui/src/vayla-design-lib/datepicker/datepicker.tsx
Hieman heitto, ja niin paljon asiaa muuttava kommitti että ehdottomasti mainin päälle: Jos tällaisia lähdetään yrittämään hotfix-haaraan, 1.19 julkaistaan vuonna 2027.
Nyt:
- globalStartDate/globalEndDate ja specificItemStartDate/specificItemEndDate ovat erillisiä tietoja
- molemmissa saa olla tyhjää ainakin jonkin verran. Jos haetaan yksittäisen olion muutoshistoriaa, molemmat saa olla tyhjiä. Pienenä adhoccina jos haun loppupäivä on tyhjä, se tulkitaan koko julkaisulokinkin puolella käytännössä vaan nykypäiväksi
- Kenttien tyhjentäminen itsessään onnistuu tällä hetkellä tosin ainoastaan tyhjentämällä teksti-inputti: En lisännyt tyhjentämisrukseja, koska näyttää kuitenkin vähän siltä, että tuskinpa niitä paljoa tarvitaan
- Useimmissa kohdissa, missä valitaan yksittäisen kohteen …
> GVT-3298 Separate out single-item search date ranges in publication log

- ui/src/publication/log/publication-log.tsx
Kaksi testien löytämää bugia, molemmat todellisia, tosin toinen hyvin pieni:
- Normaalitavan mukaan hakuvälin loppupäivän julkaisut tulee hakuun mukaan, koska muu maailma ei ole vielä kuullut Dijkstran hyvää sanomaa
- Vaikka (aiemmassa pullarissa mainitusti) epäsuora reagointi kenttien muutoksiin aiheuttaa vähän ylimääräisiä rendereitä, niin eihän se tarkoita, ettei loading-spinneriä pysty heittämään jo heti ensimmäisellä renderillä päälle. Tällöin testeissäkään ei tarvitse sitten säätää odotusaikoja että no tuliko se spinneri jo näkyviin vai missattiinko se kokonaan vai mitä.
> GVT-3298 Test-based fixes

- infra/src/test/kotlin/fi/fta/geoviite/infra/linking/switches/SwitchFittingTest.kt
Pelkkä kommentoidun jutun siivous, mutta pistän 1.19 kautta koska alkuperäinen TODO liittyy 1.19 muutoksien loppuselvityksiin (ja koska 1.19 on muutenkin julkaisu vielä tulossa).
> General: Clean up todo from new switch linking. This is handled in to pology linking.
