- infra/src/main/kotlin/fi/fta/geoviite/infra/dataImport/CsvParsing.kt
Poistin nyt vielä sittenkin sen jälkivalidoinnin, tosin ainoa paikka, jossa sain sen menemään rikki, oli dividePointSegmentsSkipsOverEmptyRanges, joka tarkoituksella testaa hieman oudompaa rajatapausta. Metriaineistojen sisäänluvussa sellaista tapausta ei näyttänyt olevan, että metadataväli putoaa kokonaan kahden raidepisteen väliin.
Näitä metritietoja ei käytetä muuhun kuin switch_start_joint_numberin ja switch_end_joint_numberin asettamiseen, eli ne ovat nyt vielä tähdellinen asia katsoa lopputestauksissa.
> GVT-1485 Only adjust range ends if they were connection segment points

- infra/src/main/kotlin/fi/fta/geoviite/infra/dataImport/CsvParsing.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/dataImport/CsvParsingTest.kt
Testien paikkaus + pull review koska testit dokumentoi tapahtuneen muutoksen ja voitaisiin käydä se vielä yhdessä läpi.
> General: Fix unit tests for CSV metadata combining logic

- infra/src/main/kotlin/fi/fta/geoviite/infra/dataImport/CsvParsing.kt
Filtteröinnistä johtuen vaihteiden pisteet eivät välttämättä osu ihan niihin osoitteisiin kun millä data tulee. Tästä aiheutui datan tippumista. Korjattu säätämällä vaihdepisteet läheiseen pisteeseen ja lisätty logitusta jotta poikkeamista jää jälki tarkastettavaksi.
> Fix switch link import

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackDao.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackServiceIT.kt
- ui/src/tool-panel/location-track/location-track-infobox.tsx
Jyrkin reviewissä huomaama asia.
> General: Filter location track duplicates by publishType sooner

- infra/src/main/kotlin/fi/fta/geoviite/infra/integration/IntegrationModels.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/integration/LockDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/integration/RatkoPushDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/ratko/RatkoClient.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/ratko/RatkoClientConfiguration.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/ratko/RatkoService.kt
- infra/src/main/resources/db/migration/prod/V21__in_progress_ratko_push_status.sql
- infra/src/test/kotlin/fi/fta/geoviite/infra/integration/RatkoPushDaoIT.kt
- ui/src/publication/publication-list.tsx
- ui/src/publication/publication-model.ts
Handlataan jumitustilanteet eli merkataan vanhat ratkoviennit valmistuneiksi mikäli tietokantalukko vapautuu.
> GVT-1498: Hanging Ratko pushes no longer prevent subsequent pushes

- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/pagemodel/map/MapToolPanelElement.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/testgroup2/LinkingTestUI.kt
It was no longer quite seeing the end of the geometry on the screen.
> General: Fix track geometry replacement test

- ui/src/app-bar/app-bar.scss
- ui/src/frontpage/frontpage.tsx
- ui/src/i18n/config.ts
- ui/src/user/translations.fi.json
- ui/src/user/user-card-container.tsx
- ui/src/user/user-card.scss
- ui/src/user/user-card.tsx
- ui/src/user/user-model.ts
Näytetään etusivulla kirjautuneen käyttäjän tiedot
> GVT-1508: Frontpage user card

- ui/src/frontpage/frontpage.tsx
- ui/src/publication/publication-details.tsx
- ui/src/utils/react-utils.tsx
Kahden eri komponentin käyttämä monilta osin identtinen koodi yhdistetty custom hook apufunktioksi.
> GVT-1492 add helper function useLoaderWithTimer

- infra/src/main/kotlin/fi/fta/geoviite/infra/geocoding/GeocodingDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/PublicationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/DraftableObjectDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/DraftableObjectService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutKmPostController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutKmPostDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutKmPostService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/ReferenceLineDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/ReferenceLineService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/util/DaoBase.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ITTestBase.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutKmPostDaoIT.kt
Tiketti: https://extranet.vayla.fi/jira/browse/GVT-1544
> GVT-1544 Unify delete-state filtering into DAO layer

- ui/src/publication/publication-table-item.tsx
- ui/src/publication/publication-table.tsx
> GVT-1518: Sarakkeiden järjestys muutokset-taulukossa

- ui/src/publication/publication-table-item.tsx
- ui/src/publication/publication-table-sorting.ts
- ui/src/publication/publication-table.tsx
- ui/src/track-layout/track-layout-store.ts
Jouduin tekemään tätä varten aika paljon refaktorointia ylipäätään tuolle publication-tablelle, eikä GitHub osaa näyttää diffejä siitä kauhean fiksusti. Sori siit 🥶
> GVT-1517: Muutokset-taulukon sorttaus

- ui/src/preview/change-table-entry-mapping.ts
- ui/src/preview/change-table-sorting.ts
- ui/src/preview/preview-table.tsx
- ui/src/publication/publication-table.tsx
- ui/src/track-layout/track-layout-store.ts
- ui/src/utils/array-utils.ts
Täällä pääasiassa korjattuna review-huomioita edellisiltä mun juttuihin liittyviltä tiketeiltä ja tehty pari pienempää refaktorointia
> GVT-1551: Publish-/Preview-taulukoiden refaktorointia, part 2

- ui/src/preview/preview-table-item.tsx
- ui/src/publication/publication-table-item.scss
https://extranet.vayla.fi/jira/browse/GVT-1547
> GVT-1547 Use pointer cursor in the actions column

- ui/src/publication/publication-card.tsx
Täydennys tikettiin [https://github.com/finnishtransportagency/geoviite/pull/63](https://github.com/finnishtransportagency/geoviite/pull/63)
Näytetään viesti virheestä Ratko-yhteydessä myös muulloin kuin sillon kun on feilaava julkaisu
> GVT-1520 Show Ratko connection error even without ratkoPushFail

- ui/package-lock.json
- ui/package.json
- ui/src/map/layers/alignment-layer.ts
- ui/src/map/layers/geometry-layer.ts
- ui/src/map/layers/layer-utils.ts
- ui/src/map/map-view.tsx
- ui/src/map/tools/measurement-tool.ts
Prettier iskenyt, muutokset täällä [ui/src/map/tools/measurement-tool.ts](https://github.com/finnishtransportagency/geoviite/compare/dev/GVT-1559?expand=1#diff-f59a9da4faaa07a2e85a75d443dd60b6c136f44f56d054b265fa25208e7d9ed8)
> GVT-1559: Measurement tool snaps to nearby alignments

- ui/src/selection-panel/geometry-plan-panel/geometry-plan-panel.tsx
Suunnitelman sisältöä ei välttämättä heti suoraan ladata, mutta tässä koodissa yritettiin katsoa sisällön perusteella, onko otsikko valittu. Kartalla geometriat näkyikin jo oikein.
> GVT-1391 Fix plan header visibility

- ui/src/tool-bar/tool-bar.tsx
getOptions is a long enough function that I moved it out of the component scope to ensure any future data dependencies are explicit.
> GVT-1513 Fix search bar's missing data dependency on publishType

- infra/src/main/kotlin/fi/fta/geoviite/infra/integration/CalculatedChangesService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/integration/ChangeContext.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackDao.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ITTestBase.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/geocoding/GeocodingDaoIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutKmPostDaoIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchDaoIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberDaoIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackDaoIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/TrackLayoutDomainTestData.kt
Pieni lisäkorjaus (edellisen reviewin TODO) + kasa testejä DAO funktiolle
> GVT-1568 part 2

- infra/src/main/kotlin/fi/fta/geoviite/infra/geocoding/GeocodingDao.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/geocoding/GeocodingDaoIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/TrackLayoutDomainTestData.kt
Ignoroidaan deleted-tilaiset rivit geocoding context fetchissä
> GVT-1568 Don't include deleted things in geocoding context fetch by-moment

- infra/src/main/kotlin/fi/fta/geoviite/infra/integration/RatkoPushDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/ratko/RatkoService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/util/NamedParameterJdbcTemplateExternal.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/integration/RatkoPushDaoIT.kt
Liittyen Tiandun kommenttiin edellisessä reviewissä
> GVT-1534 Use only DB-times in ratko push DAO

- infra/src/main/kotlin/fi/fta/geoviite/infra/integration/RatkoPushDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/Publication.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/PublicationController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/PublicationDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/PublicationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/ratko/RatkoService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutKmPostDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/ReferenceLineDao.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/integration/RatkoPushDaoIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/linking/LinkingDomainTestData.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/linking/PublicationServiceIT.kt
- ui/src/frontpage/frontpage.tsx
- ui/src/preview/change-table-entry-mapping.ts
- ui/src/preview/preview-table.tsx
- ui/src/publication/publication-api.ts
- ui/src/publication/publication-details.tsx
- ui/src/publication/publication-model.ts
- ui/src/publication/publication-table-item.tsx
- ui/src/publication/publication-table.tsx
Yhtenäistin samalla publication modelit.
Jatkossa julkaisuloki sekä etusivulla näytettävät julkaisut käyttävät samoja rajapintoja ja modeleita.
> GVT-1564: API for fetching publications by date range

- infra/src/main/kotlin/fi/fta/geoviite/infra/geocoding/GeocodingDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/DraftableObjectDao.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/integration/RatkoPushDaoIT.kt
> GVT-1568 Fix SQL to use a cleaner style

- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/PublicationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/PublicationValidation.kt
Jos yritetään julkaista vaihdetta, joka on linkitetty locationtrackeihin, käyttäjälle ilmoitetaan virhe ja julkaisu estetään.
> GVT-1595 add dependency validation for staged switch publication

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/DraftableObjectService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberController.kt
- ui/src/publication/table/publication-table.tsx
- ui/src/track-layout/layout-track-number-api.ts
- ui/src/track-layout/track-layout-react-utils.tsx
Muualla pinossa näytti ookoolta passata includeDeletediä vaan totuusarvona, mutta koukun kohdalla olemassaolevat kutsut olisivat voineet käydä hieman hämärän näköisiksi, joten lisäsin sille vaan uuden erikseen nimetyn variantin.
> GVT-1615 Include deleted track numbers in publication log fetch

- infra/src/main/kotlin/fi/fta/geoviite/infra/dataImport/CsvParsing.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/dataImport/InfraModelMigration.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geography/CoordinateTransformationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geography/GeoToolsGeometries.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geography/KKJToETRSTransformation.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/BoundingPolygon.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryPlan.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/inframodel/InfraModelService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/SwitchLinkingService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/geometry/TransformationTest.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/inframodel/InfraModelParsingIT.kt
Pääasiassa täällä on refaktoroitu Transformation-luokan rakentaminen edellisen reviewin kommenttien mukaiseksi. Samalla on tehty pienempiä asioita, kanssa pääasiassa review-kommenttien mukaisesti
> GVT-1610: Review-korjauksia koordinaattimuunnoksiin

- infra/src/main/kotlin/fi/fta/geoviite/infra/geography/CoordinateTransformationService.kt
Pari juttua unohtui aiemmalta PR:ltä. Ne täällä
> GVT-1610: Transformationin haun korjaus

- infra/src/main/kotlin/fi/fta/geoviite/infra/geocoding/Geocoding.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/integration/CalculatedChangesService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/LinkingController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/SwitchLinkingService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/math/Line.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/ratko/RatkoClient.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/Draft.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/ReferenceLineService.kt
Yhdestä !! käyttöpaikasta lensi NPE devillä - tässä korjattu se ja samalla rempattu vähän muita !! käyttöpaikkoja
> GVT-1623 Replace !! usage with proper null handling

- infra/src/main/kotlin/fi/fta/geoviite/infra/integration/CalculatedChangesService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/integration/ChangeContext.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/PublicationService.kt
Säädin ChangeContextin rajapintaa juuri ja juuri sen verran, että pidetään yhä oletuksena, että kyllä ne afterVersiot löytyy *melkein* aina. Mutta ei juuri tässä tapauksessa. Sisälmysten muutokset muuten pitkälti sitä varten, että saa tuon yhden NoSuchEntityExceptionin heiton debuggausystävällisemmäksi.
> GVT-1614 Fix validation errors when trying to publish location track with no track number

- ui/src/app-bar/app-bar.scss
- ui/src/app-bar/app-bar.tsx
- ui/src/app-bar/translations.fi.json
- ui/src/i18n/config.ts
Täällä toteutettuna app-bariin menu, josta aukeaa linkit elementtilistaan, vaakageometrioihin ja kilometrien pituuksiin. Linkkien avaamista ei itsessään ole vielä toteutettu. Samalla tuli käännettyä AppBarin sisältö.
> GVT-1632: UI: Päävalikkoon uusi osio ja Elementtiluettelo-linkki

- infra/src/main/kotlin/fi/fta/geoviite/infra/integration/AddressChangesService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/integration/AddressChangesServiceIT.kt
Tämä toteutus sillä perusteella, että taskilla oli tällaista näemmä jo ajateltu; näytti ainakin lokaali-Ratkoon menevän ihan läpi.
> GVT-1606 Consider deleted tracks previously inexistent in address change calculation

- ui/package-lock.json
- ui/package.json
- ui/src/infra-model/list/infra-model-list.module.scss
- ui/src/infra-model/list/infra-model-search-form.tsx
- ui/src/infra-model/translations.fi.json
Löytyikin komponentti joka ainakin nähdäkseni täyttää kaikki meidän tarpeet. Samalla kuollutta / react-select-spesifistä koodia poistui paljon.
> GVT-1519: React-selectin korvaaminen

- ui/package-lock.json
- ui/package.json
- ui/src/index.html
- ui/src/main/main.tsx
- ui/webpack.config.js
Lähdin tutkimaan saisiko fontit preloadattua jotenkin käsin, jotta ei tarvisi tukeutua nyt jo vanhaan ja bugiseen bundlausplugariin. Turns out, tämä oli ihan mahdollista.
> GVT-1650: Fonttien parempi preload

- ui/src/data-products/element-list/continuous-geometry-search.tsx
- ui/src/data-products/element-list/element-list-store.ts
- ui/src/data-products/element-list/element-list-view.scss
- ui/src/data-products/element-list/element-list-view.tsx
- ui/src/data-products/element-list/plan-geometry-search.tsx
- ui/src/data-products/translations.fi.json
- ui/src/geometry/geometry-api.ts
Tehty Tarun branchin päälle
Näissä kahdessa tiketissä oli sen verran paljon overlappia, että totesin että helpointa lienee vaan hoitaa molemmat kerralla samassa branchissa. Pahoittelut isosta reviewistä
> GVT-1634 & GVT-1637: Elementtilistan haku-UI:t

- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/Publication.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/PublicationController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/PublicationDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/PublicationService.kt
- infra/src/main/resources/db/migration/prod/V24__add_message_to_publication.sql
- infra/src/test/kotlin/fi/fta/geoviite/infra/integration/RatkoPushDaoIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/linking/LinkingDomainTestData.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/linking/PublicationDaoIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/linking/PublicationServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ratko/RatkoServiceIT.kt
- ui/src/preview/preview-confirm-revert-changes-dialog.tsx
- ui/src/preview/preview-footer.tsx
- ui/src/preview/preview-view.scss
- ui/src/preview/preview-view.tsx
- ui/src/preview/translations.fi.json
- ui/src/publication/publication-api.ts
- ui/src/track-layout/track-layout-store.ts
Täällä toteutettu tietokantacolumni ja UI selitteen antamiselle julkaisuissa
> GVT-1661: Julkaisun selitteen syöttäminen

- ui/src/map/layers/layer-utils.ts
- ui/src/utils/array-utils.ts
Kunkin muutoksen detaljit kommittiviesteissä.
> GVT-1664 UI-optimointeja

- ui/src/publication/table/publication-table-row.tsx
- ui/src/publication/table/publication-table-utils.ts
- ui/src/publication/table/publication-table.scss
- ui/src/publication/table/publication-table.tsx
- ui/src/publication/translations.fi.json
- ui/src/vayla-design-lib/icon/Icon.tsx
- ui/src/vayla-design-lib/icon/glyphs/navigation/exit-fullscreen.svg
- ui/src/vayla-design-lib/icon/glyphs/navigation/fullscreen.svg
- ui/src/vayla-design-lib/text-area/text-area.tsx
Täällä mm. korjaus siihen, että Textarea ei enää pakota defaulttina 50 merkin maksimipituutta. Myös toteutettu expand/collapse julkaisun selitteelle
> GVT-1662: Korjauksia

- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/Publication.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/PublicationDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/PublicationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutKmPostDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/ReferenceLineDao.kt
- infra/src/main/resources/db/migration/prod/V25__segment_version_switch_id_index.sql
- infra/src/test/kotlin/fi/fta/geoviite/infra/integration/RatkoPushDaoIT.kt
- ui/src/publication/publication-model.ts
- ui/src/publication/table/publication-table-row.tsx
- ui/src/publication/table/publication-table-utils.ts
- ui/src/publication/translations.fi.json
Uusi pullari vanhasta pullarista #150
Korjaus tehty ratanumeroiden hakuun, kohdat kommentoitu
> GVT-1584: Publication calculated changes

- ui/src/publication/log/publication-log-view.tsx
- ui/src/publication/translations.fi.json
Päivämäärät muutettu `FieldLayout`:eiksi elementtilistan tyyliin ja lisätty validaatio
> GVT-1681: Julkaisuloki-näkymässä on mahdollista asettaa loppupvm ennen alkupvm

- ui/src/vayla-design-lib/dialog/dialog.tsx
Mahdollistetaan draggaaminen ainoastaan hiiren primäärinapilla.
> GVT-1407: Korjaus dialogien draggaamiseen

- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/Publication.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/PublicationController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/PublicationDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/PublicationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/DraftableObjectDao.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/linking/PublicationServiceIT.kt
- ui/src/preview/preview-view.tsx
+ also minor fixes to backend validation: avoid unnecessary round-trips to DB
> GVT-1628 Fix validation to use staged set of candidates

- ui/src/preview/calculated-changes-view.tsx
- ui/src/preview/preview-confirm-revert-changes-dialog.tsx
- ui/src/preview/preview-container.tsx
- ui/src/preview/preview-footer.tsx
- ui/src/preview/preview-view.tsx
- ui/src/publication/publication-api.ts
- ui/src/publication/publication-model.ts
- ui/src/track-layout/track-layout-store.ts
Siirretty PublishRequest publication-model:n alle ja poistettu samansisältöinen duplikaattiolio.
> GVT-1673 Remove dead code & duplicated types

- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/Publication.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/PublicationController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/PublicationCsv.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/PublicationDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/PublicationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/util/CSVPrintingUtils.kt
- ui/src/frontpage/frontpage.tsx
- ui/src/preview/change-table-entry-mapping.ts
- ui/src/preview/change-table-sorting.ts
- ui/src/preview/preview-confirm-revert-changes-dialog.tsx
- ui/src/preview/preview-table.tsx
- ui/src/publication/card/publication-card.tsx
- ui/src/publication/card/publication-list.scss
- ui/src/publication/card/publication-list.tsx
- ui/src/publication/log/publication-log-view.tsx
- ui/src/publication/log/publication-log.scss
- ui/src/publication/log/publication-log.tsx
- ui/src/publication/publication-api.ts
- ui/src/publication/publication-model.ts
- ui/src/publication/publication.scss
- ui/src/publication/publication.tsx
- ui/src/publication/table/publication-table-row.tsx
- ui/src/publication/table/publication-table-utils.ts
- ui/src/publication/table/publication-table.scss
- ui/src/publication/table/publication-table.tsx
- ui/src/publication/translations.fi.json
- ui/src/ratko/ratko-push-error.tsx
- ui/src/vayla-design-lib/table/table.tsx
+ pientä refaktorointia, kommentoituna tärkeimmät tiedostot.
> GVT-1680: Publication log paging

- ui/src/infra-model/list/infra-model-search-form.tsx
https://extranet.vayla.fi/jira/browse/GVT-1692
> GVT-1692 Don't clear the search term from InfraModel search

- infra/src/main/resources/db/migration/prod/V26__remove_geoviite_from_geometry_plan_source.sql
Eipäs koitetakaan disabloida/enabloida koko maailmaa, vaan fiksataan halutut triggerit käsin
> GVT-1686: Migraatiokorjaus

- infra/src/main/kotlin/fi/fta/geoviite/infra/inframodel/InfraModelController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/inframodel/InfraModelParsing.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/inframodel/InfraModelService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/logging/LoggerExternal.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/util/XmlUtils.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/geography/KkjToEtrsTriangulationDaoIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/inframodel/InfraModelFileTest.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/inframodel/InfraModelParsingIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/inframodel/InfraModelServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/util/XMLUtilsTest.kt
- ui/src/infra-model/infra-model-store.ts
- ui/src/infra-model/view/infra-model-view.tsx
Tuli toisessa reviewissä puhe enkoodaus charseting välittämisestä enumina joten refaktoroin sitä. Samalla vähän rakenteen pyörittelyä backariin jotta olisi hiukan loogisempi sekä fronttiin ja sulkunappien korjaus enkoodauksen valintadialogeissa.
Ei oikeasti niin iso muutos kun miltä näyttää, paljon on vain testien siirtelyä tiedostojen välillä. Kommentoin oleelliset.
> General: refactor inframodel upload backend + fix fronted error dialog close buttons

- ui/src/index.html
- ui/webpack.config.js
Tiketillä ei oltu speksattu tarkemmin että mikä olisi hyvä logo. Nappasin nyt Geoviitteen logon faviconiksi.
> GVT-745: Favicon

- ui/src/data-products/element-list/element-table-item.tsx
- ui/src/data-products/element-list/geometry-plan-name-link.tsx
> GVT-1718 Move link inside a separate component

- ui/src/index.html
- ui/webpack.config.js
Aiempi ei toiminut kuin lokaalisti. Nyt vaihdettu tämä niin, että HtmlWebpackPlugin generoi pathin faviconiin
> GVT-745: Favicon, yritys 2

- ui/src/data-products/element-list/geometry-plan-name-link.tsx
Use a real link that can be opened to a new tab
> GVT-1718 Plan name in element list: use a real link 

- .github/workflows/pull_request.yml
Reverts finnishtransportagency/geoviite#257
> Revert "GVT-1297 Run more unit tests"

- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryService.kt
- ui/src/geometry/geometry-api.ts
- ui/src/infra-model/view/dialogs/new-project-dialog.tsx
- ui/src/infra-model/view/form/fields/infra-model-project-field.tsx
- ui/src/infra-model/view/form/infra-model-form.tsx
Täällä toteutettu:
* Erillinen komponentti projektidropdownin näyttämiseen
* Viety oikeasti koko projektilistausta tarvivien juttujen projektihaut ka. komponentteihin (projektidropdown ja uuden projektin luontidialogi)
* Luotu bäkkärille uusi endpointti yksittäisen projektin hakemiseen
> GVT-1144: Optimoi projektien haku

- infra/src/test/kotlin/fi/fta/geoviite/infra/ratko/FakeRatko.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ratko/RatkoServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/TrackLayoutDomainTestData.kt
Vähän lisää testejä että toimiihan Ratko-integraatio oikein, aikalailla sillä tavalla tehtynä, että oletuksena se tällä hetkellä toimii oikein.
Review-kommenttien lisäksi ajatuksia otetaan mielellään vastaan siitä, mitkä asiat Ratko-integraatiossa eritoten tuntuvat pelottavilta ja että missä on tapahtunut aiemmin regressioita.
> GVT-1690 Add some more Ratko tests

- ui/src/data-products/data-product-table.scss
- ui/src/data-products/data-products-utils.ts
- ui/src/data-products/element-list/element-table-item.tsx
- ui/src/data-products/element-list/element-table.tsx
- ui/src/data-products/translations.fi.json
- ui/src/data-products/vertical-geometry/vertical-geometry-table-item.tsx
- ui/src/data-products/vertical-geometry/vertical-geometry-table.tsx
- ui/src/data-products/vertical-geometry/vertical-geometry-view.tsx
- ui/src/geometry/geometry-model.ts
- ui/src/utils/rounding.ts
Tehty haku-UI-branchin pohjalta
> GVT-1736: UI: Pystygeometria-sivun taulukko

- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryDao.kt
- ui/src/app-bar/app-bar.scss
- ui/src/app-bar/app-bar.tsx
https://extranet.vayla.fi/jira/browse/GVT-1758
> GVT-1759 Use correct styles in "Data products" heading when it is active

- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/VerticalGeometryListing.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/geometry/VerticalGeometryListingTest.kt
Pitäis oppia ajamaan aina testit ennen puskua 😭
> Pystygeometriakorjauksia

- ui/src/map/layers/alignment-layer.ts
Aikaisemmin highlightattiin myös ratanumero vaikka kursori oli ainoastaan sijaintiraiteen päällä
> GVT-1778: Highlight track numbers only when the cursor is near reference lines

- infra/src/test/kotlin/fi/fta/geoviite/infra/geometry/VerticalGeometryListingTest.kt
> GVT-1779: Testien korjaus

- ui/src/data-products/element-list/location-track-element-listing-search.tsx
- ui/src/data-products/element-list/plan-geometry-element-listing-search.tsx
- ui/src/data-products/kilometer-lengths/kilometer-lengths-search.tsx
- ui/src/data-products/translations.fi.json
- ui/src/data-products/vertical-geometry/location-track-vertical-geometry-search.tsx
- ui/src/data-products/vertical-geometry/plan-vertical-geometry-search.tsx
Korjauksia tämän reviewin https://github.com/finnishtransportagency/geoviite/pull/313 kommentteihin
> General: Review-korjauksia kilometrien pituuksien tietotuotenäkymään

- ui/src/publication/card/publication-list.scss
- ui/src/tool-panel/geometry-alignment/geometry-alignment-infobox.scss
- ui/src/tool-panel/geometry-alignment/geometry-alignment-linking-candidates.tsx
- ui/src/tool-panel/geometry-alignment/geometry-alignment-linking-infobox.tsx
- ui/src/tool-panel/geometry-alignment/linked-items-list.scss
- ui/src/tool-panel/geometry-alignment/location-track-names.tsx
- ui/src/tool-panel/geometry-alignment/reference-line-names.tsx
- ui/src/tool-panel/switch/geometry-switch-linking-candidates.tsx
- ui/src/tool-panel/switch/switch-infobox.scss
- ui/src/tool-panel/switch/switch-joint-infobox.tsx
- ui/src/tool-panel/translations.fi.json
+ Badgeista on jossain vaiheessa lähtenyt marginit
> GVT-1799: Show "empty text" when there are no linkable switches/location tracks/reference lines

- ui/src/selection-panel/location-track-panel/location-tracks-panel.tsx
En ole varma onko tämäkään lopullinen ratkaisu, mutta toimii nyt jota kuinkin näin:
1. Jos raiteita on alle 16 -> näytetään kaikki raiteet,
2. Jos raiteita on yli sallitun (48 kpl) -> pyydetään käyttäjää zoomaamaan lähemmäs,
3. Jos taas raiteita on välillä 16 - 48:
1. Jos mitään ole valittuna taikka valittu raide on 16. joukossa -> käyttäjä saa päättää näytetäänkö 16 vai 48. 
2. Muulloin näytetään kaikki (max 48)
> GVT-1820: Keep selected location tracks visible when panning

- ui/src/vertical-geometry/pvi-geometry.tsx
Ei kummempaa kuin että tuo radiaanien kertominen kuvasuhteella sattui vain vahingossa antamaan läheskään oikeanlaisia tuloksia.
> GVT-1838 Fix PVI angle text rendering angle

- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationService.kt
- ui/src/preview/calculated-changes-view.scss
- ui/src/preview/calculated-changes-view.tsx
- ui/src/preview/translations.fi.json
Kaksi suurempaa muutosta:
1. Vaihteen validoinnissa huomioi myös ne luonnostilaiset raiteet, jotka ovat olleet osa vaihteen geometriaa
2. Esikatselunäkymässä ei näytetty kaikkia laskettuja muutoksia mikäli raiteen ratanumero ei ole muuttuneiden joukossa
> GVT-1826: Switch validation & show all calculated changes

- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/Publication.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/TrackLayout.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberServiceIT.kt
- ui/src/app-bar/app-bar.tsx
- ui/src/data-products/data-products-slice.ts
- ui/src/data-products/kilometer-lengths/kilometer-lengths-search.tsx
- ui/src/data-products/kilometer-lengths/kilometer-lengths-table.tsx
- ui/src/data-products/kilometer-lengths/kilometer-lengths-view.tsx
- ui/src/tool-panel/infobox/infobox-field.tsx
- ui/src/tool-panel/location-track/location-track-infobox.tsx
- ui/src/tool-panel/switch/geometry-switch-linking-initiation.tsx
- ui/src/track-layout/layout-km-post-api.ts
- ui/src/track-layout/track-layout-model.tsx
> General: Rename km length methods and remove env restrict from km length view

- ui/src/vertical-geometry/height-tooltip.tsx
- ui/src/vertical-geometry/snapped-point.ts
- ui/src/vertical-geometry/vertical-geometry-diagram.tsx
Kommitit huomattavasti helppolukuisempia erillään
> GVT-1832 Clarify PVI point linking

- infra/src/main/kotlin/fi/fta/geoviite/infra/velho/VelhoClient.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/velho/VelhoClientConfiguration.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/velho/VelhoDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/velho/VelhoModel.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/velho/VelhoService.kt
- infra/src/main/resources/db/migration/prod/V39__add_projektivelho_integration.sql
Tämä on vielä aika kesken, mutta mergaan tämän nyt enivei kun aika loppui kesken. Ei pitäISI olla mitään rikkovaa. Korjailen näitä sitten kun palaan taas töihin. Täällä tehty:
* Koodiston haku ja tallennus kantaan
* Projektin, projektijoukon ja toimeksiannon haku (ei vielä toimi, rajapinta palauttaa outouksia)
* Tuki gzipatulle sisällölle (kosmiset bugit johtuivat siitä, että sitä ei handlattu defaulttina)
> GVT-1860: ProjektiVelhon koodisto (and then some)

- ui/src/app-bar/app-bar.scss
- ui/src/app-bar/app-bar.tsx
- ui/src/app-bar/infra-model-link.tsx
- ui/src/geoviite-design-lib/exclamation-point/exclamation-point.scss
- ui/src/infra-model/tabs/infra-model-tab-nav-item.tsx
- ui/src/infra-model/tabs/infra-model-tabs.tsx
Lisätty punainen pallo InfraModel-otsikon viereen, korjattu bugi url-käsittelyssä, sekä muuta pientä refaktorointia.
> GVT-1791 Add exclamation point next to InfraModel link

- ui/src/geoviite-design-lib/exclamation-point/exclamation-point.scss
- ui/src/infra-model/tabs/infra-model-tab-nav-item.tsx
- ui/src/infra-model/tabs/infra-model-tabs.scss
- ui/src/infra-model/tabs/infra-model-tabs.tsx
> GVT-1791 Tabs review fixes

- ui/src/app-bar/app-bar.scss
- ui/src/app-bar/app-bar.tsx
ks https://github.com/finnishtransportagency/geoviite/pull/446
> GVT-1883 Review fixes

- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryService.kt
- ui/src/data-products/vertical-geometry/location-track-vertical-geometry-search.tsx
- ui/src/data-products/vertical-geometry/plan-vertical-geometry-search.tsx
- ui/src/geometry/geometry-api.ts
- ui/src/vertical-geometry/vertical-geometry-diagram.tsx
Other users of the API seem to not really need caching here, so I made it optional.
> GVT-1842 Cache PVI geometry lookups for vertical geometry diagram

- ui/src/track-layout/track-layout-view.tsx
Separate useMemos so that changing publishType doesn't reload a selected plan alignment.
> GVT-1872 Display height diagram for plan alignments as well

- ui/src/infra-model/view/infra-model-view.tsx
- ui/src/linking/linking-store.ts
- ui/src/map/layers/alignment/badge-layer-utils.ts
- ui/src/map/layers/alignment/location-track-alignment-layer.ts
- ui/src/map/layers/alignment/reference-line-alignment-layer.ts
- ui/src/map/layers/geometry/geometry-alignment-layer.ts
- ui/src/map/layers/km-post/km-post-layer.ts
- ui/src/map/layers/switch/switch-layer.ts
- ui/src/map/map-store.ts
- ui/src/map/map-view.tsx
- ui/src/selection-panel/geometry-plan-panel/geometry-plan-panel.tsx
- ui/src/selection-panel/selection-panel.tsx
- ui/src/selection/selection-store.ts
- ui/src/tool-panel/geometry-alignment/geometry-alignment-linking-container.tsx
- ui/src/tool-panel/km-post/geometry-km-post-infobox-linking-container.tsx
- ui/src/tool-panel/location-track/location-track-infobox-linking-container.tsx
- ui/src/tool-panel/switch/geometry-switch-linking-container.tsx
- ui/src/tool-panel/tool-panel-container.tsx
- ui/src/tool-panel/tool-panel.tsx
- ui/src/tool-panel/track-number/track-number-infobox-linking-container.tsx
- ui/src/track-layout/track-layout-slice.ts
... kun aloitetaan linkitys tai kun valitaan suunnitelman raiteita/vaiheita yms. vasemmasta valikosta
> GVT-1885: Auto toggle map layer visibilities

- ui/src/vertical-geometry/vertical-geometry-diagram.tsx
Geometrioiden pystygeometriakuvaajassa ei näkynyt PVI-pisteitä, koska eihän niillä ole linkingSummaryä.
> GVT-1872 Fix displaying PVI points on geometry alignments on height diagram

- infra/src/main/kotlin/fi/fta/geoviite/infra/projektivelho/PVApi.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/projektivelho/PVClient.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/projektivelho/PVSearchJsonUtils.kt
Päädyin tekemään tämän pääasiassa funktiomallilla. Mielestäni tästä tuli jopa ihan semiluettava. Tällä hetkellä hakuehdoista katetaan ainoastaan ne mitä meidän alkuperäisessä JSONissa oli, mutta uusia voi lisätä tarpeen mukaan helpolla.
> GVT-1884: Projektivelhon haku-jsonin rakenteellisuus

- ui/src/infra-model/velho/velho-file-list.tsx
Jos näyttää, että syy, miksi ollaan lataamassa Velho-tiedostolistaa, on suora käyttäjän interaktio, niin näytetään lista normaalisti eikä harmaannettuna. Täydellinenhän tämä logiikka ei ole, mutta eipä sen oikein ole tarve ollakaan.
> GVT-1909 Avoid flickering when interacting with Velho file list

- ui/src/main/main.tsx
- ui/src/user/write-access-required.tsx
https://extranet.vayla.fi/jira/browse/GVT-1898
> GVT-1989 Move privilege setter to main

- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/CsvTranslations.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/integration/LockDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/ElementListingFileDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/util/CSVPrintingUtils.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/util/FileName.kt
- infra/src/main/resources/application.yml
- infra/src/main/resources/db/migration/prod/V39__add_element_listing_file_table.sql
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/ElementListingFileDaoIT.kt
- ui/src/api/api-fetch.ts
- ui/src/data-products/data-product-view.scss
- ui/src/data-products/data-products-slice.ts
- ui/src/data-products/element-list/element-list-view.tsx
- ui/src/data-products/element-list/entire-rail-network-element-listing.tsx
- ui/src/data-products/translations.fi.json
- ui/src/geometry/geometry-api.ts
Yhteiskoodauksena Jyrkin kanssa toteutettu. Käytänössä päädyttiin ratkaisuun, jossa listaus generoidaan joka yö (klo 03 aamuyöstä), tallennetaan kantaan, ja sen jälkeen ka. tiedosto servataan sieltä. Tällöin operaattori saa tiedoston ilman odottelua, vaikkakin sen tiedot voivat olla hieman vanhentuneita
> GVT-1906: Koko rataverkon geometriaelementit

- ui/src/map/layers/highlight/plan-section-highlight-layer.ts
Olin tehnyt nämä jo ennen PR:n mergeä, mutta unohdin sitten commitoida ne 🙈
> GVT-1789: Unohtuneet renamet

- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/geometry/GeometryServiceIT.kt
Jätin kommittiviestiin nälkävuoden mittaisen selostuksen siitä, mikä tässä meni vikaan, eihän sen debuggaukseen nimittäin kuin mennytkään kuin vaan koko päivä.
> GVT-1922 Fix km heights when connection segment ends right before km post

- infra/src/test/kotlin/fi/fta/geoviite/infra/ratko/FakeRatko.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ratko/RatkoServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ratko/TestRatkoAsset.kt
Jonkin verran myös laajennettu FakeRatkon toimintaa, ja siinähän on luonnollisesti tässä rakenteessa paineita mallintaa yhä enemmän koko Ratkoa; pyrin nyt sentään välttämään sitä, että mentäisiin siihen asti, että se lähtisi itse päivittämään tilanteensa sen perusteella, mitä testi on sinne puskenut.
> GVT-1760 Add more Ratko tests

- infra/src/main/kotlin/fi/fta/geoviite/infra/geocoding/Geocoding.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/integration/CalculatedChangesService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutAlignmentService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/geocoding/GeocodingTest.kt
- ui/src/map/layers/highlight/plan-section-highlight-layer.ts
- ui/src/map/map-store.ts
- ui/src/map/map-view.tsx
- ui/src/tool-panel/alignment-plan-section-infobox-content.tsx
- ui/src/tool-panel/location-track/location-track-geometry-infobox.tsx
- ui/src/tool-panel/location-track/location-track-infobox-linking-container.tsx
- ui/src/tool-panel/location-track/location-track-infobox.tsx
- ui/src/tool-panel/tool-panel-container.tsx
- ui/src/tool-panel/tool-panel.tsx
- ui/src/tool-panel/track-number/track-number-geometry-infobox.tsx
- ui/src/tool-panel/track-number/track-number-infobox-linking-container.tsx
- ui/src/tool-panel/track-number/track-number-infobox.tsx
- ui/src/track-layout/track-layout-view.tsx
Silloin tuntee aina tehneensä jotain lähtökohtaisestikin oikein kun reviewkorjausbranchissa on enemmän muutoksia kuin alkuperäisessä featurebranchissa 🚀
> GVT-1789: Review-korjauksia

- infra/src/main/kotlin/fi/fta/geoviite/infra/inframodel/InfraModelConversion.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/projektivelho/PVApi.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/projektivelho/PVClient.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/projektivelho/PVDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/projektivelho/PVDocument.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/projektivelho/PVIntegrationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/util/FileName.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/util/ResultSetExternal.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/util/SanitizedString.kt
- infra/src/main/resources/db/migration/prod/V41__add_projektivelho_integration.sql
- infra/src/test/kotlin/fi/fta/geoviite/infra/util/SanitizedStringTest.kt
- ui/src/i18n/fi/fi.json
Täällä useampia pienehköjä korjauksia. Näillä projektivelhon aineisto tuntuisi importtautuvan viimeisen vuoden ajalta.
> GVT-1944: Projektivelhointegraatio ei osaa jatkaa jos tiedoston haussa tapahtuu virhe

- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryService.kt
Logiikassa ei muutu mitään muuta kuin että tarkistetaan geometriasuunnitelman muuttumisen sijasta geometriaraiteen muuttumista. Rataverkossa on parisenkymmentä kohtaa, joissa on linkitetty peräkkäin samalta suunnitelmalta samalle sijaintiraiteelle eri geometriaraiteita, joista toisella on korkeusprofiili ja toisella ei.
> GVT-1998 Add height ticks around alignment, not just plan boundaries

- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/testgroup1/LinkingTestUI.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/testgroup2/BasicMapTestUI.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/testgroup2/InfraModelTestUI.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/testgroup2/SearchTestUI.kt
Testigrouppien sisällön swap. Testataan onko testgroup2 edelleen se joka hajoaa
> GVT-2007: E2E-testit hajoavat gradlen lukkotiedostoon

- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/testgroup1/BasicMapTestUI.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/testgroup1/InfraModelTestUI.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/testgroup1/SearchTestUI.kt
Testi menisivätkö testit nyt läpi
> GVT-2007: E2E-testit hajoavat gradlen lukkotiedostoon (testgroupien merge)

- ui/src/api/api-fetch.ts
- ui/src/cache/cache.ts
- ui/src/map/layers/utils/km-post-layer-utils.ts
- ui/src/selection-panel/geometry-plan-panel/geometry-plan-panel.tsx
- ui/src/selection-panel/selection-panel-geometry-section.tsx
- ui/src/selection-panel/selection-panel.tsx
- ui/src/selection/selection-model.ts
- ui/src/selection/selection-store.ts
- ui/src/tool-panel/tool-panel.tsx
- ui/src/track-layout/layout-km-post-api.ts
- ui/src/track-layout/layout-switch-api.ts
Loppusiivouksia + merkinnät erilliseen tikettiin splitatusta osuudesta. Mergailen tämän jälkeen mainiin ja katson seuraavia osia tuosta kokonaisuudesta.
> GVT-826 cleanup refactor

- ui/src/app-bar/app-bar.tsx
- ui/src/app-bar/data-products-menu.tsx
- ui/src/selection-panel/track-number-panel/color-selector/color-selector.tsx
Fiksejä edellisiin pullareihin:  
https://github.com/finnishtransportagency/geoviite/pull/575#pullrequestreview-1547573288 
https://github.com/finnishtransportagency/geoviite/pull/581#pullrequestreview-1547509318
> Gvt 1900 gvt 1981 review fixes

- ui/src/map/map-store.ts
- ui/src/vertical-geometry/store.ts
- ui/src/vertical-geometry/vertical-geometry-diagram-container.tsx
- ui/src/vertical-geometry/vertical-geometry-diagram-holder.tsx
Muutosviestit kommittiviesteissä. Jätin vielä tulevaisuuden työmaaksi korjata oikeasti nyt tämän VerticalGeometryDiagramHolder-himmelin niin, että siinä olisi vähemmän vaivalloista saada asiat pysymään synkassa.
> GVT-1996 Parempi synkronointi pystygeometrian kuvaajan alignmenttia muutettaessa

- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/pagemodel/map/MapPage.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/pagemodel/map/MapToolPanelElement.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/testgroup1/LinkingTestUI.kt
Ei kovin suurta vaikutusta varsinaisteen testien ajoaikaan, etu lähinnä selkeydessä, ja ajovarmuus saattaa jopa olla parempi (tai ainakin sain testit omalla koneella feilaamaan satunnaisesti ilman näitä muutoksia, mutta en niiden kanssa).
> GVT-1954/GVT-1940 Improve waiting on map loading

- infra/src/main/kotlin/fi/fta/geoviite/infra/projektivelho/PVDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/projektivelho/PVIntegrationService.kt
Also a minor tweak in search timeout logic
> GVT-1943 Store imported IM to DB, even if it's default-filtered

- ui/src/map/location-holder/location-holder-view.tsx
- ui/src/map/map-view.tsx
(cherry picked from commit d3ae817ceda90d0812413a1e8c6763d8bf4e4272)
> GVT-1974: Track address did not update after selection changes (#583)

- infra/src/test/kotlin/fi/fta/geoviite/infra/projektivelho/PVIntegrationServiceIT.kt
- ui/src/vayla-design-lib/dropdown/dropdown.tsx
https://extranet.vayla.fi/jira/browse/GVT-2023
> GVT-2023 Fix blurring in dropdown component

- infra/src/test/kotlin/fi/fta/geoviite/infra/projektivelho/PVIntegrationServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/projektivelho/PVTestData.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/pagemodel/common/ListModel.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/pagemodel/common/MainNavigationBar.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/pagemodel/common/TableModel.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/pagemodel/inframodel/InfraModelPage.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/pagemodel/inframodel/VelhoPage.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/testgroup1/VelhoTestUI.kt
- ui/src/infra-model/infra-model-slice.ts
- ui/src/infra-model/projektivelho/pv-file-list.tsx
- ui/src/infra-model/tabs/infra-model-tab-nav-item.tsx
Taulukkojen käsittely voi tulla ehkä vähän liian monen mutkan kautta. Pyrin siihen että qa-id:t olisivat nimensä mukaisesti iideitä, eli liittyvät listassa luonnostaan otsikkoon, ja että sarakkeet tunnistetaan samoin otsikkorivin perusteella.
> GVT-1962/GVT-1936 Add velho reject/accept UI test

- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/Publication.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationUtils.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/TrackLayout.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/util/ResultSetExternal.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationUtilsTest.kt
- ui/src/common/common-model.ts
- ui/src/i18n/fi/fi.json
- ui/src/linking/linking-api.ts
- ui/src/linking/linking-model.ts
- ui/src/model/geometry.ts
- ui/src/publication/publication-model.ts
- ui/src/publication/table/publication-table-row.tsx
- ui/src/publication/translations.fi.json
- ui/src/utils/enum-localization-utils.ts
Se fiilis kun sun review-korjauspullari on isompi kuin monet featurepullarit 😅 Täällä toteutettu review-korjausten lisäksi myös muita parannuksia (tikettien GVT-2020 ja GVT-2021 asiaa ja niiden liitännäisiä)
> GVT-1941: Review-korjauksia ja parannuksia

- ui/src/tool-panel/tool-panel.tsx
Review-korjaus: tabeissa oli välillä - ja välillä ... merkkinä puuttuvasta datasta. Nyt aina ...
> GVT-826 Unified tab titles when data is not available

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/DraftableObjectDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/DraftableObjectService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackDaoIT.kt
- ui/src/tool-bar/tool-bar.tsx
- ui/src/tool-panel/switch/dialog/switch-edit-dialog.tsx
- ui/src/tool-panel/switch/geometry-switch-linking-infobox.tsx
- ui/src/tool-panel/tool-panel.tsx
- ui/src/track-layout/layout-switch-api.ts
- ui/src/track-layout/track-layout-react-utils.tsx
Tarkastettu samalla meidän frontin kakutuslogiikka. En ainakaan nähnyt, että se olisi räjähtänyt näistä muutoksista mitenkään, mutta kannattanee pitää asiaa vielä silmällä
> GVT-2042: getMany-kutsut palauttavat virheen jos jokin id puuttuu

- ui/src/app-bar/app-bar.tsx
- ui/src/geoviite-design-lib/alignment/location-track-type-label.tsx
- ui/src/geoviite-design-lib/geometry-plan/plan-decision-phase.tsx
- ui/src/geoviite-design-lib/geometry-plan/plan-phase.tsx
- ui/src/geoviite-design-lib/layout-state-category/layout-state-category-label.tsx
- ui/src/geoviite-design-lib/layout-state/layout-state.tsx
- ui/src/geoviite-design-lib/measurement-method/measurement-method.tsx
- ui/src/geoviite-design-lib/switch/switch-hand.tsx
- ui/src/geoviite-design-lib/switch/switch-icons.tsx
- ui/src/i18n/fi/fi.json
- ui/src/infra-model/tabs/infra-model-tab-nav-item.tsx
- ui/src/infra-model/view/infra-model-validation-error-list.tsx
- ui/src/infra-model/view/infra-model-view-container.tsx
- ui/src/linking/linking-store.ts
- ui/src/map/layers/utils/alignment-layer-utils.ts
- ui/src/map/map-view.tsx
- ui/src/preview/preview-table.tsx
- ui/src/publication/table/publication-table-utils.ts
- ui/src/ratko/ratko-push-error.tsx
- ui/src/tool-bar/tool-bar.tsx
- ui/src/tool-panel/asset-validation-infobox-container.tsx
- ui/src/tool-panel/asset-validation-infobox.tsx
- ui/src/tool-panel/switch/geometry-switch-infobox.tsx
- ui/src/track-layout/track-layout-model.tsx
- ui/src/track-layout/track-layout-slice.ts
- ui/src/utils/rounding.ts
- ui/src/utils/type-utils.ts
https://extranet.vayla.fi/jira/browse/GVT-1874
> GVT-1874 Type safety, part 1: switch statements

- ui/src/publication/log/publication-log.tsx
- ui/src/vayla-design-lib/datepicker/datepicker.tsx
Täällä olikin jo näemmä aika pitkälle otettu huomioon mahdolliset tyhjät päivämäärät, mutta ei ihan loppuun asti.
> GVT-2049 Handle empty dates in publication log date picker

- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/LinkingService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/SwitchLinkingService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/DraftableObjectDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/DraftableObjectService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/linking/LinkingDaoIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/linking/LinkingServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ratko/RatkoServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/DraftIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutKmPostServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/ReferenceLineServiceIT.kt
- ui/src/track-layout/layout-location-track-api.ts
- ui/src/track-layout/layout-reference-line-api.ts
Suurin osa muutoksista on funktion signaturen muutoksen aiheuttamia korjailuja (varsinkin testeissä.) Samalla korjattu pari satunnaisesti huomattua fronttipäässä olevaa, tähän täysin liittymätöntä juttua, jotka eivät hanskanneet 204-tilanteita oikein
> GVT-2044: Layout-juttujen yksittäiset haut palauttamaan aina 204 jos haettua asiaa ei löydy

- infra/src/main/kotlin/fi/fta/geoviite/infra/inframodel/InfraModelService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/localization/LocalizationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/Publication.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationUtils.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberDao.kt
- infra/src/main/resources/i18n/translations.fi.json
- ui/src/infra-model/list/infra-model-list-view.tsx
- ui/src/infra-model/list/infra-model-list.module.scss
- ui/src/infra-model/projektivelho/pv-file-list.tsx
- ui/src/tool-panel/km-post/dialog/km-post-edit-store.ts
- ui/src/tool-panel/location-track/dialog/location-track-edit-store.ts
Täällä korjaukset tikettien GVT-2047, GVT-2048, GVT-2050, GVT-2051, GVT-2052 ja GVT-2053 bugeihin
> Julkaisulokin korjauksia

- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/pagemodel/common/Toast.kt
+ lisätty timeout E2EToastin haulle
> GVT-1952: Publication list tests

- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationUtils.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/util/List.kt
- ui/src/geometry/geometry-api.ts
- ui/src/geometry/geometry-model.ts
- ui/src/infra-model/list/infra-model-list-store.ts
- ui/src/infra-model/list/infra-model-search-result.tsx
- ui/src/selection-panel/selection-panel-geometry-section.tsx
- Nullit viimeiseksi aka toiseen päähän kuin "nolla"
- Nousen ja laskevan sorttauksen lisäksi ei sorttausta
> GVT-2079: Infra model table sorting

- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryService.kt
Siellähän oli jo opiskeluajoilta tuttu index out of bounds. Korjattu niin, että funktio palauttaa näissä tilanteissa tyhjän listan
> GVT-2096: Juuri luodun ja vielä linkittämättömän vaihteen valinnan yksi bäkkärihaku palauttaa error 500 jos korkeuskaavio on päällä

- ui/src/geometry/geometry-api.ts
- ui/src/infra-model/list/infra-model-list.module.scss
- ui/src/infra-model/list/infra-model-search-result.tsx
GVT-2099: Fix unexpectedly changing column widths when sorting the infra-model table
Additionally, previously invalid type was fixed.
> GVT-2099: Fix unexpectedly changing column widths when sorting the infra-model table

- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/pagemodel/inframodel/InfraModelElement.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/pagemodel/map/SelectionPanelElement.kt
Piti poistaa vanhoja E2E-testejä, mutta ne olikin jo poistettu, jotenka siistin hieman koodia.
> GVT-1956: Cleaner code

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberService.kt
- infra/src/main/resources/i18n/translations.fi.json
- ui/src/data-products/data-products-slice.ts
- ui/src/data-products/kilometer-lengths/entire-rail-network-km-lengths-listing.tsx
- ui/src/data-products/kilometer-lengths/kilometer-lengths-search.tsx
- ui/src/data-products/kilometer-lengths/kilometer-lengths-view.tsx
- ui/src/track-layout/layout-km-post-api.ts
Support for this feature was requested by the domain experts using this application.
> GVT-2111: Add data product for entire rail network's track kilometers

- ui/src/infra-model/list/confirm-download-unreliable-infra-model-dialog.tsx
- ui/src/infra-model/list/confirm-hide-infra-model-dialog.tsx
- ui/src/infra-model/projektivelho/pv-file-list.tsx
- ui/src/infra-model/view/dialogs/charset-select-dialog.tsx
- ui/src/infra-model/view/dialogs/new-author-dialog.tsx
- ui/src/infra-model/view/dialogs/new-project-dialog.tsx
- ui/src/infra-model/view/infra-model-view.tsx
- ui/src/linking/publish-type-handling-dialog.tsx
- ui/src/linking/switch/switch-suggestion-creator-dialog.tsx
- ui/src/main/main.tsx
- ui/src/preview/preview-confirm-revert-changes-dialog.tsx
- ui/src/preview/preview-footer.tsx
- ui/src/ratko/ratko-publish-button.tsx
- ui/src/tool-panel/km-post/dialog/km-post-delete-confirmation-dialog.tsx
- ui/src/tool-panel/km-post/dialog/km-post-edit-dialog.tsx
- ui/src/tool-panel/location-track/dialog/location-track-edit-dialog.tsx
- ui/src/tool-panel/location-track/dialog/location-track-ratko-push-dialog.tsx
- ui/src/tool-panel/location-track/location-track-delete-confirmation-dialog.tsx
- ui/src/tool-panel/switch/dialog/switch-delete-dialog.tsx
- ui/src/tool-panel/switch/dialog/switch-edit-dialog.tsx
- ui/src/tool-panel/track-number/dialog/track-number-delete-confirmation-dialog.tsx
- ui/src/tool-panel/track-number/dialog/track-number-edit-dialog.tsx
- ui/src/vayla-design-lib/dialog/dialog.scss
- ui/src/vayla-design-lib/dialog/dialog.tsx
Ainoa oikea muutos koskee ainoastaan dialog.tsx:ää ja sen .scss. Muut muutokset ovat lähinnä html-elementtien siirtelyt/poistot.
> GVT-General: Truly center dialog footer buttons, Dialog width as own property

- ui/src/infra-model/list/infra-model-list.module.scss
Oli vahingossa lähtenyt edellisessä pullarissa
> GVT-General: Import missing styles for react widgets (multiselect)

- infra/src/main/resources/i18n/translations.fi.json
- ui/src/tool-panel/location-track/dialog/location-track-edit-dialog.tsx
- ui/src/track-layout/track-layout-model.tsx
Samalla korjattu pari muutakin descriptioneihin liittyvää juttua
> GVT-2145: Raiteen kuvaukseen tulee dropdownissa "NONE"

- infra/src/main/kotlin/fi/fta/geoviite/infra/error/ApiErrorResponse.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/error/ClientException.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/error/ErrorHandling.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geocoding/Geocoding.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/inframodel/InfraModelService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/localization/LocalizationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/Publication.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationUtils.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationValidation.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/ratko/RatkoLocationTrackService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/geocoding/GeocodingTest.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationValidationTest.kt
- ui/src/geoviite-design-lib/form-layout/form-layout.tsx
- ui/src/geoviite-design-lib/loading-screen/loading-screen.tsx
- ui/src/tool-panel/location-track/dialog/location-track-edit-dialog.tsx
- ui/src/tool-panel/track-number/dialog/track-number-edit-dialog.tsx
- ui/src/vayla-design-lib/closeable-modal/closeable-modal.tsx
- ui/webpack.config.js
Review fiksejä, koottu useammasta pullarista.
> GVT-General: Use data class to hold localization values

- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/pagemodel/common/Toast.kt
Kokeilemisen arvoinen fiksi eli luetaan toastin arvot samantien, jotta se ei ehdi mennä staleksi
> GVT-General: Toasts going stale unexpectedly

- ui/src/app-bar/app-bar.tsx
- ui/src/geoviite-design-lib/dialog/dialog.scss
- ui/src/geoviite-design-lib/dialog/dialog.tsx
- ui/src/infra-model/list/confirm-download-unreliable-infra-model-dialog.tsx
- ui/src/infra-model/list/confirm-hide-infra-model-dialog.tsx
- ui/src/infra-model/projektivelho/pv-file-list.tsx
- ui/src/infra-model/view/dialogs/charset-select-dialog.tsx
- ui/src/infra-model/view/dialogs/new-author-dialog.tsx
- ui/src/infra-model/view/dialogs/new-project-dialog.tsx
- ui/src/infra-model/view/infra-model-view.tsx
- ui/src/linking/publish-type-handling-dialog.tsx
- ui/src/linking/switch/switch-suggestion-creator-dialog.tsx
- ui/src/main/main.tsx
- ui/src/preview/preview-confirm-revert-changes-dialog.tsx
- ui/src/preview/preview-footer.tsx
- ui/src/ratko/ratko-publish-button.tsx
- ui/src/tool-panel/km-post/dialog/km-post-delete-confirmation-dialog.tsx
- ui/src/tool-panel/km-post/dialog/km-post-edit-dialog.tsx
- ui/src/tool-panel/location-track/dialog/location-track-edit-dialog.tsx
- ui/src/tool-panel/location-track/dialog/location-track-ratko-push-dialog.tsx
- ui/src/tool-panel/location-track/location-track-delete-confirmation-dialog.tsx
- ui/src/tool-panel/switch/dialog/switch-delete-dialog.tsx
- ui/src/tool-panel/switch/dialog/switch-edit-dialog.tsx
- ui/src/tool-panel/track-number/dialog/track-number-delete-confirmation-dialog.tsx
- ui/src/tool-panel/track-number/dialog/track-number-edit-dialog.tsx
Dialogi siirrettiin Geoviite design libin alle koska se poikkeaa Väylän virallisesti dialogista
> GVT-2192: Update dialog widths, delete button overlapped with other buttons

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/ReferenceLineDao.kt
Alkuperäinen haun muoto oli sellainen, että postgres päätti joskus tehdä ensiksi aivan kaikki muut asiat, ja vasta sitten ajaa nelisen miljoonaa riviä läpi tuosta st_intersects-tarkistuksesta, joka oikeasti katsoo siis sitä, missä päin maata ollaan.
En ole tästä haun muodosta ihan satavarma, etteikö postgressillä olisi mahdollisuus yhä päättää tehdä asiat samassa järjestyksessä, mutta ainakin tähän asti käytetyt esimerkkitapaukset näyttäisivät menevän tällä näppärän nopeasti. Selkeytin haun logiikkaa myös hieman muuten.
> GVT-2179 Optimize near reference lines query

- ui/src/map/layers/geometry/geometry-switch-layer.ts
- ui/src/map/layers/switch/switch-layer.ts
Tehty resoluutiopohjaiseen piilotusmekanismiin ohitukset selectionin mukaan sekä paikannuspohjan vaihteille että geometriavaihteille
> GVT-2194: Valittu vaihde katoaa kartalta kun zoomaa tarpeeksi ulos

- ui/src/selection-panel/selection-panel-geometry-section.tsx
- ui/src/tool-panel/location-track/location-track-geometry-infobox.tsx
- ui/src/tool-panel/track-number/track-number-geometry-infobox.tsx
- ui/src/utils/react-utils.tsx
Jostain kirjastosta saattaa löytyä useRateLimitedEffect valmiiksi, mutta en nyt lähtenyt etsimään, kun traumaattiset kokemukset debounce-kirjastoista kertoo, että ne tekee aina jotain hieman muuta kuin miltä intuition perusteella näyttää.
> GVT-2180 Rate-limit spammy infoboxes

- ui/src/licenses/licenses.tsx
- ui/webpack.config.js
> General: Do not serve the whole source base as static, and handle cases when there are no license info

- infra/src/test/kotlin/fi/fta/geoviite/infra/DBTestBase.kt
Hieman hämmentävä ongelma, mutta varsinaiset lokiviestit kyllä viestii aika selkeästi siitä, että noiden deletointien ajaminen aiheuttaa triggerien ajoa, ja transaktionalisuuden lisääminen saa fleikit poistumaan. En kylläkään saanut debuggerilla oikeasti kiinni sitä, että noita deletejä ajettaisiin eri kantayhteyden kautta, mutta sen kyllä sain, että siellä näytti pitkälti olevan logiikka vaan, että jokainen komento käy itse erikseen hakemassa poolista yhteyden.
> General: Fix integration test flakiness

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/TrackLayout.kt
- ui/src/tool-panel/location-track/location-track-infobox.tsx
- ui/src/tool-panel/location-track/split-store.ts
- ui/src/track-layout/layout-location-track-api.ts
Tämän lisäksi yleistä refaktorointia tähän splittaukseen liittyen. Nyt tarvitaan vähemmän erillisiä bäkkärikutsuja kaiken hakemiseen ja tekemiseen
> GVT-2251: Katkaisukohdan tietojen automaattinen hakeminen duplikaattiraiteista

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/DraftableObjectDao.kt
Alkuperäinen haun muoto teki hakusuunnitelmia, joissa loopattiin koko taulun läpi ja tehtiin jokaisen rivin kohdalla bittikarttaindeksihaku, tämä muoto taas tekee koskaan enintään kolme tavallista indeksihakua. Vielä vähän lisää veivaamalla saisi niin, että tehtäisiin aina optimaalisesti vain kaksi indeksihakua, mutta se pidentäisi koodia vähän turhaan.
> GVT-2259 Optimize fetchVersionPair

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/DraftableObjectDao.kt
Now it does query optimally, and the code is shorter, too.
> GVT-2259 Further simplify fetchVersionPair

- infra/src/main/kotlin/fi/fta/geoviite/infra/geocoding/Geocoding.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geography/WktGeometries.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/map/AlignmentGeometry.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationUtils.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutAlignmentDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutGeometry.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackService.kt
Pistin omaan pullariin näitä review-korjauksia ja viimeiset TODO:n DO:t.
Vielä viimeisenä osana tähän settiin tulee varmaan tuo LayoutPoint -> AlignmentPoint muutos mistä toisessa reviewissä oli puhetta, mutta se näkyy monessa tiedostossa ja on muutoin vain puhdas rename, niin laitan sen omana pullarinaan.
> GVT-2217 Review fixes to m-value refactoring

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackController.kt
- infra/src/main/resources/i18n/translations.fi.json
- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/pagemodel/common/E2EViewFragment.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/pagemodel/map/ToolPanelInfobox.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/testgroup2/LinkingTestUI.kt
- ui/src/linking/linking-model.ts
- ui/src/tool-panel/geometry-alignment/geometry-alignment-infobox.scss
- ui/src/tool-panel/geometry-alignment/geometry-alignment-linking-candidates.tsx
- ui/src/tool-panel/geometry-alignment/geometry-alignment-linking-container.tsx
- ui/src/tool-panel/geometry-alignment/geometry-alignment-linking-infobox.tsx
- ui/src/tool-panel/km-post/geometry-km-post-linking-infobox.tsx
- ui/src/tool-panel/switch/geometry-switch-linking-infobox.tsx
- ui/src/tool-panel/switch/geometry-switch-linking-initiation.tsx
GVT-2258: Fix UI tests
General: Refactor UI tests (and related UI components) to use qaIds instead of text searches
> GVT-2258: Raidegeometrian linkitykseen tyypin (raide/pituusmittauslinja) valinta

- ui/src/utils/react-utils.tsx
- ui/src/vayla-design-lib/dropdown/dropdown.tsx
Aiemmin haun tekeminen Dropdown-komponentilla oli hieman sokkelo prosessi, jossa:
- event handler asettaa searchTermin
- seuraavassa renderissä searchTermiä valvovat efektit triggautuvat
- näistä yksi asettaa setOpen(true), toinen asettaa setIsLoading(true) ja laittaa haun menemään
- seuraavassa renderissä ollaan siis lataustilassa
- myöhemmin lataus menee läpi ja tulokset renderöidään
Tällä toteutuksella prosessi on suoraviivaisempi: Event handler laittaa suoraan haun tulille ja avaa myös listan. Säästytään siis yhdeltä ylimääräiseltä renderiltä. Vanhojen latauksien peruminen on siirretty koukun vastuulle, kun onhan nyt vähän hähmää, että Dropdown-komponentissa pitäisi sellaisesta detaljista välittää, ja alkuperäinen bugi oli juuri siinä, että oli välitetty väärin.
Olemassaolevaa …
> GVT-2266 Unify Dropdown option loading

- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/PlanLayoutService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/LinkingController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/LinkingService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/GeometryPlanLayout.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/PlanLayoutTransformation.kt
- ui/src/geometry/geometry-api.ts
- ui/src/linking/linking-api.ts
- ui/src/map/layers/geometry/geometry-alignment-layer.ts
- ui/src/map/layers/geometry/geometry-km-post-layer.ts
- ui/src/map/layers/geometry/geometry-switch-layer.ts
- ui/src/map/layers/highlight/plan-section-highlight-layer.ts
- ui/src/map/layers/utils/layer-utils.ts
- ui/src/selection-panel/geometry-plan-panel/geometry-plan-panel.tsx
- ui/src/selection-panel/selection-panel-geometry-section.tsx
- ui/src/selection/selection-store.ts
- ui/src/tool-panel/tool-panel.tsx
- ui/src/track-layout/track-layout-model.tsx
Täällä tehty getManyt linking statukselle ja suunnitelman layoutin hakemiselle. Tämä tosin paljasti muita uusia juttuja (layoutplanien hakemisessa siirtyy todella isoja määriä dataa,) mutta sitä ei ole lähdetty ratkomaan vielä tällä tiketillä.
> GVT-2238: Näkyviin jätetyistä suunnitelmista lähtee tsiljoona kutsua

- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/pagemodel/map/TrackLayoutPage.kt
- ui/.eslintrc.js
- ui/src/map/map-view.tsx
Juuse se keksi ihan viime metreillä, että veti ässän hihasta ja ehdotti, että kartan skaala (resolution) laitetaan johonkin talteen.
> General: Replace sleep with proper wait

- infra/src/main/kotlin/fi/fta/geoviite/infra/projektivelho/PVDocument.kt
Keskutelu on vielä kesken, mutta tähän hätään sallitaan ^ ja pari muuta merkkiä
> GVT-2213: Add more allowed characters in pv project name

- infra/src/main/kotlin/fi/fta/geoviite/infra/authorization/Privileges.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/inframodel/InfraModelController.kt
- infra/src/main/resources/db/migration/prod/V54__extend_privilege_code_length.sql
- infra/src/main/resources/db/migration/repeatable/R__01_role_data.sql
- ui/src/infra-model/list/infra-model-search-result.tsx
- ui/src/user/privilege-required.tsx
- ui/src/user/user-model.ts
Tämä systeemi on tosiaan ollut alusta alkaen olemassa mutta ei ehkä ole tutuksi kun ei ole tarvinnut näitä lisäillä. Kannattaa lukaista sen verran että ymmärtää miten tuo toimii. Voisin lisäillä myös dokumentaatioon kuvausta tuosta.
> GVT-2316 Add separate privilege for downloading IM files

- ui/src/common/common-model.ts
- ui/src/infra-model/view/form/fields/infra-model-project-field.tsx
- ui/src/infra-model/view/form/infra-model-form.tsx
Alkuperäisessä tiketissä puhuttiin pelkästä Suunnitteluyritys-listauksesta, mutta päädyin samalla vaivalla lisäilemään sortteja muihinkin kenttiin.
> GVT-2314: InfraModelFormin dropdownien sorttauksia

- ui/src/tool-panel/location-track/splitting/location-track-split.tsx
Lisäksi paranneltu input-validaation toimintaa sen osalta, että kentät merkataan nyt commitoiduiksi heti kun kenttä saa ensimmäistä kertaa validin arvon.
> GVT-2332: Kursori hyppää tekstin loppuun raiteen splittauksen tekstikentissä

- ui/src/common/common-model.ts
- ui/src/infra-model/view/form/infra-model-form.tsx
- ui/src/tool-panel/infobox/infobox.module.scss
- ui/src/tool-panel/location-track/location-track-infobox.tsx
- ui/src/tool-panel/location-track/splitting/location-track-split.tsx
- ui/src/tool-panel/location-track/splitting/location-track-splitting-infobox.tsx
Täällä korjattu mm.
- GVT-2308: Korjattu raiteen descriptionin aiemmin huonosti korjattu tasaus
- GVT-2314: Ääkköset sorttautuvat nyt viimeiseksi, eivät ensimmäiseksi
- Muuten yleisiä review-korjauksia
> General: Review- ym. korjauksia fronttipuolelle 

- ui/src/tool-panel/location-track/location-track-infobox.scss
- ui/src/tool-panel/location-track/splitting/location-track-split.tsx
- ui/src/tool-panel/location-track/splitting/location-track-splitting-infobox.tsx
Näiden korjausten jäljiltä input-kentät jäivät vähän eri kokoisiksi. Tein niiden korjaamisesta oman tikettinsä, että näitä korjauksia ei tarvitse roikottaa joulun ja vuodenvaihteen yli.
> GVT-2351 & GVT-2353: Korjauksia katkaisukohdan poistonappiin ja Suorita jako -napin enablointiin

- infra/src/main/kotlin/fi/fta/geoviite/infra/authorization/AuthorizationController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/authorization/Privileges.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/codeDictionary/CodeDictionaryController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/common/ChangeTimeController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/environmentInfo/EnvironmentInfoController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geocoding/GeocodingController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geography/GeographyController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/inframodel/InfraModelController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/LinkingController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/localization/LocalizationController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/ratko/RatkoController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/switchLibrary/SwitchLibraryController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutKmPostController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSearchController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/MapAlignmentController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/ReferenceLineController.kt
- infra/src/main/resources/db/migration/repeatable/R__01_role_data.sql
- infra/src/test/kotlin/fi/fta/geoviite/infra/authorization/AuthorizationTestController.kt
- ui/src/user/write-access-required.tsx
Jätin 1.10-haaran pullareista turhat siistimiset pois, joten tässä ne mainiin suoraan: Vakion rename, repeateble migraatiossa oleva kommentti ja WriteAccessRequired laitettu käyttämään PrivilegeRequiredia
> GVT-2317 Rename authority constant + review fixes

- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationValidation.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/linking/LinkingDomainTestData.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationValidationTest.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackDaoIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/TrackLayoutDomainTestData.kt
Also fix duplicateOf validation not always using correct versions of validated objects
> GVT-2361Validate that official tracks aren't duplicates of draft-only tracks

- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/SwitchLinkingService.kt
getSwitchBoundsFromTracksAndAlignments tekee tasan saman asian kuin getSwitchBoundsFromTracks, mutta vaan tavalla, joka näyttää enemmän siltä samalta alkuperäiseltä SQL:ltä, jonka perusteella molemmat on kirjoitettu; jätin olemaan enemmän Kotlinilta näyttävän toteutuksen.
> GVT-2325 putsaukset

- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/LinkingService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/Publication.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/split/Split.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/split/SplitDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/split/SplitService.kt
- infra/src/main/resources/db/migration/prod/V61__add_split_table.sql
- infra/src/main/resources/i18n/translations.fi.json
- infra/src/test/kotlin/fi/fta/geoviite/infra/linking/LinkingServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/split/SplitDaoIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/TrackLayoutDomainTestData.kt
Täällä myös refaktorointeja splittijuttuihin halutun mukaisesti
> GVT-2329: Linkityksen estäminen pilkonnan ajaksi (bäkkäri)

- infra/src/main/kotlin/fi/fta/geoviite/infra/split/SplitService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/split/SplitValidation.kt
- infra/src/main/resources/i18n/translations.fi.json
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationServiceIT.kt
Täällä siis haluttiin, että splittiä ei saa julkaista mikäli splitattavan raiteen tila ei ole DELETED. Tälle tehty julkaisuvalidointi ja testi
> GVT-2329: Validoi jaettavan raiteen tila

- infra/src/main/kotlin/fi/fta/geoviite/infra/error/ClientException.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/SwitchLinkingService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/split/Split.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/split/SplitController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/split/SplitService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/split/SplitValidation.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/TrackLayout.kt
Tässä ei ole vielä testit mutta varmaan hyvä mergeillä tiheään tuonne yhteiseen branchiin, joten teen ne omana pullarinaan.
Myös noissa dataluokissa olisi varmaan vielä virtaviivaistamisen varaa.
> GVT-2154 Backend for splitLocationTrack

- infra/src/main/resources/i18n/translations.fi.json
Hotfixailtu @#1018 , tällä pullarilla sama korjaus mainiin.
> GVT-2382: Modify InfraModel cant remark

- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/SwitchLinkingService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/linking/SwitchLinkingServiceIT.kt
Vähän testejäkin, mutta ei vielä tälle toiselle bugille.
> GVT-2380 Further fix overlay use in switch linking

- ui/src/vayla-design-lib/closeable-modal/closeable-modal.tsx
- ui/src/vayla-design-lib/dropdown/dropdown.tsx
Overflow korkeussuunnassa: asetetaan max height
Overflow sivuttaissuunnassa: siirretään modalia vasemmalle/oikealle
> GVT-2209: Keep closeable modal in view when it overflows

- ui/src/vayla-design-lib/dropdown/dropdown.scss
- ui/src/vayla-design-lib/text-area/text-area.scss
- ui/src/vayla-design-lib/text-area/text-area.tsx
- ui/src/vayla-design-lib/text-field/text-field.scss
- ui/src/vayla-design-lib/text-field/text-field.tsx
Inputtien tyyleissä oli pientä variaatiota focusoidessa/hoveroidessa
> GVT-2349: Input focus and hover styles were inconsistent

- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchController.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationServiceIT.kt
- ui/src/map/layers/switch/switch-layer.ts
- ui/src/map/layers/utils/switch-layer-utils.ts
- ui/src/map/map.module.scss
- ui/src/track-layout/layout-switch-api.ts
- ui/src/vayla-design-lib/icon/glyphs/misc/switch-error.svg
Suurin osa koodista Karilta. Siihen tehty mun toimestani päälle siivoilua ja validaation tekeminen tiilitettynä massahakuna
> GVT-2383: Koodinimi kukkapelto

- ui/src/common/common-slice.ts
- ui/src/data-products/data-products-slice.ts
- ui/src/index.tsx
- ui/src/infra-model/infra-model-slice.ts
- ui/src/main/main.tsx
- ui/src/store/store.ts
- ui/src/track-layout/track-layout-slice.ts
- ui/src/version-holder/version-holder-view.tsx
Previously it was possible for the previous state to be written to localStorage after resetting the redux state, resulting in the state reset not actually working properly.
> GVT-2318: Refactor persistent state reset to work more robustly

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchController.kt
- infra/src/main/resources/i18n/translations.fi.json
- ui/src/api/api-fetch.ts
- ui/src/geoviite-design-lib/snackbar/snackbar.tsx
- ui/src/map/layers/geometry/geometry-switch-layer.ts
- ui/src/map/layers/switch/switch-layer.ts
- ui/src/map/layers/utils/switch-layer-utils.ts
- ui/src/publication/publication-api.ts
- ui/src/track-layout/layout-switch-api.ts
Täällä siis review-korjauksia pääasiassa kukkapeltoon ja virheiden näyttämiseen snackbarissa
> GVT-2383 & GVT-2410: Review-korjauksia

- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/Publication.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/split/Split.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/split/SplitDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/split/SplitService.kt
- infra/src/main/resources/i18n/translations.fi.json
- infra/src/test/kotlin/fi/fta/geoviite/infra/split/SplitDaoIT.kt
- ui/src/common/navigate.ts
- ui/src/frontpage/frontpage.tsx
- ui/src/publication/card/publication-card.scss
- ui/src/publication/card/publication-card.tsx
- ui/src/publication/card/publication-list-row.tsx
- ui/src/publication/card/publication-list.scss
- ui/src/publication/card/publication-list.tsx
- ui/src/publication/publication-api.ts
- ui/src/publication/publication-model.ts
- ui/src/ratko/ratko-model.ts
- ui/src/vayla-design-lib/icon/Icon.tsx
- ui/src/vayla-design-lib/icon/glyphs/action/set-time.svg
- ui/src/vayla-design-lib/spinner/spinner.scss
- ui/src/vayla-design-lib/spinner/spinner.tsx
Tulipas yllättävän iso pullari 🙈 Käytännössä täällä on muutettu etusivun julkaisunäkymä figman mukaiseksi (linkki sinne löytyy tiketiltä)
> GVT-2406: Etusivun julkaisut-näkymän päivitys

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchService.kt
- ui/src/map/layers/switch/switch-layer.ts
- ui/src/track-layout/layout-switch-api.ts
Featuring "Jos vaikka nyt menis alle minuutti queryissä ":D"" ja muita kovia hittejä
> General: Korjauksia kukkapeltoon

- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/SwitchLinkingService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/split/SplitService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/switchLibrary/data/YV60_300_1_10.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/linking/SuggestedSwitchTest.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/linking/SwitchLinkingServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/linking/SwitchLinkingTest.kt
En putsannut vielä kokonaan pois segmentti-indeksiä menemästä kokonaan frontille vaan teen sen osana isompaa refaktoria.
> GVT-2429 Recalculate segment index when saving switch linking

- ui/src/publication/split/split-details-dialog.scss
Tämä tiedosto oli näköjään päässyt unohtumaan
> GVT-2415: Puuttuva .scss

- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/LinkingController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/SwitchLinkingService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/linking/SwitchLinkingServiceIT.kt
- ui/src/linking/linking-api.ts
- ui/src/tool-panel/tool-panel-container.tsx
Limittäisten vaihdelinkitysten esto yrittää olla estämättä limittäisyyttä itsensä kanssa, mutta tarvitsee sitä varten switchId:n.
> GVT-2445 Pass switchId when making a suggestion for linking a layout switch

- ui/src/tool-panel/infobox/infobox.module.scss
- ui/src/tool-panel/tool-panel.tsx
> GVT-2422: UI: Infoboxiin oikeat tabit (vihdoin)

- ui/src/map/layers/alignment/location-track-duplicate-endpoint-indicator-layer.ts
Previously the endpoints were being drawn based on the first and last points values available for the rendering operation. These were not always correct in cases were the duplicate track was only being partially drawn.
> GVT-2463: Fix duplicate endpoints being drawn in incorrect locations during splitting

- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/pagemodel/map/ToolPanel.kt
HTML-elementti vaihtui, UI-testi unohtui päivittää, UI-testi päivitettiin ja sen jälkeen HTML vaihtui takaisin alkuperäiseksi ja UI-testiä ei vielä päivitetty 😄
https://github.com/finnishtransportagency/geoviite/pull/1094/files
https://github.com/finnishtransportagency/geoviite/pull/1085/files
> General: Fix incorrect xpath selector in UI test

- ui/src/tool-bar/tool-bar-container.tsx
- ui/src/tool-bar/tool-bar.tsx
- ui/src/tool-panel/geometry-alignment/geometry-alignment-linking-container.tsx
- ui/src/tool-panel/km-post/geometry-km-post-infobox-container.tsx
- ui/src/tool-panel/km-post/km-post-infobox-container.tsx
- ui/src/tool-panel/location-track/location-track-infobox-linking-container.tsx
- ui/src/tool-panel/switch/dialog/geometry-switch-infobox-container.tsx
- ui/src/tool-panel/switch/dialog/suggested-switch-infobox-container.tsx
- ui/src/tool-panel/switch/switch-infobox-container.tsx
- ui/src/tool-panel/tool-panel-container.tsx
- ui/src/tool-panel/tool-panel.tsx
- ui/src/tool-panel/track-number/track-number-infobox-linking-container.tsx
- ui/src/track-layout/track-layout-view.tsx
Tämä review on aivan karmeaa luettavaa muutosten luonteesta johtuen, sori siit 🙈  Täällä siis toteutettuna containerit niille ToolPanelin tabeille joilla sellaisia ei vielä ollut, ja parannettu olemassaolevienkin isolaatiota. Samalla myös containerisoitu `ToolBar`. Koitin testata tämän parhaani mukaan enkä ainakaan löytänyt mitään tabia jossa mikään olisi räjähtänyt tämän muutoksen johdosta
> GVT-2435: ToolPanelin tabien containerisaatio

- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/SwitchLinkingService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/split/SplitService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/linking/SwitchLinkingServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/linking/SwitchLinkingTest.kt
Tämän logiikan saisi varmaan kyllä teoriassa osumaan tasan oikeaan indeksiin aina, mutta se ei maksa vaivaa, koska ainakin tähän asti kaikki käyttötapaukset saa ratkaistua jotenkin muuten.
> General: Give up on segment index recalculation

- infra/src/main/resources/i18n/translations.fi.json
- ui/src/tool-panel/location-track/location-track-task-list/location-track-task-list-container.tsx
- ui/src/tool-panel/location-track/location-track-task-list/location-track-task-list.scss
Spinnerin keskittäminen + css-luokkien uudelleennimeäminen
> General: Center spinner in location track task list

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/MapAlignmentController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/MapAlignmentService.kt
- ui/src/linking/linking-model.ts
- ui/src/track-layout/layout-map-api.ts
Aikalailla vaan tyyppien selvennystä, ja tarkistus frontilla että tulihan suunnilleen odotettua tavaraa.
> GVT-2465 Ensure getEndLinkPoints call gets expected number of points

- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/Linking.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/LinkingController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/SwitchLinkingService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/split/SplitService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/TrackLayout.kt
- infra/src/main/resources/i18n/translations.fi.json
- infra/src/test/kotlin/fi/fta/geoviite/infra/linking/SwitchLinkingServiceIT.kt
- ui/src/linking/linking-api.ts
- ui/src/linking/linking-model.ts
- ui/src/selection-panel/geometry-plan-panel/geometry-plan-panel.tsx
- ui/src/tool-panel/asset-validation-infobox-container.tsx
- ui/src/tool-panel/asset-validation-infobox.tsx
- ui/src/tool-panel/location-track/dialog/location-track-switch-relinking-dialog.tsx
- ui/src/tool-panel/location-track/location-track-infobox-linking-container.tsx
- ui/src/tool-panel/location-track/location-track-infobox.tsx
- ui/src/tool-panel/location-track/location-track-task-list/location-track-task-list-container.tsx
- ui/src/tool-panel/location-track/location-track-validation-infobox-container.tsx
- ui/src/track-layout/track-layout-model.tsx
- ui/src/track-layout/track-layout-slice.ts
- ui/src/vayla-design-lib/spinner/spinner.scss
- ui/src/vayla-design-lib/spinner/spinner.tsx
Tulihan tästä sittenkin lopulta aika iso pullari, ja mukaan pari aika oleellista fiksiä myös aiemmin toteutetun uudelleenlinkityksen validoinnin bugeihin.
> GVT-2468 Track switch relinking + various related fixes

- infra/src/main/kotlin/fi/fta/geoviite/infra/split/SplitService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackService.kt
ks. kommentteja aiemmasta pullarista https://github.com/finnishtransportagency/geoviite/pull/1106
> GVT-2478: Review fixes

- ui/src/map/layers/alignment/alignment-linking-layer.ts
- ui/src/tool-panel/km-post/geometry-km-post-linking-infobox.tsx
E2E-testit failasivat näihin. Olivat ihan oikeita issueita (alignment-linkityksessä linkityspallerot jäivät uupumaan ja km-pylväslinkityksessä geometriapylvään tabi ei pysynyt lukittuna)
> GVT-2516 & GVT-2517: Fronttibugeja linkityksessä

- doc/projektivelho.md
- ui/src/app-bar/app-bar-more-menu.tsx
- ui/src/tool-panel/location-track/location-track-location-infobox.tsx
- ui/src/vayla-design-lib/closeable-modal/closeable-modal.tsx
- ui/src/vayla-design-lib/menu/menu.tsx
Korjauksia viimeaikaisiin. Koitan merkitä kommentilla mihin kukin liittyy
> General: Review-korjauksia

- ui/src/tool-panel/location-track/splitting/location-track-split.tsx
- ui/src/tool-panel/location-track/splitting/split-utils.ts
- ui/src/tool-panel/track-number/dialog/track-number-edit-dialog.tsx
- ui/src/utils/string-utils.ts
Case-insensitive-vertailuja tunnuttiin tekevän muuallakin, niin tein sille suosiolla yleisen funktion
> GVT-2495: Muutetaan duplikaatin nimivertailu "case insensitive"ksi

- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/split/SplitDao.kt
- infra/src/main/resources/db/migration/prod/V67__rename_duplicate_id_to_duplicate_location_track_id.sql
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationServiceIT.kt
Fixes based on comments from https://github.com/finnishtransportagency/geoviite/pull/1118
Paikkoja viitattu tarkemmin tämän pullarin kommenteissa.
> GVT-2476: Review fixes

- ui/src/data-products/data-products-utils.ts
- ui/src/data-products/kilometer-lengths/kilometer-lengths-search.tsx
- ui/src/infra-model/view/dialogs/charset-select-dialog.tsx
- ui/src/infra-model/view/form/fields/infra-model-form-chosen-date-dropdowns.tsx
- ui/src/infra-model/view/form/fields/infra-model-project-field.tsx
- ui/src/infra-model/view/form/infra-model-form.tsx
- ui/src/infra-model/view/infra-model-view.tsx
- ui/src/linking/switch/switch-suggestion-creator-dialog.tsx
- ui/src/tool-bar/tool-bar.tsx
- ui/src/tool-panel/km-post/dialog/km-post-edit-dialog.tsx
- ui/src/tool-panel/location-track/dialog/location-track-edit-dialog.tsx
- ui/src/tool-panel/location-track/dialog/location-track-ratko-push-dialog.tsx
- ui/src/tool-panel/switch/dialog/switch-edit-dialog.tsx
- ui/src/utils/enum-localization-utils.ts
- ui/src/vayla-design-lib/demo/examples/button-examples.tsx
- ui/src/vayla-design-lib/demo/examples/dropdown-examples.tsx
- ui/src/vayla-design-lib/demo/examples/menu-example.tsx
- ui/src/vayla-design-lib/dropdown/dropdown.tsx
- ui/src/vayla-design-lib/menu/menu.tsx
Tässä tosin uusien qaId-kenttien arvoja ei ole valittu millään erityisen suurella viisaudella, ja niitä ei vielä käytetä testeissä (mutta ajoin kälitestit jotta näkee etteivät tule sentään nykyisten päälle)
> GVT-2512 Enforce qaId on all menu options

- infra/src/main/kotlin/fi/fta/geoviite/infra/authorization/AuthorizationController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/authorization/AuthorizationDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/authorization/AuthorizationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/authorization/UserData.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/configuration/RequestFilter.kt
- infra/src/main/resources/i18n/translations.fi.json
- infra/src/test/kotlin/fi/fta/geoviite/infra/authorization/AuthorizationIT.kt
- ui/src/app-bar/app-bar-more-menu.tsx
- ui/src/app-bar/app-bar.scss
- ui/src/app-bar/data-products-menu.tsx
- ui/src/app-bar/links/infra-model-link.tsx
- ui/src/common/common-slice.ts
- ui/src/infra-model/list/infra-model-list-view.tsx
- ui/src/infra-model/list/infra-model-search-result.tsx
- ui/src/infra-model/view/form/infra-model-form.tsx
- ui/src/main/main.tsx
- ui/src/user/privilege-required.tsx
- ui/src/user/privileged-link.tsx
- ui/src/user/user-api.ts
- ui/src/user/user-card-container.tsx
- ui/src/user/user-card.tsx
- ui/src/user/user-model.ts
Previously it was quite cumbersome to test or show the user interface with different roles. This PR adds role switching functionality to the UI for users that have more than one role assigned to them.
> GVT-2527: Add user role switching functionality

- infra/src/main/resources/application-e2e.yml
- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/LocalWebClientConfiguration.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/util/Browser.kt
- ui/webpack.config.js
Näihin liittyy toisessa repossa myös testiajojen korjaus, pistän sen samalla kertaa.
> General: Change devserver port to 9001 due to local env infra changes

- infra/src/main/kotlin/fi/fta/geoviite/infra/configuration/RequestFilter.kt
Last minute review fixes to #1170 (.copy() call removal) caused the local user role selection to no longer work properly by not accounting for the selected role for the local user. Somehow this was also not caught during development testing before merging.
> GVT-2527 (part 2): Fix local user role selection

- ui/src/app-bar/app-bar.tsx
Previously the HTML structure included the link wrapper `<li>`-element with qa-id for the infra model link (`<li qa-id="infra-model-link">`) even when the active user role did not have privileges to view the link. 
The actual link was not displayed for an unprivileged user, but the qa-id existed in the HTML structure with the `<li>`-element. This lead to an unintuitive situation during a test case creation where links are asserted to not exist for some specific user roles based on qa-ids that exist in the HTML structure.
> General: Remove partial inframodel link nav-element from unprivileged users

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/SwitchLocationTrackLink.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/TrackLayout.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/util/List.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/SwitchLocationTrackLinkTest.kt
Tämä ei vielä tee mitään hyödyllistä mutta palauttaa fronttiin splitintunnistus-logiikan tulokset. Mergeän tämän ajoissa mainiin koska ei pitäisi rikkoa mitään ja mahdollistaa frontend-hommien jakamista useammalle tekijälle.
> GVT-2525 backend partial split identification logic

- ui/package-lock.json
- ui/package.json
- ui/webpack.config.js
The LICENSE.txt file was not locally available which caused a 404 error when accessing the licenses page of Geoviite. This seems to be fairly easy to solve with a webpack build step plugin, although as is common with JS packages, there are some additional dependencies as well.
> General: Fix missing LICENSE.txt file when using local environment

- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/testgroup1/UserRoleTestUI.kt
- ui/src/app-bar/data-products-menu.tsx
Tulipas tehtyä tymästi ja rikottua testit ja hookkeja. Korjattu.
> GVT-2582: Korjauksia

- infra/src/main/kotlin/fi/fta/geoviite/infra/common/DomainId.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/common/LayoutContext.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/configuration/WebConfiguration.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/error/ClientException.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/ElementListing.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/common/IdConversionTest.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/common/LayoutBranchConversionTest.kt
GVT-2401 Yhteydessä tuli tehtyä kasa pieniä muutoksia sivussa. Irrottelen niistä tällaisia erillisiä pullareita jotta on vähän ymmärrettävämpi kokonaisuuksia.
> GVT-2401 Fix converters for layoutbranch & clean up DomainId conversions to match other types

- infra/src/main/kotlin/fi/fta/geoviite/infra/split/SplitService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutContextData.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutKmPostService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/PlanLayoutTransformation.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/ReferenceLineService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/linking/SwitchLinkingServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberDaoIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/TrackLayoutDomainTestData.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/testdata/CommonTestData.kt
Tämänkin olisi voinut tehdä esityönä jos olisi huomannut, mutta oikeastaan tajusin kaiken mitä pitää muuttaa vasta kun otin sen käyttöön. Silti, käyttöönotto ei ole tässä pullarissa vaan tulee vasta seuravassa: pilkoin tähän vain yhden osakokonaisuuden.
> GVT-2401 Add layout branch to layout context transitions with support for design branches

- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/pagemodel/map/ToolBar.kt
- ui/src/geoviite-design-lib/tab-header/tab-header.tsx
- ui/src/preview/preview-table-item.tsx
- ui/src/preview/preview-table.tsx
- ui/src/preview/preview-view.tsx
- ui/src/publication/log/publication-log.tsx
- ui/src/tool-bar/tool-bar.tsx
- ui/src/vayla-design-lib/dropdown/dropdown.tsx
Mm. yläpalkkimuutokset aiheuttivat sen, että UI-testit eivät menneet enää läpi. Korjattu täällä. Mukana myös vähän "miten tämä on voinut toimia aiemmin" -tavaraa
> General: UI-testit kuntoon

- infra/src/main/kotlin/fi/fta/geoviite/infra/configuration/WebConfiguration.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/localization/LocalizationController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/localization/LocalizationLanguage.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/localization/LocalizationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/ratko/RatkoLocationTrackService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationServiceIT.kt
Toteutettu Jyrkin review-kommentin pohjalta. Bäkkärin kielet ovat nyt enumeja, joten niiden on pakko olla jossain fiksussa arvossa tai muuten lentää konversiovirhe.
> GVT-2575: Bäkkärin kielien enumisointi

- ui/src/tool-panel/location-track/splitting/location-track-splitting-infobox.tsx
Päädyin refaktoroimaan tätä koko dialogin luontia vähän isommin. Vaikutti fiksummalta tehdä dialogi omana infoboksin sisäisenä privaattikomponenttinaan
> GVT-2604: Lopeta raiteen jakaminen -dialogista ei voi aina jatkaa jakamista

- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/switches/SwitchLinkingService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/ValidationContext.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutAssetDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutAssetService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/ReferenceLineService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/integration/CalculatedChangesServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutKmPostDaoIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackDaoIT.kt
> GVT-2404 Remove excess methods from LayoutAssetDao interface

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchDao.kt
Klassinen PostgreSQL-ongelma: Aiemmin "list them all and let GROUP BY or DISTINCT sort them out"-tyylinen haku toimi riittävän näpsäkästi, mutta layout-kontekstifunktion monimutkaisemman logiikan kanssa pitää olla vähän tarkempi sen suhteen, että tehdään semijoinit semijoineina.
> General: Optimize findLocationTracksLinkedToSwitches

- infra/src/main/kotlin/fi/fta/geoviite/infra/split/SplitDao.kt
Minimaalinen toteutus, sellaisilla ominaisuuksilla, että:
- Jos splittejä joskus satutaan suunnitelmatiloihin tekemään, niin suunnitelmaan tehty puskematon splitti ei estä raiteen geometriamuutoksia main-haarassa
- ... mutta jos main-haaraan tehdään splitti, niin se estää aina geometriamuutokset suunnitelmissakin, silloinkin kun kyseistä raidetta on suunnitelmassa aiemmin käsitelty; tämä on periaatteessa epäyhdenmukainen sitä vastaan, miten suunnitelmatilaisuus muuten toimii, en vaan lähtenyt tässä etupeltoon tekemään "korrektia" toteutusta
> GVT-2617 Filter unfinished splits by branch

- infra/src/main/kotlin/fi/fta/geoviite/infra/ratko/RatkoOperatingPointDao.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ratko/RatkoLocalServiceIT.kt
* Ekspliittisempi hakupatternin määritys
* Refaktoroitu testi käyttämään ketjutusta
> GVT-2559 (part 3): Review fixes

- infra/src/main/resources/i18n/translations.fi.json
- ui/src/tool-panel/location-track/location-track-infobox-duplicate-of.tsx
- ui/src/tool-panel/location-track/location-track-infobox.scss
- ui/src/tool-panel/location-track/splitting/location-track-split-notices.tsx
- ui/src/tool-panel/location-track/splitting/location-track-splitting-infobox.tsx
- ui/src/tool-panel/location-track/splitting/split-utils.ts
https://extranet.vayla.fi/jira/browse/GVT-2598
> Dev/gvt 2598 - 0% päällekkäin olevien duplikaattien käsittely pilkkomisessa

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackDao.kt
Vaihteiden linkitys ei tuntunut vielä edellisellä koodilla hyvältä, koska tämä funktio oli in_layout_context-funktion massahakumuodon käytön takia yhä selvästi hitaampi kuin ennen. Suunnitelmatilaisuutta edeltävällä versiolla tyypillinen vaihdelinkityksen käyttämä fetchVersionsNear()-haku vei aikaa noin kymmenen millisekunnin luokkaa, tätä kommittia edeltävällä versiolla 60-80 millisekunnin luokkaa, ja vaihteen linkitys tekee useamman fetchVersionsNear()-haun.
Massahausta erottautumalla ajoaika menee tyypillisessä tapauksessa hyvin kolmeen millisekuntiin tai sen alle, eli alkuperäistäkin nopeammaksi. Se oletus tässä tosin on, että hakualue on melko pieni. Riittävän optimointityön jälkeen näemmä alignment-taulun bounding boxien käyttö oli tässä yleisessä tapauksessa lopulta vain hidastus.
> GVT-2673 Optimize fetchVersionsNear even harder

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackDao.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackDaoIT.kt
Josko testien avittamana tulisi tämä fetchVersionsNear()-saaga loppuunsa. Edellinen versio palautteli nimittäin vielä vähän miten sattuu raiteen eri kontekstissa näkyviä versioita.
Haun muotoa piti myös muuttaa hieman, jotta sen sai pakotettua korjauksen kanssa käyttämään yhä optimaalista hakusuunnitelmaa yleisimmässä tapauksessa (siis siinä, että hakualue on parin metrin kokoinen).
> GVT-2673 Fix context confusion in fetchVersionsNear

- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/pagemodel/common/E2EDialog.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/pagemodel/map/ToolBar.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/pagemodel/map/ToolPanel.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/pagemodel/map/TrackLayoutPage.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/testgroup1/UserRoleTestUI.kt
- ui/src/geoviite-design-lib/tab-header/tab-header.scss
- ui/src/geoviite-design-lib/tab-header/tab-header.tsx
- ui/src/tool-bar/tool-bar.scss
- ui/src/tool-bar/tool-bar.tsx
_See commit messages for general info_
> General: Fix broken E2E tests, slightly improve styling

- doc/automaatiotestit.md
Helpommin luettavissa formatoidusta versiosta:
https://github.com/finnishtransportagency/geoviite/blob/188d9fc3cdf956513dde7cd86d152f35ea6b77c4/doc/automaatiotestit.md
> GVT-2518: Add automation test documentation

- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutAssetService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutContextData.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/ReferenceLineService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/util/ResultSetExternal.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/TestDBService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutContextTest.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/TrackLayoutDomainTestData.kt
Enimmäkseen tämän review-keskustelun pohjalta: https://github.com/finnishtransportagency/geoviite/pull/1307#discussion_r1642351427
Lisänä myös mergen branch-argumentin tyypin tiukennus, sillä main-branchia ei ole järkeä mergetä mainiin.
> GVT-2629 Tighten typing in context data + merge branch

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutDesignDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutDesignService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/util/SanitizedString.kt
- infra/src/main/resources/i18n/translations.fi.json
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutDesignDaoIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackDaoIT.kt
- ui/src/tool-bar/workspace-dialog.tsx
Täällä lisätty sekä bäkkärille että frontille tarkastelut siitä, että työtilan nimen tulee olla uniikki. Uniikkius tarkastellaan case-insensitivenä, sillä lienee todennäköistä, että koska operaattorit ovat ihmisiä, niin he mieltäisivät nimet "Pena" ja "pena" samaksi työtilaksi.
> GVT-2671: Suunnitelmien työtilojen nimien uniikkiustarkastelu

- infra/build.gradle.kts
- infra/src/main/kotlin/fi/fta/geoviite/infra/InfraApplication.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geography/CommonSrid.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geography/CoordinateTransformationService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geography/GeoToolsGeometries.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geography/KkjEtrsTransformation.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geography/KkjTm35finTriangulationDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/ratko/model/RatkoCommonModel.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/TrackLayout.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/geometry/CoordinateTransformServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/geometry/TransformationTest.kt
- infra/start.sh
Muutos on pieni mutta tiedostoja on jokunen koska jätin yhden refaktoroinnin jota samalla tuli pyöritettyä: siirsin yleiset srid-määritykset yhteen paikkaan ja yhtenäisille nimille.
> GVT-2698 ClassDefNotFound error in km-post cache preloading

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutTrackNumberService.kt
Täällä näköjään tuli myös formatointimuutoksia. Oh well, en jaksa nyt säätää niitä sen enempää sillä ajan kohta koko koodikannan ktfmt:n läpi omassa pullarissaan
> GVT-2661: Yhtäsuuruusmuutos

- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationValidation.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/switchLibrary/SwitchStructure.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/publication/PublicationValidationTest.kt
As per: https://github.com/finnishtransportagency/geoviite/pull/1348/files#r1717873018
> General: Review fix - rename SwitchConnectivityType

- infra/build.gradle.kts
- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/util/Browser.kt
> General: Selenium-päivitys mainiin

- ui/src/geoviite-design-lib/coordinate-system/coordinate-system-view.tsx
- ui/src/infra-model/view/form/infra-model-form.tsx
- ui/src/tool-panel/geometry-plan-infobox.tsx
- ui/src/tool-panel/km-post/dialog/km-post-edit-dialog-gk-location-section.tsx
- ui/src/tool-panel/km-post/km-post-infobox.tsx
- ui/src/utils/geography-utils.ts
Review korjauksia tuolta: https://github.com/finnishtransportagency/geoviite/pull/1374
> GVT-2724 review fixes

- infra/src/main/kotlin/fi/fta/geoviite/api/frameconverter/v1/FrameConverterControllerV1.kt
- infra/src/main/kotlin/fi/fta/geoviite/api/frameconverter/v1/FrameConverterDataConvertersV1.kt
- infra/src/main/kotlin/fi/fta/geoviite/api/frameconverter/v1/FrameConverterDataV1.kt
- infra/src/main/kotlin/fi/fta/geoviite/api/frameconverter/v1/FrameConverterErrorV1.kt
- infra/src/main/kotlin/fi/fta/geoviite/api/frameconverter/v1/FrameConverterServiceV1.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/error/ClientException.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/util/Functional.kt
- infra/src/main/resources/i18n/translations.fi.json
- infra/src/test/kotlin/fi/fta/geoviite/api/frameconverter/v1/CoordinateToTrackAddressIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/api/frameconverter/v1/FrameConverterTestDataService.kt
- infra/src/test/kotlin/fi/fta/geoviite/api/frameconverter/v1/TrackAddressToCoordinateIT.kt
Kommenttien perusteella: https://github.com/finnishtransportagency/geoviite/pull/1373
Commit-viesteistä näkee hieman tarkemmin muutosten tavoitteen.
> GVT-2678 (part 2): Review fixes

- infra/src/main/kotlin/fi/fta/geoviite/api/frameconverter/v1/FrameConverterControllerV1.kt
- infra/src/main/kotlin/fi/fta/geoviite/api/frameconverter/v1/FrameConverterDataConvertersV1.kt
- infra/src/main/kotlin/fi/fta/geoviite/api/frameconverter/v1/FrameConverterDataV1.kt
- infra/src/main/kotlin/fi/fta/geoviite/api/frameconverter/v1/FrameConverterErrorV1.kt
- infra/src/main/kotlin/fi/fta/geoviite/api/frameconverter/v1/FrameConverterServiceV1.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/error/ClientException.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/util/Functional.kt
- infra/src/main/resources/i18n/translations.fi.json
- infra/src/test/kotlin/fi/fta/geoviite/api/frameconverter/v1/CoordinateToTrackAddressIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/api/frameconverter/v1/FrameConverterTestDataService.kt
- infra/src/test/kotlin/fi/fta/geoviite/api/frameconverter/v1/MixedRequestIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/api/frameconverter/v1/TrackAddressToCoordinateIT.kt
Sisältää refakkia uusien asioiden lisäksi, kommenteissa tarkemmin.
Massapullaria jälleen, sorgen. Testikoodia toki reippaasti
> GVT-2678: Implement reverse geocoding api

- ui/src/infra-model/view/form/infra-model-form.tsx
- ui/src/infra-model/view/infra-model-import-loader.tsx
- ui/src/infra-model/view/infra-model-upload-loader.tsx
- ui/src/infra-model/view/infra-model-view-container.tsx
- ui/src/infra-model/view/infra-model-view.tsx
En päätynyt lopulta tekemään isompia refaktorointeja sen takia että ne olisivat menneet todella monimutkaisiksi, renamesin vain muuttujia ja vakioita
> GVT-2702: Review-korjauksia inframallisivun parannuksiin

- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/switches/SwitchLinkingService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/MapAlignmentService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/ReferenceLineDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/ReferenceLineService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackDaoIT.kt
Tämä ei varsinaisesti korjaa mitään bugia, ja koskettu kohta on niin keskeinen geoviitteen toiminnassa että se kyllä hoksataan ilman erillistä testausta, jos tämä jotain rikkoo -> mennään ihan taskitta.
Perffimittaukset tehty varsin epätieteellisesti, mutta ainakin minun koneella näkyy profilerissa hyvin selkeä perffiparannus.
> General: Optimize getAlignmentPolylines()

- ui/src/publication/card/publication-card.tsx
Alkuperäinen speksi itse asiassa sanoi että näytetään kaikki Ratko-puskufailit, mutta nuo design-julkaisuthan kai toimii (toivottavasti) niin, että ne ovat itsenäisiä vain toisiinsa nähden -> näytetään samaan tapaan vain viimeinen kuin main-haarallakin.
> GVT-2700 Only show one Ratko push failure per design branch

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/ReferenceLineDao.kt
Olin totta puhuen yllättynyt, että näissä oli vielä optimointivaraa, mutta niin vaan näemmä oli, että kun ajelin näitä hakuja Ilmalan ratapihan alueella design-draft-tilalla (eli monimutkaisimmalla tapauksella), molempi uusi versio toimi yli kymmenen kertaa nopeammin kuin vanha, ja hakusuunnitelmatkin oli puolet lyhyempiä. Epätieteellisesti karttaa renklaamalla ja profileria katsomalla ero ei ole yhtä iso, mutta selvä voitto sielläkin.
Oleellinen ero molemmissa on, että nyt nämä eivät käytä enää lainkaan noita toteutukseltaan monimutkaisempia foo_in_layout_context-funktioita, vaan ainoastaan foo_is_in_layout_context-suotimia. Postgressin hakuoptimointi osaa käsittää tämän esitysmuodon sen verran paremmin, että tuon eksplisiittisen alignment_id, alignment_version-uniikkiuden pystyy myös …
> General: Optimize fetchVersionsNear()s yet again

- infra/src/main/resources/application-ext-api-dev-swagger.yml
- infra/src/main/resources/application-ext-api.yml
(or more specifically, attempt to fix them)
> GVT-2720: Fix Frame converter Swagger config url bindings

- infra/src/main/kotlin/fi/fta/geoviite/api/frameconverter/v1/FrameConverterControllerV1.kt
- infra/src/main/kotlin/fi/fta/geoviite/api/frameconverter/v1/FrameConverterDataConvertersV1.kt
- infra/src/main/kotlin/fi/fta/geoviite/api/frameconverter/v1/FrameConverterDataV1.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/configuration/WebConfiguration.kt
Kyseessä siis review-korjaus, samalla yksinkertaistuksia deserialisaatiomäärityksiin.
> GVT-2782 (part 2): Use explicit request param definitions

- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationService.kt
> Use split segment info to define track address range for partial duplicates

- infra/src/main/kotlin/fi/fta/geoviite/api/frameconverter/v1/FrameConverterControllerV1.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/aspects/ReflectedLogging.kt
Katselmointihuomion fiksaus: https://github.com/finnishtransportagency/geoviite/pull/1448#discussion_r1784293130
> General: Rename automatic logging disabling annotation

- ui/src/linking/linking-store.ts
Liittyy siis https://github.com/finnishtransportagency/geoviite/pull/1469/files#r1798801505. Vaikuttaisi siltä, että kaikki toimii tämän poistosta huolimatta (UI-testit menevät läpi, enkä huomannut käsin testatessakaan mitään ongelmia.) Toki vaatinee vielä parempaa testausta
> General: Segmenttien päihin linkityspisteitä generoivan turhan lambdan poisto

- ui/src/environment/env-restricted.tsx
- ui/src/environment/environment-info.ts
- ui/src/main/main.tsx
Korjaa siis konsolivirheet:
Samalla:
* Vaihdettu funkkarin nimitys hookiksi (eli funkkarin nimitykseen use-prefiksi, oikeasti Arin dailyhuomio)
* Vaihdettu aiempi raaka-fetch käyttämään frontin standardifunkkareita.
> General: Fix React side effect warning

- infra/src/main/kotlin/fi/fta/geoviite/infra/geocoding/GeocodingDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutAlignmentDao.kt
- ui/start_front.sh
Also:
- Don't list geocoding contexts for deleted tracknumbers
- Allow delete node_modules failure in dev start_front.sh
> GVT-2711 Cache empty alignments

- infra/src/main/resources/i18n/translations.fi.json
- ui/src/publication/log/publication-log.scss
- ui/src/publication/log/publication-log.tsx
- ui/src/utils/date-utils.ts
Fronttirajoite, mietiskellään laitetaanko myös bäkkärille
> GVT-2840: Restrict publication log date search range to less than 180 days

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchDao.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchDaoIT.kt
Josko tässä jossain vaiheessa lakkaisi tekemästä törkeitä id-häröilyvirheitä :sweat_smile: Edellinen koodihan siis palautti kaikki raiteet, joiden minkään elävän kontekstin versiossa oli linkki annettuun vaihteeseen.
Hieman oudolta näyttävä SQL-syntaksi on postgressin ominaisuus, jolla location_track-taulun riviä käsitellään vaan yksittäisenä oliona.
> GVT-2855 Fix versioning in findLocationTracksLinkedToSwitches

- infra/src/main/kotlin/fi/fta/geoviite/infra/geocoding/Geocoding.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geocoding/GeocodingService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/Publication.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutAlignmentDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutGeometry.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/ReferenceLineController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/ReferenceLineService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/TrackLayout.kt
- infra/src/main/resources/i18n/translations.fi.json
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackServiceIT.kt
- ui/src/map/layers/alignment/location-track-split-badge-layer.ts
- ui/src/map/layers/highlight/duplicate-split-section-highlight-layer.ts
- ui/src/tool-panel/location-track/dialog/location-track-edit-dialog.tsx
- ui/src/tool-panel/location-track/dialog/location-track-ratko-push-dialog.tsx
- ui/src/tool-panel/location-track/location-track-infobox-duplicate-track-entry.tsx
- ui/src/tool-panel/location-track/location-track-location-infobox.tsx
- ui/src/tool-panel/location-track/split-store.ts
- ui/src/tool-panel/location-track/splitting/location-track-split.tsx
- ui/src/tool-panel/location-track/splitting/location-track-splitting-infobox.tsx
- ui/src/tool-panel/track-number/dialog/track-number-edit-dialog.tsx
- ui/src/track-layout/layout-location-track-api.ts
- ui/src/track-layout/track-layout-model.tsx
- ui/src/track-layout/track-layout-react-utils.tsx
Samalla vähän backendin refaktorointia koska luokkavariaatioita oli tarpeettoman paljon ja nullable käsittelyissä oli joitain epämääräisyyksiä.
> GVT-2817 Fix track start/end caching and action disabling

- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/switches/SwitchLinkingService.kt
Alustusmuutoksia varsinaiselle vaihdelinkityksen optimoinnin pullarille. Näiden myötä tehtävälistan lataamisesta tulee bitilleen sama tulos eri ajokerroilla kullakin paikannuspohjan raiteelle, mikä helpottaa huomattavasti sellaisen optimoinnin massatestausta, josta ei pitäisi tulla tuloksiin muutoksia.
> GVT-2852 Stabilize relinking validation results

- infra/src/main/kotlin/fi/fta/geoviite/infra/projektivelho/PVClient.kt
Ei mitään toiminnallista, poistettu vain parit warnit tiedostosta ja korjailtu nimiä.
> General: Clean up warnings from PVClient

- ui/src/tool-panel/km-post/dialog/km-post-edit-store.ts
> Ad-hoc: Lisää GK31-koordinaatisto hyväksyttyjen koordinaatistojen listaan frontilla (main)

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/TrackLayout.kt
- ui/src/model/geometry.ts
- ui/src/tool-bar/tool-bar.tsx
- ui/src/tool-panel/km-post/dialog/km-post-edit-store.ts
Tein nämä omaan pullariinsa etteivät ne olisi peittäneet alkuperäiselle reviewille tehtyjä selityskommentteja (plus täällä on korjauksia muualtakin)
> GVT-2865 Part 3: Korjauksia ja muita parannuksia

- ui/src/frontpage/frontpage.tsx
> GVT-2884: Suunnitelmien julkaisut -kortin EnvRestricted (main)

- ui/src/tool-bar/tool-bar.tsx
Korjaus: Disabloidaan toolbarin tabit ja työtilan vaihto -dropdown kun linkitystila on päällä
> GVT-2881: Luonnos- ja suunnitelmatilojen välillä voi vaihtaa kilometripylvään linkitystilan ollessa päällä

- infra/src/main/kotlin/fi/fta/geoviite/infra/dataImport/SwitchLibraryDataMigration.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationUtils.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/ratko/RatkoUtils.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/ratko/model/RatkoConversion.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/switchLibrary/SwitchStructure.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/switchLibrary/data/EV_SJ43_5_9_1_9.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/common/SwitchStructureTest.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/ratko/RatkoUtilsTest.kt
- ui/src/common/common-model.ts
- ui/src/geoviite-design-lib/switch/switch-hand.tsx
- ui/src/geoviite-design-lib/switch/switch-icons.tsx
Täällä siis toteutettu tuki ruotsalaisten näkemykselle YV-vaihteesta.
> GVT-2787: Operaatio "Enkel Växel"

- ui/src/publication/log/publication-log.tsx
Aiemmin siis julkaisulokin vanhat arvot järjestettiin frontilla samaan aikaan kun uusi hakupyyntö lähetettiin bäkkärille -> tämä näyttäytyi outona käyttäytymisenä ("miksikäs tässä on maitolasi vaikka sehän selkeästi sorttasi?")
> GVT-2847: Julkaisulokin sorttaus ainoastaan bäkkärillä jos entryjä on 500+

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackDaoIT.kt
VKM:n käänteisen geokoodauksen toteutushistoriaa, sittemmin korvattu LocationTrackSpatialCachella.
> General: Remove dead location track fetch code

- infra/src/main/kotlin/fi/fta/geoviite/infra/aspects/GeoviiteScheduledTaskWrapper.kt
Review-korjaus: https://github.com/finnishtransportagency/geoviite/pull/1538#discussion_r1846061890
> General: Don't catch a throwable, catch an exception instead

- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/testgroup1/FrontPageTestUI.kt
> General: Luovuta ja disabloi `Retry failed publication`

- infra/src/main/kotlin/fi/fta/geoviite/api/frameconverter/v1/FrameConverterServiceV1.kt
- infra/src/test/kotlin/fi/fta/geoviite/api/frameconverter/v1/TrackAddressToCoordinateIT.kt
Pyynnöt ryhmiteltiin ratanumerokohtaisesti... ja sitten jokaiselta ratanumerolta tehtiin kaikki pyydetyt haut...
> GVT-2940 Fix requests with multiple track numbers in batch in VKM

- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationDao.kt
Entinen koodi ei ollut varsinaisesti väärin, koska näissä kaikissa kohdissa tallennetaan aina suoria muutoksia, ja siksi julkaisun haara on aina sama kuin julkaistavan olion oma haara. Mutta tällä tavalla nämä menevät selkeämmin niin, ettei tarvitse miettiä, löytyykö se oikea versio nyt vai ei.
> GVT-2726 Simplify version lookup when saving direct publication changes

- .github/workflows/build_and_test_ui.yml
- ui/jest.config.json
- ui/package-lock.json
- ui/package.json
- ui/test/vertical-geometry/km-heights-fetch.test.ts
- ui/tsconfig.json
This will reduce the chance of ui build issues in the distribution build and give earlier feedback on possible ui-build issues.
At the same time, this guides devs that ui-unit tests can be added and they are actually being ran in pipelines.
> GVT-2966: Build frontend and run unit tests in GitHub workflows

- ui/src/ratko/ratko-push-error.tsx
- ui/src/utils/enum-localization-utils.ts
Probably an earlier oversight
_Noteerattu testaillessa_
> General: Fix Ratko error translation key paths

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchDao.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchDaoIT.kt
Hakulogiikka menee varsin monimutkaiseksi otukseksi, koska onhan mahdollista esim. että jossain suunnitelmassa ensiksi muokataan jotain raidetta, muokkaus julkistetaan, perutaan, peruminen julkaistaan (jolloin design-official-rivi poistetaan), ja sitten muokkaus tehdään uusiksi.
En lähtenyt vielä tämän taskin tarpeiden perusteella erottamaan tästä perintää tukevaa foo_at_moment()-SQL-funktiota (tai siis viittä funktiota), mutta sinälläänhän se kyllä tuosta irtoaa helposti kunhan vaan irrottaa.
> GVT-2802 Branchify findLocationTracksLinkedToSwitchAtMoment

- infra/src/main/resources/i18n/translations.fi.json
- ui/src/tool-panel/location-track/splitting/location-track-split.tsx
- ui/src/tool-panel/location-track/splitting/removal-confirmation-menu.tsx
- ui/src/utils/use-scroll-listener.ts
Previously it was a little too simple to remove a split point
> GVT-2988: Add confirmation menu for split point removal

- ui/src/map/layers/debug/debug-geometry-graph-layer.ts
Taaskaan ei millään tavalla valmista/viilattua koodia, lähinnä käytän PR:n kautta että jää jälki. Täällä tehty Micro- ja Nano-tasojen erottaminen toisistaan visuaalisesti sekä LayoutNodejen kakuttaminen frontissa Mappiin
> GVT-2982: Parannuksia raidegraafin debug-karttatasoon

- ui/src/tool-panel/switch/geometry-switch-linking-infobox.tsx
Ongelmana oli se, että geometriavaihteen infoboksissa koitettiin käydä hakemassa vaihde-ehdotus potentiaalista linkitystä varten. Tämä ei tietenkään sitten onnistunut, kun virastokäyttäjällä ei ole oikeuksia nähdä draftia
> GVT-2943: Geometriavaihteen valinta suunnitelmasta virastokäyttäjällä heittää virheen

- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/inframodel/InfraModelController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/inframodel/InfraModelService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/geometry/GeometryServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/inframodel/InfraModelServiceIT.kt
- ui/src/tool-panel/geometry-plan/geometry-plan-applicability.tsx
Tämä olikin jäänyt enemmän vaiheeseen kuin ajattelinkaan, kun nappeja oli jäänyt wirettämättä 😅 Isoimmat korjaukset kuitenkin bäkkärille. Enää ei ole kantaan saakka kokonaan omaa polkua soveltuvuustiedon asettamiselle.
> GVT-3007: Korjauksia suunnitelman soveltuvuustiedon asettamiseen

- infra/src/main/kotlin/fi/fta/geoviite/api/frameconverter/v1/FrameConverterServiceV1.kt
Review-fiksi, ks. https://github.com/finnishtransportagency/geoviite/pull/1677#discussion_r1970939914. Samalla siirretty ulos servicestä
Noidenhan palautusarvoina vois myös käyttää kuvaavampaa Settiä, mutta sitten taas tämän käyttäjä joutuisi muuttamaan Setin heti listaksi Daon funkkarisignatuurin vuoksi
> GVT-2836 (part 2): Simplify cache hit to asset id mapping functions

- infra/src/main/kotlin/fi/fta/geoviite/infra/geocoding/Geocoding.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/math/Line.kt
Muistinkäyttöongelmien tutkimisen yhteydessä löytyneitä tosi helppoja voittoja.
> General: Decrease memory use for geocoding projection lines

- ui/src/vayla-design-lib/closeable-modal/closeable-modal.tsx
- ui/src/vayla-design-lib/dropdown/dropdown.tsx
- If blank search term is entered and enter/tab is pressed, dropdown value is cleared
- If clicked outside dropdown/popup then the search term is discarded (and selected value is shown)
> Fix dropdown behavior

- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutAlignmentDao.kt
En lähtenyt tekemään tähän ylimääräistä kompleksisuutta sen vuoksi että saisi eroteltua hakuun jo haettua id-joukkoa, koska onhan datan lapiointi itsessään halpaa. Mutta uusia instansseja alignmenteista ja segmenttigeometrioista ei tarvitse enää allokoida eikä vanhojen elinaikoja miettiä, eikä jo haettuja geometrioita tarvitse preloadin yhteydessä enää parsia.
> GVT-3050 Don't recreate already-loaded alignments and segment geometries in preload

- infra/src/main/kotlin/fi/fta/geoviite/infra/geometry/GeometryService.kt
Pienenpieni refaktori fetchTriangles()in käyttöön niin, että näkyy selkeämmin, että laskentaan käytettävä tieto haetaan vain kerran. Käytöksellistä muutosta tässä ei ole lainkaan, koska processFlattened()hän kutsuu sille annettua lambdaa vain kerran, ja getHeightAtTickInLayoutAlignment()-kutsuja oli taas tässä lambdassa vain yksi, joka sitten vaan palautti oman varsinaisen monta kertaa kutsuttavan lambdansa. Mutta tällä tavalla rakenne on ehkä hieman selkeämpi.
> General: Slightly refactor getHeightAtTickInLayoutAlignment

- ui/src/vertical-geometry/vertical-geometry-diagram-container.tsx
- ui/src/vertical-geometry/vertical-geometry-diagram-holder.tsx
- ui/src/vertical-geometry/vertical-geometry-diagram.tsx
Ei mitään muuta ajatusta kuin puhtaasti vaan React-devtoolsin profilerista katsottu että mikä propsi muuttui, oliko tarpeen muuttua, ei ollut, memotetaan/callbackitetään.
> GVT-3074 Fix unnecessary vertical geometry diagram rerenders

- doc/readme.md
- doc/valimuisti.md
Tämä tuli pullautettua puhtaasti proosana. Tuleeko mieleen jonkinlaista kuvaa/diagrammia, jota tämä kaipaisi havainnollistamiseksi?
> GVT-2697 Document cache use in Geoviite (back- & frontend)

- infra/build.gradle.kts
- infra/src/test/kotlin/fi/fta/geoviite/infra/ui/util/Browser.kt
Minulla ainakin turhan tuore chrome joten piti päivittää että ui-testit lähti pyörimään
> General: Update selenium

- infra/src/main/kotlin/fi/fta/geoviite/api/tracklayout/v1/ExtLocationTrackCollectionServiceV1.kt
- infra/src/main/kotlin/fi/fta/geoviite/api/tracklayout/v1/ExtLocationTrackControllerV1.kt
- infra/src/main/kotlin/fi/fta/geoviite/api/tracklayout/v1/ExtTrackLayoutConstantsV1.kt
Kannattaa ainakin lukasta noi fraasit läpi, ja tulkita että vaikuttaako ne ulkopuoliselle käyttäjälle/devaajalle ymmärrettäviltä.
> GVT-3177: Fix invalid HTTP 500 response, improve openapi documentation

- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/Publication.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationController.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/publication/PublicationLogService.kt
- ui/src/tool-bar/search-dropdown.tsx
Tärkeimpien katselmointihuomioiden fiksejä.
> Cleanups for GVT-3161

- ui/src/map/plan-download/plan-download-popup.tsx
Erotettu tuo sisäkomponentti ylemmälle tasolle
> GVT-3251: Review fixes

- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/switches/SwitchLinking.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/linking/switches/SwitchLinkingService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutAlignmentDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LayoutSwitchService.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackDao.kt
- infra/src/main/kotlin/fi/fta/geoviite/infra/tracklayout/LocationTrackService.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/integration/CalculatedChangesServiceIT.kt
- infra/src/test/kotlin/fi/fta/geoviite/infra/linking/switches/SwitchLinkingServiceIT.kt
Millään tästä ei pitäisi olla vaikutusta toiminnallisuuteen eikä näkyvästi myöskään suorituskykyyn. Lähdin siis alunperin tarkastelemaan olisiko helppoa tapaa nopeuttaa topologian tallennusta mutta se on hiukan kinkkinen ja pakitin ne muutokset pois. Tein kuitenkin loppuun asti muutamat refaktoroinnit joita räpläsin samalla kun lueskelin koodia edestakaisin: kuolleen koodin poistoa, renameja, vastuun siirtelyitä funktioiden välillä, jne.
> General: Non-functional refactorings to switch linking and track topology saving

- ui/src/publication/card/main-publication-list-row.tsx
- ui/src/publication/card/publication-list-row.scss
Tiketissä puhuttiin että olisi muuttunut. Tämä ei välttämättä ole täsmälleen identtinen alkuperäisen kanssa (tasasin noita sellaisiksi mitkä näytti omasta mielestäni kivalta), mutta kuitenkin aiempaa tilannetta parempi
> GVT-3283: Ikonien asettelu muuttunut julkaisukortissa
